-- ============================================================================
-- VERIFICACION-ENTIDADES-VS-ESQUEMA-CXC-CXP-TSR.sql
-- Escrito por el arbitro del equipo el 2026-08-29
-- ============================================================================
--
-- POR QUE EXISTE
-- La verificacion por sondas (VERIFICACION-DDL-EQUIPO-*.sql) encontro que
-- cxc/sql/add-anticipo-cliente-devolucion.sql nunca se corrio: faltaba
-- CBR.ANTC.ANTCIDPG. Lo grave no fue el script en si, sino que esa columna
-- ESTA MAPEADA en la entidad (model/cxc/AnticipoCliente.java:166). Hibernate
-- incluye toda columna @Column basica en el SELECT que genera, asi que la
-- ausencia no rompe solo la devolucion: rompe CUALQUIER lectura de
-- AnticipoCliente con ORA-00904.
--
-- Una sonda por script no puede encontrar ese tipo de fallo en general. Esta
-- verificacion si: compara TODAS las columnas mapeadas de TODAS las entidades
-- de cxc, cxp y tsr (179 entidades, 2.310 columnas entre @Column y @JoinColumn)
-- contra lo que existe de verdad en la base.
--
-- NO MODIFICA NADA. Son dos consultas de solo lectura.
--
-- COMO LEERLO
--   Consulta A: tablas mapeadas que no existen. Deberia dar 0 filas.
--   Consulta B: columnas mapeadas que faltan, solo en tablas que si existen.
--               Deberia dar 0 filas. Cada fila es un ORA-00904 esperando el
--               despliegue.
--
-- DOS LIMITACIONES, DICHAS DE FRENTE
--   1. ALL_TAB_COLUMNS solo muestra lo que el usuario conectado puede ver. Si
--      corres esto con un usuario sin privilegios sobre CBR/PGS/TSR, van a
--      salir falsos FALTA. Conectarse con el mismo usuario que usa el
--      datasource, o con DBA.
--   2. Cubre cxc, cxp y tsr. NO cubre crd (otro equipo), ni rhh, ni los
--      esquemas compartidos (cnt, scp). Ampliarlo es mecanico si hace falta.
--
-- ALCANCE: generado el 2026-08-29 leyendo src/main/java/com/saa/model/{cxc,cxp,
-- tsr}. Si se agregan entidades o columnas despues, hay que regenerarlo.
-- ============================================================================

WITH ESPERADO AS (
SELECT 'CBR' AS OWNER_ESP, 'ANTC' AS TABLA_ESP, 'ANTCAPLC,ANTCBANC,ANTCFPAG,ANTCIDPG,ANTCREFR,ANTCSALD,ASIENTO,EMPRESA,ESTADO,FECHAANTICIPO,FECHARECEPCION,FECHAREGISTRO,ID,NUMERODOC,OBSERVACION,TITULAR,USUARIO,VALOR' AS COLS FROM DUAL
UNION ALL SELECT 'CBR', 'APLC', 'APLCANTC,APLCANTO,APLCASNT,APLCBANC,APLCCDGO,APLCESTD,APLCFAPL,APLCFCRG,APLCFCTR,APLCFPAG,APLCLQCS,APLCMAPL,APLCNTCR,APLCNTDB,APLCOBSR,APLCPJRQ,APLCRCV2,APLCREFR,APLCRTCM,APLCTDPG,APLCUSAR' FROM DUAL
UNION ALL SELECT 'CBR', 'CCIC', 'CCICCDGO,CCICVLRR,CCICVLRV,FXDCCDGO,RVDCCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'CXDC', 'CXDCABNO,CXDCCDGO,CXDCFCIN,CXDCFCVN,CXDCNMCL,CXDCNMSC,CXDCNMTC,CXDCSLDO,CXDCTPOO,CXDCVLRR,FXDCCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'DTDC', 'CNCSCDGO,DCMCCDGO,DTDCCDGO,DTDCCNTD,DTDCDSCR,DTDCESTD,DTDCFCIN,DTDCNMLN,DTDCPRUN,DTDCSBTT,DTDCTTIM,DTDCTTLL,PJRQCDGO,PRDCCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'DTFC', 'BASEIMPONIBLE,CANTIDAD,CODIGOIVASRI,DESCRIPCION,DESCUENTO,ESTADO,FACTURA,ID,PORCENTAJEICE,PORCENTAJEIVA,PRECIOSINSUB,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'DTLC', 'CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,LIQUIDACION,PORCENTAJEICE,PORCENTAJEIVA,PRECIOSINSUB,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'DTNC', 'BASEIMPONIBLE,CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,NOTACREDITO,PORCENTAJEICE,PORCENTAJEIVA,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'DTND', 'BASEIMPONIBLE,CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,NOTADEBITO,PORCENTAJEICE,PORCENTAJEIVA,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'DTRT', 'BASEIMPONIBLE,CODIMPUESTO,CODRETENCION,ESTADO,FECHAEMIDOC,ID,NUMDOCRETEN,PORCENTAJERETEN,RETENCION,TIPODOCRETEN,VALORRETEN' FROM DUAL
UNION ALL SELECT 'CBR', 'DRV2', 'BASEIMPONIBLE,CODIMPUESTO,CODRETENCION,DOCRESAUTORIZACION,DOCRESFORPAGO,DOCRESIVACERO,DOCRESPORIVA,DOCRESTOTAL,DOCRESTOTALIVA,DOCRESTSINIMPUESTOS,ESTADO,FECHAEMIDOC,FECHAREG,ID,NUMDOCRETEN,PORCENTAJERETEN,RETENCIONV2,TIPODOCRETEN,VALORRETEN' FROM DUAL
UNION ALL SELECT 'CBR', 'DCMC', 'ASNTCDGO,DCMCABNN,DCMCANOO,DCMCCDGO,DCMCDRCC,DCMCDSVN,DCMCFCAU,DCMCFCDC,DCMCFCVN,DCMCFRPG,DCMCIDFS,DCMCMSSS,DCMCNMAU,DCMCNMRN,DCMCNMRO,DCMCNMRS,DCMCRUCC,DCMCRYYA,DCMCRZSC,DCMCRZZA,DCMCSLDD,DCMCSREE,DCMCTTLL,PJRQCDGO,PRDOCDGO,STDCCDGO,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'ESTB', 'CODIGO,CREACION,DESCRIPCION,DIRECCION,ESTADO,FACTURADOR,ID,LOGO,MAIL,MATRIZ,NOMBRE,TELEFONO' FROM DUAL
UNION ALL SELECT 'CBR', 'FCTR', 'AHORROSUB,AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,COMPRADOR,DESCUENTO,EMPRESA,ESTADO,ESTADOEMISION,FACTURADOR,FCTREPAG,FECHA,FECHAANULACION,FECHAAUTORIZACION,FORMAPAGO,ID,MOTIVOANULACION,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,SUBTOTAL5,SUBTOTAL8,TIPOCOMPROBANTE,TIPODOC,TOTAL,TOTALSINSUB,USUARIO,USUARIOANULACION,VICE,VIRBPNR,VIVA,VIVA5,VIVA8' FROM DUAL
UNION ALL SELECT 'CBR', 'FCDR', 'AGENTERETENCION,AMBIENTE,ARTESANO,CLAVEFIRMA,CODCLAVE,CONTABILIDAD,CONTRIBUYENTEESPECIAL,CREADO,DIRECCION,DOCEMITIDOS,DOCPERMITIDOS,EMPRESA,EMPRESAFIRMA,EMPTRANSPORTE,ESTADO,FIRMA,GENERACONTA,ID,IMPCODPROD,INICIA,INVENTARIO,LOGO,MAIL,MICROEMPRESA,NOMBRE,NOMBRECOMERCIAL,NUMDOC,POPULARRIMPE,RAZONSOCIAL,RIMPE,SINLIMITECONSFINAL,TELEFONO,TURISTICO,VENCE' FROM DUAL
UNION ALL SELECT 'CBR', 'FXDC', 'DCMCCDGO,FXDCAPCI,FXDCAPIN,FXDCCDGO,FXDCDPOF,FXDCFTIN,FXDCIDDC,FXDCNDCD,FXDCNMPG,FXDCPRIN,FXDCRYYA,FXDCRZZA,FXDCTPCA,FXDCTPCI,FXDCTPDP,FXDCTPFN,FXDCVCIB,FXDCVNMC,FXDCVPRC,FXDCVTCI' FROM DUAL
UNION ALL SELECT 'CBR', 'FPFC', 'FACTURA,FORMAPAGO,ID,PLAZO,UNIDADTIEMPO,VALOR' FROM DUAL
UNION ALL SELECT 'CBR', 'FPLC', 'FORMAPAGO,ID,LIQUIDACION,PLAZO,UNIDADTIEMPO,VALOR' FROM DUAL
UNION ALL SELECT 'CBR', 'GRPC', 'GRPCCDGO,GRPCESTD,GRPCNMBR,GRPCRYYA,GRPCRZZA,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'IXGC', 'DTIMCDGO,GRPCCDGO,IXGCCDGO,IXGCESTD' FROM DUAL
UNION ALL SELECT 'CBR', 'LQCS', 'AHORROSUB,AMBIENTE,AUTORIZACION,CLAVE,DESCUENTO,ESTADO,ESTADOEMISION,ESTADOPAGO,FACTURADOR,FECHA,FECHAAUTORIZACION,ID,LQCSASNT,LQCSLQCC,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TITULAR,TOTAL,TOTALSINSUB,USUARIO,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'LSRI', 'DETALLE,ESTADO,ID,TABLA' FROM DUAL
UNION ALL SELECT 'CBR', 'NTCR', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,ESTADO,ESTADOEMISION,FACTURA,FACTURADOR,FECHA,FECHAANULACION,FECHAAUTORIZACION,FECHAEMISIONDM,ID,MOTIVOANULACION,NUMDOCMODIFICADO,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TIPODOCMODIFICADO,TITULAR,TOTAL,USUARIO,USUARIOANULACION,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'NTDB', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,ESTADO,ESTADOEMISION,FACTURA,FACTURADOR,FECHA,FECHAANULACION,FECHAAUTORIZACION,FECHAEMISIONDM,ID,MOTIVOANULACION,NUMDOCMODIFICADO,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TIPODOCMODIFICADO,TITULAR,TOTAL,USUARIO,USUARIOANULACION,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'CBR', 'NXPE', 'ID,NUMACTUAL,PTOEMISION,TIPODOC' FROM DUAL
UNION ALL SELECT 'CBR', 'PAFC', 'FXDCCDGO,PAFCANOO,PAFCCDGO,PAFCDAAA,PAFCFCPG,PAFCMSSS,PAFCVLRR' FROM DUAL
UNION ALL SELECT 'CBR', 'PTFC', 'ALTERNO,FACTURA,ID,PATH' FROM DUAL
UNION ALL SELECT 'CBR', 'PTLC', 'ALTERNO,ID,LIQUIDACION,PATH' FROM DUAL
UNION ALL SELECT 'CBR', 'PTNC', 'ALTERNO,ID,NOTACREDITO,PATH' FROM DUAL
UNION ALL SELECT 'CBR', 'PTND', 'ALTERNO,ID,NOTADEBITO,PATH' FROM DUAL
UNION ALL SELECT 'CBR', 'PTRT', 'ALTERNO,ID,PATH,RETENCION' FROM DUAL
UNION ALL SELECT 'CBR', 'PRT2', 'ALTERNO,ID,PATH,RETENCIONV2' FROM DUAL
UNION ALL SELECT 'CBR', 'PRDC', 'CODIGO,CODIGOAUX,DESCRIPCION,DESCUENTO,EMPRESA,ESTADO,GRUPOPRODUCTO,ICE,ID,INCLUYEIVA,IRBPNR,MANEJAUNIDAD,MULTIPRECIO,NOMBRE,PRECIOSINSUB,PRECIOUNITARIO,STOCK,SUBSIDIO,TIPODESCUENTO,TIPOICE,TIPOIVA,UNIDAD' FROM DUAL
UNION ALL SELECT 'CBR', 'PTEM', 'CODIGO,CREADO,ESTABLECIMIENTO,ESTADO,ID,NOMBRE,OBSERVACION,TRANSPORTISTA' FROM DUAL
UNION ALL SELECT 'CBR', 'RVDC', 'DCMCCDGO,RVDCCATP,RVDCCDGO,RVDCVLRR' FROM DUAL
UNION ALL SELECT 'CBR', 'RTNC', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,ESTADO,ESTADOEMISION,FACTURADOR,FECHA,FECHAANULACION,FECHAAUTORIZACION,ID,MOTIVOANULACION,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PERIODOFISCAL,PROVEEDOR,PTOEMISION,SECUENCIAL,TIPOCOMPROBANTE,TIPODOC,TOTAL,USUARIO,USUARIOANULACION' FROM DUAL
UNION ALL SELECT 'CBR', 'RTV2', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,ESTADO,ESTADOEMISION,FACTURADOR,FECHA,FECHAANULACION,FECHAAUTORIZACION,ID,MOTIVOANULACION,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PERIODOFISCAL,PROVEEDOR,PTOEMISION,SECUENCIAL,TIPOCOMPROBANTE,TIPODOC,TOTAL,USUARIO,USUARIOANULACION' FROM DUAL
UNION ALL SELECT 'CBR', 'TCIC', 'TCICCDGO,TCICVLRR,TCICVLRV,TFDCCDGO,TRDCCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'TCDC', 'TCDCABNO,TCDCCDGO,TCDCFCIN,TCDCFCVN,TCDCNMCL,TCDCNMSC,TCDCNMTC,TCDCSLDO,TCDCTPOO,TCDCVLRR,TFDCCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'TDTC', 'CNCSCDGO,PJRQCDGO,PRDCCDGO,TDCCCDGO,TDTCCDGO,TDTCCNTD,TDTCDSCR,TDTCESTD,TDTCFCIN,TDTCNMLN,TDTCPRUN,TDTCSBTT,TDTCTTIM,TDTCTTLL' FROM DUAL
UNION ALL SELECT 'CBR', 'TDCC', 'ASNTCDGO,PJRQCDGO,PRDOCDGO,STDCCDGO,TDCCABNO,TDCCANIO,TDCCCDGO,TDCCDRCC,TDCCDSVN,TDCCFCAT,TDCCFCDC,TDCCFCVN,TDCCFISC,TDCCMSSS,TDCCNMAT,TDCCNMNR,TDCCNMRO,TDCCRBE1,TDCCRBE2,TDCCRSLN,TDCCRUCC,TDCCRZSC,TDCCSLDO,TDCCSREE,TDCCTOTT,TDCCTPFO,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'CBR', 'TFDC', 'TDCCCDGO,TFDCAPCI,TFDCAPIN,TFDCCDGO,TFDCDPFD,TFDCDPOF,TFDCFTIN,TFDCNMCO,TFDCNMDP,TFDCPRIN,TFDCRBRH,TFDCRBRP,TFDCTPCB,TFDCTPCI,TFDCTPFN,TFDCTPPD,TFDCVCIB,TFDCVNMC,TFDCVPRC,TFDCVTCL' FROM DUAL
UNION ALL SELECT 'CBR', 'TPFC', 'TFDCCDGO,TPFCANOO,TPFCCDGO,TPFCDAAA,TPFCFCPG,TPFCMSSS,TPFCVLRR' FROM DUAL
UNION ALL SELECT 'CBR', 'TRDC', 'TDCCCDGO,TRDCCATP,TRDCCDGO,TRDCVLRR' FROM DUAL
UNION ALL SELECT 'CBR', 'TITC', 'DTIMCDGO,TDTCCDGO,TITCCDGO,TITCNMBR,TITCPRCT,TITCVLRR,TITCVLSA' FROM DUAL
UNION ALL SELECT 'CBR', 'TIDC', 'DTIMCDGO,TDCCCDGO,TIDCCAVD,TIDCCDGO,TIDCNMBR,TIDCPRCT,TIDCVLRR,TIDCVLSA' FROM DUAL
UNION ALL SELECT 'CBR', 'TSRI', 'CODIGO,DETALLE,ESTADO,ID,LSRI,PLNNCDGO,PORCENTAJE,TEXTO,VALOR' FROM DUAL
UNION ALL SELECT 'CBR', 'VITC', 'DTDCCDGO,DTIMCDGO,VITCCDGO,VITCNMBR,VITCPRCT,VITCVLRR,VITCVLSA' FROM DUAL
UNION ALL SELECT 'CBR', 'VIDC', 'DCMCCDGO,DTIMCDGO,VIDCCAVD,VIDCCDGO,VIDCNMBR,VIDCPRCT,VIDCVLRR,VIDCVLSA' FROM DUAL
UNION ALL SELECT 'PGS', 'ADNG', 'DESCRIPCION,ESTADO,FECHAADENDUM,FECHAREGISTRO,ID,NEGOCIACION,NUMADENDUM,OBSERVACION,USUARIO,VALORAJUSTE,VALORTOTALRESULTANTE' FROM DUAL
UNION ALL SELECT 'PGS', 'ANTP', 'ANTPASNT,ANTPBANC,ANTPCDGO,ANTPESTD,ANTPFANT,ANTPFCRG,ANTPFPAG,ANTPFRCP,ANTPNDOC,ANTPOBSR,ANTPPJRQ,ANTPREFR,ANTPSALD,ANTPTTLR,ANTPUSAR,ANTPVLOR' FROM DUAL
UNION ALL SELECT 'PGS', 'APLP', 'APLPANTO,APLPANTP,APLPASNT,APLPBANC,APLPCDGO,APLPESTD,APLPFAPL,APLPFCRG,APLPFCTC,APLPFPAG,APLPMAPL,APLPNTCC,APLPNTDC,APLPOBSR,APLPPJRQ,APLPREFR,APLPRTNC,APLPRTV2,APLPTDPG,APLPUSAR' FROM DUAL
UNION ALL SELECT 'PGS', 'APXM', 'APXMCDGO,APXMESTD,APXMFCIN,APXMNMBR,APXMNUIN,APXMORDN,APXMSLBN,MNAPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'AXPR', 'AXPRCDGO,AXPRESTD,AXPRFCAP,AXPRNMUS,AXPRNVAP,AXPROBSR,PJRQCDUS,PRPDCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'CRTX', 'CRTXCDGO,CRTXESTD,CRTXFCGA,CRTXNARV,CRTXOBSR,CRTXPJRQ,CRTXRGDP,CRTXRGND,CRTXRGNV,CRTXTTLR,CRTXUSAR,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'CCIP', 'CCIPCDGO,CCIPVLRR,CCIPVLRV,FXDPCDGO,RVDPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'CXDP', 'CXDPABNO,CXDPCDGO,CXDPFCIN,CXDPFCVN,CXDPNMCL,CXDPNMSC,CXDPNMTC,CXDPSLDO,CXDPTPOO,CXDPVLRR,FXDPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'DCTX', 'CRTXCDGO,DCTXCDGO,DCTXFAUT,DCTXFEMS,DCTXIMTT,DCTXIVAA,DCTXOBSR,DCTXRSLT,DCTXVSIM,DCXPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'DTDP', 'CNCSCDGO,DCMPCDGO,DTDPCDGO,DTDPCNTD,DTDPDSCR,DTDPESTD,DTDPFCIN,DTDPNMLN,DTDPPRUN,DTDPSBTT,DTDPTTIM,DTDPTTLL,PJRQCDGO,PRDPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'DFCC', 'BASEIMPONIBLE,CANTIDAD,CODIGOIVASRI,DESCRIPCION,DESCUENTO,ESTADO,FACTURA,ID,PORCENTAJEICE,PORCENTAJEIVA,PRECIOSINSUB,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'DLCM', 'CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,LIQUIDACION,PORCENTAJEICE,PORCENTAJEIVA,PRECIOSINSUB,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'DTCC', 'BASEIMPONIBLE,CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,NOTACREDITO,PORCENTAJEICE,PORCENTAJEIVA,PRODUCTO,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'DTDC', 'BASEIMPONIBLE,CANTIDAD,DESCRIPCION,DESCUENTO,ESTADO,ID,NOTADEBITO,PORCENTAJEICE,PORCENTAJEIVA,SUBSIDIO,SUBTOTAL,TOTAL,VALOR,VALORICE,VALORIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'DPGT', 'DPGTCDGO,DPGTCNCP,DPGTPRDP,DPGTVLRR,PGTRCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'DRCM', 'BASEIMPONIBLE,CODIMPUESTO,CODRETENCION,ESTADO,FECHAEMIDOC,ID,NUMDOCRETEN,PORCENTAJERETEN,RETENCION,TIPODOCRETEN,VALORRETEN' FROM DUAL
UNION ALL SELECT 'PGS', 'DRC2', 'BASEIMPONIBLE,CODIMPUESTO,CODRETENCION,DOCRESAUTORIZACION,DOCRESFORPAGO,DOCRESIVACERO,DOCRESPORIVA,DOCRESTOTAL,DOCRESTOTALIVA,DOCRESTSINIMPUESTOS,ESTADO,FECHAEMIDOC,FECHAREG,ID,NUMDOCRETEN,PORCENTAJERETEN,RETENCIONV2,TIPODOCRETEN,VALORRETEN' FROM DUAL
UNION ALL SELECT 'PGS', 'DCXP', 'DCXPCDGO,DCXPCLAC,DCXPENOV,DCXPESRM,DCXPESTD,DCXPFAUT,DCXPFCXM,DCXPFDSC,DCXPFEMS,DCXPFRBD,DCXPFRVS,DCXPIDBD,DCXPIDRC,DCXPIMTT,DCXPIVAA,DCXPMSRI,DCXPNDMD,DCXPNVDD,DCXPOBSR,DCXPORXM,DCXPPJRQ,DCXPPXML,DCXPRCEM,DCXPRSEM,DCXPRSRI,DCXPSRCM,DCXPTBTD,DCXPTPCM,DCXPUCXM,DCXPURBD,DCXPURVS,DCXPVSIM,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'DCMP', 'ASNTCDGO,DCMPABNN,DCMPANOO,DCMPCDGO,DCMPDRCC,DCMPDSVN,DCMPFCAU,DCMPFCDC,DCMPFCVN,DCMPFRPG,DCMPIDFS,DCMPMSSS,DCMPNMAU,DCMPNMRN,DCMPNMRO,DCMPNMRS,DCMPRUCC,DCMPRYYA,DCMPRZSC,DCMPRZZA,DCMPSLDD,DCMPSREE,DCMPTTLL,PJRQCDGO,PRDOCDGO,STDCCDGO,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'FCTC', 'AHORROSUB,AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,EMPRESA,ESTADO,ESTADOEMISION,FCTCCDRM,FCTCCSUS,FCTCEPAG,FCTCESRM,FCTCFCAN,FCTCFCRG,FCTCMTAN,FCTCTBRM,FCTCTCRM,FCTCTIRM,FCTCUSAN,FECHA,FECHAAUTORIZACION,FORMAPAGO,ID,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,SUBTOTAL5,SUBTOTAL8,TIPOCOMPROBANTE,TIPODOC,TITULAR,TOTAL,TOTALSINSUB,USUARIO,VICE,VIRBPNR,VIVA,VIVA5,VIVA8' FROM DUAL
UNION ALL SELECT 'PGS', 'FXDP', 'DCMPCDGO,FXDPAPCI,FXDPAPIN,FXDPCDGO,FXDPDPOF,FXDPFTIN,FXDPIDDC,FXDPNDCD,FXDPNMPG,FXDPPRIN,FXDPRYYA,FXDPRZZA,FXDPTPCA,FXDPTPCI,FXDPTPDP,FXDPTPFN,FXDPVCIB,FXDPVNMC,FXDPVPRC,FXDPVTCI' FROM DUAL
UNION ALL SELECT 'PGS', 'FPFM', 'FACTURA,FORMAPAGO,ID,PLAZO,UNIDADTIEMPO,VALOR' FROM DUAL
UNION ALL SELECT 'PGS', 'FPLM', 'FORMAPAGO,ID,LIQUIDACION,PLAZO,UNIDADTIEMPO,VALOR' FROM DUAL
UNION ALL SELECT 'PGS', 'FPNG', 'DESCRIPCION,ESTADO,FECHAPAGO,ID,NEGOCIACION,NUMEROCUOTA,ORDEN,PORCENTAJE,VALORCUOTA' FROM DUAL
UNION ALL SELECT 'PGS', 'GRPP', 'GRPPCDGO,GRPPCSUS,GRPPESTD,GRPPNMBR,GRPPRYYA,GRPPRZZA,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'IXGP', 'DTIMCDGO,GRPPCDGO,IXGPCDGO,IXGPESTD' FROM DUAL
UNION ALL SELECT 'PGS', 'LQCC', 'AHORROSUB,AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,EMPRESA,ESTADO,ESTADOEMISION,FECHA,FECHAAUTORIZACION,ID,LQCCCSUS,LQCCFCAN,LQCCFCRG,LQCCMTAN,LQCCUSAN,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TITULAR,TOTAL,TOTALSINSUB,USUARIO,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'LTPG', 'LTPGCDGO,LTPGCNBC,LTPGESTD,LTPGFCRG,LTPGFGNR,LTPGNMAR,LTPGNPAG,LTPGOBSR,LTPGPATH,LTPGPJRQ,LTPGUSAR,LTPGVLTT' FROM DUAL
UNION ALL SELECT 'PGS', 'LSRI', 'DETALLE,ESTADO,ID,TABLA' FROM DUAL
UNION ALL SELECT 'PGS', 'MNAP', 'MNAPCDGO,MNAPFCIN,MNAPNUIN,MNAPVLDS,MNAPVLHS,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'NGCP', 'DESCRIPCION,EMPRESA,ESTADO,FECHAFIN,FECHAINICIO,FECHAMODIF,FECHANEGOCIACION,FECHAREGISTRO,ID,NUMCONTRATO,NUMEROPAGOS,OBSERVACION,TIPOFINANCIACION,TITULAR,USUARIO,USUARIOMODIF,VALORTOTAL' FROM DUAL
UNION ALL SELECT 'PGS', 'NTCC', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,EMPRESA,ESTADO,ESTADOEMISION,FECHA,FECHAAUTORIZACION,FECHAEMISIONDM,ID,NTCCCSUS,NTCCFCAN,NTCCFCRG,NTCCMTAN,NTCCUSAN,NUMDOCMODIFICADO,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TIPODOCMODIFICADO,TITULAR,TOTAL,USUARIO,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'NTDC', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,DESCUENTO,EMPRESA,ESTADO,ESTADOEMISION,FECHA,FECHAAUTORIZACION,FECHAEMISIONDM,ID,NTDCCSUS,NTDCFCAN,NTDCFCRG,NTDCMTAN,NTDCUSAN,NUMDOCMODIFICADO,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PIVA,PORDESCUENTO,PROPINA,PTOEMISION,SECUENCIAL,SUBCERO,SUBSIDIO,SUBTOTAL,TIPOCOMPROBANTE,TIPODOC,TIPODOCMODIFICADO,TITULAR,TOTAL,USUARIO,VICE,VIRBPNR,VIVA' FROM DUAL
UNION ALL SELECT 'PGS', 'PGNG', 'DESCRIPCION,ESTADO,FACTURACOMPRA,FACTURADO,FECHAPAGO,FECHAREGISTRO,FORMAPAGO,ID,PAGADO,REFCOMPROBANTE,TIPOPAGO,USUARIO,VALORPAGO' FROM DUAL
UNION ALL SELECT 'PGS', 'PGTR', 'PGTRANTP,PGTRAPLP,PGTRASNT,PGTRBFBC,PGTRBFCT,PGTRBFID,PGTRBFNM,PGTRBFTP,PGTRCDGO,PGTRCNBC,PGTRCTBN,PGTRDBAT,PGTRDTCH,PGTREGRS,PGTRESTD,PGTRFCRG,PGTRFCTC,PGTRFPAG,PGTRFPRG,PGTRFRSP,PGTRIDOR,PGTRLTPG,PGTRMTVO,PGTROBSR,PGTRORGN,PGTRPJRQ,PGTRRFBN,PGTRTTLR,PGTRUSAR,PGTRVLOR' FROM DUAL
UNION ALL SELECT 'PGS', 'PAFP', 'FXDPCDGO,PAFPANOO,PAFPCDGO,PAFPDAAA,PAFPFCPG,PAFPMSSS,PAFPVLRR' FROM DUAL
UNION ALL SELECT 'PGS', 'PFCC', 'ALTERNO,FACTURA,ID,PATH' FROM DUAL
UNION ALL SELECT 'PGS', 'PLCC', 'ALTERNO,ID,LIQUIDACION,PATH' FROM DUAL
UNION ALL SELECT 'PGS', 'PTNG', 'ADENDUM,ID,NEGOCIACION,NOMBREDOC,PATH,PRINCIPAL,TIPODOC' FROM DUAL
UNION ALL SELECT 'PGS', 'PTCV', 'ALTERNO,ID,NOTACREDITO,PATH' FROM DUAL
UNION ALL SELECT 'PGS', 'PTDC', 'ALTERNO,ID,NOTADEBITO,PATH' FROM DUAL
UNION ALL SELECT 'PGS', 'PRCM', 'ALTERNO,ID,PATH,RETENCION' FROM DUAL
UNION ALL SELECT 'PGS', 'PRDP', 'CODIGO,CODIGOAUX,DESCRIPCION,DESCUENTO,EMPRESA,ESTADO,GRUPOPRODUCTO,ICE,ID,INCLUYEIVA,IRBPNR,MANEJAUNIDAD,MULTIPRECIO,NOMBRE,PRECIOSINSUB,PRECIOUNITARIO,STOCK,SUBSIDIO,TIPODESCUENTO,TIPOICE,TIPOIVA,UNIDAD' FROM DUAL
UNION ALL SELECT 'PGS', 'PRPD', 'CXDPCDGO,PRPDCDGO,PRPDESTD,PRPDFCIN,PRPDFCPG,PRPDNMAB,PRPDNMAP,PRPDTPPR,PRPDUSPR,PRPDVLCT,PRPDVLRR' FROM DUAL
UNION ALL SELECT 'PGS', 'RMBF', 'RMBFBSCR,RMBFBSGR,RMBFCDDC,RMBFCDGO,RMBFCDPS,RMBFESTB,RMBFESTD,RMBFFCTC,RMBFFEMS,RMBFIDPR,RMBFNAUT,RMBFOBSR,RMBFORGN,RMBFPRDC,RMBFPTEM,RMBFSCNL,RMBFTIPR,RMBFTPPR,RMBFTRIV,RMBFTTAL,RMBFVLIC,RMBFVLIV' FROM DUAL
UNION ALL SELECT 'PGS', 'RVDP', 'DCMPCDGO,RVDPCATP,RVDPCDGO,RVDPVLRR' FROM DUAL
UNION ALL SELECT 'PGS', 'RTCM', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,EMPRESA,ESTADO,ESTADOEMISION,FECHA,FECHAAUTORIZACION,ID,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PERIODOFISCAL,PROVEEDOR,PTOEMISION,SECUENCIAL,TIPOCOMPROBANTE,TIPODOC,TOTAL,USUARIO' FROM DUAL
UNION ALL SELECT 'PGS', 'RCV2', 'AMBIENTE,ASIENTO,AUTORIZACION,CLAVE,EMPRESA,ESTADO,ESTADOEMISION,FECHA,FECHAAUTORIZACION,ID,NUMERO,NUMESTABLECIMIENTO,NUMPTOEMISION,OBSERVACION,PATHGEN,PERIODOFISCAL,PROVEEDOR,PTOEMISION,SECUENCIAL,TIPOCOMPROBANTE,TIPODOC,TOTAL,USUARIO' FROM DUAL
UNION ALL SELECT 'PGS', 'TAPX', 'TAPXCDGO,TAPXESTD,TAPXFCIN,TAPXNMBR,TAPXNUIN,TAPXORDN,TAPXSLBN,TMNACDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'TCIP', 'TCIPCDGO,TCIPVLRR,TCIPVLRV,TFDPCDGO,TRDPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'TCDP', 'TCDPABNO,TCDPCDGO,TCDPFCIN,TCDPFCVN,TCDPNMCL,TCDPNMSC,TCDPNMTC,TCDPSLDO,TCDPTPOO,TCDPVLRR,TFDPCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'TDTP', 'CNCSCDGO,PJRQCDGO,PRDPCDGO,TDCPCDGO,TDTPCDGO,TDTPCNTD,TDTPDSCR,TDTPESTD,TDTPFCIN,TDTPNMLN,TDTPPRUN,TDTPSBTT,TDTPTTIM,TDTPTTLL' FROM DUAL
UNION ALL SELECT 'PGS', 'TDCP', 'ASNTCDGO,PJRQCDGO,PRDOCDGO,STDCCDGO,TDCPABNN,TDCPANOO,TDCPCDGO,TDCPDRCC,TDCPDSVN,TDCPFCAU,TDCPFCDC,TDCPFCVN,TDCPFRPG,TDCPIDFS,TDCPMSSS,TDCPNMAU,TDCPNMRN,TDCPNMRO,TDCPNMRS,TDCPRUCC,TDCPRYYA,TDCPRZSC,TDCPRZZA,TDCPSLDD,TDCPSREE,TDCPTTLL,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'PGS', 'TFDP', 'TDCPCDGO,TFDPAPCI,TFDPAPIN,TFDPCDGO,TFDPDPOF,TFDPFTIN,TFDPIDDC,TFDPNDCD,TFDPNMPG,TFDPPRIN,TFDPRYYA,TFDPRZZA,TFDPTPCA,TFDPTPCI,TFDPTPDP,TFDPTPFN,TFDPVCIB,TFDPVNMC,TFDPVPRC,TFDPVTCI' FROM DUAL
UNION ALL SELECT 'PGS', 'TMNA', 'PJRQCDGO,TMNACDGO,TMNAFCIN,TMNANUIN,TMNAVLDS,TMNAVLHS' FROM DUAL
UNION ALL SELECT 'PGS', 'TPFP', 'TFDPCDGO,TPFPANOO,TPFPCDGO,TPFPDAAA,TPFPFCPG,TPFPMSSS,TPFPVLRR' FROM DUAL
UNION ALL SELECT 'PGS', 'TRDP', 'TDCPCDGO,TRDPCATP,TRDPCDGO,TRDPVLRR' FROM DUAL
UNION ALL SELECT 'PGS', 'TUXA', 'PJRQCDUS,TAPXCDGO,TUXACDGO,TUXAFCIN' FROM DUAL
UNION ALL SELECT 'PGS', 'TITP', 'DTIMCDGO,TDTPCDGO,TITPCDGO,TITPNMBR,TITPPRCT,TITPVLRR,TITPVLSA' FROM DUAL
UNION ALL SELECT 'PGS', 'TIDP', 'DTIMCDGO,TDCPCDGO,TIDPCAVD,TIDPCDGO,TIDPNMBR,TIDPPRCT,TIDPVLRR,TIDPVLSA' FROM DUAL
UNION ALL SELECT 'PGS', 'TSRI', 'CODIGO,DETALLE,ESTADO,ID,LSRI,PLNNCDGO,PORCENTAJE,TEXTO,VALOR' FROM DUAL
UNION ALL SELECT 'PGS', 'UXAP', 'APXMCDGO,PJRQCDUS,UXAPCDGO,UXAPFCIN' FROM DUAL
UNION ALL SELECT 'PGS', 'VITP', 'DTDPCDGO,DTIMCDGO,VITPCDGO,VITPNMBR,VITPPRCT,VITPVLRR,VITPVLSA' FROM DUAL
UNION ALL SELECT 'PGS', 'VIDP', 'DCMPCDGO,DTIMCDGO,VIDPCAVD,VIDPCDGO,VIDPNMBR,VIDPPRCT,VIDPVLRR,VIDPVLSA' FROM DUAL
UNION ALL SELECT 'TSR', 'ADTD', 'ADTDCDGO,ADTDVLCH,ADTDVLEF,ADTDVLRR,BNCOCDGO,CNBCCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'ACPD', 'ACPDCDGO,ACPDFCCR,ACPDMNCH,ACPDMNDP,ACPDMNEF,ACPDMNTT,ACPDNMCJ,ACPDSLCC,CRCJCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'APDS', 'APDSCDGO,APDSSLCC,APDSTPOO,APDSVLRR,BEXTCDGO,BNCOCDGO,CBROCDGO,CCHQCDGO,CCHQNMRO,CNBCCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'BNCO', 'BNCOCDGO,BNCOCNDS,BNCOESTD,BNCOFCDS,BNCOFCIN,BNCONMBR,BNCORYYA,BNCORZZA,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'BEXT', 'BEXTCDGO,BEXTESTD,BEXTFCIN,BEXTNMBR,BEXTTRJT' FROM DUAL
UNION ALL SELECT 'TSR', 'CJCH', 'CJCHCDGO,CJCHESTD,CJCHFCRG,CJCHMNTO,CJCHMXGS,CJCHNMBR,CJCHOBSR,CJCHPRAL,CJCHRSPN,CJCHUSAR,CJCHUSCS,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CJAA', 'CJAACDGO,CJAAESTD,CJAAFCDS,CJAAFCIN,CJAANMBR,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CJCN', 'CJCNCDGO,CJCNCNCT,CJCNESTD,CJCNFCDS,CJCNFCIN,CJCNNMBR,CJINCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CCXC', 'CCXCCDGO,CCXCESTD,CCXCFCIN,CJAACDGO,CJCNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DTCH', 'ASNTCDGO,CHQRCDGO,DTCHBNFC,DTCHCDGO,DTCHEGRS,DTCHFANL,DTCHFCDC,DTCHFENT,DTCHFIMP,DTCHFUSO,DTCHIDBN,DTCHNMRO,DTCHRYYA,DTCHRYYB,DTCHRZZA,DTCHRZZB,DTCHVLRR,PRSNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CHQR', 'CHQRCDGO,CHQRCMNZ,CHQRFCEN,CHQRFCSL,CHQRFNLZ,CHQRNMRO,CHQRRYYA,CHQRRZZA,CNBCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CRCJ', 'ASNTCDGO,CRCJCDGO,CRCJFCHA,CRCJMNCH,CRCJMNEF,CRCJMNRT,CRCJMNTJ,CRCJMNTO,CRCJMNTR,CRCJRYYA,CRCJRZZA,CRCJUSRO,DPSTCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CRCH', 'ASNTCDGO,CJCHCDGO,CRCHCDGO,CRCHDFRN,CRCHESTD,CRCHFCFN,CRCHFCHA,CRCHFCIN,CRCHFCRG,CRCHOBSR,CRCHSLDO,CRCHSLFS,CRCHSLIN,CRCHTAJS,CRCHTGST,CRCHTRPS,CRCHUSAR' FROM DUAL
UNION ALL SELECT 'TSR', 'CBRO', 'ASNTCDGO,CBROCDGO,CBROCLNT,CBRODSCR,CBROFCDS,CBROFCHA,CBROIDNT,CBRONMAS,CBRORYYA,CBRORYYB,CBRORZZA,CBRORZZB,CBROTPCB,CBROTPID,CBROUSRO,CBROVLRR,CJCNCDGO,CRCJCDGO,DPSTCDGO,DTDPCDGO,PJRQCDGO,TTLRCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CCHQ', 'BEXTCDGO,CBROCDGO,CCHQCDGO,CCHQESTD,CCHQNMRO,CCHQVLRR,DTDPCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CEFC', 'CBROCDGO,CEFCCDGO,CEFCVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'CRTN', 'CBROCDGO,CRTNCDGO,CRTNNMRO,CRTNVLRR,DTPLCDGO,PLNSCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CTRJ', 'CBROCDGO,CTRJCDGO,CTRJFCDC,CTRJNMRO,CTRJVCHR,CTRJVLRR,DTPLCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CTRN', 'BEXTCDGO,BNCOCDGO,CBROCDGO,CNBCCDGO,CTRNCDGO,CTRNCTDS,CTRNCTOR,CTRNNMRO,CTRNVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'CNCL', 'CNBCCDGO,CNCLCDGO,CNCLCHNC,CNCLCHQE,CNCLDPST,CNCLDPTR,CNCLESTD,CNCLFCCR,CNCLFCHA,CNCLMTAN,CNCLNCRD,CNCLNCTR,CNCLNDTR,CNCLNTDB,CNCLPRDO,CNCLRYYA,CNCLRZZA,CNCLSILB,CNCLSLDB,CNCLSLDE,CNCLSLDF,CNCLTCTR,CNCLTDTR,CNCLTRCR,CNCLTRDB,CNCLUSCR,CNCLUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CNCT', 'CNBCCDGO,CNCTCDGO,CNCTESTD,CNCTESTR,CNCTFCRG,CNCTFCVR,CNCTPDAS,CNCTPDEX,CNCTTTGR,CNCTUSVR,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CTEB', 'CTEBANOO,CTEBCARG,CTEBCDGO,CTEBCONC,CTEBCRRE,CTEBESTD,CTEBFCCR,CTEBFCRG,CTEBFVNC,CTEBMSSS,CTEBOBSR,CTEBTOTC,CTEBUSCR,PJRQCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CNBC', 'BNCOCDGO,CNBCCBCR,CNBCCDGO,CNBCCHQR,CNBCCLLR,CNBCDRCC,CNBCEMLL,CNBCESTD,CNBCFCCR,CNBCFCDS,CNBCFCIN,CNBCFXXX,CNBCNMRO,CNBCOBSR,CNBCOFCL,CNBCRYYA,CNBCRYYB,CNBCRZZA,CNBCRZZB,CNBCSLIN,CNBCTLF1,CNBCTLF2,CNBCTTLR,PLNNCDGO,PLNNORGN' FROM DUAL
UNION ALL SELECT 'TSR', 'CTBN', 'BEXTCDGO,CTBNCDGO,CTBNESTD,CTBNFCRG,CTBNNMCT,CTBNOBSR,CTBNTPCT,CTBNUSAR,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DBCR', 'ASNTCDGO,CNBCCDGO,DBCRCDGO,DBCRDSCR,DBCRESTD,DBCRFCHA,DBCRNMAS,DBCRUSRO,DSCRTPOO,MVCBCDGO,PJRQCDUS' FROM DUAL
UNION ALL SELECT 'TSR', 'DPST', 'ASNTRTCD,DPSTCDGO,DPSTCHQS,DPSTEFCT,DPSTESTD,DPSTFCHA,DPSTTOTL,DPSTUSRO,PJRQCDGO,PJRQCDUS,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DSDT', 'BEXTCDGO,CBROCDGO,CCHQCDGO,CCHQNMRO,DSDTCDGO,DSDTTPOO,DSDTVLRR,DTDPCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DTCR', 'CBROCDGO,CBROCLNT,CBROFCHA,CBROVLRR,CRCJCDGO,DTCRCDGO,DTCRCHQQ,DTCREFCT,DTCRRTNC,DTCRTRJC,DTCRTRNS' FROM DUAL
UNION ALL SELECT 'TSR', 'DTCL', 'ASNTCDGO,CNCLCDGO,DTCHCDGO,DTCLANOO,DTCLCDGO,DTCLCHQN,DTCLCNCL,DTCLDSCR,DTCLESTD,DTCLFRGS,DTCLIDMV,DTCLMSSS,DTCLNMAS,DTCLRYYA,DTCLRYYB,DTCLRZZA,DTCLRZZB,DTCLVLRR,DTDPCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DTDC', 'DBCRCDGO,DTDCCDGO,DTDCDSCR,DTDCVLRR,DTPLCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DTDP', 'ASNTRTFC,BNCOCDGO,CNBCCDGO,DPSTCDGO,DTDPCDGO,DTDPESTD,DTDPFCEN,DTDPFCRT,DTDPNMDP,DTDPVLCH,DTDPVLEF,DTDPVLRR,USRORTFC,USRTNMBR' FROM DUAL
UNION ALL SELECT 'TSR', 'DEXB', 'CNBCCDGO,DEXBCDGO,DEXBCDMV,DEXBCNCL,DEXBCRDO,DEXBCRDT,DEXBDBTO,DEXBDSCR,DEXBESTD,DEXBESTR,DEXBFCNT,DEXBFCRG,DEXBFTRN,DEXBHASH,DEXBNFIL,DEXBREFR,DEXBSLDO,DEXBUSAR,EXBCCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DTCN', 'CNCLCDGO,DTCNCDGO,DTCNCNSL,DTCNDTAS,DTCNESTD,DTCNFCRG,DTCNIDEX,DTCNOBSR,DTCNTPOO,DTCNVLOR,MVCBCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'PDRC', 'PDRCCDGO,PDRCDRCC,PDRCPRNC,PDRCRYYA,PDRCRZZA,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'EGRS', 'EGRSASNT,EGRSCDGO,EGRSDBAT,EGRSDSCR,EGRSESTD,EGRSFCHA,EGRSFCRG,EGRSOBSR,EGRSPJRQ,EGRSPRDP,EGRSTTLR,EGRSUSAR,EGRSVLOR' FROM DUAL
UNION ALL SELECT 'TSR', 'EXBC', 'CNBCCDGO,EXBCARCH,EXBCCDGO,EXBCESTD,EXBCESTP,EXBCFCRG,EXBCFDSD,EXBCFHST,EXBCFRMT,EXBCHASH,EXBCOBSR,EXBCPRSR,EXBCSLFN,EXBCSLIN,EXBCUSAR,PJRQCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CJIN', 'CJINCDGO,CJINESTD,CJINFCDS,CJINFCIN,CJINNMBR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'GCAS', 'DTASCDGO,GCASCDGO,GRCCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'GRCC', 'CNCTCDGO,GRCCCDGO,GRCCDIFF,GRCCESTD,GRCCFCCN,GRCCFCMN,GRCCFCMX,GRCCOBSR,GRCCTOLD,GRCCUSCN,GRCCVLAS,GRCCVLEX' FROM DUAL
UNION ALL SELECT 'TSR', 'GCEX', 'DEXBCDGO,GCEXCDGO,GRCCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'CNCH', 'CNBCCDGO,CNCHCDGO,CNCHCHNC,CNCHCHQE,CNCHCNCD,CNCHDPST,CNCHDPTR,CNCHESTD,CNCHFCHA,CNCHNCRD,CNCHNCTR,CNCHNDTR,CNCHNTDB,CNCHPRDO,CNCHSILB,CNCHSLDB,CNCHSLDE,CNCHSLDF,CNCHTCTR,CNCHTDTR,CNCHTRCR,CNCHTRDB,CNCHUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'DCHI', 'ASNTCDGO,CNCHCDGO,DCHIANOO,DCHICDGO,DCHICHQN,DCHICNCL,DCHIDSCR,DCHIESTD,DCHIFRGS,DCHIIDMV,DCHIMSSS,DCHINMAS,DCHIRYYA,DCHIRYYB,DCHIRZZA,DCHIRZZB,DCHIVLRR,DTCHCDGO,DTDPCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'INGR', 'INGRASNT,INGRCDGO,INGRCNBC,INGRDSCR,INGRESTD,INGRFCHA,INGRFCRG,INGROBSR,INGRPJRQ,INGRPRDC,INGRREFR,INGRTTLR,INGRUSAR,INGRVLOR' FROM DUAL
UNION ALL SELECT 'TSR', 'CMTV', 'CBROCDGO,CMTVCDGO,CMTVDSCR,CMTVVLRR,DTPLCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'PMTV', 'DTPLCDGO,PGSSCDGO,PLNSCDGO,PMTVCDGO,PMTVDSCR,PMTVVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'MVCB', 'ASNTCDGO,CNBCCDGO,CNCLCDGO,DTCHCDGO,DTDPCDGO,MVCBANOO,MVCBCDGO,MVCBCHQN,MVCBCNCL,MVCBDSCR,MVCBESTD,MVCBFCCN,MVCBFRGS,MVCBIDMV,MVCBMSSS,MVCBNMAS,MVCBRYYA,MVCBRYYB,MVCBRZZA,MVCBRZZB,MVCBVLRR,PJRQCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'MVCH', 'ASNTCDGO,CJCHCDGO,CRCHCDGO,MVCHCDGO,MVCHDSCR,MVCHESTD,MVCHFCHA,MVCHFCRG,MVCHMTAN,MVCHNDOC,MVCHOBSR,MVCHPRDP,MVCHTPOO,MVCHUSAR,MVCHVLOR,PGTRCDGO,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'PGSS', 'ASNTCDGO,DTCHCDGO,PGSSCDGO,PGSSDSCR,PGSSFCDS,PGSSFCHA,PGSSIDNT,PGSSNMAS,PGSSPRVD,PGSSRYYA,PGSSRYYB,PGSSRZZA,PGSSRZZB,PGSSTPID,PGSSTPPG,PGSSUSRO,PGSSVLRR,PJRQCDGO,PJRQCDUS,TPGSCDGO,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'PTCH', 'MVCHCDGO,PTCHCDGO,PTCHFCRG,PTCHNMDC,PTCHPATH,PTCHTPDC,PTCHUSAR' FROM DUAL
UNION ALL SELECT 'TSR', 'PRCC', 'PJRQCDGO,PLNNCDGO,PRCCCDGO,PRCCCLPR,PRCCSLIN,PRCCTPOO,PRRLCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'PRRL', 'PJRQCDGO,PRRLCDGO,PRRLCLRS,PRRLDSSC,PRRLDSVF,PRRLESTD,PRRLRYYA,PRRLRZZA,PRSNCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'SLCB', 'CNBCCDGO,PRDOANNN,PRDOCDGO,PRDOMSSS,SLCBANTR,SLCBCDGO,SLCBCRDT,SLCBDBTO,SLCBFNLL,SLCBNTCR,SLCBNTDB,SLCBTRCR,SLCBTRDB' FROM DUAL
UNION ALL SELECT 'TSR', 'PCNT', 'PCNTCDGO,PCNTCNTC,PCNTPRNC,PCNTRYYA,PCNTRYYB,PCNTRZZA,PCNTRZZB,PCNTTLFN,PDRCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'TCBR', 'CJCNCDGO,CRCJCDGO,PJRQCDGO,TCBRCDGO,TCBRCLNT,TCBRDSCR,TCBRFCDS,TCBRFCHA,TCBRIDNT,TCBRRYYA,TCBRRYYB,TCBRRZZA,TCBRRZZB,TCBRTPCB,TCBRTPID,TCBRUSRO,TCBRVLRR,TTLRCDGO,USXCCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'TCCH', 'BEXTCDGO,TCBRCDGO,TCCHCDGO,TCCHNMRO,TCCHVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TCEF', 'TCBRCDGO,TCEFCDGO,TCEFVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TCRT', 'DTPLCDGO,PLNSCDGO,TCBRCDGO,TCRTCDGO,TCRTNMRO,TCRTVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TCTJ', 'DTPLCDGO,TCBRCDGO,TCTJCDGO,TCTJFCDC,TCTJNMRO,TCTJVCHR,TCTJVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TCTR', 'BEXTCDGO,BNCOCDGO,CNBCCDGO,TCBRCDGO,TCTRCDGO,TCTRCTDS,TCTRCTOR,TCTRNMRO,TCTRVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TDBC', 'DTPLCDGO,PJRQCDGO,PJRQCDUS,TDBCCDGO,TDBCDSCR,TDBCTPOO,TDBCVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TCMT', 'DTPLCDGO,TCBRCDGO,TCMTCDGO,TCMTDSCR,TCMTVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TPMT', 'DTPLCDGO,PLNSCDGO,TPGSCDGO,TPMTCDGO,TPMTDSCR,TPMTVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'TPGS', 'ASNTCDGO,DTCHCDGO,PGSSNMAS,PJRQCDGO,PJRQCDUS,TGSSDSCR,TPGSCDGO,TPGSFCDS,TPGSFCHA,TPGSIDNT,TPGSPRVD,TPGSRYYA,TPGSRYYB,TPGSRZZA,TPGSRZZB,TPGSTPID,TPGSTPPG,TPGSUSRO,TPGSVLRR,TTLRCDGO' FROM DUAL
UNION ALL SELECT 'TSR', 'TTLR', 'PSSSCDGO,TTLRAPIV,TTLRAPLL,TTLRAPRT,TTLRBNFC,TTLRCDGO,TTLRCLNT,TTLRDRCC,TTLREMPL,TTLRESTD,TTLREXTR,TTLRIDNT,TTLRMLLL,TTLRNMBR,TTLRPREL,TTLRPRVD,TTLRRYYA,TTLRRYYB,TTLRRZSC,TTLRRZZA,TTLRRZZB,TTLRSCOO,TTLRTLFN,TTLRTPAT' FROM DUAL
UNION ALL SELECT 'TSR', 'TRNS', 'BNCODSTN,BNCOORGN,CNBCDSTN,CNBCORGN,CNTADSTN,CNTAORGN,TRNSCDGO,TRNSESTD,TRNSFCHA,TRNSOBSR,TRNSTPOO,TRNSUSRO,TRNSVLRR' FROM DUAL
UNION ALL SELECT 'TSR', 'USXC', 'CJAACDGO,PJRQCDUS,USXCCDGO,USXCESTD,USXCFCDS,USXCFCIN,USXCNMBR' FROM DUAL
),
COLS AS (
    SELECT E.OWNER_ESP,
           E.TABLA_ESP,
           TRIM(REGEXP_SUBSTR(E.COLS, '[^,]+', 1, L.LVL)) AS COLUMNA_ESP
    FROM   ESPERADO E
           CROSS JOIN (SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 60) L
    WHERE  REGEXP_SUBSTR(E.COLS, '[^,]+', 1, L.LVL) IS NOT NULL
)
-- ============================================================================
-- CONSULTA A - Tablas mapeadas por una entidad que NO existen en la base.
-- Esperado: 0 filas.
-- ============================================================================
SELECT DISTINCT 'A. TABLA INEXISTENTE' AS HALLAZGO,
       C.OWNER_ESP || '.' || C.TABLA_ESP AS OBJETO,
       NULL AS COLUMNA
FROM   COLS C
WHERE  NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP)

UNION ALL

-- ============================================================================
-- CONSULTA B - Columnas mapeadas que faltan, en tablas que SI existen.
-- Cada fila es un ORA-00904 esperando el despliegue. Esperado: 0 filas.
-- ============================================================================
SELECT 'B. COLUMNA FALTANTE',
       C.OWNER_ESP || '.' || C.TABLA_ESP,
       C.COLUMNA_ESP
FROM   COLS C
WHERE  EXISTS     (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP)
AND    NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP
                   AND   A.COLUMN_NAME = C.COLUMNA_ESP)

ORDER BY 1, 2, 3;
