-- =============================================================================
-- SCRIPT: Renombrar columnas de DCTX, DCXP y CRTX al estándar de 4 letras
-- Schema:  PGS
-- Fecha:   2026-07-25
-- Motivo:  Las tablas fueron creadas con nombres largos (CARGATXT, DOCUMENTO,
--          VALORSINIMPUESTOS_CARGA, etc.) pero los modelos Java esperan el
--          estándar de 4 letras (CRTXCDGO, DCXPCDGO, DCTXVSIM, etc.)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TABLA PGS.DCTX (DetalleCargaTxt)
-- -----------------------------------------------------------------------------
-- PK
ALTER TABLE PGS.DCTX RENAME COLUMN ID                      TO DCTXCDGO;
-- FKs
ALTER TABLE PGS.DCTX RENAME COLUMN CARGATXT                TO CRTXCDGO;
ALTER TABLE PGS.DCTX RENAME COLUMN DOCUMENTO               TO DCXPCDGO;
-- Valores snapshot
ALTER TABLE PGS.DCTX RENAME COLUMN VALORSINIMPUESTOS_CARGA TO DCTXVSIM;
ALTER TABLE PGS.DCTX RENAME COLUMN IVA_CARGA               TO DCTXIVAA;
ALTER TABLE PGS.DCTX RENAME COLUMN IMPORTETOTAL_CARGA      TO DCTXIMTT;
ALTER TABLE PGS.DCTX RENAME COLUMN FECHAAUTORIZACION_CARGA TO DCTXFAUT;
ALTER TABLE PGS.DCTX RENAME COLUMN FECHAEMISION_CARGA      TO DCTXFEMS;
-- Resultado y observación
ALTER TABLE PGS.DCTX RENAME COLUMN RESULTADO               TO DCTXRSLT;
ALTER TABLE PGS.DCTX RENAME COLUMN OBSERVACION             TO DCTXOBSR;

-- -----------------------------------------------------------------------------
-- 2. TABLA PGS.DCXP (DocumentoCxp)
-- -----------------------------------------------------------------------------
ALTER TABLE PGS.DCXP RENAME COLUMN ID                        TO DCXPCDGO;
ALTER TABLE PGS.DCXP RENAME COLUMN EMPRESA                   TO DCXPPJRQ;
ALTER TABLE PGS.DCXP RENAME COLUMN RUCEMISOR                 TO DCXPRCEM;
ALTER TABLE PGS.DCXP RENAME COLUMN RAZONSOCIALEMISOR         TO DCXPRSEM;
ALTER TABLE PGS.DCXP RENAME COLUMN TIPOCOMPROBANTE           TO DCXPTPCM;
ALTER TABLE PGS.DCXP RENAME COLUMN SERIECOMPROBANTE          TO DCXPSRCM;
ALTER TABLE PGS.DCXP RENAME COLUMN CLAVEACCESO               TO DCXPCLAC;
ALTER TABLE PGS.DCXP RENAME COLUMN FECHAAUTORIZACION         TO DCXPFAUT;
ALTER TABLE PGS.DCXP RENAME COLUMN FECHAEMISION              TO DCXPFEMS;
ALTER TABLE PGS.DCXP RENAME COLUMN IDENTIFICACIONRECEPTOR    TO DCXPIDRC;
ALTER TABLE PGS.DCXP RENAME COLUMN VALORSINIMPUESTOS         TO DCXPVSIM;
ALTER TABLE PGS.DCXP RENAME COLUMN IVA                       TO DCXPIVAA;
ALTER TABLE PGS.DCXP RENAME COLUMN IMPORTETOTAL              TO DCXPIMTT;
ALTER TABLE PGS.DCXP RENAME COLUMN NUMERODOCUMENTOMODIFICADO TO DCXPNDMD;
ALTER TABLE PGS.DCXP RENAME COLUMN ESTADODOCUMENTO          TO DCXPESTD;
ALTER TABLE PGS.DCXP RENAME COLUMN PATHXML                   TO DCXPPXML;
ALTER TABLE PGS.DCXP RENAME COLUMN FECHACARGAXML             TO DCXPFCXM;
ALTER TABLE PGS.DCXP RENAME COLUMN USUARIOCARGAXML           TO DCXPUCXM;
ALTER TABLE PGS.DCXP RENAME COLUMN IDDOCUMENTOBD             TO DCXPIDBD;
ALTER TABLE PGS.DCXP RENAME COLUMN TIPOTABLADESTINO          TO DCXPTBTD;
ALTER TABLE PGS.DCXP RENAME COLUMN FECHAREGISTROBD           TO DCXPFRBD;
ALTER TABLE PGS.DCXP RENAME COLUMN USUARIOREGISTROBD         TO DCXPURBD;
ALTER TABLE PGS.DCXP RENAME COLUMN FECHAREVERSION            TO DCXPFRVS;
ALTER TABLE PGS.DCXP RENAME COLUMN USUARIOREVERSION          TO DCXPURVS;
ALTER TABLE PGS.DCXP RENAME COLUMN NOVEDAD                   TO DCXPNVDD;
ALTER TABLE PGS.DCXP RENAME COLUMN ESTADONOVEDAD             TO DCXPENOV;
ALTER TABLE PGS.DCXP RENAME COLUMN OBSERVACION               TO DCXPOBSR;

-- -----------------------------------------------------------------------------
-- 3. TABLA PGS.CRTX (CargaArchivoTxt)
-- -----------------------------------------------------------------------------
ALTER TABLE PGS.CRTX RENAME COLUMN ID                  TO CRTXCDGO;
ALTER TABLE PGS.CRTX RENAME COLUMN EMPRESA             TO CRTXPJRQ;
ALTER TABLE PGS.CRTX RENAME COLUMN USUARIO             TO CRTXUSAR;
ALTER TABLE PGS.CRTX RENAME COLUMN FECHACARGA          TO CRTXFCGA;
ALTER TABLE PGS.CRTX RENAME COLUMN NOMBREARCHIVO       TO CRTXNARV;
ALTER TABLE PGS.CRTX RENAME COLUMN TOTALREGISTROS      TO CRTXTTLR;
ALTER TABLE PGS.CRTX RENAME COLUMN REGISTROSNUEVOS     TO CRTXRGNV;
ALTER TABLE PGS.CRTX RENAME COLUMN REGISTROSDUPLICADOS TO CRTXRGDP;
ALTER TABLE PGS.CRTX RENAME COLUMN REGISTROSNOVEDAD    TO CRTXRGND;
ALTER TABLE PGS.CRTX RENAME COLUMN ESTADO              TO CRTXESTD;
ALTER TABLE PGS.CRTX RENAME COLUMN OBSERVACION         TO CRTXOBSR;

-- =============================================================================
-- VERIFICACIÓN — ejecutar después para confirmar
-- =============================================================================
-- SELECT COLUMN_NAME, TABLE_NAME
-- FROM ALL_TAB_COLUMNS
-- WHERE OWNER = 'PGS'
--   AND TABLE_NAME IN ('DCTX','DCXP','CRTX')
-- ORDER BY TABLE_NAME, COLUMN_ID;
