/*
 * SCRIPT: Nuevas tablas para carga y seguimiento de documentos CXP del SRI
 * Módulo: CXP (Cuentas por Pagar) - Schema PGS
 * Fecha:  2026-07-19
 *
 * Orden de ejecución: 1 de 5
 * Siguiente script:   02-alter-periodo-contable-cxp.sql
 *
 * =============================================================================
 * CONCEPTO:
 *   CRTX (CargaArchivoTxt) → Cabecera de cada archivo TXT cargado.
 *   DCXP (DocumentoCxp)    → Un registro ÚNICO por documento de proveedor
 *                            identificado por claveAcceso. Aquí vive todo el
 *                            seguimiento: XML, registro en BD, reversión, novedad.
 *   DCTX (DetalleCargaTxt) → Una línea por cada aparición del documento en un
 *                            archivo TXT. Referencia al DCXP correspondiente.
 *                            Puede haber N líneas para un mismo documento.
 *
 * ESTADOS estadoDocumento (DCXP):
 *   1 = LEIDO          - Documento leído del TXT, pendiente de XML
 *   2 = XML_CARGADO    - XML subido, pendiente de registro en BD
 *   3 = REGISTRADO_BD  - Registros creados en tablas destino (FacturaCompra, etc.)
 *   4 = ERROR          - Error en algún paso del proceso
 *   5 = NOVEDAD        - Ya existía con valores distintos, pendiente resolución
 *   6 = REVERTIDO      - Registros de BD eliminados (reversión aplicada)
 *
 * ESTADOS estadoNovedad (DCXP):
 *   1 = PENDIENTE    - Novedad detectada, sin resolución
 *   2 = REEMPLAZADO  - Usuario eligió reemplazar XML anterior y re-registrar
 *   3 = MANTENIDO    - Usuario eligió mantener el documento previo sin cambios
 *
 * RESULTADO (DCTX):
 *   1 = NUEVO        - Primera vez que aparece el documento   (Rubro 174)
 *   2 = DUPLICADO    - Ya existía en DCXP sin diferencias de valores
 *   3 = NOVEDAD      - Ya existía en DCXP pero con diferencias de valores/fechas
 *   4 = IGNORADO     - Receptor no coincide con la empresa
 *   5 = DESAPARECIDO - Estaba activo en el período y no apareció en esta carga
 * =============================================================================
 */

-- -----------------------------------------------------------------------------
-- 1. TABLA CABECERA: PGS.CRTX (CargaArchivoTxt)
-- -----------------------------------------------------------------------------
CREATE TABLE PGS.CRTX (
    ID                  NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    EMPRESA             NUMBER(11)      NOT NULL,
    USUARIO             NUMBER(11)      NOT NULL,
    FECHACARGA          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    NOMBREARCHIVO       VARCHAR2(500),
    TOTALREGISTROS      NUMBER(11)      DEFAULT 0,
    REGISTROSNUEVOS     NUMBER(11)      DEFAULT 0,
    REGISTROSDUPLICADOS NUMBER(11)      DEFAULT 0,
    REGISTROSNOVEDAD    NUMBER(11)      DEFAULT 0,
    ESTADO              NUMBER(2),
    OBSERVACION         VARCHAR2(2000),
    CONSTRAINT PK_CRTX         PRIMARY KEY (ID),
    CONSTRAINT FK_CRTX_EMPRESA FOREIGN KEY (EMPRESA) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_CRTX_USUARIO FOREIGN KEY (USUARIO) REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX PGS.IDX_CRTX_EMPRESA ON PGS.CRTX(EMPRESA);

COMMENT ON TABLE  PGS.CRTX                     IS 'Cabecera de carga de archivo TXT recibidos del SRI';
COMMENT ON COLUMN PGS.CRTX.ESTADO              IS '1=PROCESADO 2=ERROR_PARCIAL';
COMMENT ON COLUMN PGS.CRTX.TOTALREGISTROS      IS 'Total de líneas del archivo (excluye encabezado e ignorados)';
COMMENT ON COLUMN PGS.CRTX.REGISTROSNUEVOS     IS 'Documentos nuevos en esta carga';
COMMENT ON COLUMN PGS.CRTX.REGISTROSDUPLICADOS IS 'Documentos ya existentes sin diferencias de valores';
COMMENT ON COLUMN PGS.CRTX.REGISTROSNOVEDAD    IS 'Documentos ya existentes con diferencias de valores/fechas';


-- -----------------------------------------------------------------------------
-- 2. TABLA DOCUMENTO ÚNICO: PGS.DCXP (DocumentoCxp)
--    Un registro por claveAcceso. Aquí vive todo el ciclo de vida del documento.
-- -----------------------------------------------------------------------------
CREATE TABLE PGS.DCXP (
    ID                        NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    -- Empresa receptora
    EMPRESA                   NUMBER(11)      NOT NULL,
    -- Datos del documento (del TXT SRI)
    RUCEMISOR                 VARCHAR2(20),
    RAZONSOCIALEMISOR         VARCHAR2(500),
    TIPOCOMPROBANTE           VARCHAR2(100),
    SERIECOMPROBANTE          VARCHAR2(50),
    CLAVEACCESO               VARCHAR2(100)   NOT NULL,
    FECHAAUTORIZACION         TIMESTAMP,
    FECHAEMISION              DATE,
    IDENTIFICACIONRECEPTOR    VARCHAR2(20),
    VALORSINIMPUESTOS         NUMBER(14,2),
    IVA                       NUMBER(12,2),
    IMPORTETOTAL              NUMBER(14,2),
    NUMERODOCUMENTOMODIFICADO VARCHAR2(50),
    -- Control de estado del ciclo de vida
    ESTADODOCUMENTO           NUMBER(2)       DEFAULT 1,
    -- XML (Fase 2)
    PATHXML                   VARCHAR2(2000),
    FECHACARGAXML             TIMESTAMP,
    USUARIOCARGAXML           NUMBER(11),
    -- Registro en BD (Fase 3)
    IDDOCUMENTOBD             NUMBER(11),
    TIPOTABLADESTINO          VARCHAR2(50),
    FECHAREGISTROBD           TIMESTAMP,
    USUARIOREGISTROBD         NUMBER(11),
    -- Reversión (Fase 5)
    FECHAREVERSION            TIMESTAMP,
    USUARIOREVERSION          NUMBER(11),
    -- Novedad (Fase 4)
    NOVEDAD                   VARCHAR2(2000),
    ESTADONOVEDAD             NUMBER(2),
    -- General
    OBSERVACION               VARCHAR2(2000),
    CONSTRAINT PK_DCXP              PRIMARY KEY (ID),
    CONSTRAINT UQ_DCXP_CLAVEACCESO  UNIQUE (CLAVEACCESO),
    CONSTRAINT FK_DCXP_EMPRESA      FOREIGN KEY (EMPRESA)           REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_DCXP_UCARGAXML    FOREIGN KEY (USUARIOCARGAXML)   REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_DCXP_UREGISTROBD  FOREIGN KEY (USUARIOREGISTROBD) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_DCXP_UREVERSION   FOREIGN KEY (USUARIOREVERSION)  REFERENCES SCP.PJRQ(PJRQCDGO)
);

CREATE INDEX PGS.IDX_DCXP_EMPRESA          ON PGS.DCXP (EMPRESA);
CREATE INDEX PGS.IDX_DCXP_CLAVEACCESO      ON PGS.DCXP (CLAVEACCESO);
CREATE INDEX PGS.IDX_DCXP_ESTADODOCUMENTO  ON PGS.DCXP (ESTADODOCUMENTO);
CREATE INDEX PGS.IDX_DCXP_IDENTIFICACIONREC ON PGS.DCXP (IDENTIFICACIONRECEPTOR);
CREATE INDEX PGS.IDX_DCXP_RUCEMISOR        ON PGS.DCXP (RUCEMISOR);

COMMENT ON TABLE  PGS.DCXP                  IS 'Documento único por claveAcceso. Ciclo de vida completo del documento CXP.';
COMMENT ON COLUMN PGS.DCXP.EMPRESA          IS 'Empresa receptora del documento.';
COMMENT ON COLUMN PGS.DCXP.ESTADODOCUMENTO  IS '1=LEIDO 2=XML_CARGADO 3=REGISTRADO_BD 4=ERROR 5=NOVEDAD 6=REVERTIDO';
COMMENT ON COLUMN PGS.DCXP.TIPOTABLADESTINO IS 'FACTURA_COMPRA|NOTA_CREDITO_COMPRA|NOTA_DEBITO_COMPRA|RETENCION_COMPRA|RETENCION_COMPRA_V2|LIQUIDACION_COMPRA_COMPRA';
COMMENT ON COLUMN PGS.DCXP.IDDOCUMENTOBD    IS 'ID del registro en la tabla destino (FacturaCompra.id, NotaCreditoCompra.id, etc.)';
COMMENT ON COLUMN PGS.DCXP.ESTADONOVEDAD    IS '1=PENDIENTE 2=REEMPLAZADO 3=MANTENIDO';
COMMENT ON COLUMN PGS.DCXP.NOVEDAD          IS 'Descripción de las diferencias detectadas respecto a la carga previa';


-- -----------------------------------------------------------------------------
-- 3. TABLA LÍNEA DE CARGA: PGS.DCTX (DetalleCargaTxt)
--    Una fila por cada aparición de un documento en un archivo TXT.
-- -----------------------------------------------------------------------------
CREATE TABLE PGS.DCTX (
    ID                      NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    CARGATXT                NUMBER(11)      NOT NULL,
    DOCUMENTO               NUMBER(11)      NOT NULL,
    -- Snapshot de los valores tal como vinieron en ESTA carga
    VALORSINIMPUESTOS_CARGA NUMBER(14,2),
    IVA_CARGA               NUMBER(12,2),
    IMPORTETOTAL_CARGA      NUMBER(14,2),
    FECHAAUTORIZACION_CARGA TIMESTAMP,
    FECHAEMISION_CARGA      DATE,
    -- Resultado numérico (Rubro 174): 1=NUEVO 2=DUPLICADO 3=NOVEDAD 4=IGNORADO 5=DESAPARECIDO
    RESULTADO               NUMBER(2),
    OBSERVACION             VARCHAR2(2000),
    CONSTRAINT PK_DCTX           PRIMARY KEY (ID),
    CONSTRAINT FK_DCTX_CARGATXT  FOREIGN KEY (CARGATXT)  REFERENCES PGS.CRTX(ID),
    CONSTRAINT FK_DCTX_DOCUMENTO FOREIGN KEY (DOCUMENTO) REFERENCES PGS.DCXP(ID)
);

CREATE INDEX PGS.IDX_DCTX_CARGATXT  ON PGS.DCTX (CARGATXT);
CREATE INDEX PGS.IDX_DCTX_DOCUMENTO ON PGS.DCTX (DOCUMENTO);

COMMENT ON TABLE  PGS.DCTX                         IS 'Línea de archivo TXT. N filas por documento si aparece en varias cargas.';
COMMENT ON COLUMN PGS.DCTX.CARGATXT               IS 'FK a CRTX: archivo TXT del que proviene esta línea';
COMMENT ON COLUMN PGS.DCTX.DOCUMENTO              IS 'FK a DCXP: documento único al que corresponde esta línea';
COMMENT ON COLUMN PGS.DCTX.RESULTADO              IS 'Rubro 174: 1=NUEVO 2=DUPLICADO 3=NOVEDAD 4=IGNORADO 5=DESAPARECIDO';
COMMENT ON COLUMN PGS.DCTX.VALORSINIMPUESTOS_CARGA IS 'Valor que traía el TXT en esta carga (puede diferir del DCXP si hubo novedad)';
COMMENT ON COLUMN PGS.DCTX.IVA_CARGA              IS 'IVA que traía el TXT en esta carga';
COMMENT ON COLUMN PGS.DCTX.IMPORTETOTAL_CARGA     IS 'Importe total que traía el TXT en esta carga';


-- =============================================================================
-- MIGRACIÓN (solo si ya existía DCTX con la estructura anterior)
-- =============================================================================

-- Paso M1: Renombrar la tabla antigua
-- RENAME PGS.DCTX TO PGS.DCTX_OLD;

-- Paso M2: Crear la nueva DCTX (ejecutar sección 3 de arriba)

-- Paso M3: Poblar DCXP con el registro más reciente por CLAVEACCESO
/*
INSERT INTO PGS.DCXP (
    EMPRESA, RUCEMISOR, RAZONSOCIALEMISOR, TIPOCOMPROBANTE, SERIECOMPROBANTE,
    CLAVEACCESO, FECHAAUTORIZACION, FECHAEMISION, IDENTIFICACIONRECEPTOR,
    VALORSINIMPUESTOS, IVA, IMPORTETOTAL, NUMERODOCUMENTOMODIFICADO,
    ESTADODOCUMENTO, PATHXML, FECHACARGAXML, USUARIOCARGAXML,
    IDDOCUMENTOBD, TIPOTABLADESTINO, FECHAREGISTROBD, USUARIOREGISTROBD,
    FECHAREVERSION, USUARIOREVERSION, NOVEDAD, ESTADONOVEDAD, OBSERVACION
)
SELECT c.EMPRESA,
       o.RUCEMISOR, o.RAZONSOCIALEMISOR, o.TIPOCOMPROBANTE, o.SERIECOMPROBANTE,
       o.CLAVEACCESO, o.FECHAAUTORIZACION, o.FECHAEMISION, o.IDENTIFICACIONRECEPTOR,
       o.VALORSINIMPUESTOS, o.IVA, o.IMPORTETOTAL, o.NUMERODOCUMENTOMODIFICADO,
       o.ESTADODOCUMENTO, o.PATHXML, o.FECHACARGAXML, o.USUARIOCARGAXML,
       o.IDDOCUMENTOBD, o.TIPOTABLADESTINO, o.FECHAREGISTROBD, o.USUARIOREGISTROBD,
       o.FECHAREVERSION, o.USUARIOREVERSION, o.NOVEDAD, o.ESTADONOVEDAD, o.OBSERVACION
FROM PGS.DCTX_OLD o
JOIN PGS.CRTX c ON c.ID = o.CARGATXT
WHERE o.ID = (
    SELECT MAX(o2.ID) FROM PGS.DCTX_OLD o2 WHERE o2.CLAVEACCESO = o.CLAVEACCESO
);
COMMIT;
*/

-- Paso M4: Poblar nueva DCTX mapeando cada línea al DCXP correspondiente
/*
INSERT INTO PGS.DCTX (
    CARGATXT, DOCUMENTO,
    VALORSINIMPUESTOS_CARGA, IVA_CARGA, IMPORTETOTAL_CARGA,
    FECHAAUTORIZACION_CARGA, FECHAEMISION_CARGA,
    RESULTADO, OBSERVACION
)
SELECT o.CARGATXT, d.ID, o.VALORSINIMPUESTOS, o.IVA, o.IMPORTETOTAL,
       o.FECHAAUTORIZACION, o.FECHAEMISION, 1, o.OBSERVACION
FROM PGS.DCTX_OLD o
JOIN PGS.DCXP d ON d.CLAVEACCESO = o.CLAVEACCESO;
COMMIT;
*/

-- Paso M5: Verificar conteos antes de eliminar la tabla antigua
-- SELECT COUNT(*) FROM PGS.DCTX_OLD;
-- SELECT COUNT(*) FROM PGS.DCXP;
-- SELECT COUNT(*) FROM PGS.DCTX;

-- Paso M6: Eliminar tabla antigua
-- DROP TABLE PGS.DCTX_OLD;
