-- =============================================================================
-- 07-reembolso-gastos.sql
-- Facturas de reembolso de gastos (Ficha Técnica SRI, ANEXO 5)
-- Fecha: 2026-08-19
-- Ejecutar como usuario con privilegios sobre el schema PGS.
-- Estándares: docs/estandar/ESTANDARES-CREACION-TABLAS-ORACLE.md
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Flag y totales de reembolso en la cabecera de factura de compra (PGS.FCTC)
--    (columnas 8-char agregadas a tabla legacy, precedente: FCTCEPAG)
-- -----------------------------------------------------------------------------
ALTER TABLE PGS.FCTC ADD (
    FCTCESRM NUMBER(1) DEFAULT 0,
    FCTCCDRM VARCHAR2(2),
    FCTCTCRM NUMBER(14,2),
    FCTCTBRM NUMBER(14,2),
    FCTCTIRM NUMBER(14,2)
);

COMMENT ON COLUMN PGS.FCTC.FCTCESRM IS 'Es factura de reembolso de gastos: 0=No 1=Si';
COMMENT ON COLUMN PGS.FCTC.FCTCCDRM IS 'codDocReembolso del XML (tabla 3 SRI, normalmente 41)';
COMMENT ON COLUMN PGS.FCTC.FCTCTCRM IS 'totalComprobantesReembolso (del XML o recalculado desde PGS.RMBF)';
COMMENT ON COLUMN PGS.FCTC.FCTCTBRM IS 'totalBaseImponibleReembolso';
COMMENT ON COLUMN PGS.FCTC.FCTCTIRM IS 'totalImpuestoReembolso';

-- -----------------------------------------------------------------------------
-- 2. Flag en el documento de la bandeja (PGS.DCXP)
--    El usuario marca "es reembolso" desde la bandeja o desde gestión de
--    documentos; persistirlo aquí hace que sobreviva a reintentos (bloqueantes
--    422, crearProductosYRegistrar, resolverNovedad REEMPLAZAR).
-- -----------------------------------------------------------------------------
ALTER TABLE PGS.DCXP ADD (
    DCXPESRM NUMBER(1) DEFAULT 0
);

COMMENT ON COLUMN PGS.DCXP.DCXPESRM IS 'Marcado como factura de reembolso de gastos: 0=No 1=Si';

-- -----------------------------------------------------------------------------
-- 3. Tabla de detalles de reembolso (PGS.RMBF)
--    Una fila por documento sustento (<reembolsoDetalle> del XML SRI).
--    Cada fila referencia un producto (PGS.PRDP) para la contabilización por
--    grupo de producto, igual que hace PGS.DFCC.PRODUCTO (columna sin FK).
-- -----------------------------------------------------------------------------
CREATE TABLE PGS.RMBF (
    RMBFCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    RMBFFCTC NUMBER          NOT NULL,          -- FK -> PGS.FCTC(ID)
    RMBFTIPR VARCHAR2(2),                       -- tipoIdentificacionProveedorReembolso (tabla 6 SRI)
    RMBFIDPR VARCHAR2(20)    NOT NULL,          -- identificacionProveedorReembolso
    RMBFCDPS VARCHAR2(3)     DEFAULT '593',     -- codPaisPagoProveedorReembolso (tabla 25 SRI)
    RMBFTPPR VARCHAR2(2),                       -- tipoProveedorReembolso (tabla 26: 01=PN 02=Sociedad)
    RMBFCDDC VARCHAR2(2),                       -- codDocReembolso del sustento (tabla 3: 01=Factura...)
    RMBFESTB VARCHAR2(3),                       -- estabDocReembolso
    RMBFPTEM VARCHAR2(3),                       -- ptoEmiDocReembolso
    RMBFSCNL VARCHAR2(9),                       -- secuencialDocReembolso
    RMBFFEMS DATE,                              -- fechaEmisionDocReembolso
    RMBFNAUT VARCHAR2(49),                      -- numeroautorizacionDocReemb
    RMBFBSCR NUMBER(14,2)    DEFAULT 0,         -- base imponible tarifa 0 / no objeto / exento
    RMBFBSGR NUMBER(14,2)    DEFAULT 0,         -- base imponible gravada
    RMBFTRIV NUMBER(5,2),                       -- tarifa IVA de la base gravada (15/12/8/5)
    RMBFVLIV NUMBER(14,2)    DEFAULT 0,         -- valor IVA
    RMBFVLIC NUMBER(14,2)    DEFAULT 0,         -- valor ICE
    RMBFTTAL NUMBER(14,2)    DEFAULT 0,         -- total del documento sustento
    RMBFPRDC NUMBER(11),                        -- id de producto PGS.PRDP (para contabilizacion)
    RMBFORGN NUMBER(1)       DEFAULT 1,         -- origen: 1=XML 2=MANUAL
    RMBFESTD NUMBER(1)       DEFAULT 1,         -- estado: 1=Activo 0=Anulado
    RMBFOBSR VARCHAR2(500),
    CONSTRAINT PK_RMBF PRIMARY KEY (RMBFCDGO),
    CONSTRAINT FK_RMBF_FACTURA FOREIGN KEY (RMBFFCTC) REFERENCES PGS.FCTC(ID)
);

CREATE INDEX PGS.IDX_RMBF_FACTURA  ON PGS.RMBF (RMBFFCTC);
CREATE INDEX PGS.IDX_RMBF_PRODUCTO ON PGS.RMBF (RMBFPRDC);

COMMENT ON TABLE  PGS.RMBF IS 'Detalle de reembolsos de gastos de una factura de compra (un registro por documento sustento / reembolsoDetalle del XML SRI, ANEXO 5 Ficha Tecnica)';
COMMENT ON COLUMN PGS.RMBF.RMBFCDGO IS 'Identificador unico';
COMMENT ON COLUMN PGS.RMBF.RMBFFCTC IS 'FK a la factura de compra PGS.FCTC(ID)';
COMMENT ON COLUMN PGS.RMBF.RMBFTIPR IS 'Tipo identificacion proveedor del gasto (tabla 6 SRI: 04=RUC 05=Cedula 06=Pasaporte 08=Id exterior)';
COMMENT ON COLUMN PGS.RMBF.RMBFIDPR IS 'Identificacion del proveedor del gasto reembolsado';
COMMENT ON COLUMN PGS.RMBF.RMBFCDPS IS 'Codigo pais de pago (tabla 25 SRI, 593=Ecuador)';
COMMENT ON COLUMN PGS.RMBF.RMBFTPPR IS 'Tipo proveedor reembolso (tabla 26 SRI: 01=Persona natural 02=Sociedad)';
COMMENT ON COLUMN PGS.RMBF.RMBFCDDC IS 'Tipo documento sustento (tabla 3 SRI: 01=Factura 03=Liquidacion...)';
COMMENT ON COLUMN PGS.RMBF.RMBFESTB IS 'Establecimiento del documento sustento';
COMMENT ON COLUMN PGS.RMBF.RMBFPTEM IS 'Punto de emision del documento sustento';
COMMENT ON COLUMN PGS.RMBF.RMBFSCNL IS 'Secuencial del documento sustento';
COMMENT ON COLUMN PGS.RMBF.RMBFFEMS IS 'Fecha de emision del documento sustento';
COMMENT ON COLUMN PGS.RMBF.RMBFNAUT IS 'Numero de autorizacion / clave de acceso del documento sustento';
COMMENT ON COLUMN PGS.RMBF.RMBFBSCR IS 'Base imponible tarifa 0 / no objeto / exento';
COMMENT ON COLUMN PGS.RMBF.RMBFBSGR IS 'Base imponible gravada';
COMMENT ON COLUMN PGS.RMBF.RMBFTRIV IS 'Tarifa IVA de la base gravada (15/12/8/5)';
COMMENT ON COLUMN PGS.RMBF.RMBFVLIV IS 'Valor IVA';
COMMENT ON COLUMN PGS.RMBF.RMBFVLIC IS 'Valor ICE';
COMMENT ON COLUMN PGS.RMBF.RMBFTTAL IS 'Total del documento sustento (bases + impuestos)';
COMMENT ON COLUMN PGS.RMBF.RMBFPRDC IS 'Id de producto PGS.PRDP para la contabilizacion por grupo (sin FK, igual que PGS.DFCC.PRODUCTO)';
COMMENT ON COLUMN PGS.RMBF.RMBFORGN IS 'Origen del registro: 1=Leido del XML 2=Ingresado manualmente';
COMMENT ON COLUMN PGS.RMBF.RMBFESTD IS 'Estado: 1=Activo 0=Anulado';
COMMENT ON COLUMN PGS.RMBF.RMBFOBSR IS 'Observacion';

-- -----------------------------------------------------------------------------
-- SELECTs de verificacion post-ejecucion
-- -----------------------------------------------------------------------------
-- SELECT column_name, data_type, data_length FROM all_tab_columns
--  WHERE owner='PGS' AND table_name='RMBF' ORDER BY column_id;
-- SELECT column_name FROM all_tab_columns
--  WHERE owner='PGS' AND table_name='FCTC' AND column_name LIKE 'FCTC%RM';
-- SELECT column_name FROM all_tab_columns
--  WHERE owner='PGS' AND table_name='DCXP' AND column_name='DCXPESRM';
