-- =============================================================================
-- CONSOLIDADO PARA PRODUCCION - Carga automatica CXP desde el SRI
--
-- Reune el DDL de los scripts 07 (reembolso de gastos) y 08 (carga automatica
-- SRI), que son los dos que el WAR nuevo necesita para arrancar.
--
-- ES IDEMPOTENTE: se puede correr en un ambiente que ya tenga parte aplicada,
-- o dos veces seguidas, sin error. Cada bloque comprueba antes de actuar.
--
-- CORRER ANTES DE DESPLEGAR EL WAR. Si el WAR sube primero, el mapeo JPA no
-- encuentra las columnas y WildFly no levanta el despliegue.
--
-- COMO EJECUTARLO
--   DBeaver / SQL Developer / cualquier cliente JDBC:
--       ejecutar como SCRIPT completo (en DBeaver es Alt+X, no Ctrl+Enter).
--       Para ver la traza de que se agrego y que se omitio, activar antes la
--       vista de "Server Output" / DBMS Output. Si no la activas no pasa nada:
--       las consultas de control del final dicen el estado real igual.
--   SQL*Plus:
--       ejecutar SET SERVEROUTPUT ON antes de correr el archivo.
--
--   Este script NO lleva comandos SET ni PROMPT a proposito: son de SQL*Plus y
--   un cliente JDBC los rechaza con ORA-00922.
--
-- Fecha: 2026-08-23
-- =============================================================================


-- =============================================================================
-- CONTROL PREVIO - que hay antes de tocar nada
-- =============================================================================

SELECT 'PGS.FCTC' AS objeto, column_name AS nombre
  FROM all_tab_columns
 WHERE owner = 'PGS' AND table_name = 'FCTC'
   AND column_name IN ('FCTCESRM','FCTCCDRM','FCTCTCRM','FCTCTBRM','FCTCTIRM')
UNION ALL
SELECT 'PGS.DCXP', column_name
  FROM all_tab_columns
 WHERE owner = 'PGS' AND table_name = 'DCXP'
   AND column_name IN ('DCXPESRM','DCXPORXM','DCXPRSRI','DCXPMSRI','DCXPFDSC')
UNION ALL
SELECT 'TABLA', table_name
  FROM all_tables
 WHERE owner = 'PGS' AND table_name = 'RMBF'
 ORDER BY 1, 2;


-- =============================================================================
-- BLOQUE 1 - Columnas de reembolso en PGS.FCTC (script 07)
-- =============================================================================

DECLARE
    PROCEDURE agrega(p_col VARCHAR2, p_tipo VARCHAR2) IS
        c NUMBER;
    BEGIN
        SELECT COUNT(*) INTO c FROM all_tab_columns
         WHERE owner = 'PGS' AND table_name = 'FCTC' AND column_name = p_col;
        IF c = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE PGS.FCTC ADD (' || p_col || ' ' || p_tipo || ')';
            DBMS_OUTPUT.PUT_LINE('  + FCTC.' || p_col || ' agregada');
        ELSE
            DBMS_OUTPUT.PUT_LINE('  = FCTC.' || p_col || ' ya existia, se omite');
        END IF;
    END;
BEGIN
    agrega('FCTCESRM', 'NUMBER(1) DEFAULT 0');
    agrega('FCTCCDRM', 'VARCHAR2(2)');
    agrega('FCTCTCRM', 'NUMBER(14,2)');
    agrega('FCTCTBRM', 'NUMBER(14,2)');
    agrega('FCTCTIRM', 'NUMBER(14,2)');
END;
/


-- =============================================================================
-- BLOQUE 2 - Columnas en PGS.DCXP (scripts 07 y 08)
-- =============================================================================

DECLARE
    PROCEDURE agrega(p_col VARCHAR2, p_tipo VARCHAR2) IS
        c NUMBER;
    BEGIN
        SELECT COUNT(*) INTO c FROM all_tab_columns
         WHERE owner = 'PGS' AND table_name = 'DCXP' AND column_name = p_col;
        IF c = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE PGS.DCXP ADD (' || p_col || ' ' || p_tipo || ')';
            DBMS_OUTPUT.PUT_LINE('  + DCXP.' || p_col || ' agregada');
        ELSE
            DBMS_OUTPUT.PUT_LINE('  = DCXP.' || p_col || ' ya existia, se omite');
        END IF;
    END;
BEGIN
    -- del script 07
    agrega('DCXPESRM', 'NUMBER(1) DEFAULT 0');
    -- del script 08. Nullables a proposito: los documentos historicos se
    -- cargaron a mano y no tienen resultado del SRI. Un DCXPORXM nulo se lee
    -- como "manual, anterior a este cambio".
    agrega('DCXPORXM', 'NUMBER(1)');
    agrega('DCXPRSRI', 'VARCHAR2(30)');
    agrega('DCXPMSRI', 'VARCHAR2(500)');
    agrega('DCXPFDSC', 'TIMESTAMP');
END;
/


-- =============================================================================
-- BLOQUE 3 - Tabla PGS.RMBF con su PK y FK (script 07)
-- =============================================================================

DECLARE
    c NUMBER;
BEGIN
    SELECT COUNT(*) INTO c FROM all_tables
     WHERE owner = 'PGS' AND table_name = 'RMBF';

    IF c > 0 THEN
        DBMS_OUTPUT.PUT_LINE('  = PGS.RMBF ya existia, se omite la creacion');
    ELSE
        EXECUTE IMMEDIATE '
        CREATE TABLE PGS.RMBF (
            RMBFCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
            RMBFFCTC NUMBER          NOT NULL,
            RMBFTIPR VARCHAR2(2),
            RMBFIDPR VARCHAR2(20)    NOT NULL,
            RMBFCDPS VARCHAR2(3)     DEFAULT ''593'',
            RMBFTPPR VARCHAR2(2),
            RMBFCDDC VARCHAR2(2),
            RMBFESTB VARCHAR2(3),
            RMBFPTEM VARCHAR2(3),
            RMBFSCNL VARCHAR2(9),
            RMBFFEMS DATE,
            RMBFNAUT VARCHAR2(49),
            RMBFBSCR NUMBER(14,2)    DEFAULT 0,
            RMBFBSGR NUMBER(14,2)    DEFAULT 0,
            RMBFTRIV NUMBER(5,2),
            RMBFVLIV NUMBER(14,2)    DEFAULT 0,
            RMBFVLIC NUMBER(14,2)    DEFAULT 0,
            RMBFTTAL NUMBER(14,2)    DEFAULT 0,
            RMBFPRDC NUMBER(11),
            RMBFORGN NUMBER(1)       DEFAULT 1,
            RMBFESTD NUMBER(1)       DEFAULT 1,
            RMBFOBSR VARCHAR2(500),
            CONSTRAINT PK_RMBF PRIMARY KEY (RMBFCDGO),
            CONSTRAINT FK_RMBF_FACTURA FOREIGN KEY (RMBFFCTC) REFERENCES PGS.FCTC(ID)
        )';
        DBMS_OUTPUT.PUT_LINE('  + PGS.RMBF creada con PK_RMBF y FK_RMBF_FACTURA');
    END IF;
END;
/


-- =============================================================================
-- BLOQUE 4 - Indices de PGS.RMBF (script 07)
-- =============================================================================

DECLARE
    PROCEDURE crea_indice(p_nombre VARCHAR2, p_columna VARCHAR2) IS
        c NUMBER;
    BEGIN
        SELECT COUNT(*) INTO c FROM all_indexes
         WHERE owner = 'PGS' AND index_name = p_nombre;
        IF c = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX PGS.' || p_nombre
                           || ' ON PGS.RMBF (' || p_columna || ')';
            DBMS_OUTPUT.PUT_LINE('  + indice ' || p_nombre || ' creado');
        ELSE
            DBMS_OUTPUT.PUT_LINE('  = indice ' || p_nombre || ' ya existia, se omite');
        END IF;
    END;
BEGIN
    crea_indice('IDX_RMBF_FACTURA',  'RMBFFCTC');
    crea_indice('IDX_RMBF_PRODUCTO', 'RMBFPRDC');
END;
/


-- =============================================================================
-- BLOQUE 5 - Comentarios. Se sobrescriben, no fallan al repetir.
-- =============================================================================

COMMENT ON COLUMN PGS.FCTC.FCTCESRM IS 'Es factura de reembolso de gastos: 0=No 1=Si';

COMMENT ON COLUMN PGS.FCTC.FCTCCDRM IS 'codDocReembolso del XML (tabla 3 SRI, normalmente 41)';

COMMENT ON COLUMN PGS.FCTC.FCTCTCRM IS 'totalComprobantesReembolso (del XML o recalculado desde PGS.RMBF)';

COMMENT ON COLUMN PGS.FCTC.FCTCTBRM IS 'totalBaseImponibleReembolso';

COMMENT ON COLUMN PGS.FCTC.FCTCTIRM IS 'totalImpuestoReembolso';

COMMENT ON COLUMN PGS.DCXP.DCXPESRM IS 'Marcado como factura de reembolso de gastos: 0=No 1=Si';

COMMENT ON COLUMN PGS.DCXP.DCXPORXM IS 'Origen del XML: 1=Manual (subido por el usuario) 2=SRI (descargado por servicio web). NULL=historico anterior al cambio';

COMMENT ON COLUMN PGS.DCXP.DCXPRSRI IS 'Resultado del ultimo intento de descarga: DESCARGADO, FUERA_VENTANA, NO_ENCONTRADO, NO_AUTORIZADO, ERROR_CONEXION';

COMMENT ON COLUMN PGS.DCXP.DCXPMSRI IS 'Mensaje devuelto por el SRI, o el motivo calculado localmente cuando no se llego a llamar';

COMMENT ON COLUMN PGS.DCXP.DCXPFDSC IS 'Fecha y hora del ultimo intento de descarga del XML desde el SRI';

COMMENT ON TABLE PGS.RMBF IS 'Detalle de reembolsos de gastos de una factura de compra (un registro por documento sustento / reembolsoDetalle del XML SRI, ANEXO 5 Ficha Tecnica)';

COMMIT;


-- =============================================================================
-- CONTROL POSTERIOR - deben salir las 10 columnas nuevas
-- =============================================================================

SELECT 'PGS.FCTC' AS objeto, column_name AS nombre, data_type, nullable
  FROM all_tab_columns
 WHERE owner = 'PGS' AND table_name = 'FCTC'
   AND column_name IN ('FCTCESRM','FCTCCDRM','FCTCTCRM','FCTCTBRM','FCTCTIRM')
UNION ALL
SELECT 'PGS.DCXP', column_name, data_type, nullable
  FROM all_tab_columns
 WHERE owner = 'PGS' AND table_name = 'DCXP'
   AND column_name IN ('DCXPESRM','DCXPORXM','DCXPRSRI','DCXPMSRI','DCXPFDSC')
 ORDER BY 1, 2;


-- Debe devolver una fila: RMBF
SELECT table_name FROM all_tables WHERE owner = 'PGS' AND table_name = 'RMBF';


-- Deben devolver dos filas cada una
SELECT constraint_name, constraint_type
  FROM all_constraints
 WHERE owner = 'PGS' AND table_name = 'RMBF'
   AND constraint_name IN ('PK_RMBF','FK_RMBF_FACTURA');

SELECT index_name FROM all_indexes
 WHERE owner = 'PGS' AND index_name IN ('IDX_RMBF_FACTURA','IDX_RMBF_PRODUCTO');


-- Los datos existentes no deben haber cambiado. Las columnas nuevas salen en
-- cero salvo DCXPESRM y FCTCESRM, que llevan DEFAULT 0 y se pueblan solas.
SELECT COUNT(*)          AS total_documentos,
       COUNT(DCXPPXML)   AS con_path_xml,
       COUNT(DCXPORXM)   AS con_origen_xml,
       COUNT(DCXPRSRI)   AS con_resultado_sri
  FROM PGS.DCXP;

SELECT COUNT(*) AS total_facturas_compra FROM PGS.FCTC;


-- =============================================================================
-- ROLLBACK - solo si hay que deshacer. Descomentar y ejecutar.
-- Borra los datos de todas estas columnas y la tabla completa.
-- =============================================================================
--
-- DROP TABLE PGS.RMBF CASCADE CONSTRAINTS;
-- ALTER TABLE PGS.FCTC DROP (FCTCESRM, FCTCCDRM, FCTCTCRM, FCTCTBRM, FCTCTIRM);
-- ALTER TABLE PGS.DCXP DROP (DCXPESRM, DCXPORXM, DCXPRSRI, DCXPMSRI, DCXPFDSC);
-- COMMIT;
