-- =====================================================================================
-- e2-78 — DDL: devolución del saldo de anticipos de un proveedor (depósito en nuestro banco)
--          PGS.DVPR (cabecera = el depósito) y PGS.DDPR (detalle = cuánto devuelve cada anticipo)
-- Equipo omen-saa-2 · 2026-10-01 · Diseño: docs/logica-negocio/cxp/API-DEVOLUCION-ANTICIPO-PROVEEDOR.md
--
-- ⛔ VA ANTES DEL WAR que trae las entidades DevolucionAnticipoProveedor / DetalleDevolucionAnticipo.
--    Con el WAR primero, cualquier lectura de esas entidades revienta con ORA-00942.
-- PK por IDENTITY: no hay secuencia que sincronizar.
-- FK solo dentro de PGS (a ANTP y entre las dos tablas). Hacia TSR (titular, cuenta bancaria), CNT
-- (asiento) y SCP (empresa) NO hay FK: una FK entre esquemas exige GRANT REFERENCES, y un GRANT que
-- falla en silencio ya costó dos scripts (estado del equipo §27).
-- Correr de corrido: el BLOQUE 1 se detiene solo si alguna tabla ya existe.
-- =====================================================================================

-- BLOQUE 0 — CONTROL ANTES: las dos tablas no deben existir (ESPERADO: CERO filas)
SELECT 'BLOQUE 0 - no deben existir' AS bloque, OWNER, TABLE_NAME
  FROM ALL_TABLES WHERE TABLE_NAME IN ('DVPR', 'DDPR');

-- BLOQUE 1 — DDL
DECLARE
    v_existen NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existen FROM ALL_TABLES WHERE TABLE_NAME IN ('DVPR', 'DDPR');
    IF v_existen > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'DVPR o DDPR ya existen en algún esquema: el nombre de 4 letras '
            || 'es único en todo el proyecto. No se crea nada; revisar el BLOQUE 0.');
    END IF;

    EXECUTE IMMEDIATE q'[
    CREATE TABLE PGS.DVPR (
        DVPRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        DVPRPJRQ NUMBER NOT NULL,
        DVPRTTLR NUMBER NOT NULL,
        DVPRCNBC NUMBER NOT NULL,
        DVPRFCHA DATE NOT NULL,
        DVPRVLOR NUMBER(18,2) NOT NULL,
        DVPRREFR VARCHAR2(200),
        DVPROBSR VARCHAR2(2000),
        DVPRASNT NUMBER,
        DVPRESTD NUMBER DEFAULT 1 NOT NULL,
        DVPRMTAN VARCHAR2(1000),
        DVPRFCAN TIMESTAMP,
        DVPRUSAR NUMBER,
        DVPRFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_DVPR PRIMARY KEY (DVPRCDGO),
        CONSTRAINT CK_DVPRESTD CHECK (DVPRESTD IN (1, 2)),
        CONSTRAINT CK_DVPRVLOR CHECK (DVPRVLOR > 0)
    )]';

    EXECUTE IMMEDIATE 'CREATE INDEX PGS.IX_DVPR_TTLR ON PGS.DVPR (DVPRTTLR)';
    EXECUTE IMMEDIATE 'CREATE INDEX PGS.IX_DVPR_ASNT ON PGS.DVPR (DVPRASNT)';

    EXECUTE IMMEDIATE q'[
    CREATE TABLE PGS.DDPR (
        DDPRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        DVPRCDGO NUMBER NOT NULL,
        ANTPCDGO NUMBER NOT NULL,
        DDPRVLOR NUMBER(18,2) NOT NULL,
        CONSTRAINT PK_DDPR PRIMARY KEY (DDPRCDGO),
        CONSTRAINT FK_DDPR_DVPR FOREIGN KEY (DVPRCDGO) REFERENCES PGS.DVPR (DVPRCDGO),
        CONSTRAINT FK_DDPR_ANTP FOREIGN KEY (ANTPCDGO) REFERENCES PGS.ANTP (ANTPCDGO),
        CONSTRAINT CK_DDPRVLOR CHECK (DDPRVLOR > 0),
        CONSTRAINT UK_DDPR_DVPR_ANTP UNIQUE (DVPRCDGO, ANTPCDGO)
    )]';

    EXECUTE IMMEDIATE 'CREATE INDEX PGS.IX_DDPR_ANTP ON PGS.DDPR (ANTPCDGO)';

    EXECUTE IMMEDIATE q'[COMMENT ON TABLE PGS.DVPR IS 'Devolucion de saldo de anticipos de un proveedor: un deposito del proveedor en una cuenta bancaria propia. Asiento DEBE banco / HABER anticipos del proveedor']';
    EXECUTE IMMEDIATE q'[COMMENT ON TABLE PGS.DDPR IS 'Cuanto de cada anticipo (PGS.ANTP) cubre una devolucion. La suma de DDPRVLOR es DVPRVLOR']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PGS.DVPR.DVPRESTD IS '1 ACTIVA, 2 ANULADA']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PGS.DVPR.DVPRPJRQ IS 'Empresa (SCP.PJRQ, sin FK: otro esquema)']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PGS.DVPR.DVPRTTLR IS 'Proveedor (TSR.TTLR, sin FK: otro esquema)']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PGS.DVPR.DVPRCNBC IS 'Cuenta bancaria propia donde entro el deposito (TSR.CNBC, sin FK: otro esquema)']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN PGS.DVPR.DVPRASNT IS 'Asiento de la devolucion (CNT.ASNT, sin FK: otro esquema)']';
END;
/

-- BLOQUE 2 — CONTROL DESPUÉS
-- ESPERADO: 2 tablas, y 8 restricciones con nombre
--   DVPR: PK_DVPR, CK_DVPRESTD, CK_DVPRVLOR
--   DDPR: PK_DDPR, FK_DDPR_DVPR, FK_DDPR_ANTP, CK_DDPRVLOR, UK_DDPR_DVPR_ANTP
SELECT 'BLOQUE 2 - tablas' AS bloque, OWNER, TABLE_NAME
  FROM ALL_TABLES WHERE TABLE_NAME IN ('DVPR', 'DDPR');
SELECT 'BLOQUE 2 - restricciones' AS bloque, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM ALL_CONSTRAINTS
 WHERE OWNER = 'PGS' AND TABLE_NAME IN ('DVPR', 'DDPR') AND CONSTRAINT_NAME NOT LIKE 'SYS_%'
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;

-- REVERSO (comentado; sólo si las tablas están vacías y hay que deshacerlo)
-- DROP TABLE PGS.DDPR;
-- DROP TABLE PGS.DVPR;
