-- =====================================================================
-- CAJA CHICA: modelo propio (fondo fijo con reposicion)
-- Módulo: TSR
-- Fecha:  2026-08-26
-- Autor:  orquestador (verificado contra BD local saa-oracle-23ai)
--
-- Tablas nuevas: TSR.CJCH (CajaChica), TSR.MVCH (MovimientoCajaChica),
--                TSR.CRCH (CierreCajaChica), TSR.PTCH (PathCajaChica)
-- Rubros nuevos: 232 TIPO MOVIMIENTO CAJA CHICA, 233 ESTADO CIERRE CAJA CHICA
--   (MAX PRBRCDGO en BD local = 231; PDTRCDGO desde 1118 porque 1116/1117
--    los usa 01-cheques-pago-programado.sql)
-- Verificado sin colision: no existen CJCH/MVCH/CRCH/PTCH en ninguna schema.
--
-- Descriptores reutilizados del diccionario vivo (model/): NMBR, MNTO, TPOO,
-- FCHA, VLOR, DSCR, OBSR, ESTD, FCRG, USAR, FCIN, FCFN, SLDO, PATH.
--
-- Ejecutar por bloques revisando los SELECT de control. SQL puro.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ---------------------------------------------------------------------
-- BLOQUE 0: privilegios REFERENCES para las FK cross-schema
--   Oracle NO considera los privilegios heredados por ROL al crear un
--   constraint: hace falta el GRANT REFERENCES directo, aunque TSR tenga
--   rol DBA. SCP.PJRQ, CNT.PLNN y CNT.ASNT ya lo tienen concedido a
--   PUBLIC, por eso esas FK no fallan; PGS.PGTR, PGS.PRDP y RHH.MPLD no.
--   VA PRIMERO: los CREATE TABLE de abajo dependen de estos permisos.
--   Ejecutar conectado como DBA (o cada GRANT como el owner de la tabla).
-- ---------------------------------------------------------------------
GRANT REFERENCES ON PGS.PGTR TO TSR;
GRANT REFERENCES ON PGS.PRDP TO TSR;
GRANT REFERENCES ON RHH.MPLD TO TSR;
-- Control: deben aparecer las tres filas
SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE FROM ALL_TAB_PRIVS
 WHERE PRIVILEGE = 'REFERENCES' AND GRANTEE = 'TSR';

-- BLOQUE 1: TSR.CJCH — Caja chica (cabecera / fondo)
-- ---------------------------------------------------------------------
CREATE TABLE TSR.CJCH (
    CJCHCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PJRQCDGO NUMBER NOT NULL,
    CJCHNMBR VARCHAR2(200) NOT NULL,
    PLNNCDGO NUMBER NOT NULL,
    CJCHMNTO NUMBER(18,2) NOT NULL,
    CJCHMXGS NUMBER(18,2),
    CJCHPRAL NUMBER(5,2) DEFAULT 20,
    CJCHRSPN VARCHAR2(200),
    CJCHUSCS NUMBER,
    CJCHOBSR VARCHAR2(1000),
    CJCHESTD NUMBER DEFAULT 1,
    CJCHFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CJCHUSAR NUMBER,
    CONSTRAINT PK_CJCH PRIMARY KEY (CJCHCDGO),
    CONSTRAINT FK_CJCH_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_CJCH_PLNN FOREIGN KEY (PLNNCDGO) REFERENCES CNT.PLNN(PLNNCDGO),
    CONSTRAINT FK_CJCH_MPLD FOREIGN KEY (CJCHUSCS) REFERENCES RHH.MPLD(MPLDCDGO)
);
CREATE INDEX TSR.IDX_CJCH_PJRQ ON TSR.CJCH(PJRQCDGO);
CREATE INDEX TSR.IDX_CJCH_PLNN ON TSR.CJCH(PLNNCDGO);
COMMENT ON TABLE TSR.CJCH IS 'Caja chica: fondo fijo con limite, cuenta contable propia y reposicion';
COMMENT ON COLUMN TSR.CJCH.CJCHCDGO IS 'PK';
COMMENT ON COLUMN TSR.CJCH.PJRQCDGO IS 'Empresa (SCP.PJRQ)';
COMMENT ON COLUMN TSR.CJCH.CJCHNMBR IS 'Nombre de la caja chica';
COMMENT ON COLUMN TSR.CJCH.PLNNCDGO IS 'Cuenta contable de la caja (CNT.PLNN)';
COMMENT ON COLUMN TSR.CJCH.CJCHMNTO IS 'Monto del fondo fijo (limite de la caja)';
COMMENT ON COLUMN TSR.CJCH.CJCHMXGS IS 'Monto maximo permitido por gasto individual; NULL = sin tope';
COMMENT ON COLUMN TSR.CJCH.CJCHPRAL IS 'Porcentaje del fondo bajo el cual se alerta que hay que reponer (default 20)';
COMMENT ON COLUMN TSR.CJCH.CJCHRSPN IS 'Nombre del responsable o custodio';
COMMENT ON COLUMN TSR.CJCH.CJCHUSCS IS 'Colaborador custodio de la caja (RHH.MPLD), opcional';
COMMENT ON COLUMN TSR.CJCH.CJCHOBSR IS 'Observaciones';
COMMENT ON COLUMN TSR.CJCH.CJCHESTD IS 'Estado: 1=Activa, 2=Inactiva';
COMMENT ON COLUMN TSR.CJCH.CJCHFCRG IS 'Fecha de registro';
COMMENT ON COLUMN TSR.CJCH.CJCHUSAR IS 'Usuario que registra';

-- ---------------------------------------------------------------------
-- BLOQUE 2: TSR.CRCH — Cierre / arqueo de caja chica
--   (se crea antes que MVCH porque MVCH la referencia)
-- ---------------------------------------------------------------------
CREATE TABLE TSR.CRCH (
    CRCHCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CJCHCDGO NUMBER NOT NULL,
    CRCHFCHA DATE NOT NULL,
    CRCHFCIN DATE,
    CRCHFCFN DATE,
    CRCHSLIN NUMBER(18,2) DEFAULT 0,
    CRCHTGST NUMBER(18,2) DEFAULT 0,
    CRCHTRPS NUMBER(18,2) DEFAULT 0,
    CRCHTAJS NUMBER(18,2) DEFAULT 0,
    CRCHSLDO NUMBER(18,2) DEFAULT 0,
    CRCHSLFS NUMBER(18,2),
    CRCHDFRN NUMBER(18,2),
    CRCHOBSR VARCHAR2(2000),
    CRCHESTD NUMBER DEFAULT 1,
    ASNTCDGO NUMBER,
    CRCHFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRCHUSAR NUMBER,
    CONSTRAINT PK_CRCH PRIMARY KEY (CRCHCDGO),
    CONSTRAINT FK_CRCH_CJCH FOREIGN KEY (CJCHCDGO) REFERENCES TSR.CJCH(CJCHCDGO),
    CONSTRAINT FK_CRCH_ASNT FOREIGN KEY (ASNTCDGO) REFERENCES CNT.ASNT(ASNTCDGO)
);
CREATE INDEX TSR.IDX_CRCH_CJCH ON TSR.CRCH(CJCHCDGO);
COMMENT ON TABLE TSR.CRCH IS 'Cierre / arqueo de caja chica: saldo libros vs saldo fisico';
COMMENT ON COLUMN TSR.CRCH.CRCHCDGO IS 'PK';
COMMENT ON COLUMN TSR.CRCH.CJCHCDGO IS 'Caja chica (TSR.CJCH)';
COMMENT ON COLUMN TSR.CRCH.CRCHFCHA IS 'Fecha del cierre';
COMMENT ON COLUMN TSR.CRCH.CRCHFCIN IS 'Inicio del periodo cerrado';
COMMENT ON COLUMN TSR.CRCH.CRCHFCFN IS 'Fin del periodo cerrado';
COMMENT ON COLUMN TSR.CRCH.CRCHSLIN IS 'Saldo inicial del periodo';
COMMENT ON COLUMN TSR.CRCH.CRCHTGST IS 'Total gastos del periodo';
COMMENT ON COLUMN TSR.CRCH.CRCHTRPS IS 'Total reposiciones y aperturas del periodo';
COMMENT ON COLUMN TSR.CRCH.CRCHTAJS IS 'Total ajustes del periodo (positivos menos negativos)';
COMMENT ON COLUMN TSR.CRCH.CRCHSLDO IS 'Saldo segun libros al cierre';
COMMENT ON COLUMN TSR.CRCH.CRCHSLFS IS 'Saldo fisico contado';
COMMENT ON COLUMN TSR.CRCH.CRCHDFRN IS 'Diferencia = saldo fisico - saldo libros';
COMMENT ON COLUMN TSR.CRCH.CRCHOBSR IS 'Observaciones del arqueo';
COMMENT ON COLUMN TSR.CRCH.CRCHESTD IS 'Estado (rubro 233): 1=Borrador, 2=Cerrado, 3=Anulado';
COMMENT ON COLUMN TSR.CRCH.ASNTCDGO IS 'Asiento de ajuste por diferencia (CNT.ASNT), opcional';
COMMENT ON COLUMN TSR.CRCH.CRCHFCRG IS 'Fecha de registro';
COMMENT ON COLUMN TSR.CRCH.CRCHUSAR IS 'Usuario que registra';

-- ---------------------------------------------------------------------
-- ---------------------------------------------------------------------
-- BLOQUE 3: TSR.MVCH — Movimiento de caja chica
-- ---------------------------------------------------------------------
CREATE TABLE TSR.MVCH (
    MVCHCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CJCHCDGO NUMBER NOT NULL,
    MVCHTPOO NUMBER NOT NULL,
    MVCHFCHA DATE NOT NULL,
    MVCHVLOR NUMBER(18,2) NOT NULL,
    MVCHDSCR VARCHAR2(500) NOT NULL,
    MVCHOBSR VARCHAR2(2000),
    MVCHPRDP NUMBER,
    TTLRCDGO NUMBER,
    MVCHNDOC VARCHAR2(50),
    ASNTCDGO NUMBER,
    PGTRCDGO NUMBER,
    CRCHCDGO NUMBER,
    MVCHESTD NUMBER DEFAULT 1,
    MVCHMTAN VARCHAR2(500),
    MVCHFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MVCHUSAR NUMBER,
    CONSTRAINT PK_MVCH PRIMARY KEY (MVCHCDGO),
    CONSTRAINT FK_MVCH_CJCH FOREIGN KEY (CJCHCDGO) REFERENCES TSR.CJCH(CJCHCDGO),
    CONSTRAINT FK_MVCH_PRDP FOREIGN KEY (MVCHPRDP) REFERENCES PGS.PRDP(ID),
    CONSTRAINT FK_MVCH_TTLR FOREIGN KEY (TTLRCDGO) REFERENCES TSR.TTLR(TTLRCDGO),
    CONSTRAINT FK_MVCH_ASNT FOREIGN KEY (ASNTCDGO) REFERENCES CNT.ASNT(ASNTCDGO),
    CONSTRAINT FK_MVCH_PGTR FOREIGN KEY (PGTRCDGO) REFERENCES PGS.PGTR(PGTRCDGO),
    CONSTRAINT FK_MVCH_CRCH FOREIGN KEY (CRCHCDGO) REFERENCES TSR.CRCH(CRCHCDGO),
    CONSTRAINT CK_MVCH_TPOO CHECK (MVCHTPOO IN (1,2,3,4,5)),
    CONSTRAINT CK_MVCH_VLOR CHECK (MVCHVLOR > 0)
);
CREATE INDEX TSR.IDX_MVCH_CJCH ON TSR.MVCH(CJCHCDGO);
CREATE INDEX TSR.IDX_MVCH_FCHA ON TSR.MVCH(CJCHCDGO, MVCHFCHA);
CREATE INDEX TSR.IDX_MVCH_CRCH ON TSR.MVCH(CRCHCDGO);
CREATE INDEX TSR.IDX_MVCH_PGTR ON TSR.MVCH(PGTRCDGO);
COMMENT ON TABLE TSR.MVCH IS 'Movimientos de caja chica: apertura, gastos, reposiciones y ajustes';
COMMENT ON COLUMN TSR.MVCH.MVCHCDGO IS 'PK';
COMMENT ON COLUMN TSR.MVCH.CJCHCDGO IS 'Caja chica (TSR.CJCH)';
COMMENT ON COLUMN TSR.MVCH.MVCHTPOO IS 'Tipo (rubro 232): 1=Apertura, 2=Gasto, 3=Reposicion, 4=Ajuste positivo, 5=Ajuste negativo';
COMMENT ON COLUMN TSR.MVCH.MVCHFCHA IS 'Fecha del movimiento';
COMMENT ON COLUMN TSR.MVCH.MVCHVLOR IS 'Valor positivo; el tipo determina si suma o resta al saldo';
COMMENT ON COLUMN TSR.MVCH.MVCHDSCR IS 'Concepto';
COMMENT ON COLUMN TSR.MVCH.MVCHOBSR IS 'Observacion; obligatoria en gastos (se valida en el servicio)';
COMMENT ON COLUMN TSR.MVCH.MVCHPRDP IS 'Producto de pago (PGS.PRDP) que clasifica el gasto y da la cuenta contable via su grupo';
COMMENT ON COLUMN TSR.MVCH.TTLRCDGO IS 'Beneficiario o proveedor (TSR.TTLR), opcional';
COMMENT ON COLUMN TSR.MVCH.MVCHNDOC IS 'Numero del comprobante pagado (factura, recibo, vale)';
COMMENT ON COLUMN TSR.MVCH.ASNTCDGO IS 'Asiento contable generado (CNT.ASNT)';
COMMENT ON COLUMN TSR.MVCH.PGTRCDGO IS 'Pago programado (PGS.PGTR) con el que se pago la apertura o reposicion desde el banco';
COMMENT ON COLUMN TSR.MVCH.CRCHCDGO IS 'Cierre de caja chica (TSR.CRCH) en el que quedo incluido';
COMMENT ON COLUMN TSR.MVCH.MVCHESTD IS 'Estado: 1=Activo, 2=Anulado';
COMMENT ON COLUMN TSR.MVCH.MVCHMTAN IS 'Motivo de anulacion';
COMMENT ON COLUMN TSR.MVCH.MVCHFCRG IS 'Fecha de registro';
COMMENT ON COLUMN TSR.MVCH.MVCHUSAR IS 'Usuario que registra';

-- ---------------------------------------------------------------------
-- BLOQUE 4: TSR.PTCH — Documento digitalizado del movimiento
-- ---------------------------------------------------------------------
CREATE TABLE TSR.PTCH (
    PTCHCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    MVCHCDGO NUMBER NOT NULL,
    PTCHPATH VARCHAR2(1000) NOT NULL,
    PTCHNMDC VARCHAR2(500),
    PTCHTPDC VARCHAR2(50),
    PTCHFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PTCHUSAR NUMBER,
    CONSTRAINT PK_PTCH PRIMARY KEY (PTCHCDGO),
    CONSTRAINT FK_PTCH_MVCH FOREIGN KEY (MVCHCDGO) REFERENCES TSR.MVCH(MVCHCDGO)
);
CREATE INDEX TSR.IDX_PTCH_MVCH ON TSR.PTCH(MVCHCDGO);
COMMENT ON TABLE TSR.PTCH IS 'Archivos digitalizados (comprobantes) de movimientos de caja chica';
COMMENT ON COLUMN TSR.PTCH.PTCHCDGO IS 'PK';
COMMENT ON COLUMN TSR.PTCH.MVCHCDGO IS 'Movimiento de caja chica (TSR.MVCH)';
COMMENT ON COLUMN TSR.PTCH.PTCHPATH IS 'Ruta del archivo devuelta por FileService';
COMMENT ON COLUMN TSR.PTCH.PTCHNMDC IS 'Nombre original del documento';
COMMENT ON COLUMN TSR.PTCH.PTCHTPDC IS 'Tipo de documento: FACTURA, RECIBO, VALE, OTRO';
COMMENT ON COLUMN TSR.PTCH.PTCHFCRG IS 'Fecha de registro';
COMMENT ON COLUMN TSR.PTCH.PTCHUSAR IS 'Usuario que registra';

-- Control: 4 tablas creadas
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'TSR' AND TABLE_NAME IN ('CJCH','MVCH','CRCH','PTCH') ORDER BY 1;

-- ---------------------------------------------------------------------
-- BLOQUE 5: rubros 232 y 233
-- ---------------------------------------------------------------------
-- Control previo: 232/233 libres en PRBRCDGO y PRBRALTR; PDTRCDGO >= 1118 libre
SELECT MAX(PRBRCDGO) AS MAX_CDGO, MAX(PRBRALTR) AS MAX_ALTR FROM SCP.PRBR;
SELECT MAX(PDTRCDGO) FROM SCP.PDTR;
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (232, 'TSR - Tipo de movimiento de caja chica (MVCH)', SYSDATE, 232, 0);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1118, 232, 'APERTURA: fondo inicial entregado a la caja', 1, 'APERTURA', 1, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1119, 232, 'GASTO: pago realizado con dinero de la caja', 2, 'GASTO', 2, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1120, 232, 'REPOSICION: reembolso del fondo desde una cuenta bancaria', 3, 'REPOSICION', 3, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1121, 232, 'AJUSTE POSITIVO: sobrante detectado en arqueo', 4, 'AJUSTE_POSITIVO', 4, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1122, 232, 'AJUSTE NEGATIVO: faltante detectado en arqueo', 5, 'AJUSTE_NEGATIVO', 5, 1);
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (233, 'TSR - Estado del cierre de caja chica (CRCH)', SYSDATE, 233, 0);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1123, 233, 'BORRADOR: arqueo en preparacion', 1, 'BORRADOR', 1, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1124, 233, 'CERRADO: arqueo confirmado, movimientos bloqueados', 2, 'CERRADO', 2, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1125, 233, 'ANULADO: arqueo anulado', 3, 'ANULADO', 3, 1);
-- Control
SELECT P.PRBRCDGO, P.PRBRDSCR, D.PDTRALTR, D.PDTRVLRV FROM SCP.PRBR P JOIN SCP.PDTR D ON D.PRBRCDGO = P.PRBRCDGO WHERE P.PRBRCDGO IN (232, 233) ORDER BY 1, 3;
COMMIT;

-- ---------------------------------------------------------------------
-- BLOQUE 6 (NO EJECUTAR TODAVIA): retiro de las cuentas bancarias "CAJA CHICA"
--   Hoy la caja chica vive como bancos TSR.BNCO 425/427 y cuentas TSR.CNBC
--   428 (plan cuenta 10029) y 429 (plan cuenta 10033). Se ejecuta SOLO
--   despues de crear las cajas chicas en la pantalla nueva con su saldo
--   inicial migrado (movimiento tipo 1 APERTURA sin asiento) y de verificar
--   que no queda ningun pago pendiente sobre esas cuentas.
-- ---------------------------------------------------------------------
-- Control: pagos programados no confirmados/anulados sobre esas cuentas (debe ser 0)
SELECT PGTRCDGO, PGTRESTD, PGTRVLOR FROM PGS.PGTR WHERE PGTRCNBC IN (428, 429) AND PGTRESTD IN (1, 2);
-- Control: cuentas y su plan de cuenta (la caja chica nueva debe usar el mismo PLNNCDGO)
SELECT CNBCCDGO, CNBCNMRO, PLNNCDGO, CNBCESTD FROM TSR.CNBC WHERE CNBCCDGO IN (428, 429);
-- UPDATE TSR.CNBC SET CNBCESTD = 2, CNBCFCDS = SYSDATE WHERE CNBCCDGO IN (428, 429);
-- COMMIT;
