-- =====================================================================
-- ANTICIPOS A TRABAJADORES: la entrega del anticipo
-- Módulo: RRHH
-- Fecha:  2026-08-27
-- Autor:  orquestador (verificado contra la BD local, copia de producción)
--
-- CONTEXTO
--   Hoy en RRHH solo existe el DESCUENTO del anticipo: se crea a mano una
--   fila de RHH.DSRC (DescuentoRecurrente) con tipo ANTICIPO_DE_SUELDO y
--   el motor de rol la cobra en cuotas. No hay ningún rastro de que el
--   dinero salió: ni documento, ni pago, ni asiento de la entrega.
--
--   Esta tabla es ese documento. El ciclo queda:
--     aprobar RHH.ANTE
--       -> PagoProgramado de origen externo RHH_ANTICIPO_EMPLEADO
--          (hereda transferencia, debito automatico y cheque)
--       -> al confirmarse el pago: asiento DEBE cuentas por cobrar
--          empleados / HABER banco, y se crea el DescuentoRecurrente
--       -> cada rol descuenta una cuota y baja el saldo
--       -> saldo en cero: CANCELADO
--
--   La cuenta contable es la MISMA que ya usa el descuento del rol
--   (RhhLineaAsiento.CUENTAS_POR_COBRAR_EMPLEADOS), asi el ciclo cuadra
--   solo: la entrega la debita y el descuento del rol la acredita.
--
-- Verificado: no existe ninguna tabla ANTE/ANTC/ANEM en el schema RHH.
-- Descriptores tomados del diccionario vivo de RHH (patron de DSRC):
-- MPLD, VLOR, NMRO, VLCT, SLDD, FCHI, FCHF, OBSR, ESTD, FCHR, USRR.
--
-- SQL puro. Ejecutar por bloques revisando los SELECT de control.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BLOQUE 0: privilegios REFERENCES para las FK cross-schema
--   RHH.ANTE apunta a PGS.PGTR (el pago) y a RHH.DSRC (el descuento que
--   genera). Oracle NO considera los privilegios heredados por ROL al
--   crear un constraint. Ejecutar como DBA (o cada GRANT como el owner).
--   VA PRIMERO: el CREATE TABLE de abajo depende de esto.
-- ---------------------------------------------------------------------
GRANT REFERENCES ON PGS.PGTR TO RHH;

SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE FROM ALL_TAB_PRIVS
 WHERE PRIVILEGE = 'REFERENCES' AND GRANTEE = 'RHH' AND OWNER = 'PGS';

-- ---------------------------------------------------------------------
-- BLOQUE 1: RHH.ANTE — Anticipo entregado a un colaborador
-- ---------------------------------------------------------------------
CREATE TABLE RHH.ANTE (
    ANTECDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    MPLDCDGO NUMBER NOT NULL,
    ANTEFCHA DATE NOT NULL,
    ANTEVLOR NUMBER(18,2) NOT NULL,
    ANTENMRO NUMBER NOT NULL,
    ANTEVLCT NUMBER(18,2) NOT NULL,
    ANTESLDD NUMBER(18,2) NOT NULL,
    ANTEFCHI DATE,
    ANTEMTVO VARCHAR2(500),
    ANTEOBSR VARCHAR2(2000),
    ANTEESTD NUMBER DEFAULT 1 NOT NULL,
    PGTRCDGO NUMBER,
    DSRCCDGO NUMBER,
    ANTEUSAP NUMBER,
    ANTEFCAP DATE,
    ANTEMTAN VARCHAR2(500),
    ANTEFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ANTEUSRR VARCHAR2(60),
    CONSTRAINT PK_ANTE PRIMARY KEY (ANTECDGO),
    CONSTRAINT FK_ANTE_MPLD FOREIGN KEY (MPLDCDGO) REFERENCES RHH.MPLD(MPLDCDGO),
    CONSTRAINT FK_ANTE_PGTR FOREIGN KEY (PGTRCDGO) REFERENCES PGS.PGTR(PGTRCDGO),
    CONSTRAINT FK_ANTE_DSRC FOREIGN KEY (DSRCCDGO) REFERENCES RHH.DSRC(DSRCCDGO),
    CONSTRAINT CK_ANTE_VLOR CHECK (ANTEVLOR > 0),
    CONSTRAINT CK_ANTE_NMRO CHECK (ANTENMRO >= 1),
    CONSTRAINT CK_ANTE_ESTD CHECK (ANTEESTD IN (1,2,3,4,5,6))
);

CREATE INDEX RHH.IDX_ANTE_MPLD ON RHH.ANTE(MPLDCDGO);
CREATE INDEX RHH.IDX_ANTE_ESTD ON RHH.ANTE(ANTEESTD);
CREATE INDEX RHH.IDX_ANTE_PGTR ON RHH.ANTE(PGTRCDGO);

COMMENT ON TABLE RHH.ANTE IS 'Anticipo de sueldo entregado a un colaborador, con su plan de descuento en cuotas';
COMMENT ON COLUMN RHH.ANTE.ANTECDGO IS 'PK';
COMMENT ON COLUMN RHH.ANTE.MPLDCDGO IS 'Colaborador que recibe el anticipo (RHH.MPLD)';
COMMENT ON COLUMN RHH.ANTE.ANTEFCHA IS 'Fecha de la solicitud';
COMMENT ON COLUMN RHH.ANTE.ANTEVLOR IS 'Valor total entregado';
COMMENT ON COLUMN RHH.ANTE.ANTENMRO IS 'Numero de cuotas en que se descuenta del rol';
COMMENT ON COLUMN RHH.ANTE.ANTEVLCT IS 'Valor de cada cuota';
COMMENT ON COLUMN RHH.ANTE.ANTESLDD IS 'Saldo pendiente por descontar; al llegar a 0 el anticipo queda CANCELADO';
COMMENT ON COLUMN RHH.ANTE.ANTEFCHI IS 'Mes desde el que empieza a descontarse en el rol';
COMMENT ON COLUMN RHH.ANTE.ANTEMTVO IS 'Motivo por el que se solicita';
COMMENT ON COLUMN RHH.ANTE.ANTEOBSR IS 'Observaciones';
COMMENT ON COLUMN RHH.ANTE.ANTEESTD IS 'Estado (rubro 234): 1=Solicitado, 2=Aprobado, 3=Pagado, 4=En descuento, 5=Cancelado, 6=Anulado';
COMMENT ON COLUMN RHH.ANTE.PGTRCDGO IS 'Pago programado con el que se entrego el dinero (PGS.PGTR)';
COMMENT ON COLUMN RHH.ANTE.DSRCCDGO IS 'Descuento recurrente generado al confirmarse el pago (RHH.DSRC)';
COMMENT ON COLUMN RHH.ANTE.ANTEUSAP IS 'Usuario que aprobo';
COMMENT ON COLUMN RHH.ANTE.ANTEFCAP IS 'Fecha de aprobacion';
COMMENT ON COLUMN RHH.ANTE.ANTEMTAN IS 'Motivo de anulacion';
COMMENT ON COLUMN RHH.ANTE.ANTEFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.ANTE.ANTEUSRR IS 'Usuario que registra';

-- Control: la tabla y sus tres FK
SELECT C.CONSTRAINT_NAME, C.R_OWNER || '.' || RC.TABLE_NAME AS TABLA_REFERENCIADA, CC.COLUMN_NAME
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC ON CC.CONSTRAINT_NAME = C.CONSTRAINT_NAME AND CC.OWNER = C.OWNER
  JOIN ALL_CONSTRAINTS RC ON RC.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME AND RC.OWNER = C.R_OWNER
 WHERE C.OWNER = 'RHH' AND C.TABLE_NAME = 'ANTE' AND C.CONSTRAINT_TYPE = 'R'
 ORDER BY C.CONSTRAINT_NAME;

-- ---------------------------------------------------------------------
-- BLOQUE 2: rubro 234 — estados del anticipo a colaborador
--   MAX PRBRCDGO y PRBRALTR en la base = 233; MAX PDTRCDGO = 1125.
-- ---------------------------------------------------------------------
SELECT MAX(PRBRCDGO) AS MAX_CDGO, MAX(PRBRALTR) AS MAX_ALTR FROM SCP.PRBR;
SELECT MAX(PDTRCDGO) FROM SCP.PDTR;

INSERT INTO SCP.PRBR (PRBRCDGO, PRBRDSCR, PRBRFCHA, PRBRALTR, PRBRTPOO)
VALUES (234, 'RHH - Estado del anticipo a colaborador (ANTE)', SYSDATE, 234, 0);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1126, 234, 'SOLICITADO: registrado, pendiente de aprobacion', 1, 'SOLICITADO', 1, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1127, 234, 'APROBADO: autorizado, pendiente de pago', 2, 'APROBADO', 2, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1128, 234, 'PAGADO: el dinero se entrego y se contabilizo', 3, 'PAGADO', 3, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1129, 234, 'EN DESCUENTO: se esta cobrando en el rol', 4, 'EN_DESCUENTO', 4, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1130, 234, 'CANCELADO: saldo en cero, totalmente descontado', 5, 'CANCELADO', 5, 1);
INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRDSCR, PDTRVLRN, PDTRVLRV, PDTRALTR, PDTRESTD) VALUES (1131, 234, 'ANULADO', 6, 'ANULADO', 6, 1);

-- Control
SELECT P.PRBRCDGO, P.PRBRDSCR, D.PDTRALTR, D.PDTRVLRV
  FROM SCP.PRBR P JOIN SCP.PDTR D ON D.PRBRCDGO = P.PRBRCDGO
 WHERE P.PRBRCDGO = 234 ORDER BY D.PDTRALTR;
COMMIT;
