-- =====================================================================
-- RRHH: detalle de qué año se consumió en cada aprobación de vacaciones
-- Modulo: RHH
-- Fecha:  2026-08-27
-- Autor:  orquestador
--
-- PARA QUE
--   Al aprobar vacaciones, el saldo se consume FIFO del año mas antiguo
--   primero, y una sola solicitud puede tomar dias de VARIOS años.
--   `AcreditacionVacacionesService.revertirConsumo` devuelve en orden
--   inverso sobre el estado ACTUAL de RHH.SLDV, no sobre lo que esa
--   solicitud consumio realmente.
--
--   El fallo concreto: la solicitud A consume de 2023+2024; despues se
--   aprueba B, que consume de 2024+2025; al anular A, los dias pueden
--   volver a 2025 en vez de a 2023/2024. El total cuadra y el año no.
--
-- POR QUE SE CREA AHORA Y NO CUANDO HAGA FALTA
--   Hoy el riesgo es CERO: los 22 saldos de la base son todos de 2025 y
--   ningun empleado tiene saldo en dos años, asi que el FIFO entre años
--   todavia no ocurre. Se crea igual, y por una razon que no admite
--   postergarse: **el dato de que año se consumio solo existe en el
--   instante de aprobar**. Si la tabla se crea despues, no hay de donde
--   reconstruir el historico -- la informacion no esta en ningun lado.
--   Crearla ahora cuesta esta pagina; crearla despues cuesta perder la
--   trazabilidad de todo lo aprobado en el medio.
--
--   Y el año no es cosmetico: la caducidad se marca POR AÑO (SLDVCDCD, ya
--   hay 4 saldos caducados). Un dia devuelto al año equivocado puede
--   caducar cuando no debia, o sobrevivir cuando debia caducar.
--
-- Modelo propuesto por el agente de backend en
-- docs/logica-negocio/rhh/CICLO-APROBACION-VACACIONES.md, aceptado sin
-- cambios de fondo: es el mismo patron de trazabilidad de
-- RhhOrigenRenglon + idReferencia.
--
-- SQL puro. Ejecutar por bloques revisando los SELECT de control.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BLOQUE 0: control previo
--   La tabla no debe existir. Las dos referenciadas si.
-- ---------------------------------------------------------------------
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'RHH' AND TABLE_NAME IN ('DVAC','SLCT','SLDV');

-- Estado del que partimos, para poder comparar despues
SELECT COUNT(*) AS SALDOS, COUNT(DISTINCT SLDVANOO) AS ANIOS,
       SUM(CASE WHEN NVL(SLDVCDCD,'N') = 'S' THEN 1 ELSE 0 END) AS CADUCADOS
  FROM RHH.SLDV;

-- ---------------------------------------------------------------------
-- BLOQUE 1: RHH.DVAC — una fila por (solicitud, año consumido)
--   Una solicitud que cruza dos años produce dos filas.
-- ---------------------------------------------------------------------
CREATE TABLE RHH.DVAC (
    DVACCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    SLCTCDGO NUMBER NOT NULL,
    SLDVCDGO NUMBER NOT NULL,
    DVACDIAS NUMBER(18,4) NOT NULL,
    DVACESTD NUMBER DEFAULT 1 NOT NULL,
    DVACFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DVACUSRR VARCHAR2(60),
    CONSTRAINT PK_DVAC PRIMARY KEY (DVACCDGO),
    CONSTRAINT FK_DVAC_SLCT FOREIGN KEY (SLCTCDGO) REFERENCES RHH.SLCT(SLCTCDGO),
    CONSTRAINT FK_DVAC_SLDV FOREIGN KEY (SLDVCDGO) REFERENCES RHH.SLDV(SLDVCDGO),
    CONSTRAINT CK_DVAC_DIAS CHECK (DVACDIAS > 0),
    CONSTRAINT CK_DVAC_ESTD CHECK (DVACESTD IN (0,1))
);

-- Una solicitud no puede tomar dos veces del mismo año: si necesita mas
-- dias de ese año, es la MISMA fila con mas dias.
CREATE UNIQUE INDEX RHH.UQ_DVAC_SLCT_SLDV ON RHH.DVAC(SLCTCDGO, SLDVCDGO);

-- Ojo: prefijar el schema. Sin prefijo el indice queda en el schema de la
-- SESION, ocupa la columna igual y luego da ORA-01408.
CREATE INDEX RHH.IDX_DVAC_SLCT ON RHH.DVAC(SLCTCDGO);

COMMENT ON TABLE RHH.DVAC IS 'Detalle de que año de saldo consumio cada aprobacion de vacaciones. Permite devolver los dias exactamente a los años de los que salieron al anular, sin depender del orden en que se consumio despues';
COMMENT ON COLUMN RHH.DVAC.DVACCDGO IS 'PK';
COMMENT ON COLUMN RHH.DVAC.SLCTCDGO IS 'Solicitud de vacaciones aprobada (RHH.SLCT)';
COMMENT ON COLUMN RHH.DVAC.SLDVCDGO IS 'Saldo anual del que se tomaron los dias (RHH.SLDV)';
COMMENT ON COLUMN RHH.DVAC.DVACDIAS IS 'Dias tomados de ese año por esta solicitud';
COMMENT ON COLUMN RHH.DVAC.DVACESTD IS '1 vigente, 0 revertido al anular la aprobacion';
COMMENT ON COLUMN RHH.DVAC.DVACFCHR IS 'Fecha de registro';
COMMENT ON COLUMN RHH.DVAC.DVACUSRR IS 'Usuario que aprobo';

-- ---------------------------------------------------------------------
-- BLOQUE 2: control final
--   Esperado: la tabla, sus dos FK, los dos CHECK y los dos indices.
-- ---------------------------------------------------------------------
SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE,
       CASE WHEN C.CONSTRAINT_TYPE = 'R'
            THEN (SELECT R.TABLE_NAME FROM ALL_CONSTRAINTS R
                   WHERE R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME AND R.OWNER = C.R_OWNER)
            ELSE NULL END AS REFERENCIA
  FROM ALL_CONSTRAINTS C
 WHERE C.OWNER = 'RHH' AND C.TABLE_NAME = 'DVAC'
 ORDER BY C.CONSTRAINT_TYPE, C.CONSTRAINT_NAME;

SELECT INDEX_NAME, UNIQUENESS FROM ALL_INDEXES
 WHERE TABLE_OWNER = 'RHH' AND TABLE_NAME = 'DVAC' ORDER BY INDEX_NAME;

COMMIT;

-- ---------------------------------------------------------------------
-- NO HAY BACKFILL, Y ES A PROPOSITO
--   Las aprobaciones anteriores a esta tabla no dejaron registro de que
--   año consumieron. No se puede reconstruir sin inventar. Si alguna de
--   esas se anula, seguira usando revertirConsumo con su imprecision;
--   de ahi en adelante, todas las nuevas seran exactas.
-- ---------------------------------------------------------------------
