SET PAGESIZE 200
SET LINESIZE 200
COLUMN TABLA FORMAT A8
COLUMN COLUMNA FORMAT A14
COLUMN TIPO FORMAT A18
COLUMN DIAGNOSTICO FORMAT A20

WITH esperado (TABLA, COLUMNA, TIPO) AS (
  SELECT 'LQDC','ASNTCDGO','Long' FROM DUAL
  UNION ALL
  SELECT 'LQDC','CNTECDGO','ContratoEmpleado' FROM DUAL
  UNION ALL
  SELECT 'LQDC','CSTRCDGO','CausalTerminacion' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCACSU','String' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCANSR','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCCDGO','Long' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCDSHC','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCDSPD','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCESTD','Long' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCFCAP','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCFCHR','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCFCHS','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCFCIN','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCFCSU','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCJBPT','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCMTVO','String' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCNETO','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCTTDS','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCTTIN','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCULRM','Double' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCUSAP','String' FROM DUAL
  UNION ALL
  SELECT 'LQDC','LQDCUSRR','String' FROM DUAL
  UNION ALL
  SELECT 'LQDC','MPLDCDGO','Empleado' FROM DUAL
  UNION ALL
  SELECT 'NMNA','CNTECDGO','ContratoEmpleado' FROM DUAL
  UNION ALL
  SELECT 'NMNA','MPLDCDGO','Empleado' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAAPPR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAAPPT','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNABSDC','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNABSDT','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNABSFR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNABSIE','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNABSIR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNACDGO','Long' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNADITR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAESTD','Long' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAFCHR','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAFNRS','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAHRTR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAIESC','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNANETO','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAOBSR','String' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNARTIR','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNASLRB','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNATDSC','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNATING','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNATTPT','Double' FROM DUAL
  UNION ALL
  SELECT 'NMNA','NMNAUSRR','String' FROM DUAL
  UNION ALL
  SELECT 'NMNA','PRDNCDGO','PeriodoNomina' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PJRQCDGO','Empresa' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNANOO','Integer' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNASNT','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNASPG','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNASPR','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNCDGO','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNESTD','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCAP','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCCN','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCCR','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCHF','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCHI','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNFCHR','LocalDate' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNMODO','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNMSEE','Integer' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNNMEM','Integer' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNOBSR','String' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNTPNM','Long' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNTTDS','Double' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNTTIN','Double' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNTTNT','Double' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNTTPT','Double' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNUSAP','String' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNUSCR','String' FROM DUAL
  UNION ALL
  SELECT 'PRDN','PRDNUSRR','String' FROM DUAL
)
SELECT e.TABLA, e.COLUMNA, e.TIPO, 'FALTA EN LA BASE' AS DIAGNOSTICO
  FROM esperado e
 WHERE NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS c
                    WHERE c.OWNER='RHH' AND c.TABLE_NAME=e.TABLA AND c.COLUMN_NAME=e.COLUMNA)
UNION ALL
SELECT c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, 'SOBRA EN LA BASE'
  FROM ALL_TAB_COLUMNS c
 WHERE c.OWNER='RHH' AND c.TABLE_NAME IN ('PRDN','NMNA','LQDC')
   AND NOT EXISTS (SELECT 1 FROM esperado e
                    WHERE e.TABLA=c.TABLE_NAME AND e.COLUMNA=c.COLUMN_NAME)
ORDER BY 4, 1, 2;
