-- ============================================================================
-- e2-02-verificacion-entidades-vs-esquema-rhh-cnt.sql
-- Escrito por el arbitro del equipo omen-saa-2 el 2026-09-01
-- ============================================================================
--
-- POR QUE EXISTE
-- VERIFICACION-ENTIDADES-VS-ESQUEMA-CXC-CXP-TSR.sql (2026-08-29) hace esta misma
-- comprobacion para cxc, cxp y tsr, y su propio encabezado avisa que NO cubre
-- rhh ni cnt. Este cierra ese hueco, y lo hace ahora porque hay un despliegue de
-- rhh en camino (frentes 2 y 3-C).
--
-- QUE COMPARA
-- TODAS las columnas mapeadas de TODAS las entidades JPA de rhh y cnt contra lo
-- que existe de verdad en la base: 84 entidades, 1.254 columnas entre @Column y
-- @JoinColumn.
--
-- POR QUE IMPORTA
-- Hibernate incluye toda columna @Column basica en el SELECT que genera, asi que
-- una columna mapeada que no existe en la base no rompe solo la funcion nueva:
-- rompe CUALQUIER lectura de esa entidad con ORA-00904. No se ve al compilar y
-- aparece cuando un usuario abre la pantalla. Es el defecto CBR.ANTC del
-- 2026-08-29, que motivo el script original.
--
-- NO MODIFICA NADA. Son dos consultas de solo lectura. Seguro de correr de
-- corrido, en local y en produccion.
--
-- COMO LEERLO
--   Consulta A: tablas mapeadas que no existen.   Deberia dar 0 filas.
--   Consulta B: columnas mapeadas que faltan.     Deberia dar 0 filas.
--               Cada fila de B es un ORA-00904 esperando el despliegue.
--
-- TRES COSAS QUE CONVIENE SABER ANTES DE INTERPRETARLO
--   1. ALL_TAB_COLUMNS solo muestra lo que el usuario conectado puede ver. Con
--      un usuario sin privilegios sobre RHH/CNT/AOT van a salir falsos FALTA.
--      Conectarse con el mismo usuario del datasource, o con DBA.
--   2. NO todo el paquete com.saa.model.cnt es schema CNT: AnioMotor vive ahi
--      pero su @Table declara schema = "AOT". El script respeta el schema
--      declarado en cada entidad, no el nombre del paquete. (Avisado por el
--      agente de backend; asumir CNT habria dado un falso negativo.)
--   3. El listado se genero leyendo src/main/java/com/saa/model/{rhh,cnt} el
--      2026-09-01, balanceando parentesis y NO por regex de una linea: en este
--      modelo hay @Table de tres lineas (ResumenNomina, con uniqueConstraints
--      anidado) que una extraccion ingenua pierde en silencio. Si se agregan
--      entidades o columnas despues, HAY QUE REGENERARLO.
--
-- NOTA SOBRE COLUMNAS REPETIDAS
-- Cuatro entidades de cnt (Asiento, CentroCosto, DesgloseMayorizacionCC,
-- MayorAnalitico) declaran la misma columna dos veces: una sobre el campo y otra
-- sobre el getter. NO es un defecto -- como @Id esta en el campo, JPA usa acceso
-- por campo y la anotacion del getter se ignora. Aca aparecen una sola vez.
-- ============================================================================

WITH ESPERADO AS (
SELECT 'X' AS OWNER_ESP, 'X' AS TABLA_ESP, 'X' AS COLS FROM DUAL WHERE 1=0
UNION ALL SELECT 'RHH', 'ACMN', 'ACMNANOO,ACMNAPRT,ACMNCDGO,ACMNDIAS,ACMNESTD,ACMNFCHR,ACMNMSEE,ACMNTPAC,ACMNUSRR,ACMNVLOR,MPLDCDGO,PRDNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'ANTE', 'ANTECDGO,ANTEESTD,ANTEFCAP,ANTEFCHA,ANTEFCHI,ANTEFCHR,ANTEMTAN,ANTEMTVO,ANTENMRO,ANTEOBSR,ANTESLDD,ANTEUSAP,ANTEUSRR,ANTEVLCT,ANTEVLOR,DSRCCDGO,MPLDCDGO,PGTRCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CBEM', 'BNCOCDGO,CBEMCDGO,CBEMESTD,CBEMFCHR,CBEMIDTT,CBEMNMCT,CBEMPRCN,CBEMPRCP,CBEMTPCT,CBEMTTLR,CBEMUSRR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CFNM', 'CFNMAPDS,CFNMAPJP,CFNMAPUT,CFNMCDGO,CFNMCTMR,CFNMDCCS,CFNMESTD,CFNMFCHR,CFNMPLLQ,CFNMPLPG,CFNMPLPR,CFNMPLRL,CFNMRDND,CFNMSCIE,CFNMSGSC,CFNMTALQ,CFNMTAPG,CFNMTAPR,CFNMTARL,CFNMTLCD,CFNMTPEM,CFNMUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CNTE', 'CNTEAPRT,CNTECDGO,CNTECDSC,CNTECNCS,CNTECSTR,CNTEDCCM,CNTEDCMS,CNTEDCTM,CNTEDIAD,CNTEESTD,CNTEFCHF,CNTEFCHI,CNTEFCHR,CNTEFCTR,CNTEFRMA,CNTEFRMD,CNTEHRSM,CNTEJRND,CNTENMRO,CNTENRIR,CNTENRMT,CNTEOBSR,CNTEOCUP,CNTEPRRF,CNTERTFN,CNTESLRB,CNTETPRL,CNTETRNO,CNTEUSRR,CNTEVLHR,MPLDCDGO,TPCECDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CPNM', 'CPNMABRV,CPNMALTR,CPNMAPFR,CPNMBSCL,CPNMBSDC,CPNMBSDT,CPNMBSUT,CPNMBSVC,CPNMCDGO,CPNMESTD,CPNMF107,CPNMFCHR,CPNMFRML,CPNMIESS,CPNMIMIE,CPNMIMIR,CPNMNMBR,CPNMOBLG,CPNMORDN,CPNMPRCN,CPNMPRVS,CPNMPTRN,CPNMRCRT,CPNMRDEP,CPNMROLM,CPNMTPCL,CPNMTPCN,CPNMTPRL,CPNMUSRR,CPNMVLRR,DTPLCDGO,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CPXM', 'CNTECDGO,CPNMCDGO,CPXMCANT,CPXMCDGO,CPXMESTD,CPXMFCHF,CPXMFCHI,CPXMFCHR,CPXMOBSR,CPXMPRCN,CPXMUSRR,CPXMVLRR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CRGF', 'CRGFAPLL,CRGFCDGO,CRGFDPEC,CRGFDSCP,CRGFESTD,CRGFFCFN,CRGFFCHN,CRGFFCHR,CRGFFCIN,CRGFIDNT,CRGFIRRB,CRGFNMBR,CRGFPRDS,CRGFPRNT,CRGFUSRR,CRGFUTIL,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CRGO', 'CRGOCDGO,CRGODSCR,CRGOESTD,CRGOFCHR,CRGONMBR,CRGORQST,CRGOUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'CRMR', 'CRMRCDGO,CRMRESTD,CRMRFCCR,CRMRFCDS,CRMRFCHR,CRMRFCHS,CRMRHASH,CRMRLGGO,CRMRLNDP,CRMRLNER,CRMRLNOK,CRMRLNTT,CRMRNMAR,CRMRUSRR,FMRCCDGO,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CSTR', 'CSTRACSU,CSTRALTR,CSTRARTC,CSTRAVSL,CSTRCDGO,CSTRDCPR,CSTRDSHC,CSTRDSPD,CSTRESTD,CSTRFCHR,CSTRJBPT,CSTRNMBR,CSTRUSRR,CSTRVCPR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CTDS', 'CTDSCDGO,CTDSCPTL,CTDSESTD,CTDSFCHR,CTDSFCVN,CTDSINTR,CTDSNMCT,CTDSSLDD,CTDSTTAL,CTDSUSRR,CTDSVLDS,DSRCCDGO,PRDNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'CTLG', 'CTLGCDGO,CTLGDSNM,CTLGESTD,CTLGFCHR,CTLGGCEE,CTLGMXDI,CTLGNMBR,CTLGRQDC,CTLGTPAS,CTLGUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DFMB', 'DFMBCDGO,DFMBCMPO,DFMBCRLL,DFMBDCML,DFMBESTD,DFMBFCHR,DFMBFRFC,DFMBINCO,DFMBLNGT,DFMBORDN,DFMBRLLN,DFMBSPDC,DFMBUSRR,DFMBVLFJ,FMBNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DFMR', 'DFMRCDGO,DFMRCMPO,DFMRESTD,DFMRFCHR,DFMRINCO,DFMRLNGT,DFMRMPEO,DFMROBLG,DFMRORDN,DFMRPSCN,DFMRUSRR,FMRCCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DPRT', 'DPRTCDGO,DPRTESTD,DPRTFCHR,DPRTNMBR,DPRTUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'DPTC', 'CRGOCDGO,DPRTCDGO,DPTCCDGO,DPTCESTD,DPTCFCHR,DPTCUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'DRPG', 'CBEMCDGO,DRPGBNCO,DRPGCDGO,DRPGESTD,DRPGFCHR,DRPGIDNT,DRPGMTRC,DRPGNMBN,DRPGNMCT,DRPGRCHZ,DRPGTPCT,DRPGUSRR,DRPGVLOR,MPLDCDGO,NMNACDGO,RDPGCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DSRC', 'CPNMCDGO,DSRCAPRT,DSRCBNFC,DSRCCDGO,DSRCCTPG,DSRCESTD,DSRCFCHF,DSRCFCHI,DSRCFCHR,DSRCNMCT,DSRCNMRO,DSRCOBSR,DSRCPRCN,DSRCSLDD,DSRCTPDS,DSRCUSRR,DSRCVLCT,DSRCVLOR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DTLL', 'DTLLCDGO,DTLLDIAA,DTLLENTR,DTLLFCHR,DTLLLBRB,DTLLMNDS,DTLLSLDA,DTLLUSRR,TRNOCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DTUT', 'DTUTCDGO,DTUTDIAS,DTUTESTD,DTUTEXCD,DTUTFCHR,DTUTNCRG,DTUTRTIR,DTUTTTAL,DTUTUSRR,DTUTVL05,DTUTVL10,DTUTVLPG,MPLDCDGO,UTLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'DVAC', 'DVACCDGO,DVACDIAS,DVACESTD,DVACFCHR,DVACUSRR,SLCTCDGO,SLDVCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'FMBN', 'FMBNBNCO,FMBNCBCR,FMBNCDFC,FMBNCDGO,FMBNDLMT,FMBNESTD,FMBNEXTN,FMBNFCHR,FMBNFRFC,FMBNMPTC,FMBNNMBR,FMBNPIEE,FMBNTPFR,FMBNUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'FMRC', 'FMRCCDFC,FMRCCDGO,FMRCDLMT,FMRCESTD,FMRCFCHR,FMRCFRFC,FMRCFRFH,FMRCFRHR,FMRCLNCB,FMRCLNPI,FMRCMRCA,FMRCNMBR,FMRCTPFR,FMRCUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'GSPR', 'GSPRANOO,GSPRCDGO,GSPRESTD,GSPRFCHR,GSPRFCPR,GSPRTPGP,GSPRUSRR,GSPRVGNT,GSPRVLOR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'HREX', 'HREXAPRB,HREXCDGO,HREXESTD,HREXEXCP,HREXFCAP,HREXFCHA,HREXFCHR,HREXHORS,HREXOBSR,HREXRCRG,HREXTPHR,HREXUSAP,HREXUSRR,HREXVLHR,HREXVLOR,MPLDCDGO,PRDNCDGO,RSMNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'HSTR', 'CRGOCDGO,DPTCCDGO,HSTRACTL,HSTRCDGO,HSTRFCHF,HSTRFCHI,HSTRFCHR,HSTROBSR,HSTRSLAN,HSTRSLNW,HSTRTPCM,HSTRUSRR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'LQBS', 'LQBSANOO,LQBSBSCL,LQBSCDGO,LQBSDIAS,LQBSESTD,LQBSFCHF,LQBSFCHI,LQBSFCHR,LQBSFCPG,LQBSTPBN,LQBSUSRR,LQBSVLMN,LQBSVLPG,LQBSVLRR,MPLDCDGO,PRDNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'LQDC', 'ASNTCDGO,CNTECDGO,CSTRCDGO,LQDCACSU,LQDCANSR,LQDCCDGO,LQDCDSHC,LQDCDSPD,LQDCESTD,LQDCFCAP,LQDCFCHR,LQDCFCHS,LQDCFCIN,LQDCFCSU,LQDCJBPT,LQDCMTVO,LQDCNETO,LQDCTTDS,LQDCTTIN,LQDCULRM,LQDCUSAP,LQDCUSRR,MPLDCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'MPLD', 'MPLDAPLL,MPLDCDAF,MPLDCDBM,MPLDCDGO,MPLDCNCS,MPLDCNDS,MPLDCTEM,MPLDCTSF,MPLDDRCC,MPLDDSCP,MPLDEMAI,MPLDESTC,MPLDESTD,MPLDFCHN,MPLDFCHR,MPLDFCIN,MPLDFOTO,MPLDGNRO,MPLDIDNT,MPLDNCNL,MPLDNMBR,MPLDNVIN,MPLDPRDS,MPLDPRFS,MPLDRGNN,MPLDTLEM,MPLDTLFN,MPLDTPID,MPLDTPSN,MPLDUSRR,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'MRCC', 'CRMRCDGO,MPLDCDGO,MRCCCDGO,MRCCDSPS,MRCCFCHH,MRCCFCHR,MRCCLNAR,MRCCOBSR,MRCCORGN,MRCCPRCS,MRCCTPOO,MRCCUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'NMNA', 'CNTECDGO,MPLDCDGO,NMNAAPPR,NMNAAPPT,NMNABSDC,NMNABSDT,NMNABSFR,NMNABSIE,NMNABSIR,NMNACDGO,NMNADITR,NMNAESTD,NMNAFCHR,NMNAFNRS,NMNAHRTR,NMNAIESC,NMNANETO,NMNAOBSR,NMNARTIR,NMNASLRB,NMNATDSC,NMNATING,NMNATTPT,NMNAUSRR,PRDNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'NVIS', 'CNTECDGO,MPLDCDGO,NVISCAIS,NVISCDGO,NVISCSTR,NVISDIAS,NVISESTD,NVISFCFL,NVISFCFN,NVISFCHC,NVISFCHR,NVISFCLM,NVISFCRP,NVISLOTE,NVISMDFR,NVISMSLB,NVISOBSR,NVISPRDS,NVISPRHS,NVISRSPT,NVISSLAN,NVISSLNW,NVISSLRF,NVISTPNV,NVISUSRR,NVISVLVR' FROM DUAL
UNION ALL SELECT 'RHH', 'NVNM', 'CPNMCDGO,MPLDCDGO,NVNMAPRB,NVNMCANT,NVNMCDGO,NVNMDSCR,NVNMESTD,NVNMFCAP,NVNMFCHR,NVNMUSAP,NVNMUSRR,NVNMVLRR,PRDNCDGO' FROM DUAL
UNION ALL SELECT 'RHH', 'NXOO', 'CNTECDGO,NXOOCDGO,NXOODTLL,NXOOFCHA,NXOOFCHF,NXOOFCHR,NXOOSLRN,NXOOTPOO,NXOOUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'PRDN', 'PJRQCDGO,PRDNANOO,PRDNASNT,PRDNASPG,PRDNASPR,PRDNCDGO,PRDNESTD,PRDNFCAP,PRDNFCCN,PRDNFCCR,PRDNFCHF,PRDNFCHI,PRDNFCHR,PRDNMODO,PRDNMSEE,PRDNNMEM,PRDNOBSR,PRDNTPNM,PRDNTTDS,PRDNTTIN,PRDNTTNT,PRDNTTPT,PRDNUSAP,PRDNUSCR,PRDNUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'PRNM', 'PJRQCDGO,PRNMANOO,PRNMANVC,PRNMAPPR,PRNMAPPT,PRNMCCCP,PRNMCDGO,PRNMCDVC,PRNMCNBS,PRNMCNCT,PRNMDANO,PRNMDIAN,PRNMDIAS,PRNMDIMN,PRNMDIMX,PRNMDIVC,PRNMDSPR,PRNMESTD,PRNMFCHR,PRNMFNRS,PRNMHRDI,PRNMHRFN,PRNMHRIN,PRNMHRMS,PRNMHRMX,PRNMHRSX,PRNMIECE,PRNMMXVC,PRNMRCEX,PRNMRCNC,PRNMRCSP,PRNMSBUU,PRNMSCAP,PRNMSSTP,PRNMTPGP,PRNMUSRR,PRNMUTCG,PRNMUTDI,PRNMUTPR,PRNMUTSB' FROM DUAL
UNION ALL SELECT 'RHH', 'PRTE', 'NMNACDGO,PRTEBSEE,PRTECDGO,PRTECNCP,PRTEENTD,PRTEFCHR,PRTEPRCN,PRTEUSRR,PRTEVLRO' FROM DUAL
UNION ALL SELECT 'RHH', 'PTCN', 'CTLGCDGO,MPLDCDGO,PTCNAPRB,PTCNCDGO,PTCNDOCC,PTCNESTD,PTCNFCHD,PTCNFCHH,PTCNFCHR,PTCNHRAS,PTCNMTVO,PTCNOBSR,PTCNUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'PVNM', 'CPNMCDGO,MPLDCDGO,PRDNCDGO,PVNMBSCL,PVNMCDGO,PVNMESTD,PVNMFCHR,PVNMTPPR,PVNMUSRR,PVNMVLOR' FROM DUAL
UNION ALL SELECT 'RHH', 'PYIR', 'MPLDCDGO,PYIRANOO,PYIRAPPR,PYIRBSIM,PYIRCDGO,PYIRCTSF,PYIRESTD,PYIRFCHR,PYIRGSDC,PYIRIMCS,PYIRIMPG,PYIRINFT,PYIRINPR,PYIRINRL,PYIRMSDS,PYIRMSRS,PYIRMTVO,PYIRNCRG,PYIRRBJA,PYIRRTEF,PYIRRTEM,PYIRTPGS,PYIRUSRR,PYIRVGNT' FROM DUAL
UNION ALL SELECT 'RHH', 'RDPG', 'ASNTCDGO,CTBNCDGO,EGRSCDGO,PJRQCDGO,PRDNCDGO,RDPGCDGO,RDPGESTD,RDPGFCAC,RDPGFCEM,RDPGFCHR,RDPGNMEM,RDPGNMRO,RDPGOBSR,RDPGRTAR,RDPGTTAL,RDPGUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'RLPG', 'NMNACDGO,RLPGCDGO,RLPGESTD,RLPGFCEN,RLPGFCHA,RLPGFCHR,RLPGHASH,RLPGNETO,RLPGNMRO,RLPGPDFO,RLPGRCBD,RLPGTTDS,RLPGTTIN,RLPGUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'RNGL', 'CPNMCDGO,NMNACDGO,RNGLBSCL,RNGLCANT,RNGLCDGO,RNGLDSCR,RNGLFCHR,RNGLIMIE,RNGLIMIR,RNGLIMPN,RNGLMNAL,RNGLORDN,RNGLORGN,RNGLPRCN,RNGLPTRN,RNGLRFID,RNGLRFTB,RNGLTPCN,RNGLUSRR,RNGLVLRO' FROM DUAL
UNION ALL SELECT 'RHH', 'RSMN', 'MPLDCDGO,RSMNASNT,RSMNCDGO,RSMNENTR,RSMNENTT,RSMNEXTR,RSMNFCHA,RSMNFCHR,RSMNFNTE,RSMNHREX,RSMNHRNC,RSMNHRSP,RSMNHRTR,RSMNINCN,RSMNJSTC,RSMNJSTF,RSMNPRCS,RSMNSLAN,RSMNSLDA,RSMNSLDT,RSMNTPAS,RSMNTRDE,RSMNUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'SLAP', 'MPLDCDGO,PJRQCDGO,SLAPANOO,SLAPAPLC,SLAPCDGO,SLAPDIAS,SLAPESTD,SLAPFCAN,SLAPFCAP,SLAPFCCR,SLAPFCHA,SLAPFCHR,SLAPIDNT,SLAPNMCT,SLAPOBSR,SLAPRFID,SLAPRFTB,SLAPTPSL,SLAPUSRR,SLAPVLOR' FROM DUAL
UNION ALL SELECT 'RHH', 'SLCT', 'MPLDCDGO,SLCTAPRB,SLCTCDGO,SLCTDIAS,SLCTESTD,SLCTFCHD,SLCTFCHH,SLCTFCHR,SLCTFHAP,SLCTOBSR,SLCTUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'SLDV', 'MPLDCDGO,SLDVANOO,SLDVAPRT,SLDVASGN,SLDVCDCD,SLDVCDGO,SLDVDIAD,SLDVDIAR,SLDVDIPG,SLDVESTD,SLDVFCHF,SLDVFCHI,SLDVFCHR,SLDVPNDE,SLDVUSDO,SLDVUSRR,SLDVVLDI' FROM DUAL
UNION ALL SELECT 'RHH', 'SLOF', 'MPLDCDGO,PJRQCDGO,SLOFANOO,SLOFCDGO,SLOFESTD,SLOFFCGN,SLOFFCHR,SLOFFCPR,SLOFHASH,SLOFMESS,SLOFNMAR,SLOFNRCM,SLOFOBSR,SLOFRUTA,SLOFTPSL,SLOFUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'TBIR', 'PJRQCDGO,TBIRANOO,TBIRCDGO,TBIRESTD,TBIREXCS,TBIRFCHR,TBIRFRBS,TBIRIMFB,TBIRORDN,TBIRPRCN,TBIRUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'TMLQ', 'CPNMCDGO,LQDCCDGO,TMLQBSCL,TMLQCDGO,TMLQDIAS,TMLQDSCR,TMLQFCHR,TMLQORDN,TMLQTPCN,TMLQUSRR,TMLQVLRO' FROM DUAL
UNION ALL SELECT 'RHH', 'TPCE', 'PJRQCDGO,TPCECDGO,TPCEESTD,TPCEFCHR,TPCEMXMS,TPCENMBR,TPCERQRE,TPCETPRL,TPCEUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'TPGP', 'PJRQCDGO,TPGPANOO,TPGPCDGO,TPGPESTD,TPGPFCHR,TPGPNCAN,TPGPNCRG,TPGPUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'TRNO', 'TRNOCDGO,TRNOENTR,TRNOESTD,TRNOFCHR,TRNOMNDS,TRNOMNTS,TRNONMBR,TRNOSLDA,TRNOUSRR' FROM DUAL
UNION ALL SELECT 'RHH', 'UTLD', 'PJRQCDGO,PRDNCDGO,UTLDANOO,UTLDBS05,UTLDBS10,UTLDBS15,UTLDCDGO,UTLDESTD,UTLDEXCD,UTLDFCHR,UTLDFCPG,UTLDTPSB,UTLDTTCG,UTLDTTDI,UTLDUSRR,UTLDUTCN,UTLDVLCG,UTLDVLDI' FROM DUAL
UNION ALL SELECT 'AOT', 'ANIO', 'ANIOANIO,ANIOCDGO,ANIOESTD' FROM DUAL
UNION ALL SELECT 'CNT', 'ASNH', 'ASNHANOO,ASNHASNT,ASNHASRV,ASNHCDGO,ASNHESTD,ASNHFCHA,ASNHFCPR,ASNHMNDA,ASNHNMAL,ASNHNMMS,ASNHNMRO,ASNHOBSR,ASNHPRDO,ASNHRYYA,ASNHRYYB,ASNHRZZA,ASNHRZZB,ASNHUSRO,MYRHCDGO,PJRQCDGO,PLNTCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'ASNT', 'ASNTANOO,ASNTASRV,ASNTCDGO,ASNTESTD,ASNTFCAN,ASNTFCHA,ASNTFCPR,ASNTMNDA,ASNTMTAN,ASNTNMAL,ASNTNMMS,ASNTNMRO,ASNTOBSR,ASNTPRDO,ASNTRYYA,ASNTRYYB,ASNTRZZA,ASNTRZZB,ASNTUSAN,ASNTUSRO,MYRZCDGO,PJRQCDGO,PLNTCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'CNCS', 'CNCSCDGO,CNCSCDPD,CNCSESTD,CNCSFCDS,CNCSFCHA,CNCSNMBR,CNCSNMRO,CNCSNVLL,CNCSTPOO,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTAH', 'ASNHCDGO,CNCSCDGO,DTAHCDGO,DTAHCNTA,DTAHDBEE,DTAHDSCR,DTAHHBRR,DTAHNMCT,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTAS', 'ASNTCDGO,CNCSCDGO,DTASCDGO,DTASCNTA,DTASDBEE,DTASDSCR,DTASHBRR,DTASNMCT,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTMA', 'ASNTCDGO,ASNTESTD,CNCSNMBR,CNCSNMRO,DTMACDGO,DTMADBEE,DTMADSCR,DTMAFCHA,DTMAHBRR,DTMANMRO,DTMASLAC,MYANCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTMC', 'DTMCCDGO,DTMCCTCN,DTMCDBEE,DTMCHBRR,MYCCCDGO,PLNNCDGO,PLNNCDPD,PLNNNMBR,PLNNNVLL,PLNNTPOO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTMH', 'DTMHCDGO,DTMHCTCN,DTMHDBEE,DTMHHBRR,DTMHSLAC,DTMHSLAN,MYRHCDGO,MYRZCDGO,PLNNCDGO,PLNNCDPD,PLNNNMBR,PLNNNVLL,PLNNTPOO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTMT', 'DTMTCDGO,DTMTCSCG,DTMTCSNB,DTMTCSNM,DTMTCTCN,DTMTDBEE,DTMTHBRR,DTMTSCRP,DTMTSLAC,DTMTSLAN,MYRZCDGO,PLNNCDGO,PLNNCDPD,PLNNNMBR,PLNNNVLL,PLNNTPOO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTMY', 'DTMYCDGO,DTMYCTCN,DTMYDBEE,DTMYHBRR,DTMYSLAC,DTMYSLAN,MYRZCDGO,PLNNCDGO,PLNNCDPD,PLNNNMBR,PLNNNVLL,PLNNTPOO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTPL', 'DTPLAXL1,DTPLAXL2,DTPLAXL3,DTPLAXL4,DTPLAXL5,DTPLCDGO,DTPLDSCR,DTPLESTD,DTPLFCDS,DTPLFCFN,DTPLFCIN,DTPLMVMN,PLNNCDGO,PLNSCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'DTRP', 'DTRPCDGO,DTRPSGNO,NMBCTADS,NMBCTAHS,NUMCTADS,NUMCTAHS,PLNNCDDS,PLNNCDHS,RPRTCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'MTCH', 'MTCHCDGO,MTCHESTD,PJRQCDFN,PJRQCDOR,PLNNCDFN,PLNNCDOR' FROM DUAL
UNION ALL SELECT 'CNT', 'MYAN', 'CNCSCDGO,MYANCDGO,MYANCNTA,MYANNMBR,MYANOBSR,MYANSCNC,MYANSLAN,PJRQCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'MYCC', 'CNCSCDGO,MYCCCDGO,MYCCDBEE,MYCCHBRR,MYCCNMBR,MYCCNMRO,MYCCSLAC,MYCCSLAN,MYRCCDGO,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'MYRC', 'MYRCCDGO,MYRCFCHA,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'MYRH', 'MYRHCDGO,MYRHFCHA,MYRZCDGO,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'MYRZ', 'MYRZCDGO,MYRZFCHA,PRDOCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'NTRL', 'NTRLCDGO,NTRLCNCS,NTRLESTD,NTRLNMBR,NTRLNMRO,NTRLTPOO,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'CNT', 'PLNN', 'NTRLCDGO,PJRQCDGO,PLNNCDGO,PLNNCDPD,PLNNCNTA,PLNNESTD,PLNNFCDS,PLNNFCHA,PLNNNMBR,PLNNNVLL,PLNNTPOO' FROM DUAL
UNION ALL SELECT 'CNT', 'PLNS', 'PJRQCDGO,PLNSCDAL,PLNSCDGO,PLNSESTD,PLNSFCDS,PLNSNMBR,PLNSOBSR,PLNSSSTM' FROM DUAL
UNION ALL SELECT 'CNT', 'PLNT', 'PJRQCDGO,PLNTCDAL,PLNTCDGO,PLNTESTD,PLNTFCDS,PLNTNMBR,PLNTOBSR,PLNTSSTM' FROM DUAL
UNION ALL SELECT 'CNT', 'PRDO', 'PJRQCDGO,PRDOANNN,PRDOCDGO,PRDOCRRE,PRDODMCR,PRDODSMY,PRDOESTD,PRDOFNN,PRDOINCO,PRDOMSSS,PRDOMYCR,PRDOMYRZ,PRDONMBR' FROM DUAL
UNION ALL SELECT 'CNT', 'RCNC', 'PLNNCDGO,RCNCCDGO,RCNCDBEE,RCNCHBRR,RCNCNMBR,RCNCNMRO,RCNCSCNC,RCNCSLAC,RCNCSLAN' FROM DUAL
UNION ALL SELECT 'CNT', 'RDTC', 'CNCSCDGO,CNCSNMBR,CNCSNMRO,RCNCCDGO,RDTCCDGO,RDTCDBEE,RDTCHBRR' FROM DUAL
UNION ALL SELECT 'CNT', 'RPRT', 'PJRQCDGO,RPRTALTR,RPRTCDGO,RPRTESTD,RPRTNMBR' FROM DUAL
UNION ALL SELECT 'CNT', 'SDAS', 'DTASCDGO,SDASBSDP,SDASCDAC,SDASCDGO,SDASCSAD,SDASCTDP,SDASCTGR,SDASDPAC,SDASESTF,SDASFACT,SDASFCAD,SDASMJCP,SDASNMBR,SDASOBSR,SDASPRDP,SDASRSPN,SDASTIPO,SDASUBES,SDASUBGN,SDASVLNL,SDASVLRS,SDASVRMS,SDASVTMS' FROM DUAL
UNION ALL SELECT 'CNT', 'SLDS', 'PJRQCDGO,PLNNCDGO,SLDSCDGO,SLDSFCHN,SLDSSTDO,SLDSVLRR' FROM DUAL
),
COLS AS (
    SELECT E.OWNER_ESP,
           E.TABLA_ESP,
           TRIM(REGEXP_SUBSTR(E.COLS, '[^,]+', 1, L.LVL)) AS COLUMNA_ESP
    FROM   ESPERADO E
           CROSS JOIN (SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 60) L
    WHERE  REGEXP_SUBSTR(E.COLS, '[^,]+', 1, L.LVL) IS NOT NULL
)
-- ============================================================================
-- CONSULTA A - Tablas mapeadas por una entidad que NO existen en la base.
-- Esperado: 0 filas.
-- ============================================================================
SELECT DISTINCT 'A. TABLA INEXISTENTE' AS HALLAZGO,
       C.OWNER_ESP || '.' || C.TABLA_ESP AS OBJETO,
       NULL AS COLUMNA
FROM   COLS C
WHERE  NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP)

UNION ALL

-- ============================================================================
-- CONSULTA B - Columnas mapeadas que faltan, en tablas que SI existen.
-- Cada fila es un ORA-00904 esperando el despliegue. Esperado: 0 filas.
-- ============================================================================
SELECT 'B. COLUMNA FALTANTE',
       C.OWNER_ESP || '.' || C.TABLA_ESP,
       C.COLUMNA_ESP
FROM   COLS C
WHERE  EXISTS     (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP)
AND    NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS A
                   WHERE A.OWNER = C.OWNER_ESP AND A.TABLE_NAME = C.TABLA_ESP
                   AND   A.COLUMN_NAME = C.COLUMNA_ESP)

ORDER BY 1, 2, 3;

-- ============================================================================
-- FIN. Nada de lo anterior modifica datos. No hay bloque de reverso porque no
-- hay nada que revertir.
-- ============================================================================
