-- =====================================================================================
-- e3-05 — DDL: liquidaciones de ex-colaboradores de la administración anterior
--          RHH.LQEX (cabecera) y RHH.DLEX (conceptos)
-- Equipo omen-saa-3 · 2026-09-30 · Diseño: docs/logica-negocio/rhh/API-LIQUIDACION-EXCOLABORADORES.md
--
-- ⛔ VA ANTES DEL WAR que trae las entidades LiquidacionExterna / DetalleLiquidacionExterna.
--    Con el WAR primero, cualquier lectura de esas entidades revienta con ORA-00942.
-- Sin FK hacia TSR ni PGS a propósito (diseño D6): una FK entre esquemas exige GRANT REFERENCES.
-- Correr de corrido: el BLOQUE 1 se detiene solo si alguna tabla ya existe.
-- =====================================================================================

-- BLOQUE 0 — CONTROL ANTES: las dos tablas no deben existir (se esperan CERO filas)
SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE TABLE_NAME IN ('LQEX', 'DLEX');

-- BLOQUE 1 — DDL
DECLARE
    v_existen NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existen FROM ALL_TABLES WHERE TABLE_NAME IN ('LQEX', 'DLEX');
    IF v_existen > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'LQEX o DLEX ya existen en algún esquema: el nombre de 4 letras '
            || 'es único en todo el proyecto. No se crea nada; revisar el BLOQUE 0.');
    END IF;

    EXECUTE IMMEDIATE q'[
    CREATE TABLE RHH.LQEX (
        LQEXCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        PJRQCDGO NUMBER NOT NULL,
        LQEXTPID VARCHAR2(1) NOT NULL,
        LQEXIDNT VARCHAR2(20) NOT NULL,
        LQEXAPLL VARCHAR2(100) NOT NULL,
        LQEXNMBR VARCHAR2(100) NOT NULL,
        LQEXCRGO VARCHAR2(150),
        LQEXFCIN DATE,
        LQEXFCSL DATE NOT NULL,
        LQEXCSTR NUMBER,
        LQEXULRM NUMBER(18,2),
        LQEXTTIN NUMBER(18,2) NOT NULL,
        LQEXTTDS NUMBER(18,2) NOT NULL,
        LQEXNETO NUMBER(18,2) NOT NULL,
        LQEXPRDP NUMBER NOT NULL,
        LQEXBEXT NUMBER,
        LQEXTPCT NUMBER,
        LQEXNMCT VARCHAR2(30),
        LQEXESTD NUMBER DEFAULT 1 NOT NULL,
        LQEXPGTR NUMBER,
        LQEXASNT NUMBER,
        LQEXFCPG DATE,
        LQEXOBSR VARCHAR2(500),
        LQEXMTAN VARCHAR2(300),
        LQEXFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LQEXUSRR VARCHAR2(60),
        CONSTRAINT PK_LQEX PRIMARY KEY (LQEXCDGO),
        CONSTRAINT FK_LQEX_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ (PJRQCDGO),
        CONSTRAINT FK_LQEX_CSTR FOREIGN KEY (LQEXCSTR) REFERENCES RHH.CSTR (CSTRCDGO),
        CONSTRAINT CK_LQEXTPID CHECK (LQEXTPID IN ('C', 'P')),
        CONSTRAINT CK_LQEXESTD CHECK (LQEXESTD IN (1, 2, 3, 4)),
        CONSTRAINT CK_LQEXNETO CHECK (LQEXNETO > 0),
        CONSTRAINT CK_LQEXFCSL CHECK (LQEXFCSL < DATE '2026-01-01')
    )]';

    EXECUTE IMMEDIATE 'CREATE INDEX RHH.IX_LQEX_IDNT ON RHH.LQEX (LQEXIDNT)';
    EXECUTE IMMEDIATE 'CREATE INDEX RHH.IX_LQEX_PGTR ON RHH.LQEX (LQEXPGTR)';

    EXECUTE IMMEDIATE q'[
    CREATE TABLE RHH.DLEX (
        DLEXCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        LQEXCDGO NUMBER NOT NULL,
        DLEXTPCN NUMBER NOT NULL,
        DLEXDSCR VARCHAR2(200),
        DLEXVLOR NUMBER(18,2) NOT NULL,
        DLEXORDN NUMBER,
        DLEXFCHR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        DLEXUSRR VARCHAR2(60),
        CONSTRAINT PK_DLEX PRIMARY KEY (DLEXCDGO),
        CONSTRAINT FK_DLEX_LQEX FOREIGN KEY (LQEXCDGO) REFERENCES RHH.LQEX (LQEXCDGO),
        CONSTRAINT CK_DLEXTPCN CHECK (DLEXTPCN IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23)),
        CONSTRAINT CK_DLEXVLOR CHECK (DLEXVLOR > 0)
    )]';

    EXECUTE IMMEDIATE 'CREATE INDEX RHH.IX_DLEX_LQEX ON RHH.DLEX (LQEXCDGO)';

    EXECUTE IMMEDIATE q'[COMMENT ON TABLE RHH.LQEX IS 'Liquidacion de un ex-colaborador de la administracion anterior (salida antes de 2026), sin registro en MPLD. Se paga por Tesoreria (origen RHH_LIQ_EXCOLABORADOR)']';
    EXECUTE IMMEDIATE q'[COMMENT ON TABLE RHH.DLEX IS 'Conceptos de la liquidacion de un ex-colaborador: tipo (RhhConceptoLiquidacionExterna) y valor siempre positivo']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN RHH.LQEX.LQEXPRDP IS 'Producto de pago PGS.PRDP cuyo grupo apunta a la cuenta por pagar que se debita al pagar (sin FK: otro esquema)']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN RHH.LQEX.LQEXFCPG IS 'Fecha real del pago confirmado en Tesoreria; decide el anio del RDEP']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN RHH.LQEX.LQEXESTD IS '1 REGISTRADA, 2 EN_TESORERIA, 3 PAGADA, 4 ANULADA']';
END;
/

-- BLOQUE 2 — CONTROL DESPUÉS (se esperan 2 tablas y 11 restricciones con nombre:
--           LQEX: PK, 2 FK, 4 CHECK · DLEX: PK, 1 FK, 2 CHECK)
SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE TABLE_NAME IN ('LQEX', 'DLEX');
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM ALL_CONSTRAINTS
 WHERE OWNER = 'RHH' AND TABLE_NAME IN ('LQEX', 'DLEX') AND CONSTRAINT_NAME NOT LIKE 'SYS_%'
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;

-- REVERSO (comentado; sólo si las tablas están vacías y hay que deshacerlo)
-- DROP TABLE RHH.DLEX;
-- DROP TABLE RHH.LQEX;
