-- =====================================================================
-- lap1-11  ·  RHH.DVAN — devolucion de un anticipo a empleado
-- Equipo lap-saa-1 · 2026-09-07
-- =====================================================================
--
-- QUE RESUELVE
-- Hoy un anticipo solo se recupera descontandolo del rol. Si el empleado
-- deposita la plata en la cuenta de la empresa no hay donde registrarlo,
-- no se contabiliza, y el descuento del mes se le aplica igual: se le cobra
-- dos veces.
--
-- Cada devolucion genera un ingreso de tesoreria (TSR.INGR), que ya
-- contabiliza DEBE banco / HABER la cuenta del producto y emite el
-- movimiento bancario para la conciliacion.
--
-- VA ANTES DEL WAR. La entidad mapea estas columnas.
-- Diseno: docs/logica-negocio/rhh/API-DEVOLUCION-ANTICIPO.md
-- =====================================================================


-- ---------------------------------------------------------------------
-- CONTROL 1 — la tabla no debe existir todavia (0 filas esperadas).
-- ---------------------------------------------------------------------
SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE TABLE_NAME = 'DVAN';


-- ---------------------------------------------------------------------
-- CONTROL 2 — foto de los anticipos vivos, para tener el antes.
--             ANTEESTD: 1 solicitado, 2 aprobado, 3 pagado,
--                       4 en descuento, 5 cancelado, 6 anulado.
-- ---------------------------------------------------------------------
SELECT a.ANTEESTD AS ESTADO,
       COUNT(*)   AS ANTICIPOS,
       SUM(NVL(a.ANTESLDD, 0)) AS SALDO_PENDIENTE
  FROM RHH.ANTE a
 GROUP BY a.ANTEESTD
 ORDER BY a.ANTEESTD;


-- =====================================================================
-- BLOQUE 1: RHH.DVAN
-- =====================================================================
CREATE TABLE RHH.DVAN (
    DVANCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    ANTECDGO NUMBER NOT NULL,
    DVANFCHA DATE NOT NULL,
    DVANVLOR NUMBER(18,2) NOT NULL,
    CNBCCDGO NUMBER NOT NULL,
    DVANRFRN VARCHAR2(200),
    DVANOBSR VARCHAR2(2000),
    INGRCDGO NUMBER,
    DVANASNT NUMBER,
    DVANESTD NUMBER DEFAULT 1 NOT NULL,
    DVANMTAN VARCHAR2(500),
    DVANFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DVANUSAR NUMBER,
    CONSTRAINT PK_DVAN PRIMARY KEY (DVANCDGO),
    CONSTRAINT FK_DVAN_ANTE FOREIGN KEY (ANTECDGO) REFERENCES RHH.ANTE(ANTECDGO),
    CONSTRAINT CK_DVAN_ESTD CHECK (DVANESTD IN (1,2)),
    CONSTRAINT CK_DVAN_VLOR CHECK (DVANVLOR > 0)
);

CREATE INDEX RHH.IDX_DVAN_ANTE ON RHH.DVAN(ANTECDGO);
CREATE INDEX RHH.IDX_DVAN_CNBC ON RHH.DVAN(CNBCCDGO);

COMMENT ON TABLE RHH.DVAN IS 'Devolucion de un anticipo: el empleado deposita en la cuenta de la empresa en vez de que se le descuente del rol';
COMMENT ON COLUMN RHH.DVAN.DVANCDGO IS 'PK';
COMMENT ON COLUMN RHH.DVAN.ANTECDGO IS 'Anticipo devuelto (RHH.ANTE)';
COMMENT ON COLUMN RHH.DVAN.DVANFCHA IS 'Fecha real del deposito, no la de captura';
COMMENT ON COLUMN RHH.DVAN.DVANVLOR IS 'Valor devuelto; puede ser parcial y puede haber varias por anticipo';
COMMENT ON COLUMN RHH.DVAN.CNBCCDGO IS 'Cuenta bancaria de la empresa donde deposito (TSR.CNBC)';
COMMENT ON COLUMN RHH.DVAN.DVANRFRN IS 'Numero de papeleta o de transferencia';
COMMENT ON COLUMN RHH.DVAN.INGRCDGO IS 'Ingreso de tesoreria generado (TSR.INGR). Id crudo a proposito: Ingreso tiene varios ManyToOne EAGER';
COMMENT ON COLUMN RHH.DVAN.DVANASNT IS 'Asiento del ingreso (CNT.ASNT)';
COMMENT ON COLUMN RHH.DVAN.DVANESTD IS '1 Vigente, 2 Anulada';

-- ⚠️ La FK a TSR.CNBC se deja fuera A PROPOSITO: es cross-schema y el rol
--    DBA no habilita REFERENCES por si solo (hace falta un GRANT explicito
--    de TSR a RHH). Si se quiere la FK, correr antes:
--      GRANT REFERENCES ON TSR.CNBC TO RHH;
--    y despues:
--      ALTER TABLE RHH.DVAN ADD CONSTRAINT FK_DVAN_CNBC
--          FOREIGN KEY (CNBCCDGO) REFERENCES TSR.CNBC(CNBCCDGO);
--    Sin la FK la columna sigue siendo valida: el backend verifica que la
--    cuenta exista antes de grabar.


-- =====================================================================
-- BLOQUE 2: producto de cobro para la devolucion
-- =====================================================================
-- procesarIngreso arma el HABER con la cuenta del GRUPO del producto. La
-- devolucion tiene que acreditar la MISMA cuenta que la entrega del
-- anticipo debito: RhhLineaAsiento.CUENTAS_POR_COBRAR_EMPLEADOS (14).
--
-- ⛔ Si acreditara otra, el saldo del empleado no se cerraria nunca y no se
--    veria hasta un cierre.

-- ---------------------------------------------------------------------
-- CONTROL 3 — que cuenta usa hoy la linea 14. Es el insumo del INSERT.
-- ---------------------------------------------------------------------
SELECT d.DTPLLNEA AS LINEA,
       p.PLNNCDGO AS ID_CUENTA,
       p.PLNNCNTA AS CUENTA,
       p.PLNNNMBR AS NOMBRE_CUENTA
  FROM CNT.DTPL d
  JOIN CNT.PLNN p ON p.PLNNCDGO = d.PLNNCDGO
 WHERE d.DTPLLNEA = 14;

-- ⚠️ Nombres de CNT.DTPL sin verificar contra el DDL real. Si falla:
--      SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS
--       WHERE OWNER='CNT' AND TABLE_NAME='DTPL' ORDER BY COLUMN_ID;


-- ---------------------------------------------------------------------
-- CONTROL 4 — quiza el producto ya existe y no hace falta crear nada.
-- ---------------------------------------------------------------------
SELECT p.ID, p.CODIGO, p.NOMBRE, g.GRPPNMBR, c.PLNNCNTA
  FROM PGS.PRDP p
  LEFT JOIN PGS.GRPP g ON g.GRPPCDGO = p.GRUPOPRODUCTO
  LEFT JOIN CNT.PLNN c ON c.PLNNCDGO = g.PLNNCDGO
 WHERE UPPER(p.NOMBRE) LIKE '%EMPLEADO%'
    OR UPPER(p.NOMBRE) LIKE '%ANTICIPO%'
    OR UPPER(g.GRPPNMBR) LIKE '%COBRAR%EMPLEADO%';


-- ---------------------------------------------------------------------
-- El grupo y el producto. COMENTADO: completar <ID_CUENTA_LINEA_14> con
-- lo que devolvio el CONTROL 3 y <ID_EMPRESA> con la empresa.
-- Si el CONTROL 4 ya mostro un producto con la cuenta correcta, NO crear
-- otro: usar ese y anotar su CODIGO en el backend.
-- ---------------------------------------------------------------------
-- INSERT INTO PGS.GRPP (GRPPNMBR, PLNNCDGO, PJRQCDGO, GRPPESTD)
-- VALUES ('CUENTAS POR COBRAR EMPLEADOS', <ID_CUENTA_LINEA_14>, <ID_EMPRESA>, 1);
--
-- COMMIT;
--
-- INSERT INTO PGS.PRDP (EMPRESA, GRUPOPRODUCTO, NOMBRE, CODIGO, ESTADO)
-- SELECT <ID_EMPRESA>, GRPPCDGO, 'Devolucion de anticipo a empleado', 'RHH-DVAN', 1
--   FROM PGS.GRPP WHERE GRPPNMBR = 'CUENTAS POR COBRAR EMPLEADOS';
--
-- COMMIT;
--
-- ⚠️ Verificar columnas NOT NULL de PGS.GRPP y PGS.PRDP antes de
--    descomentar, con ALL_TAB_COLUMNS.


-- ---------------------------------------------------------------------
-- CONTROL 5 — despues: la tabla y el producto.
-- ---------------------------------------------------------------------
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'RHH' AND TABLE_NAME = 'DVAN';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
  FROM ALL_CONSTRAINTS WHERE OWNER = 'RHH' AND TABLE_NAME = 'DVAN';

SELECT p.CODIGO, p.NOMBRE, c.PLNNCNTA AS CUENTA
  FROM PGS.PRDP p
  JOIN PGS.GRPP g ON g.GRPPCDGO = p.GRUPOPRODUCTO
  JOIN CNT.PLNN c ON c.PLNNCDGO = g.PLNNCDGO
 WHERE p.CODIGO = 'RHH-DVAN';


-- ---------------------------------------------------------------------
-- CONTROL 6 — el que importa: la cuenta del producto tiene que ser la
--             MISMA de la linea 14. Debe decir COINCIDE.
-- ---------------------------------------------------------------------
SELECT g.PLNNCDGO AS CUENTA_DEL_PRODUCTO,
       d.PLNNCDGO AS CUENTA_DE_LA_PLANTILLA,
       CASE WHEN g.PLNNCDGO = d.PLNNCDGO THEN 'COINCIDE' ELSE 'NO COINCIDE' END AS DIAGNOSTICO
  FROM PGS.PRDP p
  JOIN PGS.GRPP g ON g.GRPPCDGO = p.GRUPOPRODUCTO
  CROSS JOIN (SELECT PLNNCDGO FROM CNT.DTPL WHERE DTPLLNEA = 14 AND ROWNUM = 1) d
 WHERE p.CODIGO = 'RHH-DVAN';


-- =====================================================================
-- REVERSO (comentado a proposito — no correr salvo que haga falta)
-- =====================================================================
-- Solo si el WAR no esta desplegado y no se registro ninguna devolucion.
--
-- DELETE FROM PGS.PRDP WHERE CODIGO = 'RHH-DVAN';
-- DELETE FROM PGS.GRPP WHERE GRPPNMBR = 'CUENTAS POR COBRAR EMPLEADOS';
-- DROP TABLE RHH.DVAN;
-- COMMIT;
