-- =====================================================================
-- lap1-08  ·  RHH.PLIS / RHH.DLIS — planillas del IESS y su conciliacion
-- Equipo lap-saa-1 · 2026-09-07
-- =====================================================================
--
-- Captura la planilla que EMITE el portal del IESS para enfrentarla contra
-- la planilla de control antes de pagar. Son varias por periodo, una por
-- rubro: rol normal, prestamos quirografarios, prestamos hipotecarios y
-- fondos de reserva.
--
-- VA ANTES DEL WAR. Las entidades mapean estas columnas; con el WAR primero
-- cualquier lectura muere con ORA-00904.
--
-- Diseno completo: docs/logica-negocio/rhh/API-PLANILLA-IESS.md
-- =====================================================================


-- ---------------------------------------------------------------------
-- CONTROL 1 — las tablas no deben existir todavia (0 filas esperadas).
-- ---------------------------------------------------------------------
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME IN ('PLIS', 'DLIS');


-- ---------------------------------------------------------------------
-- CONTROL 2 — el bloque de rubros de este equipo (PRBR 330-349 /
--             PDTR 1600-1699) debe estar libre. Se esperan 0 filas en las
--             dos consultas, y los MAX por debajo del bloque.
-- ---------------------------------------------------------------------
SELECT PRBRCDGO, PRBRNMBR FROM SCP.PRBR WHERE PRBRCDGO BETWEEN 330 AND 349;

SELECT PDTRCDGO, PDTRNMBR FROM SCP.PDTR WHERE PDTRCDGO BETWEEN 1600 AND 1699;

SELECT (SELECT MAX(PRBRCDGO) FROM SCP.PRBR) AS MAX_PRBR,
       (SELECT MAX(PDTRCDGO) FROM SCP.PDTR) AS MAX_PDTR
  FROM DUAL;


-- =====================================================================
-- BLOQUE 1: RHH.PLIS — cabecera de la planilla emitida por el IESS
-- =====================================================================
CREATE TABLE RHH.PLIS (
    PLISCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PJRQCDGO NUMBER NOT NULL,
    PRDNCDGO NUMBER NOT NULL,
    PLISTIPO NUMBER NOT NULL,
    PLISNMCM VARCHAR2(50) NOT NULL,
    PLISFCEM DATE,
    PLISFCMX DATE,
    PLISVLIS NUMBER(18,2) NOT NULL,
    PLISVLCT NUMBER(18,2),
    PLISDIFR NUMBER(18,2),
    PLISESTD NUMBER DEFAULT 1 NOT NULL,
    PLISFCPG DATE,
    PLISASNT NUMBER,
    PLISOBSR VARCHAR2(1000),
    PLISMTAN VARCHAR2(500),
    PLISFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PLISUSAR NUMBER,
    CONSTRAINT PK_PLIS PRIMARY KEY (PLISCDGO),
    CONSTRAINT FK_PLIS_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT FK_PLIS_PRDN FOREIGN KEY (PRDNCDGO) REFERENCES RHH.PRDN(PRDNCDGO),
    CONSTRAINT CK_PLIS_TIPO CHECK (PLISTIPO IN (1,2,3,4)),
    CONSTRAINT CK_PLIS_ESTD CHECK (PLISESTD IN (1,2,3,4))
);

CREATE INDEX RHH.IDX_PLIS_PRDN ON RHH.PLIS(PRDNCDGO);
CREATE INDEX RHH.IDX_PLIS_PJRQ ON RHH.PLIS(PJRQCDGO);

-- El comprobante del portal no se repite dentro de una empresa y un tipo.
-- Se deja fuera el estado a proposito: una planilla anulada y una nueva con
-- el MISMO comprobante seria volver a registrar lo ya rechazado.
CREATE UNIQUE INDEX RHH.UX_PLIS_COMPROBANTE ON RHH.PLIS(PJRQCDGO, PLISTIPO, PLISNMCM);

COMMENT ON TABLE RHH.PLIS IS 'Planilla emitida por el portal del IESS: se captura para conciliar contra la planilla de control antes de pagar';
COMMENT ON COLUMN RHH.PLIS.PLISCDGO IS 'PK';
COMMENT ON COLUMN RHH.PLIS.PJRQCDGO IS 'Empresa (SCP.PJRQ)';
COMMENT ON COLUMN RHH.PLIS.PRDNCDGO IS 'Periodo de nomina (RHH.PRDN)';
COMMENT ON COLUMN RHH.PLIS.PLISTIPO IS 'Tipo de planilla (rubro 330): 1 rol normal, 2 quirografarios, 3 hipotecarios, 4 fondos de reserva';
COMMENT ON COLUMN RHH.PLIS.PLISNMCM IS 'Numero de comprobante que emitio el portal';
COMMENT ON COLUMN RHH.PLIS.PLISFCEM IS 'Fecha de emision del comprobante';
COMMENT ON COLUMN RHH.PLIS.PLISFCMX IS 'Fecha maxima de pago del comprobante';
COMMENT ON COLUMN RHH.PLIS.PLISVLIS IS 'Total que cobra el IESS';
COMMENT ON COLUMN RHH.PLIS.PLISVLCT IS 'Total segun nuestra planilla de control al momento de conciliar (snapshot, no se recalcula)';
COMMENT ON COLUMN RHH.PLIS.PLISDIFR IS 'valorIess - valorControl, grabado para poder auditar que diferencia se acepto';
COMMENT ON COLUMN RHH.PLIS.PLISESTD IS '1 Registrada, 2 Conciliada, 3 Pagada, 4 Anulada';
COMMENT ON COLUMN RHH.PLIS.PLISFCPG IS 'Fecha real en que el IESS debito';
COMMENT ON COLUMN RHH.PLIS.PLISASNT IS 'Asiento del pago (CNT.ASNT); se llena al pagar';


-- =====================================================================
-- BLOQUE 2: RHH.DLIS — renglones del comprobante
-- =====================================================================
-- El total puede cuadrar y estar mal por dentro: aca vive el valor real de
-- la conciliacion.
CREATE TABLE RHH.DLIS (
    DLISCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PLISCDGO NUMBER NOT NULL,
    DLISCNCP VARCHAR2(200) NOT NULL,
    DLISVLIS NUMBER(18,2) NOT NULL,
    DLISVLCT NUMBER(18,2),
    DLISDIFR NUMBER(18,2),
    CONSTRAINT PK_DLIS PRIMARY KEY (DLISCDGO),
    CONSTRAINT FK_DLIS_PLIS FOREIGN KEY (PLISCDGO) REFERENCES RHH.PLIS(PLISCDGO)
);

CREATE INDEX RHH.IDX_DLIS_PLIS ON RHH.DLIS(PLISCDGO);

COMMENT ON TABLE RHH.DLIS IS 'Renglones del comprobante de la planilla del IESS, con su contraparte de la planilla de control';
COMMENT ON COLUMN RHH.DLIS.DLISCNCP IS 'Texto del renglon tal como lo trae el portal';
COMMENT ON COLUMN RHH.DLIS.DLISVLIS IS 'Valor del renglon segun el IESS';
COMMENT ON COLUMN RHH.DLIS.DLISVLCT IS 'Valor equivalente segun la planilla de control; NULL si no hay control para ese tipo';
COMMENT ON COLUMN RHH.DLIS.DLISDIFR IS 'valorIess - valorControl del renglon';


-- =====================================================================
-- BLOQUE 3: rubro del tipo de planilla
-- =====================================================================
-- Bloque reservado de este equipo: PRBR 330-349 / PDTR 1600-1699.
-- Convencion del equipo: PRBRALTR = PRBRCDGO.
-- ⚠️ Correr el CONTROL 2 antes: si el MAX ya alcanzo el bloque, PARAR.
INSERT INTO SCP.PRBR (PRBRCDGO, PRBRNMBR, PRBRALTR, PRBRESTD)
VALUES (330, 'RHH_TIPO_PLANILLA_IESS', 330, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRNMBR, PDTRALTR, PDTRESTD)
VALUES (1600, 330, 'ROL NORMAL', 1, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRNMBR, PDTRALTR, PDTRESTD)
VALUES (1601, 330, 'PRESTAMOS QUIROGRAFARIOS', 2, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRNMBR, PDTRALTR, PDTRESTD)
VALUES (1602, 330, 'PRESTAMOS HIPOTECARIOS', 3, 1);

INSERT INTO SCP.PDTR (PDTRCDGO, PRBRCDGO, PDTRNMBR, PDTRALTR, PDTRESTD)
VALUES (1603, 330, 'FONDOS DE RESERVA', 4, 1);

COMMIT;

-- ⚠️ VERIFICAR ANTES DE CORRER EL BLOQUE 3: las columnas de SCP.PRBR y
-- SCP.PDTR de arriba son las que usa el resto del sistema, pero si esta
-- instalacion tiene columnas NOT NULL adicionales el INSERT falla. Correr
-- primero:
--   SELECT COLUMN_NAME, NULLABLE, DATA_TYPE FROM ALL_TAB_COLUMNS
--    WHERE OWNER='SCP' AND TABLE_NAME IN ('PRBR','PDTR') ORDER BY TABLE_NAME, COLUMN_ID;
-- y completar las que falten en vez de adivinar.


-- ---------------------------------------------------------------------
-- CONTROL 3 — despues: las dos tablas existen con sus constraints.
-- ---------------------------------------------------------------------
SELECT TABLE_NAME, NUM_ROWS FROM ALL_TABLES
 WHERE OWNER = 'RHH' AND TABLE_NAME IN ('PLIS', 'DLIS');

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
  FROM ALL_CONSTRAINTS
 WHERE OWNER = 'RHH' AND TABLE_NAME IN ('PLIS', 'DLIS')
 ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS FROM ALL_INDEXES
 WHERE OWNER = 'RHH' AND TABLE_NAME IN ('PLIS', 'DLIS');


-- ---------------------------------------------------------------------
-- CONTROL 4 — el rubro y sus cuatro detalles.
-- ---------------------------------------------------------------------
SELECT r.PRBRCDGO, r.PRBRNMBR, r.PRBRALTR,
       d.PDTRCDGO, d.PDTRNMBR, d.PDTRALTR
  FROM SCP.PRBR r
  LEFT JOIN SCP.PDTR d ON d.PRBRCDGO = r.PRBRCDGO
 WHERE r.PRBRCDGO = 330
 ORDER BY d.PDTRCDGO;


-- =====================================================================
-- LO QUE ESTE SCRIPT NO HACE, Y ES A PROPOSITO
-- =====================================================================
-- No separa la cuenta por pagar de prestamos quirografarios de la de
-- hipotecarios. Hoy RhhLineaAsiento tiene UNA sola linea (12) para los dos,
-- asi que dos planillas distintas debitan el mismo saldo y una diferencia en
-- una se compensa con la otra sin que nadie la vea (§2.1 del diseno).
-- Separarlas toca las plantillas contables y quiza el plan de cuentas, y
-- necesita que la contadora confirme contra que cuenta se registra hoy cada
-- una. Es prerrequisito del PAGO, no del registro: la Fase 1 corre sin esto.


-- =====================================================================
-- REVERSO (comentado a proposito — no correr salvo que haga falta)
-- =====================================================================
-- Solo tiene sentido si el WAR con las entidades nuevas NO esta desplegado.
--
-- DELETE FROM SCP.PDTR WHERE PDTRCDGO BETWEEN 1600 AND 1603;
-- DELETE FROM SCP.PRBR WHERE PRBRCDGO = 330;
-- DROP TABLE RHH.DLIS;
-- DROP TABLE RHH.PLIS;
-- COMMIT;
