-- =====================================================================
-- CREAR PGS.DRC2 — DetalleRetencionCompraV2
-- =====================================================================
-- Confirmado el 2026-08-11: la tabla no existe, aunque la entidad
-- com.saa.model.cxp.DetalleRetencionCompraV2 la mapea. Sin ella, cargar
-- una retencion recibida por la ruta V2 falla al persistir el detalle.
--
-- PGS.DRC2 es el gemelo estructural de CBR.DRV2 (DetalleRetencionV2):
-- las dos entidades declaran exactamente los mismos 19 campos. La unica
-- diferencia es la FK de cabecera:
--     CBR.DRV2.RETENCIONV2 -> CBR.RTV2   (retencion que la empresa EMITE)
--     PGS.DRC2.RETENCIONV2 -> PGS.RCV2   (retencion que el cliente NOS emite)
--
-- Ejecutar como PGS, o con un usuario que pueda crear objetos en PGS.
-- No hay bloques PL/SQL: ejecute sentencia por sentencia (Ctrl+Enter).
-- =====================================================================


-- ---------------------------------------------------------------------
-- OPCION A (RECOMENDADA) — Copiar la estructura exacta de CBR.DRV2
-- ---------------------------------------------------------------------
-- Garantiza que los tipos y longitudes queden identicos a los del gemelo,
-- sin depender de que yo los haya transcrito bien. Requiere SELECT sobre
-- CBR.DRV2 (su usuario ya lo tiene: aparecio en la consulta de
-- ALL_OBJECTS). CTAS copia nombres, tipos y NOT NULL, pero NO copia la
-- PK, la identidad ni las FK: por eso se agregan despues.

CREATE TABLE PGS.DRC2 AS SELECT * FROM CBR.DRV2 WHERE 1 = 0;

-- CTAS no copia la identidad, y Oracle NO permite convertir una columna
-- existente en columna de identidad: 'MODIFY ID GENERATED AS IDENTITY'
-- falla con ORA-30673 porque esa sintaxis solo cambia las opciones de una
-- columna que YA es identidad. Hay que reemplazar la columna. La tabla
-- esta vacia, asi que no se pierde nada.
-- Efecto secundario: ID queda como ultima columna en vez de primera. Es
-- solo cosmetico — JPA mapea por nombre y los scripts listan las columnas
-- explicitamente, nada depende del orden fisico.

ALTER TABLE PGS.DRC2 DROP COLUMN ID;

ALTER TABLE PGS.DRC2 ADD ID NUMBER GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE PGS.DRC2 ADD CONSTRAINT PK_DRC2 PRIMARY KEY (ID);

ALTER TABLE PGS.DRC2 MODIFY RETENCIONV2 NOT NULL;

ALTER TABLE PGS.DRC2 ADD CONSTRAINT FK_DRC2_RETENCION FOREIGN KEY (RETENCIONV2) REFERENCES PGS.RCV2 (ID);

CREATE INDEX IDX_DRC2_RETENCION ON PGS.DRC2 (RETENCIONV2);

CREATE INDEX IDX_DRC2_NUMDOCRETEN ON PGS.DRC2 (NUMDOCRETEN);

COMMENT ON TABLE PGS.DRC2 IS 'Detalle de retenciones v2 recibidas de clientes. Cada fila es un impuesto retenido; NUMDOCRETEN identifica la factura de venta a la que abona.';

COMMENT ON COLUMN PGS.DRC2.NUMDOCRETEN IS 'Numero del documento sustento (la factura de venta que esta retencion abona). Sin este dato no se puede registrar el cobro sobre la factura.';


-- ---------------------------------------------------------------------
-- OPCION B — DDL explicito (usar solo si la OPCION A no es viable)
-- ---------------------------------------------------------------------
-- Transcrito de las anotaciones de DetalleRetencionCompraV2.java. Si usa
-- esta opcion, compare despues con CBR.DRV2 usando la verificacion de mas
-- abajo, porque los tipos numericos podrian no coincidir exactamente.
--
-- CREATE TABLE PGS.DRC2 (
--     ID                   NUMBER          GENERATED BY DEFAULT AS IDENTITY,
--     RETENCIONV2          NUMBER          NOT NULL,
--     TIPODOCRETEN         VARCHAR2(2),
--     NUMDOCRETEN          VARCHAR2(100),
--     FECHAEMIDOC          DATE,
--     FECHAREG             DATE,
--     DOCRESAUTORIZACION   VARCHAR2(100),
--     DOCRESTSINIMPUESTOS  NUMBER(18,2),
--     DOCRESIVACERO        NUMBER(18,2),
--     DOCRESPORIVA         NUMBER(18,2),
--     DOCRESTOTALIVA       NUMBER(18,2),
--     DOCRESTOTAL          NUMBER(18,2),
--     DOCRESFORPAGO        VARCHAR2(2),
--     CODIMPUESTO          VARCHAR2(2),
--     CODRETENCION         VARCHAR2(100),
--     BASEIMPONIBLE        NUMBER(18,2),
--     PORCENTAJERETEN      NUMBER(18,2),
--     VALORRETEN           NUMBER(18,2),
--     ESTADO               NUMBER(1),
--     CONSTRAINT PK_DRC2 PRIMARY KEY (ID)
-- );
--
-- ALTER TABLE PGS.DRC2 ADD CONSTRAINT FK_DRC2_RETENCION FOREIGN KEY (RETENCIONV2) REFERENCES PGS.RCV2 (ID);
-- CREATE INDEX IDX_DRC2_RETENCION ON PGS.DRC2 (RETENCIONV2);
-- CREATE INDEX IDX_DRC2_NUMDOCRETEN ON PGS.DRC2 (NUMDOCRETEN);


-- ---------------------------------------------------------------------
-- PRIVILEGIOS
-- ---------------------------------------------------------------------
-- Si el datasource de la aplicacion NO se conecta como PGS, hay que dar
-- los mismos permisos que tiene PGS.DRCM. Para ver quien los tiene hoy:
--
--   SELECT grantee, privilege FROM all_tab_privs
--    WHERE owner = 'PGS' AND table_name = 'DRCM'
--    ORDER BY grantee, privilege;
--
-- Y replicarlos, por ejemplo:
--   GRANT SELECT, INSERT, UPDATE, DELETE ON PGS.DRC2 TO <usuario_app>;
--
-- Recuerde que los privilegios son POR OBJETO: que el usuario vea DRCM no
-- implica que vea DRC2.


-- ---------------------------------------------------------------------
-- VERIFICACION — comparar DRC2 contra su gemelo DRV2
-- ---------------------------------------------------------------------
-- Debe devolver una fila por columna, con las dos definiciones lado a
-- lado y la marca 'DIFERENTE' donde no coincidan. Lo esperado es que la
-- unica diferencia relevante sea ninguna (los tipos deben ser iguales).

SELECT NVL(a.column_name, b.column_name) AS COLUMNA,
       a.data_type || '(' || NVL(TO_CHAR(a.data_length), '-') || ')' AS DRC2_PGS,
       b.data_type || '(' || NVL(TO_CHAR(b.data_length), '-') || ')' AS DRV2_CBR,
       CASE WHEN a.column_name IS NULL THEN 'FALTA EN DRC2'
            WHEN b.column_name IS NULL THEN 'SOBRA EN DRC2'
            WHEN a.data_type <> b.data_type OR NVL(a.data_length,0) <> NVL(b.data_length,0)
                 THEN 'DIFERENTE'
            ELSE 'ok' END AS COMPARACION
  FROM (SELECT column_name, data_type, data_length FROM all_tab_columns
         WHERE owner = 'PGS' AND table_name = 'DRC2') a
  FULL OUTER JOIN
       (SELECT column_name, data_type, data_length FROM all_tab_columns
         WHERE owner = 'CBR' AND table_name = 'DRV2') b
    ON a.column_name = b.column_name
 ORDER BY COMPARACION, COLUMNA;

-- Y confirmar que la identidad y las constraints quedaron bien:
SELECT constraint_name, constraint_type, status
  FROM all_constraints
 WHERE owner = 'PGS' AND table_name = 'DRC2'
 ORDER BY constraint_type, constraint_name;

SELECT column_name, identity_column, nullable
  FROM all_tab_columns
 WHERE owner = 'PGS' AND table_name = 'DRC2' AND column_name IN ('ID','RETENCIONV2');
