-- =====================================================================================
-- ⛔ CRD.DSBN — DISTRIBUCION EN BANDAS. La tabla que alimenta la pantalla de auditoria
-- FECHA: 2026-09-02   EQUIPO: CRD / EQUIPO B
--
-- ⚠️ ESTE SCRIPT ESCRIBE. Correrlo ANTES de desplegar el WAR con los endpoints /dsbn.
--
-- QUE LO ORIGINA: PLAN-AUDITORIA-BANDAS.md §5.1, y el pedido del usuario del 2026-09-02:
-- contabilidad necesita revisar por que se mandaron ciertos saldos a ciertas cuentas.
--
-- ⛔ POR QUE ESTA TABLA EXISTE, y por que se escribe donde se escribe:
--
--   Hoy la clasificacion en bandas vive en un Map EN MEMORIA dentro de la contabilizacion
--   (CobroPetroContableServiceImpl:720) y muere cuando el metodo termina. Nadie la persiste.
--   Eso tiene dos consecuencias:
--     1. Contabilidad no puede auditar nada: el dato no existe despues del asiento.
--     2. Si contabilidadActiva() esta en false, NO SE CLASIFICA NADA. El dia que se
--        desconecte contabilidad para vender el sistema aparte, una pantalla alimentada
--        desde la contabilizacion queda VACIA.
--
--   Por eso la fila se escribe DONDE SE APLICA EL PAGO, no donde se arma el asiento.
--   La banda no es un dato contable: es un dato de CARTERA. "esta cuota vence en 45 dias"
--   es verdad exista o no un asiento detras. Contabilidad CONSUME esa clasificacion.
--
-- ⛔ POR ESO ASNTCDGO ES NULLABLE, y no es un descuido: es EL enganche con contabilidad,
--    y el unico. Con CNT conectado se llena; desconectado queda null y no pasa nada mas.
--    LA CUENTA CONTABLE NO SE GUARDA: se resuelve al consultar, uniendo con la
--    configuracion de bandas. Sin CNT la pantalla pierde UNA COLUMNA, no la funcion.
--
--   En cambio DSBNETQT (la etiqueta de la banda) SI se guarda, y la diferencia importa:
--   la etiqueta la deriva CRD desde su propia parametrizacion, y una reconfiguracion
--   posterior de las bandas NO debe reescribir la historia de lo que ya se distribuyo.
--   Una tabla de auditoria guarda lo que valia EN SU MOMENTO.
--
-- ⛔ ORIGEN + IDORIGEN, no "idCarga": la carga Petro es UN origen, no la estructura.
--    Clasifican por bandas tambien el cobro individual, el abono a capital y la
--    precancelacion. Colgar la tabla de la carga cuesta lo mismo hoy y obliga a rehacer
--    tabla y pantalla la primera vez que contabilidad pregunte por un cobro individual.
--
-- ESTANDAR: docs/estandar/ESTANDARES-CREACION-TABLAS-ORACLE.md
-- =====================================================================================

SET PAGESIZE 200
SET LINESIZE 200


-- =====================================================================================
-- CONTROL ANTES — ⛔ PARAR SI ALGO DE ESTO NO DA LO ESPERADO
-- =====================================================================================

-- A.1 — La tabla NO debe existir todavia. Debe salir 0 filas.
--       Si sale 1: PARAR. Alguien ya la creo y este script la duplicaria.
SELECT  t.OWNER, t.TABLE_NAME
FROM    ALL_TABLES t
WHERE   t.OWNER = 'CRD' AND t.TABLE_NAME = 'DSBN';

-- A.2 — Las tablas a las que apunta tienen que existir. Deben salir 5 filas:
--       ENTD, PRST, DTPR, PRDC, BNDP.
SELECT  t.TABLE_NAME
FROM    ALL_TABLES t
WHERE   t.OWNER = 'CRD'
AND     t.TABLE_NAME IN ('ENTD', 'PRST', 'DTPR', 'PRDC', 'BNDP')
ORDER   BY t.TABLE_NAME;


-- =====================================================================================
-- EJECUCION
--
-- PK con IDENTITY (Oracle 12c+), como manda el estandar para tablas nuevas: no hay
-- secuencia que sincronizar despues.
--
-- ⚠️ Las FK son deliberadamente NULLABLE salvo la de entidad. Un renglon de APORTE no
--    tiene prestamo ni cuota; un renglon de INTERES no tiene banda. Eso es AUSENCIA DE
--    DATO LEGITIMA, no un hueco a rellenar con ceros — y la pantalla debe mostrarlo vacio,
--    no como error.
-- =====================================================================================

CREATE TABLE CRD.DSBN (
    DSBNCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- QUE HECHO ORIGINO ESTA DISTRIBUCION
    DSBNORGN VARCHAR2(20)  NOT NULL,   -- CARGA_PETRO | COBRO_INDIVIDUAL | EVENTO_PRESTAMO | PAGO_PENSION
    DSBNIDOR NUMBER        NOT NULL,   -- codigo del hecho en su tabla (CRAR / CBCR / EVPR / PGPC)

    -- QUE SE DISTRIBUYO
    DSBNCNCP VARCHAR2(25)  NOT NULL,   -- CAPITAL | INTERES_ORDINARIO | INTERES_MORA | INTERES_VENCIDO | SEGURO_DESGRAVAMEN | SEGURO_INCENDIO | APORTE
    DSBNVALR NUMBER(18,2)  NOT NULL,   -- valor distribuido

    -- A QUIEN Y SOBRE QUE
    ENTDCDGO NUMBER        NOT NULL,   -- participe
    PRSTCDGO NUMBER,                   -- prestamo  (null en aportes)
    DTPRCDGO NUMBER,                   -- cuota     (null en aportes)
    PRDCCDGO NUMBER,                   -- producto  (null en aportes)
    TPPRCDGO NUMBER,                   -- tipo de prestamo (null en aportes)
    TPAPCDGO NUMBER,                   -- tipo de aporte   (null en prestamos)

    -- LA CLASIFICACION EN BANDA -- solo aplica a CAPITAL; null en el resto
    DSBNTPCR NUMBER,                   -- tipo de cartera: 1 POR_VENCER, 2 VENCIDO (TipoCarteraBanda)
    DSBNDIAS NUMBER,                   -- dias al vencimiento (o de vencido)
    BNDPCDGO NUMBER,                   -- banda resuelta por ClasificadorBandaService
    DSBNETQT VARCHAR2(100),            -- etiqueta derivada AL MOMENTO. Ver cabecera: no se recalcula

    -- FECHAS DEL HECHO
    DSBNFCVN DATE,                     -- vencimiento de la cuota
    DSBNFCAP DATE          NOT NULL,   -- fecha de aplicacion (la que decide la banda)

    -- ⛔ EL UNICO ENGANCHE CON CONTABILIDAD, y es anulable a proposito
    ASNTCDGO NUMBER,                   -- asiento, cuando contabilidad esta conectada

    -- AUDITORIA
    DSBNFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DSBNUSAR VARCHAR2(50),

    -- ESTADO
    DSBNESTD NUMBER DEFAULT 1,

    CONSTRAINT PK_DSBN PRIMARY KEY (DSBNCDGO),
    CONSTRAINT FK_DSBN_ENTD FOREIGN KEY (ENTDCDGO) REFERENCES CRD.ENTD(ENTDCDGO),
    CONSTRAINT FK_DSBN_PRST FOREIGN KEY (PRSTCDGO) REFERENCES CRD.PRST(PRSTCDGO),
    CONSTRAINT FK_DSBN_DTPR FOREIGN KEY (DTPRCDGO) REFERENCES CRD.DTPR(DTPRCDGO),
    CONSTRAINT FK_DSBN_PRDC FOREIGN KEY (PRDCCDGO) REFERENCES CRD.PRDC(PRDCCDGO),
    CONSTRAINT FK_DSBN_BNDP FOREIGN KEY (BNDPCDGO) REFERENCES CRD.BNDP(BNDPCDGO)
);

-- El indice que importa: TODA consulta de la pantalla entra por origen + idOrigen.
CREATE INDEX IDX_DSBN_ORIGEN    ON CRD.DSBN(DSBNORGN, DSBNIDOR);
CREATE INDEX IDX_DSBN_ENTIDAD   ON CRD.DSBN(ENTDCDGO);
CREATE INDEX IDX_DSBN_PRESTAMO  ON CRD.DSBN(PRSTCDGO);
CREATE INDEX IDX_DSBN_CONCEPTO  ON CRD.DSBN(DSBNCNCP);

COMMENT ON TABLE  CRD.DSBN IS 'Distribucion en bandas de cada valor aplicado. Se escribe al APLICAR el pago, no al contabilizar: sobrevive a que contabilidad este desconectada.';
COMMENT ON COLUMN CRD.DSBN.DSBNORGN IS 'Hecho que origino la distribucion. La carga Petro es UN origen, no el unico.';
COMMENT ON COLUMN CRD.DSBN.DSBNCNCP IS 'Concepto: es el agrupador primario de la pantalla, NO la cuenta contable (mora e interes ordinario comparten cuenta).';
COMMENT ON COLUMN CRD.DSBN.DSBNETQT IS 'Etiqueta de la banda al momento de aplicar. No se recalcula: una reconfiguracion posterior no debe reescribir la historia.';
COMMENT ON COLUMN CRD.DSBN.ASNTCDGO IS 'Unico enganche con contabilidad. NULL cuando contabilidad esta desconectada; la pantalla sigue funcionando.';

COMMIT;


-- =====================================================================================
-- CONTROL DESPUES — ⛔ SI ESTO NO DA LO ESPERADO, EL DESPLIEGUE NO VA
-- =====================================================================================

-- D.1 — La tabla y sus 21 columnas. Debe salir 1 fila con NUM_COLUMNAS = 21.
SELECT  COUNT(*) AS NUM_COLUMNAS
FROM    ALL_TAB_COLUMNS c
WHERE   c.OWNER = 'CRD' AND c.TABLE_NAME = 'DSBN';

-- D.2 — Las 5 FK mas la PK. Deben salir 6 filas.
SELECT  cn.CONSTRAINT_NAME, cn.CONSTRAINT_TYPE, cn.STATUS
FROM    ALL_CONSTRAINTS cn
WHERE   cn.OWNER = 'CRD' AND cn.TABLE_NAME = 'DSBN'
AND     cn.CONSTRAINT_TYPE IN ('P', 'R')
ORDER   BY cn.CONSTRAINT_TYPE, cn.CONSTRAINT_NAME;

-- D.3 — Los 4 indices. Deben salir 4 filas.
SELECT  i.INDEX_NAME, i.UNIQUENESS, i.STATUS
FROM    ALL_INDEXES i
WHERE   i.OWNER = 'CRD' AND i.TABLE_NAME = 'DSBN'
AND     i.INDEX_NAME LIKE 'IDX_DSBN%'
ORDER   BY i.INDEX_NAME;

-- D.4 — Que las columnas que DEBEN admitir null lo admitan. Las 11 opcionales deben
--       salir con NULLABLE = 'Y'. Si alguna sale 'N', un renglon de aporte no va a poder
--       grabarse y el proceso va a fallar en produccion, no acá.
SELECT  c.COLUMN_NAME, c.NULLABLE
FROM    ALL_TAB_COLUMNS c
WHERE   c.OWNER = 'CRD' AND c.TABLE_NAME = 'DSBN'
AND     c.COLUMN_NAME IN ('PRSTCDGO','DTPRCDGO','PRDCCDGO','TPPRCDGO','TPAPCDGO',
                          'DSBNTPCR','DSBNDIAS','BNDPCDGO','DSBNETQT','DSBNFCVN','ASNTCDGO')
ORDER   BY c.COLUMN_NAME;


-- =====================================================================================
-- REVERSO — comentado a proposito. Descomentar SOLO si hay que deshacer este script.
-- =====================================================================================
-- DROP TABLE CRD.DSBN CASCADE CONSTRAINTS;
