-- =====================================================================================
-- CRD.CFCR + CRD.ESCR — PARAMETRIZACION DE LA CALIFICACION DE RIESGO (G48)
-- FECHA: 2026-09-02   EQUIPO: CRD / EQUIPO B
--
-- ⚠️ ESTE SCRIPT ESCRIBE (CREATE TABLE + INSERT). Correrlo ANTES de desplegar el WAR.
--
-- QUE LO ORIGINA — decision del usuario, 2026-09-02: «parametrizar la calificacion de
-- riesgo por separado. Es lo correcto.» Plan: PLAN-CALIFICACION-RIESGO-PARAMETRIZABLE.md
--
-- ⛔ NO CONFUNDIR CON LAS BANDAS CONTABLES. Son dos clasificaciones distintas que conviven:
--      BANDA        -> a que CUENTA CONTABLE va el saldo   (1-30, 31-90, 91-180, ...)
--      CALIFICACION -> cuanta PROVISION se constituye       (A1, A2, A3, B1, ... E)
--    Ningun corte coincide. Usar una en lugar de la otra produce un reporte REGULATORIO
--    incorrecto, que es peor que un asiento descuadrado.
--
-- ⛔ ESTE SCRIPT CARGA LAS DOS ESCALAS EXACTAMENTE COMO ESTAN CABLEADAS HOY en
--    GeneracionG48ServiceImpl.calcularCalificacion:472 y calcularProvision:454.
--    NO es una oportunidad para corregirlas: el objetivo de esta etapa es que el G48 de el
--    MISMO resultado leyendo de la base. Cualquier diferencia es un error del script.
--
-- LA VIGENCIA NO ES DECORACION: las escalas regulatorias cambian, y un G48 de un periodo
-- anterior debe recalcularse con la escala que regia ENTONCES. Misma razon por la que CBPR
-- tiene CBPRFCIN/CBPRFCFN.
--
-- ESTANDAR: docs/estandar/ESTANDARES-CREACION-TABLAS-ORACLE.md
-- =====================================================================================

SET PAGESIZE 300
SET LINESIZE 200


-- =====================================================================================
-- CONTROL ANTES
-- =====================================================================================

-- A.1 — Las tablas NO deben existir. Debe salir 0 filas.
SELECT t.TABLE_NAME FROM ALL_TABLES t
WHERE  t.OWNER = 'CRD' AND t.TABLE_NAME IN ('CFCR', 'ESCR');

-- A.2 — ⛔ Los productos que HOY se califican como hipotecarios (literal 7, 8, 21 en el
--       codigo). Deben salir 3 filas. Si alguno no existe o cambio de nombre, PARAR:
--       el literal del codigo ya estaba desactualizado y hay que revisarlo con el usuario
--       antes de congelarlo en la parametrizacion.
SELECT p.PRDCCDGO, p.PRDCNMBR, p.PRDCCDEX
FROM   CRD.PRDC p
WHERE  p.PRDCCDGO IN (7, 8, 21)
ORDER  BY p.PRDCCDGO;

-- A.3 — ⛔ TODOS los productos de credito. Los que NO esten en (7,8,21) van a quedar con
--       escala GENERAL. Revisar la lista con el usuario ANTES de correr los INSERT:
--       si hay un producto hipotecario que no esta en el literal, HOY se esta calificando
--       mal y este script congelaria el error.
SELECT p.PRDCCDGO, p.PRDCNMBR,
       CASE WHEN p.PRDCCDGO IN (7,8,21) THEN 'HIPOTECARIA' ELSE 'GENERAL' END AS ESCALA_QUE_LE_TOCA
FROM   CRD.PRDC p
ORDER  BY ESCALA_QUE_LE_TOCA, p.PRDCCDGO;


-- =====================================================================================
-- EJECUCION — LAS TABLAS
-- =====================================================================================

CREATE TABLE CRD.CFCR (
    CFCRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PRDCCDGO NUMBER        NOT NULL,   -- producto al que aplica
    PJRQCDGO NUMBER,                   -- empresa (jerarquia), como en CBPR
    CFCRNMBR VARCHAR2(100),            -- nombre de la escala, p.ej. 'HIPOTECARIA' / 'GENERAL'
    CFCRFCIN DATE          NOT NULL,   -- vigencia desde
    CFCRFCFN DATE,                     -- vigencia hasta (null = abierta)
    CFCRFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CFCRUSAR VARCHAR2(50),
    CFCRESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_CFCR PRIMARY KEY (CFCRCDGO),
    CONSTRAINT FK_CFCR_PRDC FOREIGN KEY (PRDCCDGO) REFERENCES CRD.PRDC(PRDCCDGO)
);

CREATE TABLE CRD.ESCR (
    ESCRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CFCRCDGO NUMBER        NOT NULL,   -- configuracion a la que pertenece
    ESCRCLFC VARCHAR2(5)   NOT NULL,   -- A1, A2, A3, B1, B2, C1, C2, D, E
    ESCRDSDE NUMBER        NOT NULL,   -- dia desde (inclusive)
    ESCRHSTA NUMBER,                   -- dia hasta (inclusive). NULL = sin tope (la ultima)
    ESCRPRVS NUMBER(18,6)  NOT NULL,   -- porcentaje de provision, en tanto por uno (0.0099 = 0,99%)
    ESCRORDN NUMBER,                   -- orden de evaluacion
    ESCRFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESCRUSAR VARCHAR2(50),
    ESCRESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_ESCR PRIMARY KEY (ESCRCDGO),
    CONSTRAINT FK_ESCR_CFCR FOREIGN KEY (CFCRCDGO) REFERENCES CRD.CFCR(CFCRCDGO)
);

CREATE INDEX IDX_CFCR_PRODUCTO ON CRD.CFCR(PRDCCDGO);
CREATE INDEX IDX_ESCR_CONFIG   ON CRD.ESCR(CFCRCDGO);

COMMENT ON TABLE  CRD.CFCR IS 'Configuracion de calificacion de riesgo por producto y vigencia. DISTINTA de las bandas contables (CBPR/BNDP): la banda dice a que cuenta va el saldo, la calificacion dice cuanta provision se constituye.';
COMMENT ON TABLE  CRD.ESCR IS 'Escala de calificacion de riesgo: rango de dias y porcentaje de provision por calificacion (A1..E).';
COMMENT ON COLUMN CRD.ESCR.ESCRPRVS IS 'Porcentaje de provision en TANTO POR UNO (0.0099 = 0,99%), igual que el codigo cableado que reemplaza.';
COMMENT ON COLUMN CRD.ESCR.ESCRHSTA IS 'Dia hasta inclusive. NULL en la ultima calificacion de la escala (sin tope superior).';

COMMIT;


-- =====================================================================================
-- EJECUCION — LA CARGA INICIAL, IDENTICA A LO CABLEADO
--
-- Una configuracion por PRODUCTO. Los productos 7, 8 y 21 llevan la escala HIPOTECARIA;
-- todos los demas, la GENERAL. Es exactamente lo que hace hoy el literal del codigo.
--
-- Vigencia desde 1900-01-01: la escala cableada rigio para TODO el historico, asi que un
-- G48 de cualquier periodo anterior tiene que poder recalcularse igual.
-- =====================================================================================

-- Cabeceras: una por producto
INSERT INTO CRD.CFCR (PRDCCDGO, PJRQCDGO, CFCRNMBR, CFCRFCIN, CFCRFCFN, CFCRUSAR, CFCRESTD)
SELECT p.PRDCCDGO, NULL,
       CASE WHEN p.PRDCCDGO IN (7,8,21) THEN 'HIPOTECARIA' ELSE 'GENERAL' END,
       DATE '1900-01-01', NULL, 'sql/177', 1
FROM   CRD.PRDC p;

COMMIT;

-- Detalle HIPOTECARIA (productos 7, 8, 21)
INSERT INTO CRD.ESCR (CFCRCDGO, ESCRCLFC, ESCRDSDE, ESCRHSTA, ESCRPRVS, ESCRORDN, ESCRUSAR, ESCRESTD)
SELECT c.CFCRCDGO, e.CLFC, e.DSDE, e.HSTA, e.PRVS, e.ORDN, 'sql/177', 1
FROM   CRD.CFCR c
CROSS  JOIN (
    SELECT 'A1' CLFC,   0 DSDE,    0 HSTA, 0.0099 PRVS, 1 ORDN FROM DUAL UNION ALL
    SELECT 'A2',        1,        30,      0.0199,      2      FROM DUAL UNION ALL
    SELECT 'A3',       31,        60,      0.02,        3      FROM DUAL UNION ALL
    SELECT 'B1',       61,       120,      0.05,        4      FROM DUAL UNION ALL
    SELECT 'B2',      121,       180,      0.10,        5      FROM DUAL UNION ALL
    SELECT 'C1',      181,       210,      0.20,        6      FROM DUAL UNION ALL
    SELECT 'C2',      211,       270,      0.40,        7      FROM DUAL UNION ALL
    SELECT 'D',       271,       450,      0.60,        8      FROM DUAL UNION ALL
    SELECT 'E',       451,      NULL,      1.00,        9      FROM DUAL
) e
WHERE  c.CFCRNMBR = 'HIPOTECARIA';

-- Detalle GENERAL (todos los demas productos)
INSERT INTO CRD.ESCR (CFCRCDGO, ESCRCLFC, ESCRDSDE, ESCRHSTA, ESCRPRVS, ESCRORDN, ESCRUSAR, ESCRESTD)
SELECT c.CFCRCDGO, e.CLFC, e.DSDE, e.HSTA, e.PRVS, e.ORDN, 'sql/177', 1
FROM   CRD.CFCR c
CROSS  JOIN (
    SELECT 'A1' CLFC,   0 DSDE,    0 HSTA, 0.0099 PRVS, 1 ORDN FROM DUAL UNION ALL
    SELECT 'A2',        1,        15,      0.0199,      2      FROM DUAL UNION ALL
    SELECT 'A3',       16,        30,      0.02,        3      FROM DUAL UNION ALL
    SELECT 'B1',       31,        60,      0.05,        4      FROM DUAL UNION ALL
    SELECT 'B2',       61,        90,      0.10,        5      FROM DUAL UNION ALL
    SELECT 'C1',       91,       120,      0.20,        6      FROM DUAL UNION ALL
    SELECT 'C2',      121,       180,      0.40,        7      FROM DUAL UNION ALL
    SELECT 'D',       181,       270,      0.60,        8      FROM DUAL UNION ALL
    SELECT 'E',       271,      NULL,      1.00,        9      FROM DUAL
) e
WHERE  c.CFCRNMBR = 'GENERAL';

COMMIT;


-- =====================================================================================
-- CONTROL DESPUES — ⛔ SI ESTO NO DA LO ESPERADO, EL DESPLIEGUE NO VA
-- =====================================================================================

-- D.1 — Una configuracion por producto, y 9 calificaciones cada una.
--       CALIFICACIONES debe dar 9 en TODAS las filas. Si alguna da menos, un INSERT fallo.
SELECT c.CFCRCDGO, c.PRDCCDGO, c.CFCRNMBR, COUNT(e.ESCRCDGO) AS CALIFICACIONES
FROM   CRD.CFCR c
LEFT   JOIN CRD.ESCR e ON e.CFCRCDGO = c.CFCRCDGO
GROUP  BY c.CFCRCDGO, c.PRDCCDGO, c.CFCRNMBR
ORDER  BY c.CFCRNMBR, c.PRDCCDGO;

-- D.2 — Las dos escalas, una vez cada una, para comparar VALOR POR VALOR contra la tabla
--       del §2 del plan. Es la verificacion que importa: si un rango o un porcentaje
--       difiere de lo cableado, el G48 va a cambiar de resultado y eso es un ERROR.
SELECT DISTINCT c.CFCRNMBR AS ESCALA, e.ESCRORDN AS ORDEN, e.ESCRCLFC AS CALIFICACION,
       e.ESCRDSDE AS DIA_DESDE, e.ESCRHSTA AS DIA_HASTA, e.ESCRPRVS AS PROVISION
FROM   CRD.ESCR e
JOIN   CRD.CFCR c ON c.CFCRCDGO = e.CFCRCDGO
ORDER  BY ESCALA, ORDEN;

-- D.3 — ⛔ Huecos y solapes. Debe salir 0 filas.
--       Cada calificacion tiene que empezar justo donde termino la anterior. Un hueco deja
--       creditos sin calificar; un solape los califica dos veces.
SELECT c.CFCRNMBR AS ESCALA, e.ESCRCLFC AS CALIFICACION, e.ESCRDSDE, e.ESCRHSTA,
       LAG(e.ESCRHSTA) OVER (PARTITION BY e.CFCRCDGO ORDER BY e.ESCRORDN) AS HASTA_ANTERIOR,
       'HUECO O SOLAPE' AS PROBLEMA
FROM   CRD.ESCR e
JOIN   CRD.CFCR c ON c.CFCRCDGO = e.CFCRCDGO
WHERE  e.ESCRDSDE <> NVL(LAG(e.ESCRHSTA) OVER (PARTITION BY e.CFCRCDGO ORDER BY e.ESCRORDN), -1) + 1;

-- D.4 — Productos SIN configuracion. Debe salir 0 filas.
--       Cada fila es un producto cuyo G48 va a fallar (o a calificarse mal) tras el cambio.
SELECT p.PRDCCDGO, p.PRDCNMBR, 'SIN CONFIGURACION DE CALIFICACION' AS PROBLEMA
FROM   CRD.PRDC p
WHERE  NOT EXISTS (SELECT 1 FROM CRD.CFCR c WHERE c.PRDCCDGO = p.PRDCCDGO);


-- =====================================================================================
-- REVERSO — comentado a proposito. Descomentar SOLO si hay que deshacer este script.
-- El detalle primero: el orden inverso choca con la FK.
-- =====================================================================================
-- DROP TABLE CRD.ESCR CASCADE CONSTRAINTS;
-- DROP TABLE CRD.CFCR CASCADE CONSTRAINTS;
