-- =====================================================================================
-- DDL — CRD.CRJB, cabecera de la corrida mensual de jubilados
-- FECHA: 2026-09-07   EQUIPO: omen-saa-1 (omen1)   SCRIPT: 212 (rango 200-249)
--
-- CONTRATO: docs/logica-negocio/crd/API-DOS-PROCESOS-MENSUALES-JUBILADOS.md §3
--
-- ESCRIBE: crea una tabla, su PK, su indice unico y sus comentarios. Reverso al final,
-- comentado.
--
-- PARA QUE: hoy no existe ninguna cabecera de corrida. CRD.PGPC es una fila por jubilado y
-- por periodo, asi que no hay donde decir "el seguro de agosto ya se corrio, las pensiones
-- todavia no". Sin eso no se puede bloquear la corrida de pensiones cuando falta el seguro
-- (decision D2 del usuario) ni dar seguimiento a los dos procesos.
--
-- ⛔ ESTE SCRIPT VA **ANTES** DEL WAR. NO ES REORDENABLE.
--    Hibernate incluye toda columna @Column en el SELECT que genera. Si la entidad CorridaJubilados
--    sube sin la tabla, revienta cualquier lectura que la toque. Precedente: el incidente de
--    CBCRASRP del 2026-08-31.
--
-- ⚠️ SECUENCIA: el PK es GENERATED BY DEFAULT AS IDENTITY, igual que CRD.APRT y CRD.PGAP. La
--    base genera el codigo y NO hay ninguna secuencia SQ_* que crear ni sincronizar. Si en el
--    futuro alguien inserta filas con PK explicita, ahi si habria que revisar el IDENTITY.
--
-- ⚠️ NOMBRE DE TABLA: `CRJB` reservado el 2026-09-07 por omen-saa-1 en el §3 del
--    REGISTRO-RESERVAS-EQUIPOS.md. Verificado libre contra las mas de 400 tablas del modelo
--    y contra la lista de reservados antes de escribir esto.
--
-- COMO DEVOLVER EL RESULTADO: pegar la salida de los bloques 0 y 2.
-- =====================================================================================

SET PAGESIZE 200
SET LINESIZE 240
SET FEEDBACK ON


-- =====================================================================================
-- BLOQUE 0 — CONTROL ANTES
-- Esperado: 0 filas. Si devuelve algo, la tabla YA existe y este script no se vuelve a correr.
-- =====================================================================================

SELECT table_name, num_rows
  FROM all_tables
 WHERE owner = 'CRD' AND table_name = 'CRJB';


-- =====================================================================================
-- BLOQUE 1 — EL DDL
--
-- Nullable a proposito TODO lo que describe un proceso que todavia no corrio: una corrida
-- recien nacida tiene los dos estados en 0 y el resto en NULL. Un NOT NULL con DEFAULT 0
-- en los importes mentiria — diria "se pago cero" donde la verdad es "todavia no se pago".
-- =====================================================================================

CREATE TABLE CRD.CRJB (
    CRJBCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PJRQCDGO NUMBER          NOT NULL,
    CRJBANNO NUMBER          NOT NULL,
    CRJBMESS NUMBER          NOT NULL,

    CRJBESSG NUMBER DEFAULT 0 NOT NULL,
    CRJBFCSG TIMESTAMP,
    CRJBUSSG VARCHAR2(50),
    CRJBVLSG NUMBER(18,2),
    CRJBIDSG NUMBER,
    CRJBCTSG NUMBER,

    CRJBESPN NUMBER DEFAULT 0 NOT NULL,
    CRJBFCPN TIMESTAMP,
    CRJBUSPN VARCHAR2(50),
    CRJBVLPN NUMBER(18,2),
    CRJBVLCR NUMBER(18,2),
    CRJBCTPN NUMBER,

    CONSTRAINT PK_CRJB PRIMARY KEY (CRJBCDGO)
);

-- Un periodo, una corrida. Esto hace la idempotencia por CONSTRUCCION y no por convencion:
-- aunque dos usuarios disparen el proceso a la vez, la base impide la segunda cabecera.
CREATE UNIQUE INDEX CRD.UQ_CRJB_PERIODO ON CRD.CRJB (PJRQCDGO, CRJBANNO, CRJBMESS);

COMMENT ON TABLE  CRD.CRJB          IS 'Cabecera de la corrida mensual de jubilados: estado de los dos procesos del mes (seguro medico al inicio, pensiones al final)';
COMMENT ON COLUMN CRD.CRJB.PJRQCDGO IS 'Empresa (jerarquia) de la corrida';
COMMENT ON COLUMN CRD.CRJB.CRJBANNO IS 'Anio del periodo';
COMMENT ON COLUMN CRD.CRJB.CRJBMESS IS 'Mes del periodo';
COMMENT ON COLUMN CRD.CRJB.CRJBESSG IS 'Estado del proceso de seguro medico: 0 pendiente, 1 generado';
COMMENT ON COLUMN CRD.CRJB.CRJBFCSG IS 'Fecha y hora en que se genero el seguro medico';
COMMENT ON COLUMN CRD.CRJB.CRJBUSSG IS 'Usuario que genero el seguro medico';
COMMENT ON COLUMN CRD.CRJB.CRJBVLSG IS 'Total pagado al proveedor del seguro medico en el periodo';
COMMENT ON COLUMN CRD.CRJB.CRJBIDSG IS 'Id de la orden de pago generada al proveedor del seguro';
COMMENT ON COLUMN CRD.CRJB.CRJBCTSG IS 'Cuantos jubilados entraron en el proceso de seguro';
COMMENT ON COLUMN CRD.CRJB.CRJBESPN IS 'Estado del proceso de pensiones: 0 pendiente, 1 generado';
COMMENT ON COLUMN CRD.CRJB.CRJBFCPN IS 'Fecha y hora en que se generaron las pensiones';
COMMENT ON COLUMN CRD.CRJB.CRJBUSPN IS 'Usuario que genero las pensiones';
COMMENT ON COLUMN CRD.CRJB.CRJBVLPN IS 'Total de ordenes de pension generadas en el periodo';
COMMENT ON COLUMN CRD.CRJB.CRJBVLCR IS 'Total cruzado a prestamos en el periodo';
COMMENT ON COLUMN CRD.CRJB.CRJBCTPN IS 'Cuantos jubilados entraron en el proceso de pensiones';


-- =====================================================================================
-- BLOQUE 2 — CONTROL DESPUES
-- Esperado 2.1: 16 columnas con los tipos declarados arriba.
-- Esperado 2.2: PK_CRJB y UQ_CRJB_PERIODO, las dos con OWNER = 'CRD'.
--   ⚠️ El indice se crea con prefijo CRD. a proposito: un CREATE INDEX sin prefijo se crea en
--      el schema de la sesion y la tabla queda SIN indice, sin ningun error. Ya paso en este
--      proyecto (script 100, control 2.4).
-- Esperado 2.3: 0 filas, la tabla nace vacia y se puede leer.
-- =====================================================================================

-- 2.1 Las columnas
SELECT column_name, data_type, data_length, data_precision, data_scale, nullable, data_default
  FROM all_tab_columns
 WHERE owner = 'CRD' AND table_name = 'CRJB'
 ORDER BY column_id;

-- 2.2 PK e indice unico, y en que schema quedaron
SELECT index_name, uniqueness, table_owner, status
  FROM all_indexes
 WHERE owner = 'CRD' AND table_name = 'CRJB'
 ORDER BY index_name;

-- 2.3 Se puede leer (esto es lo que hara Hibernate)
SELECT COUNT(*) AS FILAS FROM CRD.CRJB;


-- =====================================================================================
-- BLOQUE 3 — CONFIRMAR
-- El DDL de Oracle hace COMMIT implicito: ya quedo confirmado al ejecutarse. No hay COMMIT
-- que descomentar; se deja dicho para que nadie lo busque.
-- =====================================================================================


-- =====================================================================================
-- BLOQUE 4 — REVERSO (comentado)
-- ⛔ Solo si el WAR con la entidad NO se subio todavia. Si ya esta arriba, borrar la tabla
--    rompe toda lectura que la toque.
-- ⚠️ DROP destruye el historial de corridas. No hay vuelta atras.
-- =====================================================================================

-- DROP TABLE CRD.CRJB PURGE;
