-- =====================================================================================
-- DDL — SERVICIOS DE PAGO DE PRÉSTAMOS (módulo CRD)
-- Implementa la sección 4 de docs/logica-negocio/crd/ESPECIFICACION-SERVICIOS-PAGO-PRESTAMOS.md
-- FECHA: 2026-08-13
-- FASE: 0 (Cimientos)
--
-- Contenido:
--   1. CRD.EVPR  — EventoPrestamo      (cabecera de TODA operación de pago)
--   2. CRD.HDTP  — HistDetallePrestamo (cuotas historizadas; espejo 1:1 de CRD.DTPR)
--   3. ALTER CRD.PGPR  (evento + asiento + anulación)
--   4. ALTER CRD.PGAP  (vínculo al pago de préstamo)
--   5. Índices sobre CRD.APRT (saldo agregado y FIFO)
--   6. Grants
--
-- ⚠️ EJECUCIÓN MANUAL. Correr como el owner del esquema CRD.
-- ⚠️ Los índices de CRD.APRT (sección 5) crearlos en ventana de bajo uso: ~980.000 filas.
-- =====================================================================================


-- =====================================================================================
-- 1. TABLA: CRD.EVPR (EventoPrestamo)
-- DESCRIPCIÓN: Cabecera de toda operación de pago sobre un préstamo. Cada llamada de
--              negocio (pago manual, pago con aportes, abono a capital, precancelación)
--              crea UN EventoPrestamo; los PagoPrestamo, movimientos de aportes y cuotas
--              historizadas de esa llamada cuelgan del evento. Es el punto de agrupación
--              para el reverso y para el asiento contable.
-- =====================================================================================

CREATE TABLE CRD.EVPR (
    -- PK Autoincrementable (Oracle 12c+)
    EVPRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- FK al préstamo afectado
    PRSTCDGO NUMBER NOT NULL,

    -- DATOS DE LA OPERACIÓN
    EVPRTPOO VARCHAR2(30) NOT NULL,            -- PAGO_MANUAL | PAGO_APORTES | ABONO_CAPITAL | PRECANCELACION
    EVPRVLRR NUMBER(18,2) NOT NULL,            -- valor total de la operación
    EVPRMDLD NUMBER,                           -- abono: 1=reduce plazo, 2=reduce cuota. NULL en otros tipos
    EVPRPLZA NUMBER,                           -- plazo anterior (abono modalidad 1)
    EVPRPLZN NUMBER,                           -- plazo nuevo
    EVPRCTAA NUMBER(18,2),                     -- valor cuota anterior (abono modalidad 2)
    EVPRCTNN NUMBER(18,2),                     -- valor cuota nuevo
    EVPRFCHA DATE NOT NULL,                    -- fecha de negocio de la operación
    EVPRNMAS NUMBER,                           -- número de asiento contable (hook futuro; NULL por ahora)
    EVPROBSR VARCHAR2(2000),                   -- observación del usuario

    -- AUDITORÍA
    EVPRUSAR VARCHAR2(50) NOT NULL,            -- usuario que ejecutó
    EVPRFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- ESTADO Y ANULACIÓN
    EVPRESTD NUMBER DEFAULT 1 NOT NULL,        -- 1 = vigente, 0 = anulado
    EVPRUSAN VARCHAR2(50),                     -- usuario anulación
    EVPRFCAN TIMESTAMP,                        -- fecha anulación
    EVPRMTAN VARCHAR2(500),                    -- motivo anulación

    -- CONSTRAINTS
    CONSTRAINT PK_EVPR PRIMARY KEY (EVPRCDGO),
    CONSTRAINT FK_EVPR_PRST FOREIGN KEY (PRSTCDGO) REFERENCES CRD.PRST(PRSTCDGO),
    CONSTRAINT CK_EVPR_TIPO CHECK (EVPRTPOO IN ('PAGO_MANUAL','PAGO_APORTES','ABONO_CAPITAL','PRECANCELACION'))
);

CREATE INDEX IDX_EVPR_PRST ON CRD.EVPR(PRSTCDGO);

COMMENT ON TABLE  CRD.EVPR           IS 'EventoPrestamo: cabecera de toda operación de pago de préstamo (pago manual, pago con aportes, abono a capital, precancelación). Agrupa los PGPR, movimientos de aporte y cuotas historizadas de la operación.';
COMMENT ON COLUMN CRD.EVPR.EVPRCDGO  IS 'Código del evento (PK)';
COMMENT ON COLUMN CRD.EVPR.PRSTCDGO  IS 'FK CRD.PRST - Préstamo afectado por la operación';
COMMENT ON COLUMN CRD.EVPR.EVPRTPOO  IS 'Tipo de operación: PAGO_MANUAL, PAGO_APORTES, ABONO_CAPITAL o PRECANCELACION';
COMMENT ON COLUMN CRD.EVPR.EVPRVLRR  IS 'Valor total de la operación';
COMMENT ON COLUMN CRD.EVPR.EVPRMDLD  IS 'Modalidad del abono a capital: 1 = mantiene cuota y reduce plazo, 2 = mantiene plazo y reduce cuota. NULL en los demás tipos';
COMMENT ON COLUMN CRD.EVPR.EVPRPLZA  IS 'Plazo del préstamo ANTES de la operación (abono a capital)';
COMMENT ON COLUMN CRD.EVPR.EVPRPLZN  IS 'Plazo del préstamo DESPUÉS de la operación (abono a capital)';
COMMENT ON COLUMN CRD.EVPR.EVPRCTAA  IS 'Valor de cuota ANTES de la operación (abono a capital)';
COMMENT ON COLUMN CRD.EVPR.EVPRCTNN  IS 'Valor de cuota DESPUÉS de la operación (abono a capital)';
COMMENT ON COLUMN CRD.EVPR.EVPRFCHA  IS 'Fecha de negocio de la operación (la que informa el usuario, no la de registro)';
COMMENT ON COLUMN CRD.EVPR.EVPRNMAS  IS 'Número de asiento contable generado por el hook de contabilidad. NULL mientras la contabilidad de préstamos no esté activa';
COMMENT ON COLUMN CRD.EVPR.EVPROBSR  IS 'Observación registrada por el usuario';
COMMENT ON COLUMN CRD.EVPR.EVPRUSAR  IS 'Usuario que ejecutó la operación';
COMMENT ON COLUMN CRD.EVPR.EVPRFCRG  IS 'Fecha/hora de registro del evento';
COMMENT ON COLUMN CRD.EVPR.EVPRESTD  IS 'Estado del evento: 1 = vigente, 0 = anulado';
COMMENT ON COLUMN CRD.EVPR.EVPRUSAN  IS 'Usuario que anuló el evento';
COMMENT ON COLUMN CRD.EVPR.EVPRFCAN  IS 'Fecha/hora de anulación del evento';
COMMENT ON COLUMN CRD.EVPR.EVPRMTAN  IS 'Motivo de la anulación';


-- =====================================================================================
-- 2. TABLA: CRD.HDTP (HistDetallePrestamo)
-- DESCRIPCIÓN: Cuotas historizadas. Cuando un abono a capital (o una precancelación con
--              re-amortización) reemplaza cuotas de CRD.DTPR, esas cuotas se copian aquí
--              y se BORRAN de DTPR en la misma transacción. Prohibido dejarlas en DTPR con
--              un estado nuevo: rompería contarCuotasPendientesByPrestamo y los reportes.
--              Mismo patrón que MayorizacionServiceImpl.respaldaAsientosMayorizacion / CNT.ASNH.
--
-- ESPEJO: las columnas DTPR* de abajo son un espejo 1:1 (mismo nombre y tipo) de CRD.DTPR.
--         Verificado contra com.saa.model.crd.DetallePrestamo el 2026-08-13:
--         37 columnas de datos + PRSTCDGO. No hay ningún campo de la entidad fuera del espejo.
-- =====================================================================================

CREATE TABLE CRD.HDTP (
    -- PK Autoincrementable (Oracle 12c+)
    HDTPCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- IDENTIFICACIÓN DEL ORIGEN
    DTPRCDGO NUMBER NOT NULL,        -- código que tenía la cuota en DTPR (sin FK: la fila viva se borra)
    EVPRCDGO NUMBER NOT NULL,        -- FK CRD.EVPR: evento que la historizó
    HDTPMTVO VARCHAR2(30) NOT NULL,  -- ABONO_CAPITAL | PRECANCELACION | REVERSO

    -- AUDITORÍA
    HDTPFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    HDTPUSAR VARCHAR2(50) NOT NULL,

    -- ================= ESPEJO 1:1 DE CRD.DTPR =================
    PRSTCDGO NUMBER NOT NULL,
    DTPRNMCT NUMBER,
    DTPRFCVN DATE,
    DTPRCPTL NUMBER(18,2),
    DTPRINTR NUMBER(18,2),
    DTPRMRAA NUMBER(18,2),
    DTPRINVN NUMBER(18,2),
    DTPRSLCP NUMBER(18,2),
    DTPRSLIN NUMBER(18,2),
    DTPRSLMR NUMBER(18,2),
    DTPRSLIV NUMBER(18,2),
    DTPRFCPG DATE,
    DTPRABNO NUMBER(18,2),
    DTPRCPPG NUMBER(18,2),
    DTPRINPG NUMBER(18,2),
    DTPRDSGR NUMBER(18,2),
    DTPRCTAA NUMBER(18,2),
    DTPRSLDO NUMBER(18,2),
    DTPRSLOT NUMBER(18,2),
    DTPRDSFR NUMBER(18,2),
    DTPRDSDF NUMBER(18,2),
    DTPRDSOR NUMBER(18,2),
    DTPRVLDF NUMBER(18,2),
    DTPRTTLL NUMBER(18,2),
    DTPRMRPG NUMBER(18,2),
    DTPRDSPG NUMBER(18,2),
    DTPRINVP NUMBER(18,2),
    DTPRMRCL NUMBER(18,2),
    DTPRDSMR NUMBER,
    DTPRESTD NUMBER,
    DTPRFCRG DATE,
    DTPRUSRG VARCHAR2(200),
    DTPRIDST NUMBER,
    DTPRCDEX NUMBER,
    DTPROTSG NUMBER(18,2),
    DTPRTTCS NUMBER(18,2),
    DTPRVLSI NUMBER(18,2),
    DTPRSICP NUMBER(18,2),

    -- CONSTRAINTS
    CONSTRAINT PK_HDTP PRIMARY KEY (HDTPCDGO),
    CONSTRAINT FK_HDTP_EVPR FOREIGN KEY (EVPRCDGO) REFERENCES CRD.EVPR(EVPRCDGO)
);

CREATE INDEX IDX_HDTP_PRST ON CRD.HDTP(PRSTCDGO);
CREATE INDEX IDX_HDTP_EVPR ON CRD.HDTP(EVPRCDGO);

COMMENT ON TABLE  CRD.HDTP           IS 'HistDetallePrestamo: cuotas de CRD.DTPR historizadas al re-amortizar (abono a capital / precancelación). Espejo 1:1 de DTPR con los mismos nombres de columna, más el evento que las historizó.';
COMMENT ON COLUMN CRD.HDTP.HDTPCDGO  IS 'Código del registro histórico (PK)';
COMMENT ON COLUMN CRD.HDTP.DTPRCDGO  IS 'Código que tenía la cuota en CRD.DTPR. Sin FK: la fila viva se borra al historizar';
COMMENT ON COLUMN CRD.HDTP.EVPRCDGO  IS 'FK CRD.EVPR - Evento que historizó la cuota';
COMMENT ON COLUMN CRD.HDTP.HDTPMTVO  IS 'Motivo de la historización: ABONO_CAPITAL, PRECANCELACION o REVERSO (redundante con EVPR.EVPRTPOO, útil en consultas)';
COMMENT ON COLUMN CRD.HDTP.HDTPFCRG  IS 'Fecha/hora en que se historizó la cuota';
COMMENT ON COLUMN CRD.HDTP.HDTPUSAR  IS 'Usuario que ejecutó la operación que historizó la cuota';
COMMENT ON COLUMN CRD.HDTP.PRSTCDGO  IS 'Espejo DTPR - Préstamo al que pertenecía la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRNMCT  IS 'Espejo DTPR - Número de cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRFCVN  IS 'Espejo DTPR - Fecha de vencimiento';
COMMENT ON COLUMN CRD.HDTP.DTPRCPTL  IS 'Espejo DTPR - Capital de la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRINTR  IS 'Espejo DTPR - Interés de la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRMRAA  IS 'Espejo DTPR - Mora';
COMMENT ON COLUMN CRD.HDTP.DTPRINVN  IS 'Espejo DTPR - Interés vencido';
COMMENT ON COLUMN CRD.HDTP.DTPRSLCP  IS 'Espejo DTPR - Saldo de capital';
COMMENT ON COLUMN CRD.HDTP.DTPRSLIN  IS 'Espejo DTPR - Saldo de interés';
COMMENT ON COLUMN CRD.HDTP.DTPRSLMR  IS 'Espejo DTPR - Saldo de mora';
COMMENT ON COLUMN CRD.HDTP.DTPRSLIV  IS 'Espejo DTPR - Saldo de interés vencido';
COMMENT ON COLUMN CRD.HDTP.DTPRFCPG  IS 'Espejo DTPR - Fecha en que se pagó la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRABNO  IS 'Espejo DTPR - Abono';
COMMENT ON COLUMN CRD.HDTP.DTPRCPPG  IS 'Espejo DTPR - Capital pagado';
COMMENT ON COLUMN CRD.HDTP.DTPRINPG  IS 'Espejo DTPR - Interés pagado';
COMMENT ON COLUMN CRD.HDTP.DTPRDSGR  IS 'Espejo DTPR - Desgravamen';
COMMENT ON COLUMN CRD.HDTP.DTPRCTAA  IS 'Espejo DTPR - Valor de la cuota (capital + interés)';
COMMENT ON COLUMN CRD.HDTP.DTPRSLDO  IS 'Espejo DTPR - Saldo global de la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRSLOT  IS 'Espejo DTPR - Saldo otros (pago extra / capital precancelado)';
COMMENT ON COLUMN CRD.HDTP.DTPRDSFR  IS 'Espejo DTPR - Desgravamen firmado';
COMMENT ON COLUMN CRD.HDTP.DTPRDSDF  IS 'Espejo DTPR - Desgravamen diferido';
COMMENT ON COLUMN CRD.HDTP.DTPRDSOR  IS 'Espejo DTPR - Desgravamen original';
COMMENT ON COLUMN CRD.HDTP.DTPRVLDF  IS 'Espejo DTPR - Valor diferido';
COMMENT ON COLUMN CRD.HDTP.DTPRTTLL  IS 'Espejo DTPR - Total de la cuota (cuota + desgravamen + seguro de incendio)';
COMMENT ON COLUMN CRD.HDTP.DTPRMRPG  IS 'Espejo DTPR - Mora pagada';
COMMENT ON COLUMN CRD.HDTP.DTPRDSPG  IS 'Espejo DTPR - Desgravamen pagado';
COMMENT ON COLUMN CRD.HDTP.DTPRINVP  IS 'Espejo DTPR - Interés vencido pagado';
COMMENT ON COLUMN CRD.HDTP.DTPRMRCL  IS 'Espejo DTPR - Mora calculada';
COMMENT ON COLUMN CRD.HDTP.DTPRDSMR  IS 'Espejo DTPR - Días de mora';
COMMENT ON COLUMN CRD.HDTP.DTPRESTD  IS 'Espejo DTPR - Estado de la cuota (rubro EstadoCuotaPrestamo)';
COMMENT ON COLUMN CRD.HDTP.DTPRFCRG  IS 'Espejo DTPR - Fecha de registro de la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRUSRG  IS 'Espejo DTPR - Usuario que registró la cuota';
COMMENT ON COLUMN CRD.HDTP.DTPRIDST  IS 'Espejo DTPR - Id de estado (espejo de DTPRESTD)';
COMMENT ON COLUMN CRD.HDTP.DTPRCDEX  IS 'Espejo DTPR - Código externo (p.ej. id de la carga Petro que la afectó)';
COMMENT ON COLUMN CRD.HDTP.DTPROTSG  IS 'Espejo DTPR - Otros seguros';
COMMENT ON COLUMN CRD.HDTP.DTPRTTCS  IS 'Espejo DTPR - Total con seguro';
COMMENT ON COLUMN CRD.HDTP.DTPRVLSI  IS 'Espejo DTPR - Valor del seguro de incendio';
COMMENT ON COLUMN CRD.HDTP.DTPRSICP  IS 'Espejo DTPR - Saldo inicial de capital (capital pendiente ANTES de la cuota)';


-- =====================================================================================
-- 3. ALTER CRD.PGPR (PagoPrestamo): evento + asiento + anulación
-- =====================================================================================

ALTER TABLE CRD.PGPR ADD (
    EVPRCDGO NUMBER,                 -- FK evento; NULL en pagos petro/migración existentes
    PGPRASNT NUMBER,                 -- código de asiento contable (hook futuro)
    PGPRANUL NUMBER DEFAULT 0,       -- 0 = vigente, 1 = anulado
    PGPRUSAN VARCHAR2(50),
    PGPRFCAN TIMESTAMP,
    PGPRMTAN VARCHAR2(500)
);

ALTER TABLE CRD.PGPR ADD CONSTRAINT FK_PGPR_EVPR FOREIGN KEY (EVPRCDGO) REFERENCES CRD.EVPR(EVPRCDGO);

CREATE INDEX IDX_PGPR_EVPR ON CRD.PGPR(EVPRCDGO);

COMMENT ON COLUMN CRD.PGPR.EVPRCDGO IS 'FK CRD.EVPR - Evento de pago que generó este registro. NULL en los pagos históricos (petro / migración) anteriores a los servicios de pago';
COMMENT ON COLUMN CRD.PGPR.PGPRASNT IS 'Código del asiento contable asociado al pago (hook futuro; NULL por ahora)';
COMMENT ON COLUMN CRD.PGPR.PGPRANUL IS 'Marca de anulación: 0 = vigente, 1 = anulado. Los pagos anulados NO cuentan en la reconstrucción de saldos de la cuota';
COMMENT ON COLUMN CRD.PGPR.PGPRUSAN IS 'Usuario que anuló el pago';
COMMENT ON COLUMN CRD.PGPR.PGPRFCAN IS 'Fecha/hora de anulación del pago';
COMMENT ON COLUMN CRD.PGPR.PGPRMTAN IS 'Motivo de la anulación del pago';

-- Los pagos preexistentes quedan explícitamente vigentes (el DEFAULT 0 solo aplica a filas nuevas).
UPDATE CRD.PGPR SET PGPRANUL = 0 WHERE PGPRANUL IS NULL;
COMMIT;


-- =====================================================================================
-- 4. ALTER CRD.PGAP (PagoAporte): vínculo al pago de préstamo que consumió el aporte
-- =====================================================================================

ALTER TABLE CRD.PGAP ADD (PGPRCDGO NUMBER);

ALTER TABLE CRD.PGAP ADD CONSTRAINT FK_PGAP_PGPR FOREIGN KEY (PGPRCDGO) REFERENCES CRD.PGPR(PGPRCDGO);

CREATE INDEX IDX_PGAP_PGPR ON CRD.PGAP(PGPRCDGO);

COMMENT ON COLUMN CRD.PGAP.PGPRCDGO IS 'FK CRD.PGPR - Pago de préstamo que consumió este aporte (pago con aportes / precancelación con aportes). NULL en los pagos de aporte del proceso Petro';


-- =====================================================================================
-- 5. ÍNDICES SOBRE CRD.APRT (saldo agregado por entidad/tipo y FIFO)
-- ⚠️ ~980.000 filas: correr en ventana de bajo uso.
-- ⚠️ La cláusula ONLINE requiere Oracle Enterprise Edition. Si la instancia no la soporta
--    (ORA-00439 / ORA-00905), quitar la palabra ONLINE y ejecutar con la tabla sin uso.
-- =====================================================================================

CREATE INDEX IDX_APRT_ENTD_TPAP      ON CRD.APRT(ENTDCDGO, TPAPCDGO) ONLINE;
CREATE INDEX IDX_APRT_ENTD_TPAP_SLDO ON CRD.APRT(ENTDCDGO, TPAPCDGO, APRTSLDO) ONLINE;


-- =====================================================================================
-- 6. GRANTS
-- ⚠️ Verificar el nombre real del rol en la instancia antes de ejecutar
--    (SELECT * FROM DBA_ROLES WHERE ROLE LIKE '%CRD%';). Si el esquema no usa roles,
--    omitir este bloque.
-- =====================================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.EVPR TO ROLE_CRD;
GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.HDTP TO ROLE_CRD;


-- =====================================================================================
-- 7. CONTROLES POSTERIORES A LA EJECUCIÓN
-- =====================================================================================

-- 7.1 Las dos tablas nuevas existen y están vacías
SELECT 'EVPR' AS TABLA, COUNT(*) AS FILAS FROM CRD.EVPR
UNION ALL
SELECT 'HDTP', COUNT(*) FROM CRD.HDTP;

-- 7.2 Las columnas nuevas de PGPR y PGAP existen
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM   ALL_TAB_COLUMNS
WHERE  OWNER = 'CRD'
AND   (   (TABLE_NAME = 'PGPR' AND COLUMN_NAME IN ('EVPRCDGO','PGPRASNT','PGPRANUL','PGPRUSAN','PGPRFCAN','PGPRMTAN'))
       OR (TABLE_NAME = 'PGAP' AND COLUMN_NAME = 'PGPRCDGO'))
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 7.3 El espejo HDTP tiene exactamente las mismas columnas DTPR* que DTPR (debe devolver 0 filas)
SELECT COLUMN_NAME, 'FALTA EN HDTP' AS PROBLEMA
FROM   ALL_TAB_COLUMNS
WHERE  OWNER = 'CRD' AND TABLE_NAME = 'DTPR'
AND    COLUMN_NAME NOT IN (SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER = 'CRD' AND TABLE_NAME = 'HDTP');

-- 7.4 Índices creados
SELECT INDEX_NAME, TABLE_NAME, STATUS
FROM   ALL_INDEXES
WHERE  OWNER = 'CRD'
AND    INDEX_NAME IN ('IDX_EVPR_PRST','IDX_HDTP_PRST','IDX_HDTP_EVPR','IDX_PGPR_EVPR',
                      'IDX_PGAP_PGPR','IDX_APRT_ENTD_TPAP','IDX_APRT_ENTD_TPAP_SLDO')
ORDER BY TABLE_NAME, INDEX_NAME;

-- 7.5 Ningún pago quedó con la marca de anulación en NULL (debe devolver 0)
SELECT COUNT(*) AS PAGOS_CON_ANUL_NULO FROM CRD.PGPR WHERE PGPRANUL IS NULL;
