-- =====================================================================================
-- DDL - PROCESO MENSUAL DE APERTURA / CIERRE DE CARTERA (CRD.CRCT + CRD.BDCC + CRD.ANCC)
-- Implementa la seccion 3.2 de docs/logica-negocio/crd/LEVANTAMIENTO-ALIMENTACION-CONTABLE-CREDITOS.md
-- FECHA: 2026-08-25
-- FASE: 2 (proceso mensual de apertura / cierre)
--
-- Contenido:
--   1. CRD.CRCT - CorridaCierreCartera (cabecera: empresa + anio + mes + estado de la corrida)
--   2. CRD.BDCC - BandaCierreCartera   (snapshot: capital contabilizado por banda)
--   3. CRD.ANCC - AsientoCierreCartera (un asiento por sub-proceso, para trazabilidad y reverso)
--   4. Indices
--   5. Grants
--   6. Controles posteriores
--
-- SQL PURO: sin WHENEVER / SET / DEFINE. Se ejecuta con el cliente JDBC de VS Code.
-- El DDL va ANTES del despliegue del WAR: las entidades JPA nuevas mapean estas tablas
--    y el arranque falla si no existen.
--
-- POR QUE UN SNAPSHOT Y NO LA MAYORIZACION (decision de disenio, Fase 2):
--   Los asientos de reclasificacion de bandas registran DIFERENCIAS entre la distribucion
--   nueva y la anterior. Esa "anterior" NO se lee de CNT.DTMY: el mayor mezcla lo que
--   escriben otros procesos sobre las mismas cuentas (pagos, entregas, novaciones) y el
--   asiento arrastraria movimientos ajenos. CRD.BDCC guarda lo que ESTE proceso
--   contabilizo cada mes; la corrida siguiente compara contra eso. Es reproducible,
--   auditable y reversable.
--
-- NOMENCLATURA (descriptores verificados contra src/main/java/com/saa/model):
--   FCCR fecha de corte (8 usos) . FCPR fecha de proceso (8) . ANOO anio (27) . MESS mes (3)
--   CPTL capital (3) . CNTD cantidad (7) . NMRO numero (34) . TPCR tipo de cartera (3)
--   TPOO tipo (24) . ASNT id de asiento (11) . NMAS numero de asiento (10) . VLRR valor (69)
--   OBSR observacion (53) . IDST estado operativo (52) . ESTD estado activo/inactivo (138)
--   Estado: 1 = activo, 0 = inactivo (com.saa.rubros.Estado).
-- =====================================================================================


-- =====================================================================================
-- 1. TABLA: CRD.CRCT (CorridaCierreCartera)
-- DESCRIPCION: Una fila por (empresa, anio, mes cerrado). Cabecera del proceso mensual.
--              A lo sumo UNA corrida no reversada por periodo - lo garantiza el indice
--              unico funcional UK_CRCT_PERIODO, no solo el servicio.
-- =====================================================================================

CREATE TABLE CRD.CRCT (
    -- PK autoincremental (Oracle 12c+)
    CRCTCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    -- FK a SCP.PJRQ (nodo de empresa, pgspcdgo 12 - mismo criterio que CRD.CBPR.PJRQCDGO)
    PJRQCDGO NUMBER NOT NULL,
    -- Periodo CERRADO por la corrida (no el periodo en que se ejecuta)
    CRCTANOO NUMBER NOT NULL,
    CRCTMESS NUMBER NOT NULL,
    -- Fecha de corte: ULTIMO dia del mes cerrado. Es el filtro de "cuotas/intereses
    -- pendientes con fecha <= corte" (regla 1 de la seccion 5 del levantamiento) y la
    -- fecha contable del asiento de neteo (sub-proceso 6).
    CRCTFCCR DATE NOT NULL,
    -- Fecha de proceso: PRIMER dia del mes siguiente. Es la fecha contable de los
    -- sub-procesos 1, 2, 3, 4 y 5 ("1er dia del mes", seccion 3.2) y la fecha con la que
    -- se resuelve la configuracion de bandas vigente (CRD.CBPR).
    CRCTFCPR DATE NOT NULL,
    -- Estado OPERATIVO de la corrida: 1 = PREPARADA, 2 = EJECUTADA, 3 = REVERSADA.
    -- Ver com.saa.rubros.EstadoCorridaCierreCartera. NO confundir con CRCTESTD.
    CRCTIDST NUMBER DEFAULT 1 NOT NULL,
    -- Observacion libre de la corrida
    CRCTOBSR VARCHAR2(2000),
    -- AUDITORIA (patron CRD: registro + modificacion)
    CRCTFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRCTUSRG VARCHAR2(2000),
    CRCTIPRG VARCHAR2(50),
    CRCTFCMD TIMESTAMP,
    CRCTUSMD VARCHAR2(2000),
    CRCTIPMD VARCHAR2(50),
    -- ESTADO de la fila: 1 = activo, 0 = inactivo
    CRCTESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_CRCT PRIMARY KEY (CRCTCDGO),
    CONSTRAINT FK_CRCT_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT CK_CRCT_MESS CHECK (CRCTMESS BETWEEN 1 AND 12),
    CONSTRAINT CK_CRCT_IDST CHECK (CRCTIDST IN (1, 2, 3)),
    CONSTRAINT CK_CRCT_ESTD CHECK (CRCTESTD IN (0, 1))
);

COMMENT ON TABLE CRD.CRCT IS
  'Corrida del proceso mensual de apertura/cierre de cartera: una fila por empresa, anio y mes cerrado. Ver docs/logica-negocio/crd/LEVANTAMIENTO-ALIMENTACION-CONTABLE-CREDITOS.md 3.2.';
COMMENT ON COLUMN CRD.CRCT.CRCTCDGO IS 'PK autoincremental.';
COMMENT ON COLUMN CRD.CRCT.PJRQCDGO IS 'FK al nodo de empresa (SCP.PJRQ, nivel empresa pgspcdgo 12).';
COMMENT ON COLUMN CRD.CRCT.CRCTANOO IS 'Anio del mes CERRADO por la corrida.';
COMMENT ON COLUMN CRD.CRCT.CRCTMESS IS 'Mes CERRADO por la corrida, 1 a 12.';
COMMENT ON COLUMN CRD.CRCT.CRCTFCCR IS 'Fecha de corte: ultimo dia del mes cerrado. Filtro de cuotas pendientes y fecha contable del neteo.';
COMMENT ON COLUMN CRD.CRCT.CRCTFCPR IS 'Fecha de proceso: primer dia del mes siguiente. Fecha contable de vencidos, bandas, apertura e intereses, y fecha con la que se resuelve la configuracion de bandas vigente.';
COMMENT ON COLUMN CRD.CRCT.CRCTIDST IS 'Estado operativo: 1 = PREPARADA, 2 = EJECUTADA, 3 = REVERSADA.';
COMMENT ON COLUMN CRD.CRCT.CRCTESTD IS 'Estado de la fila: 1 = activo, 0 = inactivo.';


-- =====================================================================================
-- 2. TABLA: CRD.BDCC (BandaCierreCartera)
-- DESCRIPCION: Snapshot de la distribucion de CAPITAL por (producto, tipo de cartera,
--              banda) que la corrida contabilizo. Es la "distribucion anterior" contra la
--              que compara la corrida siguiente.
--              La cuenta (PLNNCDGO) se guarda CONGELADA ademas de la FK a la banda: si la
--              parametrizacion cambia de vigencia, el snapshot debe seguir sabiendo en que
--              cuenta quedo el saldo que contabilizo.
-- =====================================================================================

CREATE TABLE CRD.BDCC (
    BDCCCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    -- FK a la corrida
    CRCTCDGO NUMBER NOT NULL,
    -- FK al producto de credito
    PRDCCDGO NUMBER NOT NULL,
    -- Tipo de cartera: 1 = por vencer, 2 = vencido (com.saa.rubros.TipoCarteraBanda)
    BDCCTPCR NUMBER NOT NULL,
    -- FK a la banda de la parametrizacion vigente en la fecha de proceso
    BNDPCDGO NUMBER NOT NULL,
    -- Numero de banda, copiado para poder ordenar y leer sin unir con BNDP
    BDCCNMRO NUMBER NOT NULL,
    -- FK a CNT.PLNN: cuenta contable en la que quedo el capital de esta banda
    PLNNCDGO NUMBER NOT NULL,
    -- Capital contabilizado en la banda
    BDCCCPTL NUMBER(18,2) DEFAULT 0 NOT NULL,
    -- Cantidad de cuotas que aportaron a ese capital (informativo / control)
    BDCCCNTD NUMBER DEFAULT 0,
    -- AUDITORIA
    BDCCFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BDCCUSRG VARCHAR2(2000),
    BDCCIPRG VARCHAR2(50),
    BDCCFCMD TIMESTAMP,
    BDCCUSMD VARCHAR2(2000),
    BDCCIPMD VARCHAR2(50),
    BDCCESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_BDCC PRIMARY KEY (BDCCCDGO),
    CONSTRAINT FK_BDCC_CRCT FOREIGN KEY (CRCTCDGO) REFERENCES CRD.CRCT(CRCTCDGO),
    CONSTRAINT FK_BDCC_PRDC FOREIGN KEY (PRDCCDGO) REFERENCES CRD.PRDC(PRDCCDGO),
    CONSTRAINT FK_BDCC_BNDP FOREIGN KEY (BNDPCDGO) REFERENCES CRD.BNDP(BNDPCDGO),
    CONSTRAINT FK_BDCC_PLNN FOREIGN KEY (PLNNCDGO) REFERENCES CNT.PLNN(PLNNCDGO),
    CONSTRAINT CK_BDCC_TPCR CHECK (BDCCTPCR IN (1, 2)),
    CONSTRAINT CK_BDCC_NMRO CHECK (BDCCNMRO >= 1),
    CONSTRAINT CK_BDCC_ESTD CHECK (BDCCESTD IN (0, 1)),
    CONSTRAINT UK_BDCC_CORRIDA UNIQUE (CRCTCDGO, PRDCCDGO, BDCCTPCR, BDCCNMRO)
);

COMMENT ON TABLE CRD.BDCC IS
  'Snapshot del capital contabilizado por producto, tipo de cartera y banda en una corrida de cierre. Es la distribucion contra la que compara la corrida siguiente para armar el asiento de reclasificacion.';
COMMENT ON COLUMN CRD.BDCC.CRCTCDGO IS 'FK a la corrida (CRD.CRCT).';
COMMENT ON COLUMN CRD.BDCC.BDCCTPCR IS 'Tipo de cartera: 1 = por vencer, 2 = vencido.';
COMMENT ON COLUMN CRD.BDCC.BNDPCDGO IS 'FK a la banda de la parametrizacion (CRD.BNDP) vigente en la fecha de proceso.';
COMMENT ON COLUMN CRD.BDCC.PLNNCDGO IS 'FK a CNT.PLNN: cuenta en la que quedo el capital. Se congela para que un cambio de vigencia de la parametrizacion no reescriba la historia.';
COMMENT ON COLUMN CRD.BDCC.BDCCCPTL IS 'Capital contabilizado en la banda.';
COMMENT ON COLUMN CRD.BDCC.BDCCCNTD IS 'Cantidad de cuotas que aportaron a ese capital.';


-- =====================================================================================
-- 3. TABLA: CRD.ANCC (AsientoCierreCartera)
-- DESCRIPCION: Un registro por sub-proceso contabilizado en la corrida. Permite reversar
--              y da trazabilidad de que asiento salio de que sub-proceso.
--              ANCCASNT es un NUMERO SIN FK a CNT.ASNT, a proposito: el sistema se
--              comercializa despues SIN el modulo crd, asi que no puede quedar integridad
--              referencial entre CRD y CNT en la direccion de los documentos. Mismo
--              criterio que CRD.PGPR.PGPRASNT y CRD.DVAP.DVAPNMAS.
-- =====================================================================================

CREATE TABLE CRD.ANCC (
    ANCCCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    -- FK a la corrida
    CRCTCDGO NUMBER NOT NULL,
    -- Sub-proceso: 1 = vencidos, 2 = cambio de bandas por vencer, 3 = cambio de bandas
    -- vencido, 4 = apertura, 5 = devengo de intereses, 6 = neteo.
    -- Ver com.saa.rubros.SubProcesoCierreCartera.
    ANCCTPOO NUMBER NOT NULL,
    -- Id del asiento generado en CNT.ASNT. Sin FK (ver cabecera).
    ANCCASNT NUMBER,
    -- Numero del asiento, para mostrarlo sin ir a CNT
    ANCCNMAS VARCHAR2(50),
    -- Fecha contable del asiento
    ANCCFCHA DATE,
    -- Total del asiento (DEBE, que iguala al HABER)
    ANCCVLRR NUMBER(18,2) DEFAULT 0,
    -- Cantidad de lineas del asiento
    ANCCCNTD NUMBER DEFAULT 0,
    -- Estado operativo: 1 = GENERADO, 2 = ANULADO (por reverso)
    ANCCIDST NUMBER DEFAULT 1 NOT NULL,
    -- AUDITORIA
    ANCCFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ANCCUSRG VARCHAR2(2000),
    ANCCIPRG VARCHAR2(50),
    ANCCFCMD TIMESTAMP,
    ANCCUSMD VARCHAR2(2000),
    ANCCIPMD VARCHAR2(50),
    ANCCESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_ANCC PRIMARY KEY (ANCCCDGO),
    CONSTRAINT FK_ANCC_CRCT FOREIGN KEY (CRCTCDGO) REFERENCES CRD.CRCT(CRCTCDGO),
    CONSTRAINT FK_ANCC_ASNT FOREIGN KEY (ANCCASNT) REFERENCES CNT.ASNT(ASNTCDGO),
    CONSTRAINT CK_ANCC_TPOO CHECK (ANCCTPOO IN (1, 2, 3, 4, 5, 6)),
    CONSTRAINT CK_ANCC_IDST CHECK (ANCCIDST IN (1, 2)),
    CONSTRAINT CK_ANCC_ESTD CHECK (ANCCESTD IN (0, 1)),
    CONSTRAINT UK_ANCC_CORRIDA UNIQUE (CRCTCDGO, ANCCTPOO)
);

COMMENT ON TABLE CRD.ANCC IS
  'Asiento generado por cada sub-proceso de una corrida de cierre de cartera. Da trazabilidad y permite el reverso.';
COMMENT ON COLUMN CRD.ANCC.ANCCTPOO IS 'Sub-proceso: 1 vencidos, 2 cambio de bandas por vencer, 3 cambio de bandas vencido, 4 apertura, 5 devengo de intereses, 6 neteo.';
COMMENT ON COLUMN CRD.ANCC.ANCCASNT IS 'FK al asiento generado (CNT.ASNT). Nulo mientras el sub-proceso no lo haya generado. El reverso ANULA el asiento (marca su estado), no lo borra, asi que la FK no estorba. La restriccion de comercializacion prohibe que CNT/TSR/CXP dependan de CRD, no al reves: CRD si puede apuntar a CNT, igual que CRD.BNDP.PLNNCDGO y CRD.BDCC.PLNNCDGO.';
COMMENT ON COLUMN CRD.ANCC.ANCCIDST IS 'Estado operativo del asiento: 1 = GENERADO, 2 = ANULADO por reverso.';


-- =====================================================================================
-- 4. INDICES
-- =====================================================================================

-- Idempotencia en la BASE, no solo en el servicio: a lo sumo UNA corrida PREPARADA o
-- EJECUTADA y activa por (empresa, anio, mes). Las REVERSADAS (CRCTIDST = 3) quedan
-- fuera del indice y por eso pueden convivir varias, que es lo que permite reprocesar.
CREATE UNIQUE INDEX CRD.UK_CRCT_PERIODO ON CRD.CRCT (
    CASE WHEN CRCTIDST IN (1, 2) AND CRCTESTD = 1 THEN PJRQCDGO END,
    CASE WHEN CRCTIDST IN (1, 2) AND CRCTESTD = 1 THEN CRCTANOO END,
    CASE WHEN CRCTIDST IN (1, 2) AND CRCTESTD = 1 THEN CRCTMESS END
);

CREATE INDEX CRD.IDX_CRCT_BUSQ ON CRD.CRCT (PJRQCDGO, CRCTANOO, CRCTMESS, CRCTIDST);
CREATE INDEX CRD.IDX_BDCC_CRCT ON CRD.BDCC (CRCTCDGO);
CREATE INDEX CRD.IDX_BDCC_BNDP ON CRD.BDCC (BNDPCDGO);
-- La busqueda por (corrida, producto, tipo de cartera, banda) NO lleva indice propio:
-- la sirve el de UK_BDCC_CORRIDA, que ya indexa esas mismas cuatro columnas en ese orden.
-- Crear otro da ORA-01408.
CREATE INDEX CRD.IDX_ANCC_CRCT ON CRD.ANCC (CRCTCDGO);


-- =====================================================================================
-- 5. GRANTS
-- Verificar el nombre real de los roles en la instancia antes de ejecutar
--    (SELECT * FROM DBA_ROLES WHERE ROLE LIKE '%CRD%';).
--    Si el esquema no usa roles, omitir este bloque.
-- =====================================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.CRCT TO ROLE_CRD;
GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.BDCC TO ROLE_CRD;
GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.ANCC TO ROLE_CRD;


-- =====================================================================================
-- 6. CONTROL POSTERIOR
-- =====================================================================================

SELECT table_name FROM all_tables WHERE owner = 'CRD' AND table_name IN ('CRCT','BDCC','ANCC');
-- Esperado: 3 filas.

SELECT index_name FROM all_indexes WHERE owner = 'CRD' AND table_name IN ('CRCT','BDCC','ANCC');
-- Esperado: los 6 indices de la seccion 4 mas los de las PK y las UNIQUE.
