-- =====================================================================================
-- DDL — MODELO DINAMICO DE BANDAS POR PRODUCTO (CRD.CBPR + CRD.BNDP)
-- Implementa la seccion 8 de docs/logica-negocio/crd/LEVANTAMIENTO-ALIMENTACION-CONTABLE-CREDITOS.md
-- FECHA: 2026-08-25
-- FASE: 1 (Cimientos del modelo de bandas)
--
-- SQL PURO: sin comandos SQL*Plus. Apto para el plugin de VS Code / DBeaver / cualquier
--   cliente JDBC, y tambien para SQL*Plus (las sentencias no tienen lineas en blanco
--   internas a proposito — SQL*Plus corta la sentencia en una linea en blanco).
--
-- Contenido:
--   1. CRD.CBPR — ConfiguracionBandaProducto (cabecera: producto + empresa + tipo cartera + vigencia)
--   2. CRD.BNDP — BandaProducto (detalle: numero de banda, periodos de 30 dias, cuenta contable)
--   3. Indices
--   4. Grants (opcional segun la instancia)
--
-- EJECUCION MANUAL, como owner del esquema CRD (o usuario con privilegios).
-- El DDL va ANTES del despliegue del WAR: las entidades JPA nuevas mapean estas tablas
--    y el arranque falla si no existen.
-- La carga inicial de datos NO esta aqui: ver sql/CARGA-INICIAL-BANDAS-PRODUCTO.sql y
--    su runbook CARGA-INICIAL-BANDAS-PRODUCTO.md (se ejecuta despues de este DDL).
--
-- DECISIONES DE DISENO (§8.2 y §9.1 del levantamiento — cerradas el 2026-08-25):
--   - Ancla: CRD.PRDC (Producto), no TipoPrestamo. Parametrizacion por producto + empresa.
--   - Vigencia historica: los cambios normativos cierran la configuracion vieja
--     (CBPRFCFN) y abren una nueva; la anterior queda para reprocesos/auditoria.
--   - Cuenta como FK a CNT.PLNN (id del plan de cuentas), nunca codigo texto.
--   - Ultima banda = BNDPCNTD NULL ("resto"/abierta).
--   - Solo CAPITAL se distribuye por bandas.
-- =====================================================================================


-- =====================================================================================
-- 1. TABLA: CRD.CBPR (ConfiguracionBandaProducto)
-- DESCRIPCION: Cabecera de la parametrizacion de bandas de cartera. Una fila por
--              (producto, empresa, tipo de cartera, vigencia). A una fecha dada solo
--              puede haber UNA configuracion vigente y activa por esa terna.
--              CBPRTPCR: 1 = por vencer, 2 = vencido.
--              CBPRFCIN / CBPRFCFN: vigencia desde / hasta (NULL = vigente).
-- =====================================================================================

CREATE TABLE CRD.CBPR (
    CBPRCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PRDCCDGO NUMBER NOT NULL,
    PJRQCDGO NUMBER NOT NULL,
    CBPRTPCR NUMBER NOT NULL,
    CBPRFCIN DATE NOT NULL,
    CBPRFCFN DATE,
    CBPRFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CBPRUSRG VARCHAR2(2000),
    CBPRIPRG VARCHAR2(50),
    CBPRFCMD TIMESTAMP,
    CBPRUSMD VARCHAR2(2000),
    CBPRIPMD VARCHAR2(50),
    CBPRESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_CBPR PRIMARY KEY (CBPRCDGO),
    CONSTRAINT FK_CBPR_PRDC FOREIGN KEY (PRDCCDGO) REFERENCES CRD.PRDC(PRDCCDGO),
    CONSTRAINT FK_CBPR_PJRQ FOREIGN KEY (PJRQCDGO) REFERENCES SCP.PJRQ(PJRQCDGO),
    CONSTRAINT CK_CBPR_TPCR CHECK (CBPRTPCR IN (1, 2))
);

COMMENT ON TABLE CRD.CBPR IS
  'Configuracion de bandas de cartera por producto, empresa y tipo de cartera (1=por vencer, 2=vencido), con vigencia historica. Cabecera de CRD.BNDP. Ver docs/logica-negocio/crd/LEVANTAMIENTO-ALIMENTACION-CONTABLE-CREDITOS.md §8.';
COMMENT ON COLUMN CRD.CBPR.CBPRCDGO IS 'PK autoincremental.';
COMMENT ON COLUMN CRD.CBPR.PRDCCDGO IS 'FK al producto de credito (CRD.PRDC).';
COMMENT ON COLUMN CRD.CBPR.PJRQCDGO IS 'FK al nodo de empresa (SCP.PJRQ, nivel empresa pgspcdgo 12). La parametrizacion es por producto + empresa.';
COMMENT ON COLUMN CRD.CBPR.CBPRTPCR IS 'Tipo de cartera: 1 = por vencer, 2 = vencido.';
COMMENT ON COLUMN CRD.CBPR.CBPRFCIN IS 'Inicio de vigencia de esta configuracion.';
COMMENT ON COLUMN CRD.CBPR.CBPRFCFN IS 'Fin de vigencia. NULL = configuracion vigente. Un cambio normativo cierra esta fecha y crea una configuracion nueva; la anterior queda para reprocesos/auditoria.';
COMMENT ON COLUMN CRD.CBPR.CBPRESTD IS 'Estado: 1 = activo, 2 = inactivo.';


-- =====================================================================================
-- 2. TABLA: CRD.BNDP (BandaProducto)
-- DESCRIPCION: Bandas de una configuracion. Numeradas consecutivas desde 1. Cada banda
--              define cuantos periodos de 30 dias abarca (BNDPCNTD; NULL = banda
--              abierta, "el resto"; solo la ultima puede serlo) y la cuenta contable
--              (PLNNCDGO, FK a CNT.PLNN) donde se registra el CAPITAL de esa banda
--              para ese producto.
--              Los rangos en dias se DERIVAN: inicio(k) = 30*SUM(periodos 1..k-1) + 1;
--              fin(k) = 30*SUM(periodos 1..k). No se almacenan.
--              La unicidad de "solo una banda abierta y es la ultima" y la
--              consecutividad 1..N las valida el servicio, no la base.
-- =====================================================================================

CREATE TABLE CRD.BNDP (
    BNDPCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CBPRCDGO NUMBER NOT NULL,
    BNDPNMRO NUMBER NOT NULL,
    BNDPCNTD NUMBER,
    PLNNCDGO NUMBER NOT NULL,
    BNDPFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BNDPUSRG VARCHAR2(2000),
    BNDPIPRG VARCHAR2(50),
    BNDPFCMD TIMESTAMP,
    BNDPUSMD VARCHAR2(2000),
    BNDPIPMD VARCHAR2(50),
    BNDPESTD NUMBER DEFAULT 1,
    CONSTRAINT PK_BNDP PRIMARY KEY (BNDPCDGO),
    CONSTRAINT FK_BNDP_CBPR FOREIGN KEY (CBPRCDGO) REFERENCES CRD.CBPR(CBPRCDGO),
    CONSTRAINT FK_BNDP_PLNN FOREIGN KEY (PLNNCDGO) REFERENCES CNT.PLNN(PLNNCDGO),
    CONSTRAINT CK_BNDP_NMRO CHECK (BNDPNMRO >= 1),
    CONSTRAINT CK_BNDP_CNTD CHECK (BNDPCNTD IS NULL OR BNDPCNTD >= 1),
    CONSTRAINT UK_BNDP_CBPR_NMRO UNIQUE (CBPRCDGO, BNDPNMRO)
);

COMMENT ON TABLE CRD.BNDP IS
  'Banda de cartera de una configuracion CRD.CBPR: numero consecutivo, periodos de 30 dias (NULL = banda abierta/resto, solo la ultima) y cuenta contable del capital (FK CNT.PLNN). Los rangos en dias se derivan acumulando periodos.';
COMMENT ON COLUMN CRD.BNDP.CBPRCDGO IS 'FK a la configuracion (CRD.CBPR).';
COMMENT ON COLUMN CRD.BNDP.BNDPNMRO IS 'Numero de banda, 1..N consecutivo dentro de la configuracion.';
COMMENT ON COLUMN CRD.BNDP.BNDPCNTD IS 'Periodos de 30 dias que abarca. NULL = banda abierta (el resto); solo puede serlo la ultima banda.';
COMMENT ON COLUMN CRD.BNDP.PLNNCDGO IS 'FK a CNT.PLNN: cuenta contable del capital de esta banda para este producto. Nunca guardar el codigo como texto.';
COMMENT ON COLUMN CRD.BNDP.BNDPESTD IS 'Estado: 1 = activo, 2 = inactivo.';


-- =====================================================================================
-- 3. INDICES
-- =====================================================================================

CREATE INDEX IDX_CBPR_PRDC ON CRD.CBPR(PRDCCDGO);
CREATE INDEX IDX_CBPR_BUSQ ON CRD.CBPR(PRDCCDGO, PJRQCDGO, CBPRTPCR, CBPRESTD);
CREATE INDEX IDX_BNDP_CBPR ON CRD.BNDP(CBPRCDGO);
CREATE INDEX IDX_BNDP_PLNN ON CRD.BNDP(PLNNCDGO);


-- =====================================================================================
-- 4. GRANTS
-- Verificar el nombre real de los roles en la instancia antes de ejecutar
--    (SELECT * FROM DBA_ROLES WHERE ROLE LIKE '%CRD%';).
--    Si el esquema no usa roles (la BD local de desarrollo no los tiene), OMITIR este
--    bloque completo.
-- =====================================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.CBPR TO ROLE_CRD;
GRANT SELECT, INSERT, UPDATE, DELETE ON CRD.BNDP TO ROLE_CRD;
GRANT SELECT ON CNT.PLNN TO ROLE_CRD;


-- =====================================================================================
-- 5. CONTROL POSTERIOR
-- =====================================================================================

SELECT table_name FROM all_tables WHERE owner = 'CRD' AND table_name IN ('CBPR','BNDP');
-- Esperado: 2 filas.
