-- ============================================================================
-- VERIFICACION-ENTIDADES-VS-ESQUEMA-CRD.sql
-- Escrito por el arbitro de crd (saabe-4b) el 2026-08-30
-- ============================================================================
--
-- POR QUE EXISTE
-- El equipo de cxp/cxc/tsr encontro el 2026-08-29 un script DDL que nunca se
-- habia corrido. Lo grave no fue el script: era una columna MAPEADA en una
-- entidad. Hibernate incluye toda columna @Column basica en el SELECT que
-- genera, asi que la ausencia no rompia solo la funcion nueva — rompia
-- CUALQUIER lectura de esa entidad con ORA-00904.
--
-- Ese fallo no se ve en el codigo, no se ve al compilar, y no se ve hasta que
-- un usuario abre la pantalla. Esta verificacion compara TODAS las columnas
-- mapeadas de TODAS las entidades de crd (98 entidades, 1.242 columnas entre
-- @Column y @JoinColumn) contra lo que existe de verdad en la base.
--
-- NO MODIFICA NADA. Son dos consultas de solo lectura.
--
-- COMO LEERLO
--   Consulta A: tablas mapeadas que no existen. Deberia dar 0 filas.
--   Consulta B: columnas mapeadas que faltan, solo en tablas que si existen.
--               Deberia dar 0 filas. Cada fila es un ORA-00904 esperando el
--               proximo despliegue.
--
-- ⚠️ TRES COSAS QUE HAY QUE SABER ANTES DE INTERPRETAR EL RESULTADO
--   1. ALL_TAB_COLUMNS solo muestra lo que el usuario conectado puede ver. Con
--      un usuario sin privilegios sobre CRD van a salir falsos FALTA.
--      Conectarse con el mismo usuario del datasource, o con DBA.
--   2. EN PRODUCCION es normal que hoy falten CRD.ACCN y CRD.DACC: son las
--      tablas de acuerdos de condonacion, cuyo DDL a proposito NO se ha
--      corrido todavia. En LOCAL si deben existir. Cualquier OTRA ausencia es
--      un problema real.
--   3. ALCANCE: solo crd. No cubre cnt ni scp (esquemas compartidos), ni los
--      modulos del otro equipo — para esos existe
--      VERIFICACION-ENTIDADES-VS-ESQUEMA-CXC-CXP-TSR.sql.
--
-- REGENERAR: este archivo se genero leyendo src/main/java/com/saa/model/crd.
-- Si se agregan entidades o columnas, hay que volver a generarlo — un script
-- de verificacion desactualizado da una tranquilidad que no corresponde.
-- ============================================================================

WITH ESPERADO AS (
SELECT 'CRD' AS OWNER_ESP, 'ACCN' AS TABLA_ESP, 'ACCNCDGO,ACCNESTD,ACCNFCAP,ACCNFCHA,ACCNFCRC,ACCNFCRG,ACCNMTRC,ACCNOBSR,ACCNUSAP,ACCNUSRC,ACCNUSRG,ACCNVLCN,ACCNVLPG,CBCRCDGO,ENTDCDGO,EVPRCDGO,PRSTCDGO' AS COLS FROM DUAL
UNION ALL SELECT 'CRD', 'ADJN', 'ADJNCDGO,ADJNFCRG,ADJNIDRF,ADJNIDST,ADJNISCA,ADJNMMTY,ADJNNMAR,ADJNOBSR,ADJNURLA,ADJNUSRG,ENTDCDGO,PRSTCDGO,TPDJCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'AVPC', 'AVPCCDGO,AVPCCPAF,AVPCDFCP,AVPCDFDG,AVPCDFIN,AVPCDFTL,AVPCDGAF,AVPCESTD,AVPCFCAF,AVPCFCRG,AVPCINAF,AVPCOBSR,AVPCUSAR,AVPCVAFA,AVPCVLCP,AVPCVLCT,AVPCVLDG,AVPCVLIN,DTPRCDGO,NVPCCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'APRT', 'APRTCDGO,APRTFCRG,APRTFCTR,APRTGLSA,APRTIDAS,APRTIDDV,APRTIDST,APRTPRDV,APRTSLDO,APRTTPMV,APRTUSRG,APRTVLPG,APRTVLRR,CNTRCDGO,CRARCDGO,ENTDCDGO,FLLLCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'APAS', 'APASACML,APASACTP,APASCLNT,APASCNTA,APASCRDP,APASFCHA,APASFCHC,APASFCHL,APASFCHM,APASFCHP,APASFCHR,APASFCHV,APASNMAP,APASNMRC,APASNMSL,APASNSTT,APASOBSR,APASPRDT,APASRGMN,APASSLDA,APASSLDC,APASSLDI,APASSTDO,APASTPLQ,APASVLRA' FROM DUAL
UNION ALL SELECT 'CRD', 'ANCP', 'ANCPASNT,ANCPCDGO,ANCPCNTD,ANCPFCHA,ANCPFCRG,ANCPIDST,ANCPIPRG,ANCPNMAS,ANCPOBSR,ANCPTPOO,ANCPUSRG,ANCPVLRR,CRARCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ANCC', 'ANCCASNT,ANCCCDGO,ANCCCNTD,ANCCESTD,ANCCFCHA,ANCCFCMD,ANCCFCRG,ANCCIDST,ANCCIPMD,ANCCIPRG,ANCCNMAS,ANCCTPOO,ANCCUSMD,ANCCUSRG,ANCCVLRR,CRCTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ADTR', 'ADTRACCN,ADTRAGNT,ADTRCDGO,ADTRFCHA,ADTRFCIN,ADTRIPCL,ADTRMDLO,ADTRNMNA,ADTRNMNN,ADTRNTDD,ADTRNTID,ADTRRLL,ADTRRSN,ADTRSSTM,ADTRUSRO,ADTRVLNA,ADTRVLNN' FROM DUAL
UNION ALL SELECT 'CRD', 'BDCC', 'BDCCCDGO,BDCCCNTD,BDCCCPTL,BDCCESTD,BDCCFCMD,BDCCFCRG,BDCCIPMD,BDCCIPRG,BDCCNMRO,BDCCTPCR,BDCCUSMD,BDCCUSRG,BNDPCDGO,CRCTCDGO,PLNNCDGO,PRDCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BNDP', 'BNDPCDGO,BNDPCNTD,BNDPESTD,BNDPFCMD,BNDPFCRG,BNDPIPMD,BNDPIPRG,BNDPNMRO,BNDPUSMD,BNDPUSRG,CBPRCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BIPR', 'BIPRCSNP,BIPRCSPR,BIPRCSRV,BIPRIDSA,BIPRJBPR,BIPRJBPT,BIPRJBRV,BIPRNMBR,BIPRNMCD,BIPRNMRO,BIPRPNSN,BIPRRNCP,BIPRRNJP,BIPRRNJR,BIPRRNPS,BIPRTTLG' FROM DUAL
UNION ALL SELECT 'CRD', 'BPRF', 'BPRFCDGO,BPRFFCHR,BPRFIDNT,BPRFIDST,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BTPC', 'BTPCCDGO,BTPCIDPC,BTPCIDST,BTPCNMBR,BTPCNMRP' FROM DUAL
UNION ALL SELECT 'CRD', 'CMBP', 'CMBPCDGO,CMBPESAC,CMBPESTD,CMBPESWB,CMBPFCAP,CMBPFCIN,CMBPFCSL,CMBPPRCS,CMBPPRJB,CMBPSLDO,CMBPUSIN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNTN', 'CNTNCDGO,CNTNCDGX,CNTNIDST,CNTNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'CRAR', 'CRARANAF,CRARCDGO,CRARESTD,CRARFCAC,CRARFCAN,CRARFCCR,CRARMSAF,CRARMTAN,CRARNMBR,CRARNMTF,CRARRTAS,CRARTCND,CRARTDND,CRARTIND,CRARTTCD,CRARTTDO,CRARTTDS,CRARTTIA,CRARTTID,CRARTTSA,CRARTTSD,CRARTTVS,CRARUSAN,CRARUSCC,CRARUSCD,FLLLCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRTF', 'CRTFANIO,CRTFCDGO,CRTFCLDD,CRTFDTOS,CRTFESTD,CRTFFCAN,CRTFFCEM,CRTFFCRG,CRTFMTAN,CRTFNMAL,CRTFNMRO,CRTFPDFF,CRTFTPCR,CRTFUSAN,CRTFUSEM,ENTDCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CSNT', 'CSNTAPDS,CSNTCDGO,CSNTESFL,CSNTESTD,CSNTFCEC,CSNTFCHA,CSNTFCLQ,CSNTFCRG,CSNTFCSL,CSNTIDSL,CSNTIDST,CSNTSLCB,CSNTSLPG,CSNTTTEG,CSNTTTIN,CSNTUSRG,CSNTVLDS,CSNTVLPG,ENTDCDGO,TPCSCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CDDD', 'CDDDCDAL,CDDDCDEX,CDDDCDGO,CDDDFCIN,CDDDIDST,CDDDNMBR,CDDDUSIN,PRVNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CBCR', 'CBCRASN1,CBCRASN2,CBCRCDGO,CBCRESTD,CBCRFCAN,CBCRFCAP,CBCRFCHA,CBCRFCPR,CBCRFCRC,CBCRFCRG,CBCRMTAN,CBCRMTRC,CBCROBSR,CBCRRFRN,CBCRRTRS,CBCRTPOO,CBCRUSAN,CBCRUSAP,CBCRUSPR,CBCRUSRC,CBCRUSRG,CBCRVLRR,CNBCCDGO,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CMNT', 'CMNTCDGO,CMNTESTD,CMNTFCHA,CMNTFNCN,CMNTIDST,CMNTOBSR,ENTDCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CBPR', 'CBPRCDGO,CBPRESTD,CBPRFCFN,CBPRFCIN,CBPRFCMD,CBPRFCRG,CBPRIPMD,CBPRIPRG,CBPRTPCR,CBPRUSMD,CBPRUSRG,PJRQCDGO,PRDCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNTR', 'CNTRCDGO,CNTRESTD,CNTRFCAP,CNTRFCIN,CNTRFCRG,CNTRFCRP,CNTRFCTR,CNTRIDST,CNTRMNAA,CNTRMNAC,CNTRMNAJ,CNTRMTTR,CNTROBSR,CNTRPRAI,CNTRPRAJ,CNTRUSAP,CNTRUSRG,ENTDCDGO,FLLLCDGO,TPCNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNYG', 'CNYGCDGO,CNYGCDLA,CNYGCRREO,CNYGIDST,CNYGNMBR,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRCT', 'CRCTANOO,CRCTCDGO,CRCTESTD,CRCTFCCR,CRCTFCMD,CRCTFCPR,CRCTFCRG,CRCTIDST,CRCTIPMD,CRCTIPRG,CRCTMESS,CRCTOBSR,CRCTUSMD,CRCTUSRG,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRDT', 'CRDTCDGO,CRDTIDPR,CRDTIDST,CRDTMNMN,CRDTMNMX' FROM DUAL
UNION ALL SELECT 'CRD', 'CNBP', 'BEXTCDGO,CNBPCDGO,CNBPIDST,CNBPNMRO,CNBPTPCN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXPG', 'CXPGCDGO,CXPGFCIN,CXPGFCMD,CXPGNNCT,CXPGUSIN,CXPGUSMD,CXPGVLCT,PDGACDGO,PRSTCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXCK', 'CXCKCDGO,CXCKCNCP,CXCKFCCR,CXCKIDCN,CXCKIDTR,CXCKSLAC,CXCKTTCR,CXCKTTDB,CXCPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXCP', 'CXCPCDGO,CXCPFCHC,CXCPIDCL,CXCPIDCN,CXCPSLCN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTSP', 'DTSPCDGO,DTSPESTD,DTSPFCRG,DTSPOTIE,DTSPOTIR,DTSPTTEG,DTSPTTSL,DTSPUSRG,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DACC', 'ACCNCDGO,DACCCDGO,DACCCPTO,DACCVLAD,DACCVLCN,DACCVLPG' FROM DUAL
UNION ALL SELECT 'CRD', 'DTCA', 'CRARCDGO,DTCACDGO,DTCACDPP,DTCAESTD,DTCANMPP,DTCATCND,DTCATDND,DTCATIND,DTCATPXP,DTCATTCD,DTCATTDO,DTCATTDS,DTCATTIA,DTCATTID,DTCATTSA,DTCATTSD,DTCATTVS' FROM DUAL
UNION ALL SELECT 'CRD', 'DCBC', 'ACCNCDGO,CBCRCDGO,DCBCCDGO,DCBCMDLD,DCBCOBSR,DCBCPRDV,DCBCVLRR,EVPRCDGO,PGAPCDGO,PRSTCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DDVA', 'DDVAAPRT,DDVAAPRV,DDVACDGO,DDVAPGAP,DDVAVLRR,DVAPCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTGA', 'DTGACDGO,DTGACDPT,DTGADSCR,DTGAFCIN,DTGAFCMD,DTGAMNTO,DTGATLRG,DTGAUSIN,DTGAUSMD,GNAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTPR', 'DTPRABNO,DTPRCDEX,DTPRCDGO,DTPRCPPG,DTPRCPTL,DTPRCTAA,DTPRDSDF,DTPRDSFR,DTPRDSGR,DTPRDSMR,DTPRDSOR,DTPRDSPG,DTPRESTD,DTPRFCPG,DTPRFCRG,DTPRFCVN,DTPRIDST,DTPRINPG,DTPRINTR,DTPRINVN,DTPRINVP,DTPRMRAA,DTPRMRCL,DTPRMRPG,DTPRNMCT,DTPROTSG,DTPRSICP,DTPRSLCP,DTPRSLDO,DTPRSLIN,DTPRSLIV,DTPRSLMR,DTPRSLOT,DTPRTTCS,DTPRTTLL,DTPRUSRG,DTPRVLDF,DTPRVLSI,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DVAP', 'CNBPCDGO,DVAPCDGO,DVAPESTD,DVAPFCAN,DVAPFCHA,DVAPFCPG,DVAPFCRG,DVAPIDEM,DVAPIDPG,DVAPMTAN,DVAPMTVO,DVAPNMAS,DVAPUSAN,DVAPUSRG,DVAPVLRR,ENTDCDGO,FLLLCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DRCC', 'DRCCCDGO,DRCCCLLR,DRCCCLPR,DRCCCLSC,DRCCDSCR,DRCCFCIN,DRCCIDST,DRCCLNGT,DRCCLTTD,DRCCNMRO,DRCCPRDF,DRCCRFRN,DRCCTLFN,DRCCTRBJ,DRCCUSIN,ENTDCDGO,PRRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DRTR', 'DRCCCDGO,DRTRCDGO,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DCMN', 'DCMNCDGO,DCMNCNTD,DCMNFCIN,DCMNIDST,DCMNOPCN,DCMNUSIN,FLLLCDGO,TPDJCDGO,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ENTD', 'ENTDBSQD,ENTDCDGO,ENTDCIVR,ENTDCPVR,ENTDCRIN,ENTDCRPR,ENTDFCIN,ENTDFCMD,ENTDFCNC,ENTDIDCD,ENTDIDST,ENTDIPIN,ENTDIPMD,ENTDMGRD,ENTDMVLI,ENTDNMCF,ENTDNMCM,ENTDNMID,ENTDPRSM,ENTDRLPC,ENTDRZNS,ENTDSCPB,ENTDTLFN,ENTDTLVR,ENTDURFL,ENTDUSIN,ENTDUSMD,ESCVCDGO,FLLLCDGO,TPDNCDGO,TPHDCDGO,TPVVCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCS', 'ESCSCDGO,ESCSDSCR,ESCSIDST' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCV', 'ESCVCAUX,ESCVCDGO,ESCVIDST,ESCVNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCP', 'ESCPCDAL,ESCPCDGO,ESCPESTD,ESCPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESPR', 'ESPRCDEX,ESPRCDGO,ESPRIDST,ESPRNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESPS', 'ESPSCDEX,ESPSCDGO,ESPSIDST,ESPSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'EVPR', 'EVPRCDGO,EVPRCTAA,EVPRCTNN,EVPRESTD,EVPRFCAN,EVPRFCHA,EVPRFCRG,EVPRMDLD,EVPRMTAN,EVPRNMAS,EVPROBSR,EVPRPLZA,EVPRPLZN,EVPRTPOO,EVPRUSAN,EVPRUSAR,EVPRVLRR,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'EXTR', 'EXTRCDLA,EXTRCLL1,EXTRCLL2,EXTRCNTN,EXTRCREX,EXTRCRIE,EXTRCRIN,EXTRCRPR,EXTRDSPN,EXTREDDD,EXTRESCV,EXTRESTD,EXTRFCDF,EXTRFCNC,EXTRGNRO,EXTRMVLL,EXTRNCNL,EXTRNMBR,EXTRNVES,EXTRPRFS,EXTRPRVN,EXTRSLFJ,EXTRSLTT,EXTRSLVR,EXTRSMCI,EXTRSMSC,EXTRTLFN,EXTRTLIE' FROM DUAL
UNION ALL SELECT 'CRD', 'FLLL', 'FLLLCDAL,FLLLCDGO,FLLLIDST,FLLLNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'GNAP', 'FLLLCDGO,GNAPANPE,GNAPCDGO,GNAPESTD,GNAPFCDS,GNAPFCEN,GNAPFCGN,GNAPFCIN,GNAPFCMD,GNAPFCPR,GNAPMSPE,GNAPMTEN,GNAPNMAR,GNAPOBSR,GNAPRTAA,GNAPTLRG,GNAPUSDS,GNAPUSGN,GNAPUSIN,GNAPUSMD' FROM DUAL
UNION ALL SELECT 'CRD', 'HDTP', 'DTPRABNO,DTPRCDEX,DTPRCDGO,DTPRCPPG,DTPRCPTL,DTPRCTAA,DTPRDSDF,DTPRDSFR,DTPRDSGR,DTPRDSMR,DTPRDSOR,DTPRDSPG,DTPRESTD,DTPRFCPG,DTPRFCRG,DTPRFCVN,DTPRIDST,DTPRINPG,DTPRINTR,DTPRINVN,DTPRINVP,DTPRMRAA,DTPRMRCL,DTPRMRPG,DTPRNMCT,DTPROTSG,DTPRSICP,DTPRSLCP,DTPRSLDO,DTPRSLIN,DTPRSLIV,DTPRSLMR,DTPRSLOT,DTPRTTCS,DTPRTTLL,DTPRUSRG,DTPRVLDF,DTPRVLSI,EVPRCDGO,HDTPCDGO,HDTPFCRG,HDTPMTVO,HDTPUSAR,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'HSTR', 'ENTDCDGO,HSTRCDGO,HSTRESTD,HSTRFCIN,HSTRMNAA,HSTRMNAC,HSTRMNAJ,HSTRPRCN,HSTRPRJB,HSTRSLDO,HSTRUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'HDAP', 'HDAPCEDU,HDAPCESA,HDAPCODI,HDAPDSCT,HDAPEMER,HDAPESTD,HDAPFCTR,HDAPHIPO,HDAPIDCA,HDAPINCE,HDAPJUBI,HDAPORDE,HDAPPREN,HDAPQUIR,HDAPTOBE,HDAPTONS,HDAPTOPR,HDAPUSAR,HDAPVEHI' FROM DUAL
UNION ALL SELECT 'CRD', 'HPCS', 'HPCSCDGO,HPCSCEDU,HPCSFCHP,HPCSFCRG,HPCSOBSV,HPCSTIPC,HPCSUSRG,HPCSVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'IGFN', 'IGFNCDGO,IGFNCEFD,IGFNCMNM,IGFNCNTN,IGFNDRCC,IGFNESTD,IGFNFCMD,IGFNFCRS,IGFNFCTR,IGFNFRCE,IGFNIDFC,IGFNNMRS,IGFNNRCE,IGFNPAPC,IGFNPAPJ,IGFNPARC,IGFNPARJ,IGFNPRVN,IGFNTIDF,IGFNTLFN,IGFNTPAD,IGFNTPAP,IGFNTPFC,IGFNTPPR,IGFNTPSS,IGFNUSRM,IGFNVARC,IGFNVARJ' FROM DUAL
UNION ALL SELECT 'CRD', 'MTDP', 'MTDPCDGO,MTDPCSBC,MTDPIDST,MTDPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'MRPR', 'MRPRCDGO,MRPRDSMN,MRPRDSMX,MRPRPRMR,MRPRTSAN,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'MTVP', 'MTVPCDGO,MTVPIDST,MTVPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'NVLS', 'NVLSCDGO,NVLSIDST,NVLSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'NVPC', 'NVPCCDCA,NVPCCDCT,NVPCCDGO,NVPCCDPR,NVPCCDPS,NVPCDSCR,NVPCESTD,NVPCIASP,NVPCMNDF,NVPCMNES,NVPCMNRC,NVPCTPNV,PXCACDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'OAVP', 'OAVPCDGO,OAVPESTD,OAVPNMBR,OAVPORDN' FROM DUAL
UNION ALL SELECT 'CRD', 'PGAP', 'APRTCDGO,FLLLCDGO,PGAPCDGO,PGAPCNCP,PGAPFCCN,PGAPFCPG,PGAPFCRG,PGAPIDST,PGAPNMAS,PGAPRFPG,PGAPRTRS,PGAPUSRG,PGAPVLRR,PGPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PGPR', 'CRARCDGO,DTPRCDGO,EVPRCDGO,PGPRANUL,PGPRASNT,PGPRCDGO,PGPRCPPG,PGPRDSGR,PGPRESTD,PGPRFCAN,PGPRFCHA,PGPRFCRG,PGPRIDST,PGPRINPG,PGPRINVP,PGPRMRPG,PGPRMTAN,PGPRNMCT,PGPROBSR,PGPRRTRS,PGPRSLOT,PGPRTPOO,PGPRUSAN,PGPRUSRG,PGPRVLRR,PGPRVLSI,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRRQ', 'CDDDCDGO,PRRQCDEX,PRRQCDGO,PRRQFCIN,PRRQIDST,PRRQNMBR,PRRQUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'PRTC', 'ENTDCDGO,PRTCCDAL,PRTCCDGO,PRTCCRGA,PRTCCSFL,PRTCESAC,PRTCESCS,PRTCFCHF,PRTCFCIF,PRTCFCIN,PRTCFCIT,PRTCFCSL,PRTCIAAC,PRTCIAMM,PRTCIDST,PRTCLGRT,PRTCMTSL,PRTCNVES,PRTCRMUN,PRTCUNAD,TPAPCDGO,TPCLCDGO,TPPCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRAS', 'PRASAPLL,PRASBNCO,PRASCDDD,PRASCDGA,PRASCDGF,PRASCDLA,PRASCDLG,PRASCNTD,PRASCRGO,PRASCRRE,PRASCTAB,PRASDRCD,PRASFCCS,PRASFCHN,PRASFCIN,PRASFCJB,PRASFCJC,PRASFCSN,PRASGNRO,PRASIDDD,PRASLCCN,PRASNDAD,PRASNMBR,PRASNSTT,PRASPRQD,PRASPRVD,PRASRGMN,PRASRGNN,PRASSTDC,PRASSTDP,PRASTLFC,PRASTLFD,PRASTLFT,PRASTPCB' FROM DUAL
UNION ALL SELECT 'CRD', 'PDGA', 'DTGACDGO,ENTDCDGO,PDGACDGO,PDGACDPT,PDGAESTD,PDGAFCDC,PDGAFCIN,PDGAFCMD,PDGAMNDC,PDGAMNEN,PDGANNLN,PDGAOBSR,PDGARLPC,PDGAUSIN,PDGAUSMD,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PXCA', 'DTCACDGO,PXCACDGO,PXCACDPT,PXCACPDS,PXCACPND,PXCADSCT,PXCADSDO,PXCADSND,PXCAESRV,PXCAESTD,PXCAINAN,PXCAINDS,PXCAITND,PXCAMSPL,PXCANMBR,PXCANVCA,PXCANVFN,PXCAPLIN,PXCASGDS,PXCASLAC,PXCAVLSG' FROM DUAL
UNION ALL SELECT 'CRD', 'PREC', 'ENTDCDGO,PRECCDGO,PRECFCAC,PRECFCIT,PRECFCRG,PRECFCRT,PRECGSMS,PRECIDST,PRECOROI,PRECOTIN,PRECPRDO,PRECPTNT,PRECSLFJ,PRECSLNT,PRECSLVR,PRECTTAC,PRECTTBN,PRECTTDD,PRECTTIN,PRECTTOA,PRECTTVH,PRECUSRG,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRSN', 'FLLLCDGO,PRSNAPLL,PRSNCDGO,PRSNESCV,PRSNFCIN,PRSNGNRO,PRSNIDST,PRSNNMBR,PRSNUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'PRST', 'ENTDCDGO,ESPSCDGO,FLLLCDGO,MTVPCDGO,PRDCCDGO,PRSTAJAP,PRSTAMRT,PRSTCDGO,PRSTDSVN,PRSTESNV,PRSTESOP,PRSTFCAC,PRSTFCAD,PRSTFCAP,PRSTFCFN,PRSTFCHA,PRSTFCIN,PRSTFCLG,PRSTFCMD,PRSTFCRC,PRSTFCRG,PRSTFRTT,PRSTIDAS,PRSTIDST,PRSTINNM,PRSTINVR,PRSTMNLD,PRSTMNNV,PRSTMNSL,PRSTMRCL,PRSTMSCB,PRSTOBSR,PRSTPLZO,PRSTPRIN,PRSTRFNN,PRSTRPRC,PRSTRSTR,PRSTSLCP,PRSTSLIN,PRSTSLOT,PRSTSLTT,PRSTSLVN,PRSTSLXV,PRSTTPAM,PRSTTSAA,PRSTTSEF,PRSTTSIN,PRSTTSNM,PRSTTTCP,PRSTTTIN,PRSTTTIV,PRSTTTMR,PRSTTTPG,PRSTTTPR,PRSTTTSG,PRSTUSAC,PRSTUSAP,PRSTUSLG,PRSTUSMD,PRSTUSRC,PRSTUSRG,PRSTVLAS,PRSTVLCT' FROM DUAL
UNION ALL SELECT 'CRD', 'PRCA', 'PRCACDGO,PRCAERRO,PRCAESDQ,PRCAESTD,PRCAFCPR,PRCAFCRG,PRCAIDAP,PRCAIDCT,PRCAIDPG,PRCAIDPS,PRCANVPR,PRCAOBSR,PRCAPRCS,PRCASLCP,PRCASLIN,PRCAUSRG,PXCACDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRDC', 'FLLLCDGO,PRDCCDEX,PRDCCDGO,PRDCCDPT,PRDCCSPB,PRDCESTD,PRDCFCMD,PRDCFCRG,PRDCIPMD,PRDCIPRG,PRDCNMBR,PRDCUSMD,PRDCUSRG,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRFS', 'PRFSCDGO,PRFSCSBC,PRFSIDST,PRFSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'PRVN', 'PRVNCDAL,PRVNCDEX,PRVNCDGO,PRVNIDST,PRVNNMBR,PSSSCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'RRFF', 'ENTDCDGO,RRFFCDGO,RRFFCDLA,RRFFCNTC,RRFFIDST,RRFFNMBR,RRFFPRNT' FROM DUAL
UNION ALL SELECT 'CRD', 'RRPP', 'ENTDCDGO,RRPPCDGO,RRPPCDLA,RRPPCNTC,RRPPIDST,RRPPNMBR,RRPPPRNT' FROM DUAL
UNION ALL SELECT 'CRD', 'RLPR', 'PRSTCDGH,PRSTCDGP,RLPRCDGO,RLPRFCRG,RLPRIDST,RLPRTPPR,RLPRUSRG' FROM DUAL
UNION ALL SELECT 'CRD', 'RQPR', 'PRSTCDGO,RQPRALRT,RQPRCDGO,RQPRDSCR,RQPRESTD,RQPRFCRG,RQPROBSR,RQPRUSRG,RQPRVLDO,TPRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'TSPR', 'PRDCCDGO,TSPRCDGO,TSPRCSBC,TSPRIDST,TSPRMNMN,TSPRMNMX,TSPRNMBR,TSPRPLMN,TSPRPLMX,TSPRTSEF,TSPRTSNM' FROM DUAL
UNION ALL SELECT 'CRD', 'TPDJ', 'TPDJCDGO,TPDJIDST,TPDJNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPAP', 'TPAPCDGO,TPAPCSBC,TPAPIDST,TPAPNMBR,TPAPPRDP' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCL', 'TPCLCDGO,TPCLCSPB,TPCLCTGR,TPCLIDST,TPCLNMBR,TPCLPRVS' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCS', 'TPCSCDGO,TPCSCSPB,TPCSIDST,TPCSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCN', 'TPCNCDGO,TPCNCSPB,TPCNIDST,TPCNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPGN', 'TPGNCDEX,TPGNCDGO,TPGNIDST,TPGNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPHD', 'ENTDCDGO,TPHDCDEX,TPHDCDGO,TPHDIDST' FROM DUAL
UNION ALL SELECT 'CRD', 'TPDN', 'TPDNCDGO,TPDNIDST,TPDNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPG', 'TPPGCDGO,TPPGCSPB,TPPGIDST,TPPGNMBR,TPPGOBSR,TPPGTPOO' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPC', 'TPPCCDGO,TPPCCSPB,TPPCIDST,TPPCNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPR', 'TPPRCDGO,TPPRCSPB,TPPRIDST,TPPRNMBR,TPPRTPOO,TPPRTSAA' FROM DUAL
UNION ALL SELECT 'CRD', 'TPRQ', 'TPRQCDGO,TPRQESTD,TPRQNMBR,TPRQVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPVV', 'TPVVCDGO,TPVVIDST,TPVVNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TRAS', 'TRASCNCP,TRASCNTA,TRASCRRR,TRASDBBB,TRASDFRN,TRASFCHD,TRASFCHP,TRASSLDA,TRASSLDC,TRASSLDN,TRASTRRR,TRASTTLC,TRASTTLD' FROM DUAL
UNION ALL SELECT 'CRD', 'TRCR', 'BEXTCDGO,BNCOCDGO,CNBCCDGO,CRARCDGO,TRCRCDGO,TRCRCTOR,TRCRFCHA,TRCRFCRG,TRCRIDST,TRCRIPRG,TRCRNMRO,TRCROBSR,TRCRUSRG,TRCRVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'VPPC', 'ENTDCDGO,VPPCCDGO,VPPCCFMD,VPPCFCRG,VPPCIDST,VPPCNMCT,VPPCTNPR,VPPCUSMD,VPPCUSRG,VPPCVLRR,VPPCVLSR' FROM DUAL
UNION ALL SELECT 'CRD', 'VGCN', 'CNTRCDGO,TPAPCDGO,VGCNCDGO,VGCNFCFN,VGCNFCIN,VGCNFCRG,VGCNIDHS,VGCNIDST,VGCNMNTO,VGCNMODO,VGCNOBSR,VGCNPRCN,VGCNRMUN,VGCNUSRG' FROM DUAL
)
-- =====================================================================
-- CONSULTA A — tablas mapeadas que NO existen en la base. Esperado: 0 filas
-- (en produccion, hasta que se corra su DDL, ACCN y DACC son las esperadas).
-- =====================================================================
SELECT e.OWNER_ESP AS ESQUEMA, e.TABLA_ESP AS TABLA, 'TABLA NO EXISTE' AS PROBLEMA
FROM   ESPERADO e
WHERE  NOT EXISTS (SELECT 1 FROM ALL_TABLES t
                   WHERE t.OWNER = e.OWNER_ESP AND t.TABLE_NAME = e.TABLA_ESP)
ORDER  BY 1, 2;

-- =====================================================================
-- CONSULTA B — columnas mapeadas que FALTAN, solo en tablas que si existen.
-- Esperado: 0 filas. Cada fila es un ORA-00904 esperando el despliegue.
-- =====================================================================
WITH ESPERADO AS (
SELECT 'CRD' AS OWNER_ESP, 'ACCN' AS TABLA_ESP, 'ACCNCDGO,ACCNESTD,ACCNFCAP,ACCNFCHA,ACCNFCRC,ACCNFCRG,ACCNMTRC,ACCNOBSR,ACCNUSAP,ACCNUSRC,ACCNUSRG,ACCNVLCN,ACCNVLPG,CBCRCDGO,ENTDCDGO,EVPRCDGO,PRSTCDGO' AS COLS FROM DUAL
UNION ALL SELECT 'CRD', 'ADJN', 'ADJNCDGO,ADJNFCRG,ADJNIDRF,ADJNIDST,ADJNISCA,ADJNMMTY,ADJNNMAR,ADJNOBSR,ADJNURLA,ADJNUSRG,ENTDCDGO,PRSTCDGO,TPDJCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'AVPC', 'AVPCCDGO,AVPCCPAF,AVPCDFCP,AVPCDFDG,AVPCDFIN,AVPCDFTL,AVPCDGAF,AVPCESTD,AVPCFCAF,AVPCFCRG,AVPCINAF,AVPCOBSR,AVPCUSAR,AVPCVAFA,AVPCVLCP,AVPCVLCT,AVPCVLDG,AVPCVLIN,DTPRCDGO,NVPCCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'APRT', 'APRTCDGO,APRTFCRG,APRTFCTR,APRTGLSA,APRTIDAS,APRTIDDV,APRTIDST,APRTPRDV,APRTSLDO,APRTTPMV,APRTUSRG,APRTVLPG,APRTVLRR,CNTRCDGO,CRARCDGO,ENTDCDGO,FLLLCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'APAS', 'APASACML,APASACTP,APASCLNT,APASCNTA,APASCRDP,APASFCHA,APASFCHC,APASFCHL,APASFCHM,APASFCHP,APASFCHR,APASFCHV,APASNMAP,APASNMRC,APASNMSL,APASNSTT,APASOBSR,APASPRDT,APASRGMN,APASSLDA,APASSLDC,APASSLDI,APASSTDO,APASTPLQ,APASVLRA' FROM DUAL
UNION ALL SELECT 'CRD', 'ANCP', 'ANCPASNT,ANCPCDGO,ANCPCNTD,ANCPFCHA,ANCPFCRG,ANCPIDST,ANCPIPRG,ANCPNMAS,ANCPOBSR,ANCPTPOO,ANCPUSRG,ANCPVLRR,CRARCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ANCC', 'ANCCASNT,ANCCCDGO,ANCCCNTD,ANCCESTD,ANCCFCHA,ANCCFCMD,ANCCFCRG,ANCCIDST,ANCCIPMD,ANCCIPRG,ANCCNMAS,ANCCTPOO,ANCCUSMD,ANCCUSRG,ANCCVLRR,CRCTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ADTR', 'ADTRACCN,ADTRAGNT,ADTRCDGO,ADTRFCHA,ADTRFCIN,ADTRIPCL,ADTRMDLO,ADTRNMNA,ADTRNMNN,ADTRNTDD,ADTRNTID,ADTRRLL,ADTRRSN,ADTRSSTM,ADTRUSRO,ADTRVLNA,ADTRVLNN' FROM DUAL
UNION ALL SELECT 'CRD', 'BDCC', 'BDCCCDGO,BDCCCNTD,BDCCCPTL,BDCCESTD,BDCCFCMD,BDCCFCRG,BDCCIPMD,BDCCIPRG,BDCCNMRO,BDCCTPCR,BDCCUSMD,BDCCUSRG,BNDPCDGO,CRCTCDGO,PLNNCDGO,PRDCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BNDP', 'BNDPCDGO,BNDPCNTD,BNDPESTD,BNDPFCMD,BNDPFCRG,BNDPIPMD,BNDPIPRG,BNDPNMRO,BNDPUSMD,BNDPUSRG,CBPRCDGO,PLNNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BIPR', 'BIPRCSNP,BIPRCSPR,BIPRCSRV,BIPRIDSA,BIPRJBPR,BIPRJBPT,BIPRJBRV,BIPRNMBR,BIPRNMCD,BIPRNMRO,BIPRPNSN,BIPRRNCP,BIPRRNJP,BIPRRNJR,BIPRRNPS,BIPRTTLG' FROM DUAL
UNION ALL SELECT 'CRD', 'BPRF', 'BPRFCDGO,BPRFFCHR,BPRFIDNT,BPRFIDST,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'BTPC', 'BTPCCDGO,BTPCIDPC,BTPCIDST,BTPCNMBR,BTPCNMRP' FROM DUAL
UNION ALL SELECT 'CRD', 'CMBP', 'CMBPCDGO,CMBPESAC,CMBPESTD,CMBPESWB,CMBPFCAP,CMBPFCIN,CMBPFCSL,CMBPPRCS,CMBPPRJB,CMBPSLDO,CMBPUSIN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNTN', 'CNTNCDGO,CNTNCDGX,CNTNIDST,CNTNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'CRAR', 'CRARANAF,CRARCDGO,CRARESTD,CRARFCAC,CRARFCAN,CRARFCCR,CRARMSAF,CRARMTAN,CRARNMBR,CRARNMTF,CRARRTAS,CRARTCND,CRARTDND,CRARTIND,CRARTTCD,CRARTTDO,CRARTTDS,CRARTTIA,CRARTTID,CRARTTSA,CRARTTSD,CRARTTVS,CRARUSAN,CRARUSCC,CRARUSCD,FLLLCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRTF', 'CRTFANIO,CRTFCDGO,CRTFCLDD,CRTFDTOS,CRTFESTD,CRTFFCAN,CRTFFCEM,CRTFFCRG,CRTFMTAN,CRTFNMAL,CRTFNMRO,CRTFPDFF,CRTFTPCR,CRTFUSAN,CRTFUSEM,ENTDCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CSNT', 'CSNTAPDS,CSNTCDGO,CSNTESFL,CSNTESTD,CSNTFCEC,CSNTFCHA,CSNTFCLQ,CSNTFCRG,CSNTFCSL,CSNTIDSL,CSNTIDST,CSNTSLCB,CSNTSLPG,CSNTTTEG,CSNTTTIN,CSNTUSRG,CSNTVLDS,CSNTVLPG,ENTDCDGO,TPCSCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CDDD', 'CDDDCDAL,CDDDCDEX,CDDDCDGO,CDDDFCIN,CDDDIDST,CDDDNMBR,CDDDUSIN,PRVNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CBCR', 'CBCRASN1,CBCRASN2,CBCRCDGO,CBCRESTD,CBCRFCAN,CBCRFCAP,CBCRFCHA,CBCRFCPR,CBCRFCRC,CBCRFCRG,CBCRMTAN,CBCRMTRC,CBCROBSR,CBCRRFRN,CBCRRTRS,CBCRTPOO,CBCRUSAN,CBCRUSAP,CBCRUSPR,CBCRUSRC,CBCRUSRG,CBCRVLRR,CNBCCDGO,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CMNT', 'CMNTCDGO,CMNTESTD,CMNTFCHA,CMNTFNCN,CMNTIDST,CMNTOBSR,ENTDCDGO,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CBPR', 'CBPRCDGO,CBPRESTD,CBPRFCFN,CBPRFCIN,CBPRFCMD,CBPRFCRG,CBPRIPMD,CBPRIPRG,CBPRTPCR,CBPRUSMD,CBPRUSRG,PJRQCDGO,PRDCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNTR', 'CNTRCDGO,CNTRESTD,CNTRFCAP,CNTRFCIN,CNTRFCRG,CNTRFCRP,CNTRFCTR,CNTRIDST,CNTRMNAA,CNTRMNAC,CNTRMNAJ,CNTRMTTR,CNTROBSR,CNTRPRAI,CNTRPRAJ,CNTRUSAP,CNTRUSRG,ENTDCDGO,FLLLCDGO,TPCNCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CNYG', 'CNYGCDGO,CNYGCDLA,CNYGCRREO,CNYGIDST,CNYGNMBR,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRCT', 'CRCTANOO,CRCTCDGO,CRCTESTD,CRCTFCCR,CRCTFCMD,CRCTFCPR,CRCTFCRG,CRCTIDST,CRCTIPMD,CRCTIPRG,CRCTMESS,CRCTOBSR,CRCTUSMD,CRCTUSRG,PJRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CRDT', 'CRDTCDGO,CRDTIDPR,CRDTIDST,CRDTMNMN,CRDTMNMX' FROM DUAL
UNION ALL SELECT 'CRD', 'CNBP', 'BEXTCDGO,CNBPCDGO,CNBPIDST,CNBPNMRO,CNBPTPCN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXPG', 'CXPGCDGO,CXPGFCIN,CXPGFCMD,CXPGNNCT,CXPGUSIN,CXPGUSMD,CXPGVLCT,PDGACDGO,PRSTCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXCK', 'CXCKCDGO,CXCKCNCP,CXCKFCCR,CXCKIDCN,CXCKIDTR,CXCKSLAC,CXCKTTCR,CXCKTTDB,CXCPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'CXCP', 'CXCPCDGO,CXCPFCHC,CXCPIDCL,CXCPIDCN,CXCPSLCN,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTSP', 'DTSPCDGO,DTSPESTD,DTSPFCRG,DTSPOTIE,DTSPOTIR,DTSPTTEG,DTSPTTSL,DTSPUSRG,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DACC', 'ACCNCDGO,DACCCDGO,DACCCPTO,DACCVLAD,DACCVLCN,DACCVLPG' FROM DUAL
UNION ALL SELECT 'CRD', 'DTCA', 'CRARCDGO,DTCACDGO,DTCACDPP,DTCAESTD,DTCANMPP,DTCATCND,DTCATDND,DTCATIND,DTCATPXP,DTCATTCD,DTCATTDO,DTCATTDS,DTCATTIA,DTCATTID,DTCATTSA,DTCATTSD,DTCATTVS' FROM DUAL
UNION ALL SELECT 'CRD', 'DCBC', 'ACCNCDGO,CBCRCDGO,DCBCCDGO,DCBCMDLD,DCBCOBSR,DCBCPRDV,DCBCVLRR,EVPRCDGO,PGAPCDGO,PRSTCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DDVA', 'DDVAAPRT,DDVAAPRV,DDVACDGO,DDVAPGAP,DDVAVLRR,DVAPCDGO,TPAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTGA', 'DTGACDGO,DTGACDPT,DTGADSCR,DTGAFCIN,DTGAFCMD,DTGAMNTO,DTGATLRG,DTGAUSIN,DTGAUSMD,GNAPCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DTPR', 'DTPRABNO,DTPRCDEX,DTPRCDGO,DTPRCPPG,DTPRCPTL,DTPRCTAA,DTPRDSDF,DTPRDSFR,DTPRDSGR,DTPRDSMR,DTPRDSOR,DTPRDSPG,DTPRESTD,DTPRFCPG,DTPRFCRG,DTPRFCVN,DTPRIDST,DTPRINPG,DTPRINTR,DTPRINVN,DTPRINVP,DTPRMRAA,DTPRMRCL,DTPRMRPG,DTPRNMCT,DTPROTSG,DTPRSICP,DTPRSLCP,DTPRSLDO,DTPRSLIN,DTPRSLIV,DTPRSLMR,DTPRSLOT,DTPRTTCS,DTPRTTLL,DTPRUSRG,DTPRVLDF,DTPRVLSI,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DVAP', 'CNBPCDGO,DVAPCDGO,DVAPESTD,DVAPFCAN,DVAPFCHA,DVAPFCPG,DVAPFCRG,DVAPIDEM,DVAPIDPG,DVAPMTAN,DVAPMTVO,DVAPNMAS,DVAPUSAN,DVAPUSRG,DVAPVLRR,ENTDCDGO,FLLLCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DRCC', 'DRCCCDGO,DRCCCLLR,DRCCCLPR,DRCCCLSC,DRCCDSCR,DRCCFCIN,DRCCIDST,DRCCLNGT,DRCCLTTD,DRCCNMRO,DRCCPRDF,DRCCRFRN,DRCCTLFN,DRCCTRBJ,DRCCUSIN,ENTDCDGO,PRRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DRTR', 'DRCCCDGO,DRTRCDGO,ENTDCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'DCMN', 'DCMNCDGO,DCMNCNTD,DCMNFCIN,DCMNIDST,DCMNOPCN,DCMNUSIN,FLLLCDGO,TPDJCDGO,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ENTD', 'ENTDBSQD,ENTDCDGO,ENTDCIVR,ENTDCPVR,ENTDCRIN,ENTDCRPR,ENTDFCIN,ENTDFCMD,ENTDFCNC,ENTDIDCD,ENTDIDST,ENTDIPIN,ENTDIPMD,ENTDMGRD,ENTDMVLI,ENTDNMCF,ENTDNMCM,ENTDNMID,ENTDPRSM,ENTDRLPC,ENTDRZNS,ENTDSCPB,ENTDTLFN,ENTDTLVR,ENTDURFL,ENTDUSIN,ENTDUSMD,ESCVCDGO,FLLLCDGO,TPDNCDGO,TPHDCDGO,TPVVCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCS', 'ESCSCDGO,ESCSDSCR,ESCSIDST' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCV', 'ESCVCAUX,ESCVCDGO,ESCVIDST,ESCVNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESCP', 'ESCPCDAL,ESCPCDGO,ESCPESTD,ESCPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESPR', 'ESPRCDEX,ESPRCDGO,ESPRIDST,ESPRNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'ESPS', 'ESPSCDEX,ESPSCDGO,ESPSIDST,ESPSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'EVPR', 'EVPRCDGO,EVPRCTAA,EVPRCTNN,EVPRESTD,EVPRFCAN,EVPRFCHA,EVPRFCRG,EVPRMDLD,EVPRMTAN,EVPRNMAS,EVPROBSR,EVPRPLZA,EVPRPLZN,EVPRTPOO,EVPRUSAN,EVPRUSAR,EVPRVLRR,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'EXTR', 'EXTRCDLA,EXTRCLL1,EXTRCLL2,EXTRCNTN,EXTRCREX,EXTRCRIE,EXTRCRIN,EXTRCRPR,EXTRDSPN,EXTREDDD,EXTRESCV,EXTRESTD,EXTRFCDF,EXTRFCNC,EXTRGNRO,EXTRMVLL,EXTRNCNL,EXTRNMBR,EXTRNVES,EXTRPRFS,EXTRPRVN,EXTRSLFJ,EXTRSLTT,EXTRSLVR,EXTRSMCI,EXTRSMSC,EXTRTLFN,EXTRTLIE' FROM DUAL
UNION ALL SELECT 'CRD', 'FLLL', 'FLLLCDAL,FLLLCDGO,FLLLIDST,FLLLNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'GNAP', 'FLLLCDGO,GNAPANPE,GNAPCDGO,GNAPESTD,GNAPFCDS,GNAPFCEN,GNAPFCGN,GNAPFCIN,GNAPFCMD,GNAPFCPR,GNAPMSPE,GNAPMTEN,GNAPNMAR,GNAPOBSR,GNAPRTAA,GNAPTLRG,GNAPUSDS,GNAPUSGN,GNAPUSIN,GNAPUSMD' FROM DUAL
UNION ALL SELECT 'CRD', 'HDTP', 'DTPRABNO,DTPRCDEX,DTPRCDGO,DTPRCPPG,DTPRCPTL,DTPRCTAA,DTPRDSDF,DTPRDSFR,DTPRDSGR,DTPRDSMR,DTPRDSOR,DTPRDSPG,DTPRESTD,DTPRFCPG,DTPRFCRG,DTPRFCVN,DTPRIDST,DTPRINPG,DTPRINTR,DTPRINVN,DTPRINVP,DTPRMRAA,DTPRMRCL,DTPRMRPG,DTPRNMCT,DTPROTSG,DTPRSICP,DTPRSLCP,DTPRSLDO,DTPRSLIN,DTPRSLIV,DTPRSLMR,DTPRSLOT,DTPRTTCS,DTPRTTLL,DTPRUSRG,DTPRVLDF,DTPRVLSI,EVPRCDGO,HDTPCDGO,HDTPFCRG,HDTPMTVO,HDTPUSAR,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'HSTR', 'ENTDCDGO,HSTRCDGO,HSTRESTD,HSTRFCIN,HSTRMNAA,HSTRMNAC,HSTRMNAJ,HSTRPRCN,HSTRPRJB,HSTRSLDO,HSTRUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'HDAP', 'HDAPCEDU,HDAPCESA,HDAPCODI,HDAPDSCT,HDAPEMER,HDAPESTD,HDAPFCTR,HDAPHIPO,HDAPIDCA,HDAPINCE,HDAPJUBI,HDAPORDE,HDAPPREN,HDAPQUIR,HDAPTOBE,HDAPTONS,HDAPTOPR,HDAPUSAR,HDAPVEHI' FROM DUAL
UNION ALL SELECT 'CRD', 'HPCS', 'HPCSCDGO,HPCSCEDU,HPCSFCHP,HPCSFCRG,HPCSOBSV,HPCSTIPC,HPCSUSRG,HPCSVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'IGFN', 'IGFNCDGO,IGFNCEFD,IGFNCMNM,IGFNCNTN,IGFNDRCC,IGFNESTD,IGFNFCMD,IGFNFCRS,IGFNFCTR,IGFNFRCE,IGFNIDFC,IGFNNMRS,IGFNNRCE,IGFNPAPC,IGFNPAPJ,IGFNPARC,IGFNPARJ,IGFNPRVN,IGFNTIDF,IGFNTLFN,IGFNTPAD,IGFNTPAP,IGFNTPFC,IGFNTPPR,IGFNTPSS,IGFNUSRM,IGFNVARC,IGFNVARJ' FROM DUAL
UNION ALL SELECT 'CRD', 'MTDP', 'MTDPCDGO,MTDPCSBC,MTDPIDST,MTDPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'MRPR', 'MRPRCDGO,MRPRDSMN,MRPRDSMX,MRPRPRMR,MRPRTSAN,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'MTVP', 'MTVPCDGO,MTVPIDST,MTVPNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'NVLS', 'NVLSCDGO,NVLSIDST,NVLSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'NVPC', 'NVPCCDCA,NVPCCDCT,NVPCCDGO,NVPCCDPR,NVPCCDPS,NVPCDSCR,NVPCESTD,NVPCIASP,NVPCMNDF,NVPCMNES,NVPCMNRC,NVPCTPNV,PXCACDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'OAVP', 'OAVPCDGO,OAVPESTD,OAVPNMBR,OAVPORDN' FROM DUAL
UNION ALL SELECT 'CRD', 'PGAP', 'APRTCDGO,FLLLCDGO,PGAPCDGO,PGAPCNCP,PGAPFCCN,PGAPFCPG,PGAPFCRG,PGAPIDST,PGAPNMAS,PGAPRFPG,PGAPRTRS,PGAPUSRG,PGAPVLRR,PGPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PGPR', 'CRARCDGO,DTPRCDGO,EVPRCDGO,PGPRANUL,PGPRASNT,PGPRCDGO,PGPRCPPG,PGPRDSGR,PGPRESTD,PGPRFCAN,PGPRFCHA,PGPRFCRG,PGPRIDST,PGPRINPG,PGPRINVP,PGPRMRPG,PGPRMTAN,PGPRNMCT,PGPROBSR,PGPRRTRS,PGPRSLOT,PGPRTPOO,PGPRUSAN,PGPRUSRG,PGPRVLRR,PGPRVLSI,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRRQ', 'CDDDCDGO,PRRQCDEX,PRRQCDGO,PRRQFCIN,PRRQIDST,PRRQNMBR,PRRQUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'PRTC', 'ENTDCDGO,PRTCCDAL,PRTCCDGO,PRTCCRGA,PRTCCSFL,PRTCESAC,PRTCESCS,PRTCFCHF,PRTCFCIF,PRTCFCIN,PRTCFCIT,PRTCFCSL,PRTCIAAC,PRTCIAMM,PRTCIDST,PRTCLGRT,PRTCMTSL,PRTCNVES,PRTCRMUN,PRTCUNAD,TPAPCDGO,TPCLCDGO,TPPCCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRAS', 'PRASAPLL,PRASBNCO,PRASCDDD,PRASCDGA,PRASCDGF,PRASCDLA,PRASCDLG,PRASCNTD,PRASCRGO,PRASCRRE,PRASCTAB,PRASDRCD,PRASFCCS,PRASFCHN,PRASFCIN,PRASFCJB,PRASFCJC,PRASFCSN,PRASGNRO,PRASIDDD,PRASLCCN,PRASNDAD,PRASNMBR,PRASNSTT,PRASPRQD,PRASPRVD,PRASRGMN,PRASRGNN,PRASSTDC,PRASSTDP,PRASTLFC,PRASTLFD,PRASTLFT,PRASTPCB' FROM DUAL
UNION ALL SELECT 'CRD', 'PDGA', 'DTGACDGO,ENTDCDGO,PDGACDGO,PDGACDPT,PDGAESTD,PDGAFCDC,PDGAFCIN,PDGAFCMD,PDGAMNDC,PDGAMNEN,PDGANNLN,PDGAOBSR,PDGARLPC,PDGAUSIN,PDGAUSMD,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PXCA', 'DTCACDGO,PXCACDGO,PXCACDPT,PXCACPDS,PXCACPND,PXCADSCT,PXCADSDO,PXCADSND,PXCAESRV,PXCAESTD,PXCAINAN,PXCAINDS,PXCAITND,PXCAMSPL,PXCANMBR,PXCANVCA,PXCANVFN,PXCAPLIN,PXCASGDS,PXCASLAC,PXCAVLSG' FROM DUAL
UNION ALL SELECT 'CRD', 'PREC', 'ENTDCDGO,PRECCDGO,PRECFCAC,PRECFCIT,PRECFCRG,PRECFCRT,PRECGSMS,PRECIDST,PRECOROI,PRECOTIN,PRECPRDO,PRECPTNT,PRECSLFJ,PRECSLNT,PRECSLVR,PRECTTAC,PRECTTBN,PRECTTDD,PRECTTIN,PRECTTOA,PRECTTVH,PRECUSRG,PRSTCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRSN', 'FLLLCDGO,PRSNAPLL,PRSNCDGO,PRSNESCV,PRSNFCIN,PRSNGNRO,PRSNIDST,PRSNNMBR,PRSNUSIN' FROM DUAL
UNION ALL SELECT 'CRD', 'PRST', 'ENTDCDGO,ESPSCDGO,FLLLCDGO,MTVPCDGO,PRDCCDGO,PRSTAJAP,PRSTAMRT,PRSTCDGO,PRSTDSVN,PRSTESNV,PRSTESOP,PRSTFCAC,PRSTFCAD,PRSTFCAP,PRSTFCFN,PRSTFCHA,PRSTFCIN,PRSTFCLG,PRSTFCMD,PRSTFCRC,PRSTFCRG,PRSTFRTT,PRSTIDAS,PRSTIDST,PRSTINNM,PRSTINVR,PRSTMNLD,PRSTMNNV,PRSTMNSL,PRSTMRCL,PRSTMSCB,PRSTOBSR,PRSTPLZO,PRSTPRIN,PRSTRFNN,PRSTRPRC,PRSTRSTR,PRSTSLCP,PRSTSLIN,PRSTSLOT,PRSTSLTT,PRSTSLVN,PRSTSLXV,PRSTTPAM,PRSTTSAA,PRSTTSEF,PRSTTSIN,PRSTTSNM,PRSTTTCP,PRSTTTIN,PRSTTTIV,PRSTTTMR,PRSTTTPG,PRSTTTPR,PRSTTTSG,PRSTUSAC,PRSTUSAP,PRSTUSLG,PRSTUSMD,PRSTUSRC,PRSTUSRG,PRSTVLAS,PRSTVLCT' FROM DUAL
UNION ALL SELECT 'CRD', 'PRCA', 'PRCACDGO,PRCAERRO,PRCAESDQ,PRCAESTD,PRCAFCPR,PRCAFCRG,PRCAIDAP,PRCAIDCT,PRCAIDPG,PRCAIDPS,PRCANVPR,PRCAOBSR,PRCAPRCS,PRCASLCP,PRCASLIN,PRCAUSRG,PXCACDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRDC', 'FLLLCDGO,PRDCCDEX,PRDCCDGO,PRDCCDPT,PRDCCSPB,PRDCESTD,PRDCFCMD,PRDCFCRG,PRDCIPMD,PRDCIPRG,PRDCNMBR,PRDCUSMD,PRDCUSRG,TPPRCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'PRFS', 'PRFSCDGO,PRFSCSBC,PRFSIDST,PRFSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'PRVN', 'PRVNCDAL,PRVNCDEX,PRVNCDGO,PRVNIDST,PRVNNMBR,PSSSCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'RRFF', 'ENTDCDGO,RRFFCDGO,RRFFCDLA,RRFFCNTC,RRFFIDST,RRFFNMBR,RRFFPRNT' FROM DUAL
UNION ALL SELECT 'CRD', 'RRPP', 'ENTDCDGO,RRPPCDGO,RRPPCDLA,RRPPCNTC,RRPPIDST,RRPPNMBR,RRPPPRNT' FROM DUAL
UNION ALL SELECT 'CRD', 'RLPR', 'PRSTCDGH,PRSTCDGP,RLPRCDGO,RLPRFCRG,RLPRIDST,RLPRTPPR,RLPRUSRG' FROM DUAL
UNION ALL SELECT 'CRD', 'RQPR', 'PRSTCDGO,RQPRALRT,RQPRCDGO,RQPRDSCR,RQPRESTD,RQPRFCRG,RQPROBSR,RQPRUSRG,RQPRVLDO,TPRQCDGO' FROM DUAL
UNION ALL SELECT 'CRD', 'TSPR', 'PRDCCDGO,TSPRCDGO,TSPRCSBC,TSPRIDST,TSPRMNMN,TSPRMNMX,TSPRNMBR,TSPRPLMN,TSPRPLMX,TSPRTSEF,TSPRTSNM' FROM DUAL
UNION ALL SELECT 'CRD', 'TPDJ', 'TPDJCDGO,TPDJIDST,TPDJNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPAP', 'TPAPCDGO,TPAPCSBC,TPAPIDST,TPAPNMBR,TPAPPRDP' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCL', 'TPCLCDGO,TPCLCSPB,TPCLCTGR,TPCLIDST,TPCLNMBR,TPCLPRVS' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCS', 'TPCSCDGO,TPCSCSPB,TPCSIDST,TPCSNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPCN', 'TPCNCDGO,TPCNCSPB,TPCNIDST,TPCNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPGN', 'TPGNCDEX,TPGNCDGO,TPGNIDST,TPGNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPHD', 'ENTDCDGO,TPHDCDEX,TPHDCDGO,TPHDIDST' FROM DUAL
UNION ALL SELECT 'CRD', 'TPDN', 'TPDNCDGO,TPDNIDST,TPDNNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPG', 'TPPGCDGO,TPPGCSPB,TPPGIDST,TPPGNMBR,TPPGOBSR,TPPGTPOO' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPC', 'TPPCCDGO,TPPCCSPB,TPPCIDST,TPPCNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPPR', 'TPPRCDGO,TPPRCSPB,TPPRIDST,TPPRNMBR,TPPRTPOO,TPPRTSAA' FROM DUAL
UNION ALL SELECT 'CRD', 'TPRQ', 'TPRQCDGO,TPRQESTD,TPRQNMBR,TPRQVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'TPVV', 'TPVVCDGO,TPVVIDST,TPVVNMBR' FROM DUAL
UNION ALL SELECT 'CRD', 'TRAS', 'TRASCNCP,TRASCNTA,TRASCRRR,TRASDBBB,TRASDFRN,TRASFCHD,TRASFCHP,TRASSLDA,TRASSLDC,TRASSLDN,TRASTRRR,TRASTTLC,TRASTTLD' FROM DUAL
UNION ALL SELECT 'CRD', 'TRCR', 'BEXTCDGO,BNCOCDGO,CNBCCDGO,CRARCDGO,TRCRCDGO,TRCRCTOR,TRCRFCHA,TRCRFCRG,TRCRIDST,TRCRIPRG,TRCRNMRO,TRCROBSR,TRCRUSRG,TRCRVLRR' FROM DUAL
UNION ALL SELECT 'CRD', 'VPPC', 'ENTDCDGO,VPPCCDGO,VPPCCFMD,VPPCFCRG,VPPCIDST,VPPCNMCT,VPPCTNPR,VPPCUSMD,VPPCUSRG,VPPCVLRR,VPPCVLSR' FROM DUAL
UNION ALL SELECT 'CRD', 'VGCN', 'CNTRCDGO,TPAPCDGO,VGCNCDGO,VGCNFCFN,VGCNFCIN,VGCNFCRG,VGCNIDHS,VGCNIDST,VGCNMNTO,VGCNMODO,VGCNOBSR,VGCNPRCN,VGCNRMUN,VGCNUSRG' FROM DUAL
),
EXPANDIDO AS (
    SELECT e.OWNER_ESP, e.TABLA_ESP,
           TRIM(REGEXP_SUBSTR(e.COLS, '[^,]+', 1, l.LVL)) AS COLUMNA_ESP
    FROM   ESPERADO e
    JOIN   (SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 200) l
      ON   l.LVL <= REGEXP_COUNT(e.COLS, ',') + 1
)
SELECT x.OWNER_ESP AS ESQUEMA, x.TABLA_ESP AS TABLA, x.COLUMNA_ESP AS COLUMNA,
       'COLUMNA MAPEADA QUE NO EXISTE' AS PROBLEMA
FROM   EXPANDIDO x
WHERE  EXISTS (SELECT 1 FROM ALL_TABLES t
               WHERE t.OWNER = x.OWNER_ESP AND t.TABLE_NAME = x.TABLA_ESP)
AND    NOT EXISTS (SELECT 1 FROM ALL_TAB_COLUMNS c
                   WHERE c.OWNER = x.OWNER_ESP
                     AND c.TABLE_NAME = x.TABLA_ESP
                     AND c.COLUMN_NAME = x.COLUMNA_ESP)
ORDER  BY 1, 2, 3;
