/**
 * Copyright o Gaemi Soft Coa. Ltda. , 2011 Reservados todos los derechos  
 * Joso Lucuma E6-95 y Pedro Cornelio
 * Quito - Ecuador
 * Este programa esto protegido por las leyes de derechos de autor y otros tratados internacionales.
 * La reproduccion o la distribucion no autorizadas de este programa, o de cualquier parte del mismo, 
 * esto penada por la ley y con severas sanciones civiles y penales, y sero objeto de todas las
 * acciones judiciales que correspondan.
 * Usted no puede divulgar dicha Informacion confidencial y se utilizaro solo en  conformidad  
 * con los torminos del acuerdo de licencia que ha introducido dentro de Gaemi Soft.
**/
package com.saa.rubros;

/**
 * @author GaemiSoft
 *         Interface con las Constantes de los diferentes codigos alternos de
 *         los Rubros
 */
public interface Rubros {
	int ALERTAS = 47;
	int ANIOS = 42;
	int CATEGORIAS = 85;
	int CLAVE_CREACION_USUARIO = 9;
	int CODIGO_ALTERNO_JERARQUIAS = 69;
	int DETENER_FALLA_AUDITORIA = 10;
	int DIAS_VENCIMIENTO_PAGO = 84;
	int ERRORES_SISTEMA = 4;
	int ESTADO = 11;
	int ESTADO_ASIENTO = 21;
	int ESTADO_CHEQUE = 26;
	int ESTADO_CHEQUERA = 25;
	int ESTADO_CIERRE_CAJAS = 32;
	int ESTADO_COBRO = 28;
	int ESTADO_COBRO_CHEQUE = 57;
	int ESTADO_CUENTAS_BANCARIAS = 50;
	int ESTADOS_DEPOSITO = 52;
	int ESTADOS_DOCUMENTO_FISICO = 77;
	int ESTADOS_DOCUMENTO_PAGO = 78;
	int ESTADO_MOVIMIENTO_BANCARIO = 66;
	int ESTADOS_MOVIMIENTO_BANCO = 58;
	int ESTADO_MOVIMIENTO_CATEGORIA = 87;
	int ESTADO_PAGO = 33;
	int ESTADO_PERIODOS = 22;
	int ESTADOS_CONCILIACION = 43;
	int FORMATOS_DOCUMENTOS_TRIBUTARIOS = 68;
	int FORMATO_FECHA = 48;
	int FORMATO_NUMERO = 67;
	int GRUPOS_CUENTAS_BASICAS = 20;
	int HORAS_DIA = 165;
	int MANEJA_PERMISOS = 7;
	int MANEJO_CARACTERISTICAS_ARBOL = 8;
	int MES_ANIO = 14;
	int MODULO_CLIENTE = 16;
	int MODULO_SISTEMA = 15;
	int MOTIVO_ANULACION_CHEQUE = 38;
	int MOTIVO_ANULACION_COBRO = 29;
	int MOTIVO_ANULACION_PAGO = 34;
	int MOVIMIENTO_CUENTA_PLANTILLA = 17;
	int NIVELES_JERARQUICO_LEGAL = 73;
	int NIVELES_PERMISOS = 6;
	int NOMBRE_MODULO_EJB = 46;
	int ORIGEN_MOVIMIENTO_CONCILIACION = 41;
	int PATH_FUENTES = 5;
	int PERIODICIDAD = 79;
	int PERIODICIDAD_MOVIMIENTO = 86;
	int PLANTILLAS_SISTEMA = 53;
	int PREFIJOS_CELULAR = 40;
	int PREFIJOS_TELEFONO = 39;
	int PROCESOS_ASIENTO = 54;
	int PROCESOS_MAYORIZACION = 49;
	int REPORTE_INCLUYE_CENTROS = 59;
	int REPORTE_INCLUYE_MOVIMIENTOS = 62;
	int REPORTES_BALACES = 44;
	int REPORTES_BASICOS = 27;
	int REPORTE_TIPO_ACUMULACION = 61;
	int REPORTE_TIPO_DISTRIBUCION = 60;
	int ROL_PERSONA = 55;
	int SECCIONES_SISTEMA_AMBITO = 72;
	int SIGNOS_REPORTES_CONTABLES = 18;
	int TIPO_ASIENTO = 45;
	int TIPO_BANCOS = 24;
	int TIPO_COMANDOS_BUSQUEDA = 71;
	int TIPO_BUSQUEDA_APROBACION_FECHA = 88;
	int TIPO_BUSQUEDA_APROBACION_VALOR = 89;
	int TIPO_CUENTA_CONTABLE = 13;
	int TIPO_CUENTAS_BANCARIAS = 23;
	int TIPO_CUOTA_INICIAL = 81;
	int TIPO_DATOS_BUSQUEDA = 70;
	int TIPO_DATOS_CARACTERISTICAS = 2;
	int TIPO_DEBITO_CREDITO = 64;
	int TIPO_DESGLOSE_DEPOSITO = 56;
	int TIPO_DIRECCION = 30;
	int TIPO_ESTRUCTURA_ITEMS = 1;
	int TIPO_FACTURACION = 51;
	int TIPO_FINANCIACION = 82;
	int TIPO_GRUPO_CONTABLES = 12;
	int TIPO_GRUPO_PRODUCTOS = 74;
	int TIPO_IDENTIFICACION = 36;
	int TIPO_IMPUESTO = 76;
	int TIPO_MONEDA = 19;
	int TIPO_MOVIMIENTO_CONCILIACION = 37;
	int TIPO_PAGOS = 83;
	int TIPO_PARAMETROS_FUNCIONES = 3;
	int TIPO_PERIODICIDAD = 80;
	int TIPO_PERIODO_VALIDACION_CONCILIACION = 65;
	int TIPO_PERSONA = 35;
	int TIPO_TELEFONO = 31;
	int TIPO_TRANSACCION = 75;
	int TIPO_TRANSFERENCIA = 63;
	int PCC_TIPO_FORMA_PAGO = 101;
	int PCC_CAMBIO_CUPONES_GANADOS = 102;
	// int PCC_TIPO_IDENTIFICACION = 103; //ELIMINAR
	int PCC_TIPO_CLIENTE = 104;
	int PCC_TIPO_CONTACTO = 105;
	int PCC_ORIGEN_CONTACTO = 106;
	int PCC_SE_ACUMULA_PUNTOS_X_VALORES_DE_ASENSO = 107;
	int PCC_SE_ACUMULA_VALOR_DE_ASCENSO_HASTA_LIMITE_DE_RANGO = 108;
	int PCC_COLOR_PROMOCION = 109;
	int PCC_ESTADO_TRANSACCION = 110;
	int PCC_CODIGO_ALTERNO_PARA_REGISTRO_TODOS = 111;
	int PCC_ESTADO_PROMOCION = 112;
	int PCC_EMPRESA_UNICA_SISTEMA = 113;
	int PCC_MOTIVO_CUPON_TRANSACCION = 114;
	int PCC_CONCEPTO_CUPONES_ADICIONALES = 115;
	int PCC_TIPO_PROVEEDOR = 116;
	int SLC_CONCEPTO_REVISION_ADICIONAL = 134;
	int SLC_NIVELES_APROBACION_PREDETERMINADO = 135;
	int SLC_TIPO_MOVIMIENTO = 136;
	int SLC_ESTADO_SOLICITUD = 137;
	int SLC_TIPO_RESTRICCION = 138;
	int SSO_AFIRMACION = 154;
	// RUBROS ASOPREP
	int ASP_ESTADO_CARGA_ARCHIVO_PETRO = 166;
}
