-- =====================================================
-- TABLA: CRD.AVPC (AfectacionValoresParticipeCarga)
-- DESCRIPCIÓN: Registra las afectaciones manuales de valores 
--              cuando hay novedades en el procesamiento.
--              Permite al frontend especificar a qué cuotas
--              y con qué valores afectar cuando el procesamiento
--              automático no puede determinar la distribución.
-- FECHA: 2026-03-25
-- =====================================================

CREATE TABLE CRD.AVPC (
    -- PK Autoincrementable automática (Oracle 12c+)
    AVPCCDGO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    
    -- FK a NovedadParticipeCarga (tabla padre)
    NVPCCDGO NUMBER NOT NULL,
    
    -- FK a Prestamo (préstamo al que se afecta)
    PRSTCDGO NUMBER NOT NULL,
    
    -- FK a DetallePrestamo (cuota específica a afectar)
    DTPRCDGO NUMBER NOT NULL,
    
    -- VALORES DE LA CUOTA ORIGINAL
    AVPCVLCT NUMBER(18,2), -- Valor total de la cuota original
    AVPCVLCP NUMBER(18,2), -- Capital de la cuota original
    AVPCVLIN NUMBER(18,2), -- Interés de la cuota original
    AVPCVLDG NUMBER(18,2), -- Desgravamen de la cuota original
    
    -- VALORES A AFECTAR (indicados por el usuario)
    AVPCVAFA NUMBER(18,2) NOT NULL, -- Valor total a afectar
    AVPCCPAF NUMBER(18,2), -- Capital a afectar
    AVPCINAF NUMBER(18,2), -- Interés a afectar
    AVPCDGAF NUMBER(18,2), -- Desgravamen a afectar
    
    -- DIFERENCIAS CALCULADAS
    AVPCDFTL NUMBER(18,2), -- Diferencia total
    AVPCDFCP NUMBER(18,2), -- Diferencia en capital
    AVPCDFIN NUMBER(18,2), -- Diferencia en interés
    AVPCDFDG NUMBER(18,2), -- Diferencia en desgravamen
    
    -- AUDITORÍA
    AVPCFCAF DATE, -- Fecha en que se registró la afectación
    AVPCUSAR VARCHAR2(50), -- Usuario que registró la afectación
    AVPCFCRG TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación
    
    -- OBSERVACIONES
    AVPCOBSR VARCHAR2(1000), -- Observaciones
    
    -- ESTADO
    AVPCESTD NUMBER DEFAULT 1, -- Estado del registro (1=ACTIVO)
    
    -- CONSTRAINTS
    CONSTRAINT PK_AVPC PRIMARY KEY (AVPCCDGO),
    CONSTRAINT FK_AVPC_NVPC FOREIGN KEY (NVPCCDGO) REFERENCES CRD.NVPC(NVPCCDGO),
    CONSTRAINT FK_AVPC_PRST FOREIGN KEY (PRSTCDGO) REFERENCES CRD.PRST(PRSTCDGO),
    CONSTRAINT FK_AVPC_DTPR FOREIGN KEY (DTPRCDGO) REFERENCES CRD.DTPR(DTPRCDGO)
);

-- Índices para mejorar performance
CREATE INDEX IDX_AVPC_NVPC ON CRD.AVPC(NVPCCDGO);
CREATE INDEX IDX_AVPC_PRST ON CRD.AVPC(PRSTCDGO);
CREATE INDEX IDX_AVPC_DTPR ON CRD.AVPC(DTPRCDGO);
CREATE INDEX IDX_AVPC_USAR ON CRD.AVPC(AVPCUSAR);

-- Comentarios
COMMENT ON TABLE CRD.AVPC IS 'Afectaciones manuales de valores cuando hay novedades en el procesamiento de archivos Petrocomercial';
COMMENT ON COLUMN CRD.AVPC.AVPCCDGO IS 'Código único de la afectación (PK Autoincremental)';
COMMENT ON COLUMN CRD.AVPC.NVPCCDGO IS 'FK a NovedadParticipeCarga';
COMMENT ON COLUMN CRD.AVPC.PRSTCDGO IS 'FK a Prestamo afectado';
COMMENT ON COLUMN CRD.AVPC.DTPRCDGO IS 'FK a DetallePrestamo (cuota) afectada';
COMMENT ON COLUMN CRD.AVPC.AVPCVLCT IS 'Valor total de la cuota original';
COMMENT ON COLUMN CRD.AVPC.AVPCVAFA IS 'Valor total a afectar indicado por el usuario';
COMMENT ON COLUMN CRD.AVPC.AVPCDFTL IS 'Diferencia entre valor cuota y valor a afectar';
COMMENT ON COLUMN CRD.AVPC.AVPCFCAF IS 'Fecha en que se registró la afectación';
COMMENT ON COLUMN CRD.AVPC.AVPCUSAR IS 'Usuario que registró la afectación';
COMMENT ON COLUMN CRD.AVPC.AVPCOBSR IS 'Observaciones adicionales del usuario';
COMMENT ON COLUMN CRD.AVPC.AVPCESTD IS 'Estado del registro (1=ACTIVO)';

-- =====================================================
-- NOTA: Para agregar esta tabla al sistema, también:
-- 1. Ya se creó la entidad JPA: AfectacionValoresParticipeCarga.java
-- 2. Ya se agregó la constante en NombreEntidadesCredito.java
-- 3. Ya se crearon los servicios DAO y Service
-- 4. Ya se creó el REST API en /avpc
-- =====================================================
