-- ============================================================
-- ALTER TABLES CG40-CG51 : Agregar FK a RPR.EJRD
-- Cada tabla de reporte G necesita saber a qué detalle de
-- ejecución (EJRD) pertenecen sus registros.
-- ============================================================

ALTER TABLE RPR.CG40 ADD (CG40EJRD NUMBER(19,0));
ALTER TABLE RPR.CG40 ADD CONSTRAINT FK_CG40_EJRD FOREIGN KEY (CG40EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG40.CG40EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G40';

ALTER TABLE RPR.CG41 ADD (CG41EJRD NUMBER(19,0));
ALTER TABLE RPR.CG41 ADD CONSTRAINT FK_CG41_EJRD FOREIGN KEY (CG41EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG41.CG41EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G41';

ALTER TABLE RPR.CG42 ADD (CG42EJRD NUMBER(19,0));
ALTER TABLE RPR.CG42 ADD CONSTRAINT FK_CG42_EJRD FOREIGN KEY (CG42EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG42.CG42EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G42';

ALTER TABLE RPR.CG43 ADD (CG43EJRD NUMBER(19,0));
ALTER TABLE RPR.CG43 ADD CONSTRAINT FK_CG43_EJRD FOREIGN KEY (CG43EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG43.CG43EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G43';

ALTER TABLE RPR.CG44 ADD (CG44EJRD NUMBER(19,0));
ALTER TABLE RPR.CG44 ADD CONSTRAINT FK_CG44_EJRD FOREIGN KEY (CG44EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG44.CG44EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G44';

ALTER TABLE RPR.CG45 ADD (CG45EJRD NUMBER(19,0));
ALTER TABLE RPR.CG45 ADD CONSTRAINT FK_CG45_EJRD FOREIGN KEY (CG45EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG45.CG45EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G45';

ALTER TABLE RPR.CG46 ADD (CG46EJRD NUMBER(19,0));
ALTER TABLE RPR.CG46 ADD CONSTRAINT FK_CG46_EJRD FOREIGN KEY (CG46EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG46.CG46EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G46';

ALTER TABLE RPR.CG47 ADD (CG47EJRD NUMBER(19,0));
ALTER TABLE RPR.CG47 ADD CONSTRAINT FK_CG47_EJRD FOREIGN KEY (CG47EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG47.CG47EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G47';

ALTER TABLE RPR.CG48 ADD (CG48EJRD NUMBER(19,0));
ALTER TABLE RPR.CG48 ADD CONSTRAINT FK_CG48_EJRD FOREIGN KEY (CG48EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG48.CG48EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G48';

ALTER TABLE RPR.CG49 ADD (CG49EJRD NUMBER(19,0));
ALTER TABLE RPR.CG49 ADD CONSTRAINT FK_CG49_EJRD FOREIGN KEY (CG49EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG49.CG49EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G49';

ALTER TABLE RPR.CG50 ADD (CG50EJRD NUMBER(19,0));
ALTER TABLE RPR.CG50 ADD CONSTRAINT FK_CG50_EJRD FOREIGN KEY (CG50EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG50.CG50EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G50';

ALTER TABLE RPR.CG51 ADD (CG51EJRD NUMBER(19,0));
ALTER TABLE RPR.CG51 ADD CONSTRAINT FK_CG51_EJRD FOREIGN KEY (CG51EJRD) REFERENCES RPR.EJRD (EJRDCDGO);
COMMENT ON COLUMN RPR.CG51.CG51EJRD IS 'FK al detalle de ejecución (RPR.EJRD) al que pertenece este registro G51';

-- Índices para mejorar búsquedas por ejecución
CREATE INDEX IDX_CG40_EJRD ON RPR.CG40 (CG40EJRD);
CREATE INDEX IDX_CG41_EJRD ON RPR.CG41 (CG41EJRD);
CREATE INDEX IDX_CG42_EJRD ON RPR.CG42 (CG42EJRD);
CREATE INDEX IDX_CG43_EJRD ON RPR.CG43 (CG43EJRD);
CREATE INDEX IDX_CG44_EJRD ON RPR.CG44 (CG44EJRD);
CREATE INDEX IDX_CG45_EJRD ON RPR.CG45 (CG45EJRD);
CREATE INDEX IDX_CG46_EJRD ON RPR.CG46 (CG46EJRD);
CREATE INDEX IDX_CG47_EJRD ON RPR.CG47 (CG47EJRD);
CREATE INDEX IDX_CG48_EJRD ON RPR.CG48 (CG48EJRD);
CREATE INDEX IDX_CG49_EJRD ON RPR.CG49 (CG49EJRD);
CREATE INDEX IDX_CG50_EJRD ON RPR.CG50 (CG50EJRD);
CREATE INDEX IDX_CG51_EJRD ON RPR.CG51 (CG51EJRD);
