-- ============================================================
-- TABLA RPR.EJRC - Cabecera de Ejecución de Reportes
-- ============================================================
CREATE TABLE RPR.EJRC (
    EJRCCDGO NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- Código único
    EJRCMESS NUMBER(2,0)    NOT NULL,  -- Mes de presentación (1-12)
    EJRCANOO NUMBER(4,0)    NOT NULL,  -- Año de presentación
    EJRCUSRO VARCHAR2(50)   NOT NULL,  -- Usuario que generó
    EJRCFCGN DATE           NOT NULL,  -- Fecha de generación
    EJRCTPEJ NUMBER(1,0)    NOT NULL,  -- Tipo ejecución: 1=Inicial, 2=Corrección
    EJRCESTD NUMBER(1,0)    NOT NULL,  -- Estado general: 1=En proceso, 2=Con novedades, 3=Completo
    EJRCOBSR VARCHAR2(500),            -- Observaciones generales
    CONSTRAINT PK_EJRC PRIMARY KEY (EJRCCDGO)
);

-- ============================================================
-- Diccionario de Datos - EJRC
-- ============================================================
COMMENT ON TABLE  RPR.EJRC            IS 'Cabecera de ejecución mensual de reportes G40-G51';
COMMENT ON COLUMN RPR.EJRC.EJRCCDGO  IS 'Código único del registro (Identity)';
COMMENT ON COLUMN RPR.EJRC.EJRCMESS  IS 'Mes de presentación de la información (1-12)';
COMMENT ON COLUMN RPR.EJRC.EJRCANOO  IS 'Año de presentación de la información';
COMMENT ON COLUMN RPR.EJRC.EJRCUSRO  IS 'Usuario que generó la ejecución';
COMMENT ON COLUMN RPR.EJRC.EJRCFCGN  IS 'Fecha en que se generó la ejecución';
COMMENT ON COLUMN RPR.EJRC.EJRCTPEJ  IS 'Tipo de ejecución: 1=Inicial, 2=Corrección';
COMMENT ON COLUMN RPR.EJRC.EJRCESTD  IS 'Estado general: 1=En proceso, 2=Con novedades, 3=Completo';
COMMENT ON COLUMN RPR.EJRC.EJRCOBSR  IS 'Observaciones generales de la ejecución';


-- ============================================================
-- TABLA RPR.EJRD - Detalle de Ejecución por Reporte G
-- ============================================================
CREATE TABLE RPR.EJRD (
    EJRDCDGO NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- Código único
    EJRCCDGO NUMBER(19,0)  NOT NULL,   -- FK a cabecera de ejecución
    EJRDTPRP VARCHAR2(10)  NOT NULL,   -- Tipo de reporte: 'G40','G41',...,'G51'
    EJRDESTD NUMBER(1,0)   NOT NULL,   -- Estado: 1=OK, 2=Con novedades, 3=Pendiente
    EJRDFCGN DATE,                     -- Fecha en que se generó este reporte G
    EJRDCNRG NUMBER(10,0),             -- Cantidad de registros generados
    EJRDNVDD VARCHAR2(1000),           -- Descripción de novedades (si hubo problemas)
    EJRDEJRO NUMBER(19,0),             -- FK al EJRD original que se está corrigiendo (null si es inicial)
    CONSTRAINT PK_EJRD  PRIMARY KEY (EJRDCDGO),
    CONSTRAINT FK_EJRD_EJRC  FOREIGN KEY (EJRCCDGO) REFERENCES RPR.EJRC (EJRCCDGO),
    CONSTRAINT FK_EJRD_EJRO  FOREIGN KEY (EJRDEJRO) REFERENCES RPR.EJRD (EJRDCDGO)
);

-- ============================================================
-- Diccionario de Datos - EJRD
-- ============================================================
COMMENT ON TABLE  RPR.EJRD            IS 'Detalle de ejecución por reporte G (G40-G51) dentro de una ejecución mensual';
COMMENT ON COLUMN RPR.EJRD.EJRDCDGO  IS 'Código único del registro (Identity)';
COMMENT ON COLUMN RPR.EJRD.EJRCCDGO  IS 'FK a la cabecera de ejecución (RPR.EJRC)';
COMMENT ON COLUMN RPR.EJRD.EJRDTPRP  IS 'Tipo de reporte generado: G40, G41, G42, G43, G44, G45, G46, G47, G48, G49, G50, G51';
COMMENT ON COLUMN RPR.EJRD.EJRDESTD  IS 'Estado del reporte: 1=OK, 2=Con novedades, 3=Pendiente';
COMMENT ON COLUMN RPR.EJRD.EJRDFCGN  IS 'Fecha en que se generó este reporte G específico';
COMMENT ON COLUMN RPR.EJRD.EJRDCNRG  IS 'Cantidad de registros generados para este reporte';
COMMENT ON COLUMN RPR.EJRD.EJRDNVDD  IS 'Descripción de novedades o errores encontrados al generar el reporte';
COMMENT ON COLUMN RPR.EJRD.EJRDEJRO  IS 'FK al detalle original (EJRD) que este registro está corrigiendo. Null si es ejecución inicial';


-- ============================================================
-- Índices de búsqueda frecuente
-- ============================================================
CREATE INDEX IDX_EJRC_MESS_ANOO ON RPR.EJRC (EJRCMESS, EJRCANOO);
CREATE INDEX IDX_EJRD_EJRC      ON RPR.EJRD (EJRCCDGO);
CREATE INDEX IDX_EJRD_TPRP      ON RPR.EJRD (EJRDTPRP);
CREATE INDEX IDX_EJRD_EJRO      ON RPR.EJRD (EJRDEJRO);
