--------------------------------------------------------------------------------
-- lap1-16 — EL CONTROL 4, EN UNA SOLA CONSULTA
--
-- Equipo: lap-saa-1 (laptop)            Fecha: 2026-09-10
--
-- *** SOLO LECTURA. UNA sola sentencia. No crea nada, no borra nada. ***
--
-- POR QUE EXISTE: reemplaza al CONTROL 4 del lap1-14, que estaba mal armado.
-- Aquel era el unico control del archivo que no se podia correr de un tirón como
-- los otros tres: tenia 25 lineas de comentario entre su titulo y su primera
-- sentencia, creaba una tabla de trabajo, seguia con un bloque PL/SQL y terminaba
-- en tres SELECT, y sus partes se llamaban "PASO" en vez de "CONTROL 4". Quien
-- bajara buscando un bloque ejecutable como los anteriores no lo encontraba.
--
-- Esto hace exactamente lo mismo sin DDL, sin PL/SQL y sin tabla temporal: se
-- selecciona entero, se ejecuta, y devuelve el resultado.
--
-- (El CONTROL 4 del lap1-14 queda obsoleto. Los CONTROL 1, 2 y 3 de ese archivo
--  siguen valiendo y ya se corrieron: 1 y 3 volvieron vacios.)
--------------------------------------------------------------------------------
-- QUE PREGUNTA RESPONDE
--
-- Cuantas filas de todo el sistema apuntan hoy a un nodo que el lap1-15 va a
-- borrar. Recorre las 100 columnas numericas llamadas %PJRQ% que encontro el
-- CONTROL 5 del lap1-13, en CBR, CNT, CRD, PGS, PRG, RHH, SCP y TSR.
--
-- COMO SE LEE EL RESULTADO
--
--   NINGUNA FILA  -> via libre. Nada del sistema apunta a lo que se va a borrar,
--                    y el lap1-15 se puede correr.
--
--   ALGUNA FILA   -> PARAR Y AVISAR. Cada fila dice tabla, columna y cuantas
--                    filas apuntan. Hay dos casos y ninguno es bueno:
--                    con FK declarada, el DELETE del lap1-15 fallaria con
--                    ORA-02292 y no borraria nada; sin FK, el DELETE pasa y esas
--                    filas quedan apuntando a un codigo que el INSERT nuevo va a
--                    reutilizar para OTRA pantalla — un permiso viejo
--                    concediendo algo nuevo, sin un solo error.
--
-- Lo esperado, por lo que ya sabemos: NINGUNA FILA. Las 48 FK contra SCP.PJRQ son
-- FK_..._EMPRESA y FK_..._USUARIO (esa tabla guarda tambien las empresas y los
-- usuarios), y los permisos asignados viven en SCP.PENP, que hoy tiene 2 filas y
-- ninguna apunta a PCC/CID/ACT. Se corre igual: el objetivo del control no es
-- confirmar lo que creemos, es enterarnos si nos equivocamos.
--
-- Se excluyen a proposito SCP.PJRQ (es la tabla origen), SCP.HTE_PJRQ (es su
-- historial: sus columnas SON la fila historizada, no una referencia) y las
-- columnas VARCHAR2 llamadas PJRQNMBR de CNT.CURSO_REPORTES y CNT.V_NTRL, que
-- son nombres y no codigos.
--------------------------------------------------------------------------------

WITH BORRAR AS (
  SELECT PJRQCDGO FROM SCP.PJRQ
   WHERE PGSPCDGO = 11
   START WITH PJRQCDGO IN (482, 315, 979)
 CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11
)
SELECT * FROM (
  SELECT 'CBR.APLC' AS TABLA, 'APLCPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.APLC x WHERE x.APLCPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.DCMC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.DCMC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.DTDC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.DTDC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.GRPC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.GRPC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.HTE_GRPC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.HTE_GRPC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.TDCC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.TDCC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CBR.TDTC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CBR.TDTC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.ASNH' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.ASNH x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.ASNT' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.ASNT x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.CNCS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.CNCS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.CURSO_REPORTES' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.CURSO_REPORTES x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.MTCH' AS TABLA, 'PJRQCDFN' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.MTCH x WHERE x.PJRQCDFN IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.MTCH' AS TABLA, 'PJRQCDOR' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.MTCH x WHERE x.PJRQCDOR IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.MYAN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.MYAN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.MYCC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.MYCC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.NTRL' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.NTRL x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.PLNN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.PLNN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.PLNS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.PLNS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.PLNT' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.PLNT x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.PRDO' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.PRDO x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.RPRT' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.RPRT x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.VCURSO_PLNS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.VCURSO_PLNS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CNT.V_NTRL' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CNT.V_NTRL x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.ACCN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.ACCN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.CBPR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.CBPR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.CFCR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.CFCR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.CRCT' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.CRCT x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.CRJB' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.CRJB x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'CRD.CTAP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM CRD.CTAP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.ANTP' AS TABLA, 'ANTPPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.ANTP x WHERE x.ANTPPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.APLP' AS TABLA, 'APLPPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.APLP x WHERE x.APLPPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.AXPR' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.AXPR x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.CRTX' AS TABLA, 'CRTXPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.CRTX x WHERE x.CRTXPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.DCMP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.DCMP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.DCXP' AS TABLA, 'DCXPPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.DCXP x WHERE x.DCXPPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.DDPG' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.DDPG x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.GRPP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.GRPP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.LTPG' AS TABLA, 'LTPGPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.LTPG x WHERE x.LTPGPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.MNAP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.MNAP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.PGTR' AS TABLA, 'PGTRPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.PGTR x WHERE x.PGTRPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.TDCP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.TDCP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.TDTP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.TDTP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.TMNA' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.TMNA x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.TUXA' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.TUXA x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PGS.UXAP' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM PGS.UXAP x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.AMBT' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.AMBT x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.BLCK' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.BLCK x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.NRRT' AS TABLA, 'PJRQUSAN' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.NRRT x WHERE x.PJRQUSAN IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.NRRT' AS TABLA, 'PJRQUSIN' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.NRRT x WHERE x.PJRQUSIN IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.ORRT' AS TABLA, 'PJRQUSAN' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.ORRT x WHERE x.PJRQUSAN IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'PRG.ORRT' AS TABLA, 'PJRQUSIN' AS COLUMNA, COUNT(*) AS FILAS FROM PRG.ORRT x WHERE x.PJRQUSIN IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.CFNM' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.CFNM x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.CPNM' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.CPNM x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.CRMR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.CRMR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.CSTR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.CSTR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.CTLG' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.CTLG x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.FMBN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.FMBN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.FMRC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.FMRC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.HTE_ODBS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.HTE_ODBS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.MPLD' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.MPLD x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.ODBS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.ODBS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.PRDN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.PRDN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.PRNM' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.PRNM x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.RDPG' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.RDPG x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.SLAP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.SLAP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.SLOF' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.SLOF x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.TBIR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.TBIR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.TPCE' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.TPCE x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.TPGP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.TPGP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.UTLD' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.UTLD x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'RHH.VNPG' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM RHH.VNPG x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'SCP.PCXU' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM SCP.PCXU x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'SCP.PDCN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM SCP.PDCN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'SCP.PEEN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM SCP.PEEN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'SCP.PENP' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM SCP.PENP x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.BNCO' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.BNCO x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CBRO' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CBRO x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CJAA' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CJAA x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CJCH' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CJCH x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CJIN' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CJIN x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CNCH' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CNCH x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CNCL' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CNCL x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.CTEB' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.CTEB x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.DBCR' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.DBCR x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.DPST' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.DPST x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.DPST' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.DPST x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.EGRS' AS TABLA, 'EGRSPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.EGRS x WHERE x.EGRSPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.EXBC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.EXBC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.INGR' AS TABLA, 'INGRPJRQ' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.INGR x WHERE x.INGRPJRQ IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.MVCB' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.MVCB x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.PGSS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.PGSS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.PGSS' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.PGSS x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.PRCC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.PRCC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.PRRL' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.PRRL x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.TCBR' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.TCBR x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.TDBC' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.TDBC x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.TDBC' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.TDBC x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.TPGS' AS TABLA, 'PJRQCDGO' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.TPGS x WHERE x.PJRQCDGO IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.TPGS' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.TPGS x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
  UNION ALL
  SELECT 'TSR.USXC' AS TABLA, 'PJRQCDUS' AS COLUMNA, COUNT(*) AS FILAS FROM TSR.USXC x WHERE x.PJRQCDUS IN (SELECT PJRQCDGO FROM BORRAR)
)
 WHERE FILAS > 0
 ORDER BY FILAS DESC;

--------------------------------------------------------------------------------
-- FIN. Una sola sentencia, cero DML, cero DDL. Con esto en verde va el lap1-15.
--------------------------------------------------------------------------------
