--------------------------------------------------------------------------------
-- lap1-15 — ARBOL DE PERMISOS DE SAA en SCP.PJRQ (PGSPCDGO = 11)
--
-- Equipo: lap-saa-1 (laptop)            Fecha: 2026-09-10
-- Borra PCC / CID / ACT e inserta la estructura completa de SAA.
--
-- *** ESTE ARCHIVO SI MODIFICA DATOS. Leer el encabezado entero antes de correr. ***
--
-- Prerrequisitos, todos ya cumplidos:
--   lap1-13 corrido -> columnas, constraints, MAX global 1252, sin huerfanos.
--   lap1-14 corrido -> la secuencia SCP.SQ_PJRQCDGO NO existe (CONTROL 1 vacio) y
--                      no hay dos hermanos homonimos hoy (CONTROL 3 vacio).
--   Los permisos asignados viven en SCP.PENP y hoy tiene 2 filas.
--
--------------------------------------------------------------------------------
-- LO UNICO QUE NO SE PUEDE OLVIDAR AL LEER ESTE ARCHIVO
--
-- SCP.PJRQ NO es solo el arbol de permisos: es TAMBIEN la tabla de EMPRESAS y de
-- USUARIOS del sistema. Empresa.java y Usuario.java mapean esta misma tabla,
-- discriminadas por PGSPCDGO (5 y 12 empresa, 9 usuario, 11 permisos).
--
-- Por eso TODOS los DELETE de este archivo llevan "PGSPCDGO = 11" Y ADEMAS un
-- CONNECT BY acotado a los tres subarboles. Un DELETE mas ancho borraria empresas
-- y usuarios, y se llevaria media base por integridad referencial.
--
-- Si alguna vez hay que modificar este script: ese filtro no es decorativo.
--------------------------------------------------------------------------------
-- QUE SE CONSERVA Y QUE NO
--
--   93   RAIZ SISTEMAS           -> SE CONSERVA. Sin la raiz el arbol no dibuja.
--   42   SEGURIDAD Y AUDITORIA   -> SE CONSERVA (75 nodos). Es el arbol del propio
--                                   modulo con el que se administran los permisos.
--   482  PCC                     -> SE BORRA (325 nodos)
--   315  CID                     -> SE BORRA (150 nodos)
--   979  ACT                     -> SE BORRA (191 nodos)
--                                   666 nodos en total
--
--   1253 SAA                     -> SE INSERTA, 305 nodos (ids 1253 a 1557)
--------------------------------------------------------------------------------
-- COMO SE CORRE: de arriba a abajo. Los CONTROL A/B/C son de solo lectura y hay
-- que MIRAR su resultado antes de seguir. El PASO 1 hace un respaldo completo del
-- arbol 11 en una tabla propia; el bloque de reverso del final, comentado,
-- restaura desde ese respaldo.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- CONTROL A — Los permisos ya asignados (SCP.PENP) contra lo que se va a borrar.
--
-- El usuario reporto 2 filas en PENP. Este control dice si alguna apunta a un
-- nodo que vamos a borrar. Muestra las filas completas y ademas resuelve a que
-- nodo apunta cada una, que es la unica forma de decidir sin adivinar.
--
-- Esperado: DESTINO distinto de "SE BORRA" en las dos filas.
-- Si alguna dice "SE BORRA", el PASO 2 la elimina.
--------------------------------------------------------------------------------
SELECT p.*,
       (SELECT j.PJRQNMBR FROM SCP.PJRQ j
         WHERE j.PJRQCDGO = p.PJRQCDGO)                        AS NODO_APUNTADO,
       (SELECT j.PGSPCDGO FROM SCP.PJRQ j
         WHERE j.PJRQCDGO = p.PJRQCDGO)                        AS JERARQUIA_DEL_NODO,
       CASE WHEN p.PJRQCDGO IN (
                 SELECT PJRQCDGO FROM SCP.PJRQ
                  WHERE PGSPCDGO = 11
                  START WITH PJRQCDGO IN (482, 315, 979)
                CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11)
            THEN 'SE BORRA'
            ELSE 'sobrevive'
       END                                                     AS DESTINO
  FROM SCP.PENP p;


--------------------------------------------------------------------------------
-- CONTROL B — Recuento de lo que se va a borrar, con el MISMO CONNECT BY que usa
-- el DELETE del PASO 3. Esperado: 666.
--------------------------------------------------------------------------------
SELECT COUNT(*) AS NODOS_A_BORRAR
  FROM SCP.PJRQ
 WHERE PGSPCDGO = 11
 START WITH PJRQCDGO IN (482, 315, 979)
CONNECT BY PRIOR PJRQCDGO = PJRQCDPD
       AND PGSPCDGO = 11;


--------------------------------------------------------------------------------
-- CONTROL C — El rango 1253..1557 tiene que estar libre en TODA la tabla, no solo
-- en la jerarquia 11: los ids son unicos globalmente porque la PK es PJRQCDGO
-- solo. Esperado: 0.
--------------------------------------------------------------------------------
SELECT COUNT(*) AS FILAS_QUE_ESTORBAN_EN_EL_RANGO
  FROM SCP.PJRQ
 WHERE PJRQCDGO BETWEEN 1253 AND 1557;


--------------------------------------------------------------------------------
-- PASO 1 — RESPALDO. Es lo que hace reversible todo lo que viene despues.
-- Copia las 742 filas de la jerarquia 11: lo que se borra Y lo que se conserva.
--------------------------------------------------------------------------------
CREATE TABLE SCP.PJRQ_BKP_LAP1 AS
SELECT * FROM SCP.PJRQ WHERE PGSPCDGO = 11;

-- Y el respaldo de los permisos asignados. Son 2 filas, y valen igual.
CREATE TABLE SCP.PENP_BKP_LAP1 AS
SELECT * FROM SCP.PENP;

-- Control del respaldo. Esperado: 742 y 2. Si no cuadra, PARAR: sin respaldo
-- valido no se sigue.
SELECT (SELECT COUNT(*) FROM SCP.PJRQ_BKP_LAP1) AS ARBOL_RESPALDADO,
       (SELECT COUNT(*) FROM SCP.PENP_BKP_LAP1) AS PERMISOS_RESPALDADOS
  FROM DUAL;


--------------------------------------------------------------------------------
-- PASO 2 — Borrar los permisos asignados que apuntan a nodos que van a
-- desaparecer. Decision del usuario: "se borran los permisos ya asignados".
--
-- Va ANTES del PASO 3 porque SCP.PENP tiene FK_PENP_PJRQ contra SCP.PJRQ: si
-- quedara una fila apuntando a un nodo borrado, el PASO 3 fallaria con ORA-02292
-- y no borraria nada.
--
-- Segun el CONTROL A esto deberia borrar 0 filas. Se deja igual: el script tiene
-- que ser correcto por si mismo, no por lo que hoy haya en la tabla.
--------------------------------------------------------------------------------
DELETE FROM SCP.PENP
 WHERE PJRQCDGO IN (
       SELECT PJRQCDGO FROM SCP.PJRQ
        WHERE PGSPCDGO = 11
        START WITH PJRQCDGO IN (482, 315, 979)
      CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11);


--------------------------------------------------------------------------------
-- PASO 3 — Borrar los tres sistemas ajenos.
--
-- No hace falta borrar hijos antes que padres: PJRQ no tiene clave foranea sobre
-- si misma. PJRQCDPD no es FK — verificado en el CONTROL 3 del lap1-13, donde las
-- unicas constraints son PK_PJRQ, FK_PJRQ_PGSP y UN_PJRQ_01. Un solo DELETE.
--
-- Esperado: 666 filas.
--------------------------------------------------------------------------------
DELETE FROM SCP.PJRQ
 WHERE PGSPCDGO = 11
   AND PJRQCDGO IN (
       SELECT PJRQCDGO FROM SCP.PJRQ
        WHERE PGSPCDGO = 11
        START WITH PJRQCDGO IN (482, 315, 979)
      CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11);


--------------------------------------------------------------------------------
-- PASO 4 — El arbol de SAA. 305 nodos, ids 1253..1557.
--
-- Generado desde el relevamiento del frontend
-- (saaFE/docs/seguridad/INVENTARIO-PANTALLAS-SAA.md, los 4 items) con un
-- generador que valida ANTES de emitir: que ningun padre falte, que el nivel del
-- padre sea exactamente uno menos, que el padre tenga id menor que el hijo — para
-- que este orden de INSERT funcione —, que ningun nombre pase de 300 caracteres,
-- y que NO haya dos hermanos con el mismo nombre, que es lo que exige UN_PJRQ_01.
--
-- El nombre mas largo mide 34 caracteres.
--
-- Criterio del arbol, escrito completo en PLAN-ARBOL-PERMISOS-SAA.md seccion 6:
--   * un nodo por PANTALLA, nunca por boton;
--   * una pantalla que ya esta en el menu tiene UN solo nodo, en su lugar del
--     menu: que otra pantalla navegue hacia ella no le crea un segundo nodo;
--   * las pantallas que NO estan en el menu (dialogos con formulario, pantallas
--     de detalle) cuelgan de la pantalla que las abre;
--   * las rutas sin puerta de entrada (ni menu, ni navigate) NO reciben nodo.
--------------------------------------------------------------------------------
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1253, 11, 'SAA', 1, 93, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1254, 11, 'CONTABILIDAD', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1255, 11, 'PARAMETRIZACION', 3, 1254, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1256, 11, 'NATURALEZA DE CUENTAS', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1257, 11, 'PLAN DE CUENTAS', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1258, 11, 'PLAN ARBOL', 5, 1257, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1259, 11, 'AGREGAR/EDITAR CUENTA', 6, 1258, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1260, 11, 'PLAN GRID', 5, 1257, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1261, 11, 'CENTRO DE COSTOS', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1262, 11, 'CENTRO COSTOS ARBOL', 5, 1261, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1263, 11, 'FORMULARIO CENTRO ARBOL', 6, 1262, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1264, 11, 'CENTRO COSTOS GRID', 5, 1261, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1265, 11, 'FORMULARIO CENTRO GRID', 6, 1264, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1266, 11, 'TIPOS DE ASIENTOS', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1267, 11, 'GENERAL', 5, 1266, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1268, 11, 'FORMULARIO TIPO DE ASIENTO', 6, 1267, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1269, 11, 'SISTEMA', 5, 1266, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1270, 11, 'FORMULARIO TIPO DE ASIENTO SISTEMA', 6, 1269, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1271, 11, 'PLANTILLAS', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1272, 11, 'GENERAL', 5, 1271, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1273, 11, 'DETALLE DE PLANTILLA', 6, 1272, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1274, 11, 'SISTEMA', 5, 1271, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1275, 11, 'PERIODOS CONTABLES', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1276, 11, 'REPORTES CONTABLES', 4, 1255, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1277, 11, 'PROCESOS', 3, 1254, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1278, 11, 'ASIENTOS DINAMICO', 4, 1277, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1279, 11, 'SUBDETALLE DE ASIENTO', 5, 1278, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1280, 11, 'LISTADO DE ASIENTOS', 4, 1277, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1281, 11, 'MAYORIZACION - PROCESO', 4, 1277, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1282, 11, 'DETALLE MAYORIZACION', 4, 1277, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1283, 11, 'REPORTES', 3, 1254, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1284, 11, 'LISTADO DE ASIENTOS', 4, 1283, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1285, 11, 'BALANCE GENERAL', 4, 1283, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1286, 11, 'MAYOR ANALITICO', 4, 1283, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1287, 11, 'ASIENTO DEL MAYOR', 5, 1286, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1288, 11, 'MAYOR ANALITICO V2', 4, 1283, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1289, 11, 'ASIENTO DEL MAYOR', 5, 1288, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1290, 11, 'TESORERIA', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1291, 11, 'PARAMETRIZACION', 3, 1290, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1292, 11, 'BANCOS', 4, 1291, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1293, 11, 'NACIONALES Y EXTRANJEROS', 5, 1292, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1294, 11, 'MIS BANCOS', 5, 1292, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1295, 11, 'BANCOS', 6, 1294, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1296, 11, 'CUENTAS BANCARIAS', 6, 1294, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1297, 11, 'CHEQUERAS', 6, 1294, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1298, 11, 'SOLICITUD CHEQUERA', 7, 1297, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1299, 11, 'RECEPCION CHEQUERA', 7, 1297, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1300, 11, 'CHEQUES', 7, 1297, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1301, 11, 'TITULARES', 4, 1291, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1302, 11, 'CAJAS CHICAS', 4, 1291, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1303, 11, 'PROCESOS', 3, 1290, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1304, 11, 'ESTADO DE CUENTA', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1305, 11, 'ANTICIPOS', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1306, 11, 'CLIENTES', 5, 1305, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1307, 11, 'ANULAR ANTICIPO', 6, 1306, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1308, 11, 'PROVEEDORES', 5, 1305, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1309, 11, 'ANULAR ANTICIPO', 6, 1308, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1310, 11, 'SEGUIMIENTO', 5, 1305, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1311, 11, 'ANULAR ANTICIPO', 6, 1310, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1312, 11, 'REGISTRAR', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1313, 11, 'INGRESOS', 5, 1312, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1314, 11, 'EGRESOS', 5, 1312, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1315, 11, 'CAJA CHICA', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1316, 11, 'GASTOS', 5, 1315, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1317, 11, 'ADJUNTOS DEL MOVIMIENTO', 6, 1316, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1318, 11, 'REPOSICION', 5, 1315, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1319, 11, 'CIERRE', 5, 1315, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1320, 11, 'PAGOS POR TRANSFERENCIA', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1321, 11, 'APROBACION DE PAGOS', 5, 1320, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1322, 11, 'GENERACION DE ARCHIVO', 5, 1320, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1323, 11, 'RECEPCION Y CONFIRMACION', 5, 1320, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1324, 11, 'CONSULTA Y GESTION', 5, 1320, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1325, 11, 'CHEQUES', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1326, 11, 'CHEQUES GENERADOS', 5, 1325, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1327, 11, 'CHEQUES IMPRESOS', 5, 1325, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1328, 11, 'CHEQUES ENTREGADOS', 5, 1325, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1329, 11, 'CONSULTA DE CHEQUES', 5, 1325, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1330, 11, 'EXTRACTOS BANCARIOS', 4, 1303, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1331, 11, 'CARGAR EXTRACTO', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1332, 11, 'CONSULTA DE EXTRACTOS', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1333, 11, 'DETALLE DE EXTRACTO', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1334, 11, 'CONCILIACION CONTABLE', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1335, 11, 'CONCILIACION - CIERRE', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1336, 11, 'TABLERO DE CUMPLIMIENTO', 5, 1330, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1337, 11, 'CUENTAS POR PAGAR', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1338, 11, 'PARAMETRIZACION', 3, 1337, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1339, 11, 'GRUPOS DE PRODUCTOS', 4, 1338, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1340, 11, 'DATOS SRI', 4, 1338, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1341, 11, 'PROCESOS', 3, 1337, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1342, 11, 'BANDEJA ELECTRONICA', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1343, 11, 'GESTION DE DOCUMENTOS', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1344, 11, 'CLASIFICAR PRODUCTOS', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1345, 11, 'SUBIR XML', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1346, 11, 'REGISTRAR DOCUMENTO', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1347, 11, 'MOTIVO', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1348, 11, 'REEMBOLSOS DE FACTURA', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1349, 11, 'REGISTRO DE BLOQUEANTES', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1350, 11, 'ERROR DE REGISTRO', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1351, 11, 'ERROR DE VALIDACION XML', 5, 1343, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1352, 11, 'CONSULTA DOCUMENTOS', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1353, 11, 'ANULAR DOCUMENTO DE COMPRA', 5, 1352, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1354, 11, 'NOTA DE VENTA MANUAL', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1355, 11, 'PROPOSICION DE PAGO', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1356, 11, 'SUSTENTO TRIBUTARIO ATS', 4, 1341, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1357, 11, 'PAGOS', 3, 1337, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1358, 11, 'SOLICITUD DE PAGO', 4, 1357, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1359, 11, 'CRUCE DE ANTICIPO', 4, 1357, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1360, 11, 'REPORTES', 3, 1337, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1361, 11, 'DASHBOARD', 4, 1360, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1362, 11, 'NEGOCIACIONES', 3, 1337, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1363, 11, 'ADMINISTRAR NEGOCIACIONES', 4, 1362, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1364, 11, 'DETALLE DE NEGOCIACION', 5, 1363, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1365, 11, 'PAGO', 6, 1364, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1366, 11, 'ADENDUM', 6, 1364, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1367, 11, 'CUENTAS POR COBRAR', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1368, 11, 'PARAMETRIZACION', 3, 1367, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1369, 11, 'GRUPOS DE PRODUCTOS', 4, 1368, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1370, 11, 'DATOS FACTURADOR', 4, 1368, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1371, 11, 'DATOS SRI', 4, 1368, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1372, 11, 'COBROS', 3, 1367, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1373, 11, 'REGISTRAR COBRO', 4, 1372, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1374, 11, 'CRUCE DE ANTICIPO', 4, 1372, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1375, 11, 'CONSULTA DE COBROS', 4, 1372, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1376, 11, 'MOTIVO', 5, 1375, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1377, 11, 'ABONOS A FACTURA', 4, 1372, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1378, 11, 'MOTIVO', 5, 1377, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1379, 11, 'EMITIR', 3, 1367, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1380, 11, 'FACTURAS', 4, 1379, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1381, 11, 'NOTAS DE CREDITO', 4, 1379, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1382, 11, 'NOTAS DE DEBITO', 4, 1379, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1383, 11, 'LIQUIDACION EN COMPRAS', 4, 1379, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1384, 11, 'ANULAR DOCUMENTO DE COMPRA', 5, 1383, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1385, 11, 'RETENCIONES', 4, 1379, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1386, 11, 'GESTIONAR', 3, 1367, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1387, 11, 'DOCUMENTOS ELECTRONICOS', 4, 1386, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1388, 11, 'ANULAR DOCUMENTO DE COMPRA', 5, 1387, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1389, 11, 'ACTUALIZAR ESTADO RESULTADO', 5, 1387, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1390, 11, 'CONSULTA AL SRI', 5, 1387, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1391, 11, 'FINANCIAR FACTURA', 4, 1386, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1392, 11, 'CONSULTA FACTURAS', 4, 1386, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1393, 11, 'ANULAR DOCUMENTO DE COMPRA', 5, 1392, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1394, 11, 'ANTICIPOS', 4, 1386, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1395, 11, 'MOTIVO', 5, 1394, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1396, 11, 'REPORTES', 3, 1367, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1397, 11, 'DASHBOARD DE VENTAS', 4, 1396, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1398, 11, 'ATS Y CUADRE 103/104', 4, 1396, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1399, 11, 'CREDITOS', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1400, 11, 'HISTORICOS', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1401, 11, 'DELTA21', 4, 1400, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1402, 11, 'APORTES POR REVISAR', 4, 1400, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1403, 11, 'PARTICIPES INICIAL', 4, 1400, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1404, 11, 'PARAMETRIZACION', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1405, 11, 'INFORMACION GENERAL DEL FONDO', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1406, 11, 'TIPOS', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1407, 11, 'ESTADOS', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1408, 11, 'LISTADOS', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1409, 11, 'PROCESOS VARIOS', 5, 1408, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1410, 11, 'BANDAS DE CARTERA', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1411, 11, 'ESCALA DE CALIFICACION DE RIESGO', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1412, 11, 'CIERRE DE CARTERA', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1413, 11, 'CONTABILIDAD DE CREDITOS', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1414, 11, 'CUENTAS POR TIPO DE APORTE', 4, 1404, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1415, 11, 'PARTICIPES', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1416, 11, 'ADMINISTRAR', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1417, 11, 'CONSULTA', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1418, 11, 'AUDITORIA', 5, 1417, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1419, 11, 'LISTADO GENERAL', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1420, 11, 'CONSOLIDADO', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1421, 11, 'EDICION DE PARTICIPE', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1422, 11, 'INFORMACION DEL PARTICIPE', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1423, 11, 'HISTORICO DE EXTERNOS', 5, 1422, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1424, 11, 'DASH DEL PARTICIPE', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1425, 11, 'AUDITORIA', 5, 1424, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1426, 11, 'PAGOS DEL APORTE', 5, 1424, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1427, 11, 'PAGOS DEL PRESTAMO', 5, 1424, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1428, 11, 'CERTIFICADOS DEL PARTICIPE', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1429, 11, 'JUBILADOS', 4, 1415, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1430, 11, 'JUBILAR PARTICIPE', 5, 1429, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1431, 11, 'PAGO JUBILADOS', 5, 1429, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1432, 11, 'CONTRATOS', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1433, 11, 'INGRESO', 4, 1432, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1434, 11, 'ADMINISTRAR', 4, 1432, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1435, 11, 'DASH', 4, 1432, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1436, 11, 'APORTES DASH', 4, 1432, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1437, 11, 'PRESTAMOS', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1438, 11, 'INGRESO', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1439, 11, 'CONSULTA', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1440, 11, 'DETALLE DEL PRESTAMO', 5, 1439, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1441, 11, 'DASH', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1442, 11, 'CONSULTA CUOTAS', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1443, 11, 'DETALLE DEL PRESTAMO', 5, 1442, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1444, 11, 'REPORTE VALORES INSOLUTOS', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1445, 11, 'ASIGNACION DE SEGUROS', 4, 1437, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1446, 11, 'ASIGNAR SEGURO', 5, 1445, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1447, 11, 'COBROS', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1448, 11, 'ARCHIVOS PETRO', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1449, 11, 'CARGA', 5, 1448, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1450, 11, 'CARGA APORTES', 6, 1449, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1451, 11, 'CONSULTA CARGA', 6, 1449, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1452, 11, 'DETALLE DE CARGA', 6, 1449, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1453, 11, 'COINCIDENCIAS DE ENTIDAD', 7, 1452, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1454, 11, 'ERROR DEL PROCESO DE ARCHIVO', 7, 1452, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1455, 11, 'AFECTACION FINANCIERA DE CUOTAS', 7, 1452, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1456, 11, 'REVALIDAR CARGA', 7, 1452, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1457, 11, 'AFECTACION POR PARTICIPE', 6, 1449, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1458, 11, 'AFECTACION DEL PARTICIPE', 7, 1457, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1459, 11, 'REVALIDAR CARGA', 7, 1457, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1460, 11, 'GENERAR', 5, 1448, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1461, 11, 'GENERAR ARCHIVO', 6, 1460, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1462, 11, 'CONSULTA GENERACION', 6, 1460, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1463, 11, 'DETALLE DE GENERACION', 6, 1460, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1464, 11, 'PAGO CUOTA', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1465, 11, 'PAGO DE CUOTA', 5, 1464, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1466, 11, 'CRUCE DE VALORES', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1467, 11, 'PAGO DE PRESTAMO', 5, 1466, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1468, 11, 'COBRO REGISTRADO', 6, 1467, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1469, 11, 'RECIBO DE OPERACION', 6, 1467, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1470, 11, 'ABONO A CAPITAL', 5, 1466, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1471, 11, 'COBRO REGISTRADO', 6, 1470, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1472, 11, 'PRECANCELACION', 5, 1466, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1473, 11, 'COBRO REGISTRADO', 6, 1472, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1474, 11, 'RECIBO DE OPERACION', 6, 1472, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1475, 11, 'RECIBO DE OPERACION', 5, 1466, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1476, 11, 'DEVOLUCION DE APORTES', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1477, 11, 'COBROS PERSONALES', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1478, 11, 'PAGO DE PRESTAMO', 5, 1477, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1479, 11, 'ABONO A CAPITAL', 5, 1477, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1480, 11, 'PRECANCELACION', 5, 1477, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1481, 11, 'COBRO REGISTRADO', 5, 1477, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1482, 11, 'RECIBO DE OPERACION', 5, 1477, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1483, 11, 'BANDEJA DE CONTABILIDAD', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1484, 11, 'AUDITORIA DE BANDAS', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1485, 11, 'PROCESO DE CREDITO', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1486, 11, 'CONSULTA DE COBROS', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1487, 11, 'SEGUIMIENTO DE COBROS', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1488, 11, 'CONDONACION DE VALORES', 4, 1447, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1489, 11, 'SIMULADORES', 3, 1399, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1490, 11, 'CREDITO NUEVO', 4, 1489, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1491, 11, 'PRESTAMO EXISTENTE', 4, 1489, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1492, 11, 'REPORTES', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1493, 11, 'CREDITOS', 3, 1492, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1494, 11, 'SUPER DE BANCOS', 4, 1493, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1495, 11, 'INFORMES MENSUALES', 4, 1493, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1496, 11, 'RECURSOS HUMANOS', 2, 1253, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1497, 11, 'PARAMETRIZACION', 3, 1496, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1498, 11, 'CONCEPTOS DE NOMINA', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1499, 11, 'PARAMETROS ANUALES', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1500, 11, 'TABLA DE IMPUESTO A LA RENTA', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1501, 11, 'TOPES DE GASTOS PERSONALES', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1502, 11, 'CAUSALES DE TERMINACION', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1503, 11, 'CONFIGURACION DE NOMINA', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1504, 11, 'FORMATOS DE MARCACION', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1505, 11, 'FORMATOS DEL ARCHIVO BANCARIO', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1506, 11, 'DEPARTAMENTOS', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1507, 11, 'CARGOS Y PUESTOS', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1508, 11, 'DEPARTAMENTO - CARGO', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1509, 11, 'TIPOS DE CONTRATO', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1510, 11, 'TURNOS Y HORARIOS', 4, 1497, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1511, 11, 'PERSONAL', 3, 1496, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1512, 11, 'COLABORADORES', 4, 1511, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1513, 11, 'FICHA DEL COLABORADOR', 4, 1511, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1514, 11, 'FORMULARIO DE CONTRATO', 5, 1513, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1515, 11, 'FORMULARIO DE CUENTA BANCARIA', 5, 1513, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1516, 11, 'VACACIONES', 4, 1511, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1517, 11, 'FORMULARIO DE VACACIONES', 5, 1516, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1518, 11, 'APROBACION DE VACACIONES', 5, 1516, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1519, 11, 'PERMISOS Y LICENCIAS', 4, 1511, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1520, 11, 'FORMULARIO DE PERMISO', 5, 1519, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1521, 11, 'APROBACION DE PERMISOS', 5, 1519, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1522, 11, 'ASISTENCIA', 3, 1496, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1523, 11, 'MARCACIONES', 4, 1522, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1524, 11, 'IMPORTACION DE MARCACIONES', 4, 1522, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1525, 11, 'RESUMEN DIARIO', 4, 1522, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1526, 11, 'HORAS EXTRA', 4, 1522, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1527, 11, 'MIGRACION DE APERTURA', 3, 1496, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1528, 11, 'SALDOS DE APERTURA', 4, 1527, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1529, 11, 'ACUMULADOS', 4, 1527, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1530, 11, 'PROCESOS', 3, 1496, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1531, 11, 'PERIODOS DE NOMINA', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1532, 11, 'DASH DEL PERIODO', 5, 1531, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1533, 11, 'PREVISUALIZACION DEL ASIENTO', 6, 1532, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1534, 11, 'NOVEDADES DEL PERIODO', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1535, 11, 'NOVEDADES DEL MES IESS', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1536, 11, 'PLANILLA DE CONTROL IESS', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1537, 11, 'PLANILLAS DEL IESS', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1538, 11, 'HORAS EXTRA', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1539, 11, 'PROYECCION DE IMPUESTO A LA RENTA', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1540, 11, 'DESCUENTOS RECURRENTES', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1541, 11, 'ROLES DE PAGO', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1542, 11, 'ORDENES DE PAGO', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1543, 11, 'VALORES NO PAGADOS', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1544, 11, 'REGISTRAR VALOR NO PAGADO', 5, 1543, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1545, 11, 'MOTIVO', 5, 1543, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1546, 11, 'PAGO DE BENEFICIOS SOCIALES', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1547, 11, 'REPORTES DE NOMINA', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1548, 11, 'LIQUIDACION', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1549, 11, 'FORMULARIO DE LIQUIDACION', 5, 1548, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1550, 11, 'SALIDAS OFICIALES', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1551, 11, 'REPARTO DE UTILIDADES', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1552, 11, 'ANTICIPOS A TRABAJADORES', 4, 1530, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1553, 11, 'FORMULARIO DE ANTICIPO', 5, 1552, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1554, 11, 'APROBAR ANTICIPO', 5, 1552, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1555, 11, 'DEVOLUCION DE ANTICIPO', 5, 1552, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1556, 11, 'MOTIVO', 5, 1552, 1);
INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR) VALUES (1557, 11, 'ACREDITAR VACACIONES', 4, 1530, 1);


--------------------------------------------------------------------------------
-- PASO 5 — CONFIRMAR EN LA MISMA SESION, ANTES DEL COMMIT.
--
-- Los CONTROL D a G leen lo que acaba de escribirse. Si alguno no da lo esperado,
-- ROLLBACK (el PASO 6 esta abajo) y avisar. NO commitear a medias.
--------------------------------------------------------------------------------

-- CONTROL D — Cuantos nodos tiene ahora la jerarquia 11, y como se reparten.
-- Esperado: SAA 305, SEGURIDAD 75, RAIZ 1, TOTAL 381 (eran 742, se borraron 666,
-- se insertaron 305).
SELECT 'SAA'                  AS SUBARBOL,
       COUNT(*)               AS NODOS
  FROM SCP.PJRQ
 WHERE PGSPCDGO = 11
 START WITH PJRQCDGO = 1253
CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11
UNION ALL
SELECT 'SEGURIDAD Y AUDITORIA', COUNT(*)
  FROM SCP.PJRQ
 WHERE PGSPCDGO = 11
 START WITH PJRQCDGO = 42
CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11
UNION ALL
SELECT 'TOTAL JERARQUIA 11', COUNT(*) FROM SCP.PJRQ WHERE PGSPCDGO = 11
UNION ALL
SELECT 'OTRAS JERARQUIAS (empresas, usuarios)', COUNT(*)
  FROM SCP.PJRQ WHERE PGSPCDGO <> 11;

-- CONTROL E — Ningun nodo puede quedar apuntando a un padre que ya no existe.
-- Es el control que atrapa un DELETE que se llevo de mas.
-- Esperado: NINGUNA FILA.
SELECT h.PJRQCDGO, h.PJRQNMBR, h.PJRQCDPD AS PADRE_INEXISTENTE
  FROM SCP.PJRQ h
 WHERE h.PGSPCDGO = 11
   AND h.PJRQCDPD <> 0
   AND NOT EXISTS (SELECT 1 FROM SCP.PJRQ p
                    WHERE p.PGSPCDGO = h.PGSPCDGO AND p.PJRQCDGO = h.PJRQCDPD);

-- CONTROL F — El UNIQUE ya lo garantiza la base, pero si el INSERT hubiera
-- fallado a medias esto lo muestra en claro. Esperado: NINGUNA FILA.
SELECT PGSPCDGO, PJRQCDPD AS PADRE, PJRQNMBR, COUNT(*) AS VECES
  FROM SCP.PJRQ
 GROUP BY PGSPCDGO, PJRQCDPD, PJRQNMBR
HAVING COUNT(*) > 1;

-- CONTROL G — El arbol de SAA como se va a ver en la pantalla del modulo de
-- seguridades, con su ruta completa. Sirve para leerlo de una y para sacar de
-- aca el codigo de cada pantalla cuando se cablee el frontend.
-- Esperado: 305 filas, empezando por SAA.
SELECT LPAD(' ', (LEVEL - 1) * 2) || PJRQNMBR AS ARBOL,
       PJRQCDGO                               AS CODIGO,
       PJRQNVLL                               AS NIVEL,
       PJRQCDPD                               AS PADRE
  FROM SCP.PJRQ
 WHERE PGSPCDGO = 11
 START WITH PJRQCDGO = 1253
CONNECT BY PRIOR PJRQCDGO = PJRQCDPD AND PGSPCDGO = 11
 ORDER SIBLINGS BY PJRQCDGO;


--------------------------------------------------------------------------------
-- PASO 6 — CERRAR LA TRANSACCION. Uno de los dos, no los dos.
--
-- Con los CONTROL D a G en verde:
--------------------------------------------------------------------------------
-- COMMIT;

-- Si algo no cuadro:
-- ROLLBACK;


--------------------------------------------------------------------------------
-- LA SECUENCIA — no aplica hoy, y queda escrito por que.
--
-- Empresa.java:19 y Usuario.java:29 declaran
-- @SequenceGenerator(sequenceName = "SCP.SQ_PJRQCDGO") con GenerationType.SEQUENCE,
-- asi que a primera vista habria que adelantarla despues de quemar 305 ids.
--
-- NO HACE FALTA, por dos razones medidas y no supuestas:
--   1. La secuencia NO EXISTE en la base. El CONTROL 1 del lap1-14 (ALL_SEQUENCES)
--      volvio vacio, y el usuario lo confirmo.
--   2. SAA no inserta en PJRQ ni podria: UsuarioRest solo tiene metodos @GET (siete,
--      ninguno @POST/@PUT/@DELETE) y no existe EmpresaRest. Los usuarios y las
--      empresas se crean unicamente desde el modulo de seguridades de escritorio,
--      que maneja sus propios codigos.
--
-- Si algun dia la secuencia se crea, el bloque de abajo la deja por encima del
-- maximo usado. Se deja comentado a proposito: correrlo sin que la secuencia
-- exista da ORA-02289.
--
-- DECLARE
--   v_max     NUMBER;
--   v_actual  NUMBER;
-- BEGIN
--   SELECT MAX(PJRQCDGO) INTO v_max FROM SCP.PJRQ;
--   LOOP
--     EXECUTE IMMEDIATE 'SELECT SCP.SQ_PJRQCDGO.NEXTVAL FROM DUAL' INTO v_actual;
--     EXIT WHEN v_actual > v_max;
--   END LOOP;
-- END;


--------------------------------------------------------------------------------
-- REVERSO — COMENTADO A PROPOSITO. Descomentar SOLO para deshacer.
--
-- Restaura la jerarquia 11 completa y los permisos, desde los respaldos del
-- PASO 1. Deja la base exactamente como estaba antes de correr este archivo.
--
-- El orden importa: primero se vacian los permisos (tienen FK contra PJRQ),
-- despues se rehace el arbol, y recien al final se reponen los permisos.
--------------------------------------------------------------------------------
-- DELETE FROM SCP.PENP;
--
-- DELETE FROM SCP.PJRQ WHERE PGSPCDGO = 11;
--
-- INSERT INTO SCP.PJRQ (PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR)
-- SELECT PJRQCDGO, PGSPCDGO, PJRQNMBR, PJRQNVLL, PJRQCDPD, PJRQINGR
--   FROM SCP.PJRQ_BKP_LAP1;
--
-- INSERT INTO SCP.PENP SELECT * FROM SCP.PENP_BKP_LAP1;
--
-- -- Control del reverso. Esperado: 742 y 2.
-- SELECT (SELECT COUNT(*) FROM SCP.PJRQ WHERE PGSPCDGO = 11) AS ARBOL_RESTAURADO,
--        (SELECT COUNT(*) FROM SCP.PENP)                     AS PERMISOS_RESTAURADOS
--   FROM DUAL;
--
-- COMMIT;


--------------------------------------------------------------------------------
-- LIMPIEZA DE LOS RESPALDOS — comentada. Descomentar recien cuando el arbol
-- nuevo lleve tiempo funcionando y ya nadie vaya a querer volver atras.
--------------------------------------------------------------------------------
-- DROP TABLE SCP.PJRQ_BKP_LAP1;
-- DROP TABLE SCP.PENP_BKP_LAP1;


--------------------------------------------------------------------------------
-- FIN. Lo que sigue despues de este script:
--   * cablear los codigos en los menus del frontend (contrato en
--     PLAN-ARBOL-PERMISOS-SAA.md), incluidos los 7 botones del menu de entrada;
--   * reasignar las 47 constantes de PermisosRrh, que hoy apuntan a codigos que
--     este script acaba de borrar;
--   * decidir de donde se lee el interruptor (rubro alterno 7 / detalle 1), que
--     hoy tiene el 0 en PDTRDSCR mientras el backend lee PDTRVLRV.
--------------------------------------------------------------------------------
