-- ============================================================
-- ANULACION: Campos de anulación en Nota de Crédito, Nota de
-- Débito y Retención (mismo estándar que CBR.FCTR)
-- ============================================================

-- ── NOTA DE CRÉDITO (CBR.NTCR) ──────────────────────────────
ALTER TABLE CBR.NTCR ADD MOTIVOANULACION  VARCHAR2(1000);
ALTER TABLE CBR.NTCR ADD FECHAANULACION   TIMESTAMP;
ALTER TABLE CBR.NTCR ADD USUARIOANULACION VARCHAR2(200);
ALTER TABLE CBR.NTCR ADD ASIENTO          NUMBER(19);

-- ── NOTA DE DÉBITO (CBR.NTDB) ───────────────────────────────
ALTER TABLE CBR.NTDB ADD MOTIVOANULACION  VARCHAR2(1000);
ALTER TABLE CBR.NTDB ADD FECHAANULACION   TIMESTAMP;
ALTER TABLE CBR.NTDB ADD USUARIOANULACION VARCHAR2(200);
ALTER TABLE CBR.NTDB ADD ASIENTO          NUMBER(19);

-- ── RETENCIÓN (CBR.RTNC) ────────────────────────────────────
ALTER TABLE CBR.RTNC ADD MOTIVOANULACION  VARCHAR2(1000);
ALTER TABLE CBR.RTNC ADD FECHAANULACION   TIMESTAMP;
ALTER TABLE CBR.RTNC ADD USUARIOANULACION VARCHAR2(200);
ALTER TABLE CBR.RTNC ADD ASIENTO          NUMBER(19);

COMMIT;
